### ISSUE TITLE
How can we compute optical images with custom spatial support?

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#105]
Some times the scene sampling is too coarse compared to the cone separation.
In such cases, it would be nice to have the ability to generate optical images whose spatial support is  independent of the respective scene spatial sampling, for example a fixed fraction of the cone separation.
How can one achieve this?

Thanks,
Nicolas

**Comment by npcottaris** [comment]
One could, of course,  interpolate the generated optical image, but I was wondering if there was built-in functionality in isetbio.

Thanks,
Nicolas

**Comment by wandell** [comment]
Here is my best effort ...

1.  Sometimes the scene is coarsely sampled with respect to the optics.  For example, the scene sample densities may be spaced more widely than the point spread function of the optics.  The user is warned in this case with an alert on the OI page.

2.  The conversion from the optical image to the sensor is always handled by linear interpolation in the routines within oiCompute.  The irradiance is linearly interpolated and the position of the each sensor pixel has a value that accounts for the irradiance per square meter at that location times the actual pixel aperture (square microns).  

So, if I am understanding your message, then my response says:  The problem arises mainly from scene to irradiance, and the linear interpolation from irradiance to sensor is handled in sensorCompute by the functions signalCurrent() which calls SignalCurrentDensity() and spatialIntegration().

(These are old functions that were tested extensively about 10 years ago.  The names kind of suck, and the idea of reworking that part of the code always terrifies me. But maybe it is time.)

**Comment by npcottaris** [comment]
I do not get any alerts regarding the scene sampling. 

What I am concerned with is that the separation between optical image samples depends on the separation of the scene samples. I was thinking it would be handy if one had the option to set the optical sample separation to an arbitrary value. In my case, I would set it to be a fixed fraction of the cone aperture. For example, in one scene, the optical sample is 1.41 microns and the cone aperture is 3.0 microns. I would like to compute my optical images with a 0.5, 1.0, or 1.5 micron resolution.

Most likely the linear interpolation from irradiance to sensor is taking care of cases where there are only a few and non-integer number of optical samples within the cone aperture, and is definitely not worth rewriting kernel code. I was just wondering whether there already existed a way to set the optical sample separation to an arbitrary value.

Thanks !
Nicolas

**Comment by wandell** [comment]
If I understand, you would like a 

  oi = oiSpatialResample(oi, 'sample spacing',value)

that spatially interpolates at each wavelength the irradiance to, say, the cone sampling spacing (0.5 um).  

We can do that.  I will help.  The function regridOI2ISA(current,OI,SENSOR,gridSpacing) is pretty much what you want, right?  Except to operate on irradiance rather than current?

Brian

**Comment by npcottaris** [comment]
Yes, an `oiSpatialResample(oi, 'sample spacing',value)` would be perfect. 
Let me know if you would like me to implement part or all of it.

Thanks,
Nicolas

**Comment by wandell** [comment]
I have drafted an oiSpatialResample and sceneSpatialResample.  I am testing and will push the new branch in the next day or two.  I will then issue a PR for @npcottaris to check.

**Comment by wandell** [comment]
Implemented and merged by a PR.
