### ISSUE TITLE
Validation script v_DIsplayLUTinversion.m

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#11]
This script requires the Matlab optimization toolbox.  Maybe that's OK.  But if you don't have it the validation script 

  - tries to run PTB FitGammaPow, which relies on the optimization
  - throws an error

Not sure what (if anything) should be done about this.  At this point it just means that the validation comparison between PTB and ISETBIO on LUT doesn't run.  But if you say it is fine on a machine that has the optimization toolbox, then that's good enough for me.

In which case, we could remove this validation script.

**Comment by DavidBrainard** [comment]
I should be able to remove this dependence and test without the optimization toolbox.

**Comment by wandell** [comment]
Right now, validateFastAll is failing on my computer, and  'v_DisplayLUTinversion' is failing too.  Before I start digging deeper, I thought I would post this message and see if anyone knows what is happening.

(Perhaps unrelated ... I am worried that the denial of service attacks on github.com produced errors in some of the repositories.  In fact, I believe this to be verifiably true in the ISET repository.  So, if none of you has an error I will do a fresh git clone.)

Error messages are pasted here
  4] 'v_DisplayColorConversion'
	Internal validation  : FAILED
	Run-time status      : exception raised
	Validation report    : exception raised (and caught) with message: Calibration structure does not contain device colorimetric data



[  5] 'v_DisplayLUTinversion'
	Internal validation  : PASSED
	Run-time status      : no exception raised
Reference to non-existent field 'generateGroundTruthDataIfNotFound'.

Error in UnitTest/validate>doFastValidation (line 338)
            if (projectSpecificPreferences.generateGroundTruthDataIfNotFound)

Error in UnitTest/validate (line 205)
                abortValidationSession = doFastValidation(obj, fastLocalGroundTruthHistoryDataFile, validationData,
                projectSpecificPreferences, smallScriptName);

Error in UnitTest.runValidationSession>validateFast (line 80)
    abortValidationSession = UnitTestOBJ.validate(vScriptsList);

Error in UnitTest.runValidationSession (line 27)
        validateFast(vScriptsList);

Error in validateFastAll (line 40)
    UnitTest.runValidationSession(vScriptsList, 'FAST');

**Comment by wandell** [comment]
So, at least one problem (small) is that the fast ground truth data file is not in the repository for the v_DisplayLUTinversion routine.

The problem with the v_DisplayColorConversion has to do with some colorimetric display data that my version thinks is missing.

**Comment by DavidBrainard** [comment]
Hi,

These two validation files are in an intermediate state, and the problems you are hitting are consistent with that fact.  Not sure how to make that clearer — I think it says so in the commit comments but I realize those are not salient.

Perhaps this is a case where I should have forked off a branch and the merged when they were done.

So, don’t worry about these until I finish them off.

> On Apr 11, 2015, at 11:58 PM, Brian Wandell <notifications@github.com> wrote:
> 
> So, at least one problem (small) is that the fast ground truth data file is not in the repository for the v_DisplayLUTinversion routine.
> 
> The problem with the v_DisplayColorConversion has to do with some colorimetric display data that my version thinks is missing.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/11#issuecomment-91982657>.
> 


=========
David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by DavidBrainard** [comment]
Generated ground truth data for these scripts, and eliminated dependency on optimization toolbox.  Although I am still fussing with these scripts a bit, I am closing this issue.
