### ISSUE TITLE
Code Guidelines Proposal / Starting Place

### ISSUE THREAD

**Issue by benjamin-heasly** [isetbio/isetbio#112]
Hi all,

I took a stab at writing some coding guidelines that we might discuss as a group: [ISETBIO Code Guidelines](https://drive.google.com/open?id=1YQldbUJsTi0I2kF_uRButolJYTAwh567w_KvapH1PsQ).

It began as a list of my own opinions.  David and I added comments and edits.  I am hoping we as a group can evolve this towards a consensus of some kind.  So please make comments!

Code guidelines can by fussy and annoying.   But the discussion may pay off when we find ourselves reading and editing each others code.

Thanks.

Ben

**Comment by DavidBrainard** [comment]
I think this can be closed.
