### ISSUE TITLE
ISETBIO Scheduler Design

### ISSUE THREAD

**Issue by benjamin-heasly** [isetbio/isetbio#118]
Hi all,

David and I (Ben) have been brainstorming about an ISETBIO architecture that would be pretty different from the currently implemented architecture and other architecture discussions.  I'm calling this new one the "Scheduler" because a distinguishing features is a Scheduler object that can order the computations performed by other objects over time.

Here is a [Google doc](https://docs.google.com/document/d/1p2ln_JGivUzqifelD2sAPs9GfJt4N5Z1cJG4Ssn_DR4/edit?usp=sharing) that outlines the design and how it might be helpful.

Would love to know what you think, and discuss it some Wednesday.

Thanks!

@DavidBrainard 
@wandell 
@npcottaris 
@chichilnisky 
@fmrieke 
@jamesgolden1

**Comment by benjamin-heasly** [comment]
Here is a pdf if you prefer.

[ISETBIOSchedulerDesign.pdf](https://github.com/isetbio/isetbio/files/210576/ISETBIOSchedulerDesign.pdf)

**Comment by DavidBrainard** [comment]
Well, this was a fun exercise but we did not go down the road.  The ideas remain interesting if we ever take on a full redesign.  

Closing.
