### ISSUE TITLE
no option to not fix the mean scene luminance when using sceneAdjustIlluminant

### ISSUE THREAD

**Issue by staceyaston13** [isetbio/isetbio#122]
@wandell In sceneAdjustIlluminant, the mean scene luminance is preserved. In cases where an illuminant change on the scene is expected to change the mean scene luminance and the user would like this to happen, it would be better to set a flag in the function that allows the user to specify that the mean scene luminance should or should not be preserved.

**Comment by DavidBrainard** [comment]
Fix as above is coming, but in the meantime we have added a new tutorial, tutorials/scene/t_sceneFromSurface that shows how to make an isetbio scene starting with an image of the surface reflectance functions and the illuminant radiance in Watts/[m2-sr-nm].
