### ISSUE TITLE
osCompute,osPlot, and osWindow not working with osIdentity

### ISSUE THREAD

**Issue by xnieamo** [isetbio/isetbio#124]
I'm running t_os.m script modified to use osIdentity as below. osCompute and osPlot crash because there is no rgbData field in osIdentity anymore.  Presumably this should be changed to the variable photonRate in the various functions? I've done this locally but didn't push in case that's the wrong variable.

The other issue is that osIdentity and osWindow do not work with each other, with the error referring to 'ConeCurrentSignal' in the osGet function. Should this be the intended behavior as osIdentity does not have cone current data or should it just graph the isomerization data instead?

```
%% Generate input signal.
% Set up parameters for stimulus
nSamples = 2000;        % 2000 samples
timeStep = 1e-4;        % time step
flashIntens = 50000;    % flash intensity in R*/cone/sec (maintained for 1 bin only)

% Create human sensor.
sensor = sensorCreate('human');
sensor = sensorSet(sensor, 'size', [1 1]); % only 1 cone
sensor = sensorSet(sensor, 'time interval', timeStep);

% Create stimulus - impulse.
stimulus = zeros(nSamples, 1);
stimulus(1) = flashIntens;
stimulus = reshape(stimulus, [1 1 nSamples]);

% Set photons.
sensor = sensorSet(sensor, 'photon rate', stimulus);

%% Instantiate an osLinear object.
identityOS = osCreate('identity');%,'noiseFlag', 1);
identityOS = osSet(identityOS, 'noiseFlag', 0);

%% Compute linear outer segment response.
identityOS = osCompute(identityOS, sensor);
osGet(identityOS, 'noiseFlag');

%% Plot results.
osPlot(identityOS, sensor);
```

**Comment by jamesgolden1** [comment]
Xiaomao, please push those changes. Thank you for catching this.

I have not used osWindow, but perhaps we should modify @osIdentity/osGet.m
to get the photon rate if the get property is 'coneCurrentSignal'. I think
this error arose because I changed osIdentity to have only the photon rate,
and I know osWindow is used with Nicolas's visualization, but I did not
update that code after the change to osIdentity.

**Comment by xnieamo** [comment]
I've upload the changes I made locally. I'll keep this issue open for a bit until the osWindow issue is resolved.

**Comment by wandell** [comment]
Seems no longer relevant with the departure of sensor*.
