### ISSUE TITLE
oiCreate('wvf human') generates a complex-valued OTF

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#125]
The Thibos-based optics, generated by
`oi = oiCreate('wvf human');`
produces a complex-valued OTF, as evidenced by the fact that
`isreal(oi.optics.OTF.OTF) `
returns 0.

This is unlike 
`oi = oiCreate('human');`
which returns a real-valued OTF.

Nicolas

**Comment by wandell** [comment]
I think this just means that the wvf Zernike polynomials introduce a slight phase shift in some frequencies.  Are you sure it is a bug, rather than a property of the (noisy) mean estimate from Thibos wvf parameters?

**Comment by DavidBrainard** [comment]
As Brian indicates, real PSFs are not typically spatially symmetric, so can have complex OTF.

Best,

David
