### ISSUE TITLE
Calculating multiple eye movements with large image using coneMosaic object

### ISSUE THREAD

**Issue by xnieamo** [isetbio/isetbio#128]
I have a few questions regarding generating eye movements using the coneMosaic object. 

1. It seems that the emGenSequence code performs the same calculation as it does on the master branch which is to generate fixational eye movements. Thus, if I wanted to have large saccadic movements I would have to add those in myself correct?  There seems to be no set method for cone locations.  

2. For my calculations, I will eventually need to calculate absorptions using scenes much larger than the cone mosaic.  In addition, many different eye movement paths may be needed for a single image.  To improve the speed of the calculation, I had split the coneAbsorption function into two functions on the master branch (coneAbsorptionsLMScone and AbsorptionsApplyPath). This allowed me to calculate the full LMS absorptions once (which would take perhaps over 1 minute) and simply use these values each time I wanted a new eye movement path.  Is there a way to implement similar functionality in the coneMosaic object? 

XD

**Comment by hjiang36** [comment]
Thanks for the comments, and here's my understanding to your questions

1. emGenSequence is exactly the same as before and it's only for fixational eye movement. If you have some good ways to simulate large saccade (salient model?), I think we can get that implemented in the coneMosaic object. But for now, it only supports fixational eye movement.

2. The computation in coneMosaic is actually taking that two steps you mentioned. The coneAbsorptionLMScone is corresponding to computeSingleFrame method in coneMosaic. That method is now private. To avoid confusion for other users (I hope there is only one public compute entry for the coneMosaic object), I prefer to change the access to public, but hidden. I will reply to you after I make the changes.

If you have other suggestions, let me know.
Thanks

HJ

**Comment by xnieamo** [comment]
Thanks for the response.

1. I hadn't realized that emPositions was a public variable.  We have experimental eye movement data that I will eventually want to plug in there, so this is no longer an issue I think.

2. That would be great. 

XD

**Comment by hjiang36** [comment]
I made some small changes to the code.
Here is one simple example code that you can refer to:

```
% scene and optical image
scene = sceneCreate;
oi = oiCreate('human');
oi = oiCompute(oi, scene);

% cone mosaic
cMosaic = coneMosaic;
cMosaic.mosaicSize = [100 120];
cMosaic.emPositions = round(200*(rand(100, 2)-0.5));

% make a large mosaic
cm = cMosaic.copy();
cm.mosaicSize = [300 320];

% cone full frame
LMS = cm.computeSingleFrame(oi, 'fullLMS', true);

% apply em positions
absorptions = cMosaic.applyEMPath(LMS, 'padRows', 100, 'padCols', 100);
```

Note that computeSingleFrame and applyEMPath are hidden method. You can call them, but they will not show up in tab completion or ismethod, etc.

If you got any problems, let me know.
HJ
