### ISSUE TITLE
Lens transmittance wrong below 400 nm

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#129]
I happened to create an OI with a wavelength range that extends below 400 nm.  The lens transmittance ends up as unity for wavelengths below 400 nm, presumably because some density got zero extended.  The PTB has lens data that extend down to whatever the lower limit of the CIE standard is, if you need it.  And if you need me to find it, let me know.

**Comment by hjiang36** [comment]
I changed the extrapolation behavior of Lens, Macular and photoPigment class.
I found that the stored data in ISETBIO is from 390 to 830 nm. I changed the code to use full range of these data.

Hope it will be fine now.
