### ISSUE TITLE
oi validation now failing, looks like a change in row/col convention in OTF fields

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#13]
Two validation scripts involving the optical image structure are now behaving differently than they once did, so they fail their comparison against the stored ground truth data.

It looks like (see validation dump below) this is because certain fields (e.g. OTF.fx, OTF.fy, OTF.wave) have been transposed relative to the way they once were.

Was this an intentional change?  I can regenerate the ground truth data for the relevant validation scripts, but since the idea of the validation scripts is to catch unintended changes I thought I should check first about what is going on.

DB

***************************************

Ground truth  file   : /Users1/Shared/Dropbox/ISETBIOFullValidationData/optics/v_oi_FullGroundTruthDataHistory.mat
	Full validation      : FAILED against ground truth data of 05-Feb-2015 14:12:32.
	 > Ground truth info : wal-isc-video012.isc-video.upenn.edu / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   : ray.PSYCH.UPENN.EDU            / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'dhb'
	[data mismatch  1]   : 'groundTruthData.humanOI.optics.OTF.fx' is a [ 1  60  ] matrix whereas 'validationData.humanOI.optics.OTF.fx' is a [60   1  ] matrix.
 	[data mismatch  2]   : 'groundTruthData.humanOI.optics.OTF.fy' is a [ 1  60  ] matrix whereas 'validationData.humanOI.optics.OTF.fy' is a [60   1  ] matrix.
 	[data mismatch  3]   : 'groundTruthData.humanOI.optics.OTF.wave' is a [ 1  31  ] matrix whereas 'validationData.humanOI.optics.OTF.wave' is a [31   1  ] matrix.
 	[data mismatch  4]   : 'groundTruthData.humanOIFromScene.optics.OTF.fx' is a [ 1  60  ] matrix whereas 'validationData.humanOIFromScene.optics.OTF.fx' is a [60   1  ] matrix.
 	[data mismatch  5]   : 'groundTruthData.humanOIFromScene.optics.OTF.fy' is a [ 1  60  ] matrix whereas 'validationData.humanOIFromScene.optics.OTF.fy' is a [60   1  ] matrix.
 	[data mismatch  6]   : 'groundTruthData.humanOIFromScene.optics.OTF.wave' is a [ 1  31  ] matrix whereas 'validationData.humanOIFromScene.optics.OTF.wave' is a [31   1  ] matrix.

**Comment by DavidBrainard** [comment]
t_humanLineSpread also now crashes, with an error that makes me think it is related to this.

**Comment by hjiang36** [comment]
I think that error perhaps results from my commits for wavelength interpolation for oi. I prefer to use column vectors in my code. But if they were row vectors, I should keep that format.

I will change for the fx and fy field. Not sure for OTF.wave because all other wave fields in oi and optics were in column vectors.

**Comment by hjiang36** [comment]
I changed the fx and fy to row vector and t_humanLineSpread works now. I haven't changed the OTF.wave field. So, the validation is still failing.

**Comment by wandell** [comment]
The validation scripts mostly now run on my home computer.  That's very good.
There are  ground truth errors for me in  
    'v_HumanRetinalIlluminance580nm'
     v_oi.
An exception arises in 'v_sceneExamples' based on 'interpolant'

I think you are all on top of these issues, and hence we are almost back together. I hope this summary is helpful.

Separately, when this settles down I will merge in the changes that eliminate all p-files.  That branch (pfile) is sitting wait for me to merge in.

**Comment by hjiang36** [comment]
I add a few lines in sceneSet(scene, 'wave') to handle the inconsistency of 'spectrum' vs wavelength sample vectors. Now, sceneSet(scene, 'wave') will check if the input is spectrum structure or wavelength vector.

v_sceneExamples, v_oi and v_HumanRetinaIlluminance580nm works fine on my computer now.

**Comment by DavidBrainard** [comment]
v_sceneExamples now works for me too.

v_oi and v_HumanRetinaIlluminance580nm still fail their validation tests.  It is a mystery to me how they can work for Haomiao.  They have fewer problems now, but there is still a transpose problem with the wavelength sampling, as per validation report for v_oi below (same thing happens for the other one too).

nternal validation  : PASSED
	Run-time status      : no exception raised
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users/Shared/Matlab/Toolboxes/isetbio/validation/data/fast/optics/v_oi_FastGroundTruthDataHistory.mat
	Fast validation      : FAILED against ground truth data of 06-Feb-2015 13:28:31.
	 > Ground truth info : wal-isc-video012.isc-video.upenn.edu / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   :            ray.PSYCH.UPENN.EDU / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'dhb'
	DataHash-this run    : ac8c83812678e0a3351409d099b08b8756037ebb63658ca68cb19664fe8f6ffe
	DataHash-groundTruth : 8f3dec3e1a5439f62a9e878882c9a06417cc46f43755b84ae18cbc00ec8be012
	---------------------------------------------------------------------------------------------------------------------------------
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users1/Shared/Dropbox/ISETBIOFullValidationData/optics/v_oi_FullGroundTruthDataHistory.mat
	Full validation      : FAILED against ground truth data of 05-Feb-2015 14:12:32.
	 > Ground truth info : wal-isc-video012.isc-video.upenn.edu / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   : ray.PSYCH.UPENN.EDU            / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'dhb'
	[data mismatch  1]   : 'groundTruthData.humanOI.optics.OTF.wave' is a [ 1  31  ] matrix whereas 'validationData.humanOI.optics.OTF.wave' is a [31   1  ] matrix.
 	[data mismatch  2]   : 'groundTruthData.humanOIFromScene.optics.OTF.wave' is a [ 1  31  ] matrix whereas 'validationData.humanOIFromScene.optics.OTF.wave' is a [31   1  ] matrix.
 	Note (*)             : script does not store any extra data.
	Validation report    :

**Comment by DavidBrainard** [comment]
I am just posting this here, for lack of a better place.

I just ran and published all the tutorials and everything ran to completion.  I did this with a minimal path configuration, consisting of just Matlab, signal, image processing, isetbio, and UnitTestToolbox.  Yay!

**Comment by hjiang36** [comment]
I just mean v_oi and v_HumanRetinaIlluminance580nm runs without errors, but still they are not consistent with the ground truth data. Because OTF.wave field is still transposed, I didn't expect the validation against ground truth to pass.

**Comment by DavidBrainard** [comment]
Now I am confused.  Isetbio's convention is for wave to be row vector.  And, that is what we get when we do something like ieReadSpectra.

But at present sensor = sensorCreate; sensorGet(sensor,'wave') is returning a column vector.  

I suspect that is at the root of the current spate of little problems.  For sure, we want it only one way throughout.  I can live either way, but I need it to be the same everywhere.   My suspicion is that the row vector convention is very deeply embedded and that we don't want to change now.

In any case, the current behavior (can't count on it being consistent) is causing me trouble by the minute so we should definitely decide soon.

**Comment by hjiang36** [comment]
In my memory, we use wave as column vector in most of the places (display, scene, oi, sensor and a lot more). Also, ieReadSpectra returns wave samples in columns and accept wave input both as column or row vectors.

I'm not sure which structure uses wave as row vector now. Fixing row vector to column vector sounds much easier to me at least. I know there is an XW format which put wavelength samples in rows. But that's not the same story as wave field to me.

**Comment by DavidBrainard** [comment]
Let’s see what Brian says.  The row vector convention is implemented in ieReadSpectra and I’m not sure where else.  Up until recently, I think it has consistently been a row vector whenever I looked (and was a row vector previously for the oi stuff, as per the now failing validations.)

**Comment by wandell** [comment]
I am wondering what Brian will say, too.   

In recent years, I have always defaulted to column vectors (since I have known Haomiao).  But it is quite possible that in earlier years, I was either sloppy or tended to row vectors (since I have known David).  

The XW decision had more to do with computation that row/col for wave.  Let's ignore that.

What do you guys want to do?  It seems to me that in modern practice, when unsure declare something a column vector.  Will that be horrible for ISETBIO coding?  Or easy?  If it is easy, I am all for it.

**Comment by wandell** [comment]
Oh, and by the way ... at one point I said that the oiCreate() bug wasn't present in ISET.  That was wrong.  It is there in the same way.  When I simplified the test script I could see the same confusing behavior.

**Comment by chichilnisky** [comment]
I got used to row vector notation because in other languages it's more efficient (because of row-major order indexing of 2D arrays) and/or less indexing bookkeeping (a single index instead of two for a row vector) and/or a tiny bit more natural for thinking about and displaying sequential multi-variate measurements (new measurement, new row ...).  But I guess that in Matlab, either way is equally natural.

ej

**Comment by DavidBrainard** [comment]
The main thing that I care about is that the conventions be consistent and stable within isetbio.  Once that is true I can work with it just fine.  Changing breaks things.

My impression has been that in isetbio, sensitivities are column vectors and spectra are row vectors, so that spectra*sensitivities*deltaLambda computes responses, with the deltaLambda needed because isetbio uses units of power per nm.  And that wave was a row vector to match the convention for spectra.  With this convention, vectors of sensor responess are row vectors and color transformation matrices are set up to be applied from the right to row vectors of sensor responses.   There is a consistent convention for applying the same color transformation matrices to images.  I could be wrong about all this, but until the recent switch in the convention in wave it seemed like a good working hypothesis.

If I am correct about all of the above, I would recommend leaving wave a row vector, just because having a stable convention seems good.  But I can live with changing wave to a column vector.   If we change, I will have to patch up some code that interfaces with PTB and redo some of the validation data.  Those are not too hard.

But,  If I am correct about the row/column conventions for sensitivities and spectra in isetbio, I think changing spectra to column vectors would break many things within isetbio.  I would leave this alone.

PTB has its own conventions.  (Wavelengths are column vectors; spectra are column vectors; sensitivities are row vectors.  Thus sensitivities*spectra computes responses.  [In PTB, spectra are specified as power per wavelength band.]  With this convention, vectors of sensor responses are column vectors (like spectra), and color transformation matrices are set up to be applied to column vectors of sensor responses.  There is a consistent convention for handling applying the same color transformation matrices to images.  Within the PTB world, these conventions are very consistently enforced.

I regard translating between ISETBIO and PTB conventions as mostly my problem, and am now pretty facile with it.

**Comment by DavidBrainard** [comment]
I regenerated the validation data for the two scripts that were failing because of the wave transpose.  Am closing this issue, and opening up a new one to remind us that we need to decide on how to handle whether wave is a row or column vector.
