### ISSUE TITLE
Older Matlab versions give error on Input Parser addParameter

### ISSUE THREAD

**Issue by jamesgolden1** [isetbio/isetbio#133]
A handful of my classmates at the CSHL workshop have told me they are getting errors on calls to addParameter by the input parser from isetbio. Apparently Matlab is aware of this:

http://www.mathworks.com/help/matlab/ref/inputparser.addparameter.html
http://www.mathworks.com/help/matlab/ref/inputparser.addparamvalue.html (the deprecated equivalent call)

Is there any easy way to make this backwards compatible for them? I will try to think of some sort of workaround in the meantime. It looks like all of the inputParser may be C functions, because addParameter.m is only comments.

**Comment by hjiang36** [comment]
I'm not sure if there is a simple fix for this problem. But a reasonable fix could be having a simple class in ISETBIO inherited from inputParser and overload the addParameter function. We need to change all the `p=inputParser;` statement to use the new class.

Besides, the function is added in Matlab 2013b, which sounds fairly old to me. I'm not sure what are the versions of Matlab do we want to support.

**Comment by wandell** [comment]
Seems like we are OK from 2013b onward.  I vote that we only support the last three years.  Can we close?

**Comment by DavidBrainard** [comment]
I like the last three years plan.

**Comment by jamesgolden1** [comment]
Agreed - closing this one.
