### ISSUE TITLE
Buglet in em position generating code

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#135]
If you set up a mosaic with rather coarse temporal sampling, the eye movements code crashes out.  The particular parameters I was using were 100 msec time steps and three frames.  I think the problem is that the em code implicitly assumes fine sampling in its generation of array indices, and with the longer parameters it generates array indices of 0, which Matlab not being C, is unhappy with.

**Comment by hjiang36** [comment]
I made a simple fix to the problem and make sure the index start from 1.
Hope it would be fine.

**Comment by DavidBrainard** [comment]
This fixed the problem.  Thanks.

David
