### ISSUE TITLE
Cone packing density as a function of eccentricity

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#136]
Today, we discussed the need for a function of cone density from eccentricity to the periphery.  We have a function for RGC scaling (retinalLocationToTEE) based on Chichilnisky.

Here are references to relatively recent AO measurements of cone sampling by Burns, Carroll and others.

    As a function of age and eccentricity:
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3183974/
http://iovs.arvojournals.org/article.aspx?articleid=2165591
Variation of Cone Photoreceptor Packing Density with Retinal Eccentricity and Age
Hongxin Song, Toco Yuen Ping Chui, Zhangyi Zhong, Ann E. Elsner, and Stephen A. Burns

    Follow up and extension
http://www.sciencedirect.com/science/article/pii/S0002939415002378
Variability in Human Cone Topography Assessed by Adaptive Optics Scanning Laser Ophthalmoscopy Tianjiao Zhanga, Pooja Godarab, Ernesto R. Blancob, Russell L. Griffinc, Xiaolin Wangb, Christine A. Curciob, Yuhua Zhangb

    From Stockman
http://www.cvrl.org/database/text/intros/introdens.htm
http://www.cvrl.org/database/text/density/cones.htm

    Eccentricity dependent changes of density, spacing and packing arrangement of parafoveal cones
Marco Lombardo, Sebastiano Serrao , Pietro Ducoli1 and Giuseppe Lombardo
http://www.inviewmedical.pl/wp-content/uploads/2015/08/2013.03-OPO-Lombardo-Eccentricity-dependent-changes-of-density-spacing-and-packing-arrangement-of-parafoveal-cones.pdf

    Variations with refractive error
Individual Variations in Human Cone Photoreceptor Packing Density: Variations with Refractive Error. Toco Yuen Ping Chui; HongXin Song; Stephen A. Burns
http://iovs.arvojournals.org/article.aspx?articleid=2125900

    On reliability
The Repeatability of In Vivo Parafoveal Cone Density and Spacing Measurementsa
Robert Garrioch, BS, Christopher Langlo, BS, Adam M. Dubis, BA, Robert F. Cooper, BS, Alf Dubra, PhD, and Joseph Carroll, PhD
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3348369/

    Classic Curcio
https://cis.uab.edu/sloan/PRtopo/Curcio_JCompNeurol1990_PRtopo_searchable.pdf

**Comment by hjiang36** [comment]
A function might be relevent in ISETBIO is [coneDensity](https://github.com/isetbio/isetbio/blob/master/isettools/deprecate/cone/coneDensity.m). That's in the old version of ISETBIO and is deprecated now.

The new version of this function is [photoPigment.eccDensity](https://github.com/isetbio/isetbio/blob/master/isettools/conemosaic/%40photoPigment/photoPigment.m) recently. 

We might update the code to incorporate the new data.

**Comment by wandell** [comment]
Thanks, I needed that information.

I added the new coneDensity data sets from Burns and updated the photoPigment.eccDensity function a bit for inputParser usage, and to allow switching between the data sets (which are nearly identical).

The extrapolation into the central fovea for the Curcio data set goes all the way to 250,000 cones per square millimeter.  Is that right?  Let's talk over tomorrow.  Apart from how to extrapolate to 0, we have excellent agreement everywhere.

Then we can use the density function to set the size of the cones when we call coneMosaic, and this bit will be done.

**Comment by wandell** [comment]
Oh, I forgot to say that I did this on a new conedensity branch that I will push shortly.

**Comment by fmrieke** [comment]
> The extrapolation into the central fovea for the Curcio data set goes all the way to 250,000 cones per square millimeter. Is that right? Let's talk over tomorrow. Apart from how to extrapolate to 0, we have excellent agreement everywhere.

This sounds right - 250,000 cones/mm^2 corresponds to a spacing between cones of 2 microns, which is about right.  

Fred

**Comment by wandell** [comment]
Good, thanks.  I can make that adjustment easily to the Burns data.  Will coordinate with HJ and add some function testing tomorrow, and then insert into the coneMosaic object.

**Comment by wandell** [comment]
A few more notes - mainly to self and HJ 
250,000 cones/mm2 is about 145 cones per linear degree (145/0.29 ~500).  A little high, I think.  We should be around 120 cones per degree at max, which is about 170,000.  Some histology estimates are bit lower, around 120,000, which is about 100 cones per degree.  This is also consistent with some psychophysics.  The main point:  we need to insert some flexibility into the generation of cone densities.

Also, the photoPigment.width/height and so forth has a lot of legacy stuff (pdWidth, pdHeight) that we need to eliminate.  Left over, I think, from the pixel structure.  So let's get that out of there.  The ability to set the size of the cone is a next step.  I am also worried about calling the object photoPigment and yet it contains cone information.

So, a few things to talk over.

Note: 0.29 mm per degree is what we have mainly been using, though that depends on accommodation and runs as high as 0.31 mm per degree.  In that case, 500 cones per mm is 155 cones per deg, which is even higher.

**Comment by DavidBrainard** [comment]
We will also need the ability to vary cone density across the mosaic patch, for larger patches.  Is that what you are implementing, or are you staying with the small patch (constant density across patch) approximation?

Nicolas has an algorithm for generating mosaics whose density follows some functional form (I'm not sure which) and that also introduces irregularity in some reasonable manner.

Do we have (and do we want) a plan for representing eccentricity dependent cone parameters (aperture, axial density) and calculating in a space variant manner?

Best,

David

**Comment by npcottaris** [comment]
(1) We are also interested in hexagonally-packed, density varying patches. My algorithm takes as input an arbitrary 2d cone spacing function. It begins by generating a perfect hexagonal mosaic of the highest specified density and then samples from it according to the desired cone spacing distribution. Next it iteratively adjusts the cone positions so as to approximate the desired spacing at each point in the mosaic. The result is a density-varying, hexagonal mosaic with various singularity points (with 5 or 7 neighbors), resembling what we see with AO. 

Here is a link to a video showing the mosaic generation process. 
https://www.dropbox.com/s/u7i8rvncx7vn7nn/hexMosaicGeneration.m4v?dl=0

Please download the video and play it in QuickTime. 
[Some times it is better to manually move the progress bar on the bottom to better visualize the progress.]

The developing LMS mosaic is shown on the left, whereas its triangularization is shown on the right. The shade of the triangles denote the degree to which they approximate isosceles shape, i.e. perfect hex mosaic. The Yellow line superimposed on the mosaic shows the achieved cone spacing as a function of eccentricity, whereas the correspondence between achieved and desired cone spacing is shown as a red scatter plot at the bottom. 

(2) I am beginning to implement density-varying hexagonally-spaced isetbio come-mosaics prototypes. My question is the following. Do we want to add this functionality in the coneMosaic class (A), or do we want a new class, say hexConeMosaic (B)? The advantage of solution (A) is that we can don't have to replicate code in another class, but it will make the coneMosaic class a bit more crowded. The advantage of solution (B) is that we will have cleaner code, but we would need to maintain two classes. Another solution (C) would be to subclass coneMosaic, but that requires substantial reorganization of coneMosaic (like making certain dependent variables protected etc), which could get messy. I am currently voting for solution (B), because classes will be cleaner, easier to understand, albeit at the expense of some extra maintenance. Any suggestions?

**Comment by wandell** [comment]
Thanks, interesting.  Thoughts here.

I think we might consider hexagonal and large, space-varying as two separate issues.  

I agree that coneMosaicHex as a separate class is better.  I would like to see comparisons between rect and hex evaluated on patches in the presence of optics and noise and eye movements.  If we get a first implementation, I could propose this for a fall class project.  Perhaps you could remotely mentor.

There are many computational issues to large and space varying.  So the research question determines the cost benefit of doing this much more complex implementation.  Having it available for some purposes seems great.  But the complexity also makes me suspect we don't want to burden all our software development with the additional complexity whenever we add features such as plotting and ROI analyses (which are coming).

In sum, I vote with you for B.

**Comment by DavidBrainard** [comment]
I think we might further separate more realistic cone locations from space varying.  That is, I don't imagine that it is too much of a burden to the current mosaic object to have some function that fills in the locations of cones according to a realistic model of how they'd look over that patch of retina.  And this function wouldn't need to be concerned about the size of the patch, and could happily round location to the nearest point on the rectilinear grid.  I think we would get some useful mileage out of that, particularly with respect to things like integration area calculations and providing Horwitz and DiCarlo with useful calculations for the eccentricity adventures.

I think this would be a valuable even if we neglect changes in cone light capture properties and space varying blurring by inner segment diameters.  So I think this functionality could and probably should be added to the current cone mosaic object.  I would think this would allow the comparison between hex sampling and rectangular sampling, when both were expressed on a rectilinear grid.  And unless I'm missing something, it wouldn't make the object much heavier, it would just be one more option about how to set the cone positions and types.

Presumably we could also set cone aperture and other parameters to match an average for whatever patch of retina was being examined.

I agree that anything fancier, including shift varying computations, should go into a new object.  I am not sure whether we want to tackle those right now - I just had the cone spacing model in mind when I suggested it.

David

P.S. Do we currently blur by the cone apertures?  We probably should fold that in as an option to coneMosaic.   It's a small but not completely trivial effect.

**Comment by npcottaris** [comment]
I also thought about rounding to the nearest rectangular mosaic, but I was concerned about the memory footprint/Compute time for mosaics that would be much much larger, with loads of blank sensors. But we can try it as a first approach.

N.

On Jul 22, 2016, at 8:33 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:

I think we might further separate more realistic cone locations from space varying. That is, I don't imagine that it is too much of a burden to the current mosaic object to have some function that fills in the locations of cones according to a realistic model of how they'd look over that patch of retina. And this function wouldn't need to be concerned about the size of the patch, and could happily round location to the nearest point on the rectilinear grid. I think we would get some useful mileage out of that, particularly with respect to things like integration area calculations and providing Horwitz and DiCarlo with useful calculations for the eccentricity adventures.

I think this would be a valuable even if we neglect changes in cone light capture properties and space varying blurring by inner segment diameters. So I think this functionality could and probably should be added to the current cone mosaic object. I would think this would allow the comparison between hex sampling and rectangular sampling, when both were expressed on a rectilinear grid. And unless I'm missing something, it wouldn't make the object much heavier, it would just be one more option about how to set the cone positions and types.

Presumably we could also set cone aperture and other parameters to match an average for whatever patch of retina was being examined.

I agree that anything fancier, including shift varying computations, should go into a new object. I am not sure whether we want to tackle those right now - I just had the cone spacing model in mind when I suggested it.

David

P.S. Do we currently blur by the cone apertures? We probably should fold that in as an option to coneMosaic. It's a small but not completely trivial effect.

**Comment by npcottaris** [comment]
Started a new branch (pseudohex) to work on these ideas.

**Comment by DavidBrainard** [comment]
With respect to the simple approach, we can currently compute with, say, a 1.5 degree fully packed rectangular mosaic at roughly central foveal density.  I think it would be of some use to be able to fill that same rectangular grid with a more realistic cone mosaic.  It's true that we would then be inefficient, computing a bunch of zero responses at non-cone locations.  But this would let us capture the effect of density at least for some cases.

For the fancier hex stuff, I wonder if Matlab's sparse matrix type would help us.

**Comment by wandell** [comment]
1. We do already have the ability to put in 'null' cones.  We use the letter 'K" to indicate a blank cone, and that has been around for quite some time.  So, one less thing for us to do.

2. I agree that we seem capable of computing 1-2 deg at central fovea packing densities.  If we wait a year or two, and buy new computers, that will go faster.  Now it is OK, but sometimes gives me an excuse to get a cup of coffee.

3. Blurring by the cone aperture itself is not implemented.  Also, we do have some potential for Stiles-Crawford, which is part of the wavefront calculation, but that isn't included here yet either.  We could and I will take it up with @hjiang36 This requires being able to specify the relationship between the cone and the angle of the rays.  For small patches, it might be good enough to treat the whole bundle of rays as having a single angle (to the center of the lens) and scaling by that.  For larger arrays, well, that's someone else's problem.

**Comment by DavidBrainard** [comment]
Also sounds good! Before jumping too far into coding, let's fold these topics into the same conversation as you set up with your previous message.  We should probably Skype and get Nicolas in on it too.

Enjoy our wonderful east coast weather, in which we revel.

**Comment by npcottaris** [comment]
**HEXAGONAL CONE MOSAICS  FINALLY ARRIVE AT AN ISETBIO INSTALLATION NEAR YOU**

Hello,

There is a new isetbio branch, **pseudohex**,  which contains, a new cone mosaic class, named `coneMosaicHex` which generates hexagonal cone mosaics. The generated mosaics are not true hex cone mosaics, i.e., they are not defined on a hex grid.  Instead they derived from a perfect hex grid which is sampled by a fine scale rectangular grid, whose resolution is user-defined. This is achieved by defining a high-resolution `coneMosaic` instance with select cones being L, M or S, 
whereas all the other cones are null.

The `coneMosaicHex` class is a subclass of `coneMosaic`, and thus it inherits all the methods and properties of `coneMosaic`.

In the current version of `coneMosaic`, cone separation and pigment width were one and the same. This had to be changed in order to have hex-positioned LMS cones whose aperture is independent on the packing of the underlying higher resolution rectangular grid.

To achieve this, I revised `coneMosaic`, by introducing a new property, `patternSampleSize`, which defines the high resolution cone spacing, leaving the pigment size to be independent of cone spacing. In the `coneMosaic` constructor, `patternSampleSize` is by default set to the `pigment width/height`, and from there on, `patternSampleSize` is used wherever pigment width/height was used to compute geometry params. Methods in `coneMosaicHex`, leave the pigment width to the same value as that set by `coneMosaic`, but change the `patternSampleSize`, so as to sample the hexGrid at different resolutions. 

I will next post images of generated hex mosaics and relevant figures. All these can be generated online by running the three tutorials found in `tutorials/coneMosaicHex` (again in the pseudohex branch)

**Comment by npcottaris** [comment]
The following code segment, will generate a hex mosaic from a 16x16 rect mosaic, (generated via `coneMosaic`), using a perfect hex grid that is sampled at 5 times the native resolution of the rect mosaic.
```
mosaicParams = struct(...
      'resamplingFactor', 5, ...
                  'size', [16 16], ...
        'spatialDensity', [0 0.62 0.31 0.07]...
    );
% Generate the hex mosaic
theHexMosaic = coneMosaicHex(mosaicParams.resamplingFactor, ...
                   'size', mosaicParams.size, ...
         'spatialDensity', mosaicParams.spatialDensity ...
);
```
Here is the generated grid, visualized  using a `coneMosaicHex` methods.
![fig1](https://cloud.githubusercontent.com/assets/3444212/17119549/43c6ef56-52cf-11e6-93aa-a0c482dc1d9e.png)

**Comment by npcottaris** [comment]
The originating rect mosaic can be visualized as follows:
```
theHexMosaic.visualizeGrid(...
    'showCorrespondingRectangularMosaicInstead', true...
    );
```
which gives the following:
![fig2](https://cloud.githubusercontent.com/assets/3444212/17119698/30bfd584-52d0-11e6-9494-e5bc6ebc715a.png)

Note that the hex mosaic is replicating the identify of the originating mosaic cones.

**Comment by npcottaris** [comment]
One can visualize the perfect hex grid that was used as follows:
```
theHexMosaic.visualizeGrid(...
    'panelPosition', [2 2], ...
    'overlayPerfectHexMesh', true...
    );
```
which gives the following:
![fig3](https://cloud.githubusercontent.com/assets/3444212/17119797/c394d53a-52d0-11e6-847d-387d449499e5.png)

**Comment by npcottaris** [comment]
Note that many cones do not fall exactly on the nodes of the perfect grid. This can be changed by increasing the `resamplingFactor`. Here we used 5, but we can change that. 

Before doing that, however, lets also visualize (the null cones) as follows:
```
theHexMosaic.visualizeGrid(...
    'overlayNullSensors', true...
    );
```
which gives the following:
![fig4](https://cloud.githubusercontent.com/assets/3444212/17119915/a8898992-52d1-11e6-8f3e-92ee3e2938c4.png)

**Comment by npcottaris** [comment]
OK, now lets increase the resamplingFactor to get a better hexagonal mosaic. Let's go to a factor of 11, as follows:
`theHexMosaic.resampleGrid(11)`

which gives:
![fig5](https://cloud.githubusercontent.com/assets/3444212/17120016/491843d0-52d2-11e6-9fc4-d2081d421068.png)

This looks almost perfect. Indeed, if we overlay the employed hex grid, we get:
<img width="995" alt="fig6" src="https://cloud.githubusercontent.com/assets/3444212/17120077/96927644-52d2-11e6-8dfe-adcc40825195.png">

**Comment by npcottaris** [comment]
How about putting hex grids to work? Here we define two L-only (48x48) mosaics: a rectangular mosaic, and a hex mosaic with resamplingFactor of 7.

```
mosaicParams = struct(...
      'resamplingFactor', 7, ...
                  'size', [48 48], ...
        'spatialDensity', [0 1 0 0], ...
             'noiseFlag', false ...
    );

theRectMosaic = coneMosaic( ...
                   'size', mosaicParams.size, ...
         'spatialDensity', mosaicParams.spatialDensity, ...
              'noiseFlag', mosaicParams.noiseFlag ...
);

theHexMosaic = coneMosaicHex(mosaicParams.resamplingFactor, ...
                   'size', mosaicParams.size, ...
                'pattern', theRectMosaic.pattern, ...
         'spatialDensity', mosaicParams.spatialDensity, ...
              'noiseFlag', mosaicParams.noiseFlag ...
);
```
Below are the isomerization response maps of these 2 mosaics for the Ring rays scene (see `t_coneMosaicHex3.m` for more details).

<img width="1375" alt="fig10b" src="https://cloud.githubusercontent.com/assets/3444212/17120400/b5105b84-52d4-11e6-91f1-4b630e429738.png">

**Comment by npcottaris** [comment]
And here are the isomerization response maps for the Vernier stimulus:

<img width="1365" alt="fig10c" src="https://cloud.githubusercontent.com/assets/3444212/17120467/2ce72f70-52d5-11e6-893f-0e052748d064.png">

**Comment by npcottaris** [comment]
Here are isomerizations responses of LMS versions of these mosaics (densities: 62/31/7) for the Vernier stimulus.

![fig10d](https://cloud.githubusercontent.com/assets/3444212/17120560/c59beb7a-52d5-11e6-9c16-3e9d9d6fcc3b.png)

**Comment by npcottaris** [comment]
And finally, here are the L,M, S cone sub mosaic (hex) isomerization response maps plotted separately, again for the Vernier stimulus.

![fig10e](https://cloud.githubusercontent.com/assets/3444212/17120647/5ace7820-52d6-11e6-8a44-a18818760439.png)

**Comment by npcottaris** [comment]
This is all for now. Sorry for the barrage of github notifications.

Nicolas

**Comment by wandell** [comment]
Thanks!  That is really impressive.  I will have a look at the computations and your tutorial in the next few days.  The functionality and images look great!

**Comment by npcottaris** [comment]
Thanks ! 

I am eagerly awaiting your (and other people's) comments. There are four` t_coneMosaicHex 1-4` tutorials that you can try. I am adding below the output of `t_coneMosaicHex4`, which demonstrates the coneMosaicHex's own mosaic activation visualization method. These maps are in response to an achromatic Gabor stimulus, and responses from all sub mosaics and from the total mosaic are all plotted using the same response scale (see colormap on the bottom right).

Nicolas
<img width="1399" alt="gabormosaicactivations" src="https://cloud.githubusercontent.com/assets/3444212/17216869/0e8bcac8-54eb-11e6-963f-9f989570a5ef.png">

**Comment by npcottaris** [comment]
Here is another example: Vernier scene isomerizations, now visualized using an achromatic color map,

```
theHexMosaic.visualizeActivationMaps(...
    isomerizationsVernier, ...
    'signalName', 'isomerizations (R*/cone/integration time)', ...
    'figureSize', [1550 950], ...
    'mapType', 'modulated hexagons', ...   % choose between 'density plot', 'modulated disks' and 'modulated hexagons''
    'colorMap', bone(1024) ...
    )
```
which produces the following figure:

<img width="1536" alt="verniermosaicactivationshex" src="https://cloud.githubusercontent.com/assets/3444212/17246487/15024de6-5595-11e6-8659-4ee50be0dd2f.png">

Again, zoom in into the figure to appreciate the fine details.

**Comment by chichilnisky** [comment]
I’ve not followed this thread closely, but it’s great that you’re working hard on a realistic cone mosaic. That has seemed like a limitation since we began with the serious RGC implementation.

Questions:
1) are the S cones on their own lattice? That certainly seems to be the physiological reality.
2) is the lattice jittered? That seems obvious and easy but I’m just checking


ej

On Jul 28, 2016, at 7:49 AM, Nicolas Cottaris <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks !

I am eagerly awaiting your (and other people's) comments. There are fourt_coneMosaicHex 1-4 tutorials that you can try. I am adding below the output of t_coneMosaicHex4, which demonstrates the coneMosaicHex's own mosaic activation visualization method. These maps are in response to an achromatic Gabor stimulus, and responses from all sub mosaics and from the total mosaic are all plotted using the same response scale (see colormap on the bottom right).

Nicolas
[gabormosaicactivations]<https://cloud.githubusercontent.com/assets/3444212/17216869/0e8bcac8-54eb-11e6-963f-9f989570a5ef.png>

**Comment by wandell** [comment]
@npcottaris 
I don't seem to have the pdist2 function. It appears to be a relatively new Matlab function (after 2013b, which I am running).

I see it on FileExchange (link below).  So our options are either to install as external or to see when it first appears in Matlab and set that as our lower bound.

Let me know you what you think.

https://www.mathworks.com/matlabcentral/fileexchange/29004-feature-points-in-image--keypoint-extraction/content/FPS_in_image/FPS%20in%20image/Help%20Functions/SearchingMatches/pdist2.m

**Comment by npcottaris** [comment]
Hmmm ...
My Matlab's docs (2015b) say it was introduced in 2010a and it is part of the Statistics toolbox.
It exists in `/Applications/MATLAB_R2015b.app/toolbox/stats/stats/pdist2.m`, but it calls a MEX file which is hidden.

Let me evaluate alternatives (including the one you sent) and will get back to you.

Thanks,
Nicolas


------------

From Matlab's 2015b documentation:

pdist2

Pairwise distance between two sets of observations
Syntax

D = pdist2(X,Y)
D = pdist2(X,Y,distance)
D = pdist2(X,Y,'minkowski',P)
D = pdist2(X,Y,'mahalanobis',C)
D = pdist2(X,Y,distance,'Smallest',K)
D = pdist2(X,Y,distance,'Largest',K)
[D,I] = pdist2(X,Y,distance,'Smallest',K)
[D,I] = pdist2(X,Y,distance,'Largest',K)

 blah blah ...

See Also
createns | ExhaustiveSearcher | KDTreeSearcher | knnsearch | pdist
**Introduced in R2010a**

**Comment by wandell** [comment]
Ah, that's it.  I don't have the statistics toolbox.

B


Stanford
Sent from mobile device

On Jul 29, 2016, at 11:25 PM, Nicolas Cottaris <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm ...
My Matlab's docs (2015b) say it was introduced in 2010a and it is part of the Statistics toolbox.
It exists in /Applications/MATLAB_R2015b.app/toolbox/stats/stats/pdist2.m, but it calls a MEX file which is hidden.

Let me evaluate alternatives (including the one you sent) and will get back to you.

Thanks,
Nicolas

________________________________

From Matlab's 2015b documentation:

pdist2

Pairwise distance between two sets of observations
Syntax

D = pdist2(X,Y)
D = pdist2(X,Y,distance)
D = pdist2(X,Y,'minkowski',P)
D = pdist2(X,Y,'mahalanobis',C)
D = pdist2(X,Y,distance,'Smallest',K)
D = pdist2(X,Y,distance,'Largest',K)
[D,I] = pdist2(X,Y,distance,'Smallest',K)
[D,I] = pdist2(X,Y,distance,'Largest',K)

blah blah ...

See Also
createns | ExhaustiveSearcher | KDTreeSearcher | knnsearch | pdist
Introduced in R2010a

-

**Comment by npcottaris** [comment]
E.J.,

Currently, the publicly available isetbio code produces regular hex mosaics. But I have developed code, which I will be introducing to isetbio next week, that generates hex mosaics with 
-semiregular S-cone sub mosaics (generated by forcing a minimum distance between S-cones)
-local irregularities, in which some cones may have 5 or 7 neighbors
-abrupt changes in mosaic orientation 
-gradients of cone spacing as you march across the mosaic 

Spatial jitter is trivial (as you say) and will also be added.

I am attaching a demo mosaic that demonstrates all that. The triangularization on the right, shows regions where irregularity is high (the darker a triangle is the more it differs from isosceles).

![demomosaic](https://cloud.githubusercontent.com/assets/3444212/17268656/95469a58-5639-11e6-8f05-2f473320ae5d.png)

**Comment by npcottaris** [comment]
So, do we want to make the statistics toolbox a requirement, or do we want to be independent of it?

**Comment by npcottaris** [comment]
@wandell : In my tests, the `pdist2` from Matlab Exchange is about 10 times slower than Matlab's own `pdist2`. Moreover, even for medium sized mosaics (0.4 x 0.4 degrees), the ME `pdist2` causes an out-of-memory error. The two function produce same results, it is just that Matlab's `pdist2` is optimized.

Looking for other alternatives ... unless, we want to make the Stats Toolbox a requirement.

**Comment by DavidBrainard** [comment]
I am in favor of using the statistics toolbox.

**Comment by npcottaris** [comment]
I am writing a mex file just in case. The computation is pretty simple anyway.

N.

On Jul 30, 2016, at 3:34 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:

I am in favor of using the statistics toolbox.

**Comment by DavidBrainard** [comment]
OK. Mex files bring their own set of distributional woes, but it is a different set.

**Comment by wandell** [comment]
I spent some time reading through parts of the coneMosaicHex subclass and running the test cases on a machine with the statistics toolbox.  Congratulations!  Really great implementation and new functionality!  

In addition to the scripts you had us run through, I added eye movements and did some timing.  The eye movements seem to run through well, nothing obviously wrong but we can keep checking.  (There is an issue with eye movements and Integration time that I fixed elsewhere and we will need to apply here).

The visualizations in the window need work, but that's true for the basic coneMosaic, not just the coneMosaicHex.

The ability to select a nonfoveal local region is something we are adding (specify the patch center), and we should coordinate on that with the coneMosaicHex.

There are (of course) new issues to discuss that we should chase down.  But I think this particular issue should be closed and we should open up the following two.

1.  Do we allow in the statistics toolbox for ISETBIO?  (I am OK with that, but we should issue/discuss).

2. The visualizations in the 'window' player. I should say what some of the problems are, and then we can all work on them.

3.  A little about the code organization - A lot of functions are buried inside the main class (coneMosaic) and I want to discuss when we should leave them in the m-file and when we should pull them out into separate files.  I kind of like the separate files in the @<> folder because they are more easily findable for me.

4. Is it OK to merge the Hex class in already ... As near as I can tell you did a very nice job of writing it so that it does not impact any of the other code.  So, I think it would be OK to clean a little and then merge the branch.

I will wait to hear - but if there are no objects I will close this issue and start the others.  This thread seems at end of useful life.

Very exciting!

**Comment by npcottaris** [comment]
I am starting the statistics toolbox issue.

**Comment by npcottaris** [comment]
The coneMosaicHex has its own visualization routines that are quite nice (I think).
Perhaps we should bring these in the coneMosaicWindow interface.

**Comment by chichilnisky** [comment]
Nicolas,

Thanks for this message. I have been seeing the messages documenting this but I didn’t catch everything. It’s great, a bit of biological realism that is very desirable for the RGC implementation.

One thing which we should discuss including is clumping of cone types (as opposed to purely random L/M cones). This has been documented, I think in a Hofer paper.  The other important thing is the cone collecting area, which I think may also vary with eccentricity (I think there was a recent comment on this).

I was on vacation with my daughter for 10 days in Europe so I fell behind. Thanks for catching me up.

ej


On Jul 29, 2016, at 11:41 PM, Nicolas Cottaris <notifications@github.com<mailto:notifications@github.com>> wrote:


E.J.,

Currently, the publicly available isetbio code produces regular hex mosaics. But I have developed code, which I will be introducing to isetbio next week, that generates hex mosaics with
-semiregular S-cone sub mosaics (generated by forcing a minimum distance between S-cones)
-local irregularities, in which some cones may have 5 or 7 neighbors
-abrupt changes in mosaic orientation
-gradients of cone spacing as you march across the mosaic

Spatial jitter is trivial (as you say) and will also be added.

I am attaching a demo mosaic that demonstrates all that. The triangularization on the right, shows regions where irregularity is high (the darker a triangle is the more it differs from isosceles).

[demomosaic]<https://cloud.githubusercontent.com/assets/3444212/17268656/95469a58-5639-11e6-8f05-2f473320ae5d.png>

**Comment by DavidBrainard** [comment]
My recollection of the Hofer paper is that the clumping effect is very small, and not present in all of the subjects.

DB

**Comment by chichilnisky** [comment]
Yes, but we observed it as well in our recordings. It influences things like the “purity” of midget cell cone inputs nontrivially. Anybody who tries to simulate midget cell color properties would want to be able to play with this important parameter, given that two forms of data indicate that it’s nonzero.

ej

On Jul 31, 2016, at 12:30 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:

My recollection of the Hofer paper is that the clumping effect is very small, and not present in all of the subjects.

DB

**Comment by DavidBrainard** [comment]
Ah, OK.

**Comment by npcottaris** [comment]
**Eccentricity-based, spatially-varying cone density hex mosaics are now available**
Usage:
```
mosaicParams = struct(...
             'resamplingFactor', 7, ...               % controls the accuracy of the hex mosaic grid      
 'spatiallyVaryingConeDensity', true, ...             % whether to have a spatially - varying cone density
                   'centerInMM', [0.2 -0.2], ...      % 0.2 mm horizontal, 0.1 vertical
                         'size', [60 60] ...          % generate from a rectangular mosaic of 60x60 cones
  );

% Generate the spatially-varying cone density hex grid
theHexMosaic = coneMosaicHex(...
                   mosaicParams.resamplingFactor, ...
                   mosaicParams.spatiallyVaryingConeDensity, ...
         'center', mosaicParams.centerInMM*1e-3, ....
           'size', mosaicParams.size ...
    ); 
```

**Resulting grid:**
![vardensitygridnocontours](https://cloud.githubusercontent.com/assets/3444212/17458925/c6f9f8e8-5c2d-11e6-962e-ceb31d1d87c5.png)

**With cone density gradient superimposed**
![vardensitygrid](https://cloud.githubusercontent.com/assets/3444212/17458934/5d226544-5c2e-11e6-88fc-3be8560d6498.png)

**Equivalent grid without spatially-varying cone density:**
![constdensitygrid](https://cloud.githubusercontent.com/assets/3444212/17458933/353be33e-5c2e-11e6-9bc6-a9682e1f029f.png)

**Visualization of isomerization maps for the spatially-varying cone density hex grid (rays scene)**
![vardensityactivation](https://cloud.githubusercontent.com/assets/3444212/17458939/ac42a51c-5c2e-11e6-84a7-afbad68303cb.png)

**Visualization of isomerization maps for the constant cone density hex grid (rays scene)**
![constdensityactivation](https://cloud.githubusercontent.com/assets/3444212/17458940/b0d47fa6-5c2e-11e6-85d3-91f12354f3de.png)

For more info, please check out the `t_coneMosaicHex5` tutorial.

**Comment by wandell** [comment]
This contribution is truly wonderful.  I have run the code, read through parts of it, and I look forward to working with it (mainly to simplify, as is typical). 

The remaining aspects - such as the points EJ raises about clumping and so forth - can now be tested beautiful with this @npcottaris implementation by placing the LMS cones in different positions through the use of functions to set the statistical properties of the coneMosaic.pattern slot.  That seems like a separate and interesting issue.  Could be an analysis in a parallel repository.

So, I think we should all congratulate Nicolas on some really great work and close this issue.  And I like pressing close!

**Comment by DavidBrainard** [comment]
EJ has a simple algorithm which we can use to implement clumping when the time comes for that.  Probably not before the Simons meeting, given other things we need to do before then.

DB

**Comment by chichilnisky** [comment]
A wonderful contribution indeed!

It would be really nice to go over how you did this, and whether/how we can do the same varying-density operation in the ganglion cell simulation in a sensible way. Not before Simons, I think, but perhaps after. This seems pretty important for simulating a large foveally-placed stimulus.

ej

On Aug 7, 2016, at 4:18 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:


This contribution is truly wonderful. I have run the code, read through parts of it, and I look forward to working with it (mainly to simplify, as is typical).

The remaining aspects - such as the points EJ raises about clumping and so forth - can now be tested beautiful with this @npcottaris<https://github.com/npcottaris> implementation by placing the LMS cones in different positions through the use of functions to set the statistical properties of the coneMosaic.pattern slot. That seems like a separate and interesting issue. Could be an analysis in a parallel repository.

So, I think we should all congratulate Nicolas on some really great work and close this issue. And I like pressing close!

**Comment by DavidBrainard** [comment]
This is great.

Are the S cones regularly spaced here?  I recall a message saying that was implemented, but they don't look regular to my eye.

**Comment by npcottaris** [comment]
You are correct. The S-cones are not placed regularly here. Coming soon though.

Nicolas

On Aug 9, 2016, at 5:11 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:

This is great.

Are the S cones regularly spaced here? I recall a message saying that was implemented, but they don't look regular to my eye.
