### ISSUE TITLE
Return arg order in coneMosaic.plot

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#138]
The [h, uData] return order in coneMosaic.plot is flipped from that in scenePlot and oiPlot.  This might be intentional, based on a vision of the future where all plot functions use the [h, uData] order.  Or it might just be confusing.

**Comment by wandell** [comment]
I am working on that plotting function and I will change the order.  I opened a coneplot branch for this and a few other things (like ROI plots, plots along a line, and so forth).
So I assigned this to me.  

If you want to flip the order in the master now, just do it.  I will close this issue when we merge the coneplot branch.

**Comment by DavidBrainard** [comment]
I have made the change in the master branch.

**Comment by wandell** [comment]
HJ and I made the changes in other places.  Seems OK now in both master branch and in conedensity branch, where we are working.  Closing.
