### ISSUE TITLE
Strange state dependence in oiCompute

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#139]
I encountered a strangeness in using oiCompute, that I don't understand.  It may be related to object pass by reference changes, which in general makes me nervous despite the fact that my object oriented pals say it is the thing to do.

The problem is illustrated on the "bugdemo" branch of ISETColorDetect, file t_colorGaborScene.   Below is the code from lines 257-282 of that program.  Toggle variable OK to see how the output at the end (the computed cone contrasts from the mosaic resulting from the optical image held in variable gaborOI) change If I do an intermediate computation into gaborOI, and then subsequently replace it.  Maybe I am missing something obvious, but the only explanation I can think of for the effect is some state dependence in gaborOI that carries through from one call to oiCompute to the next.  

If this state dependence is OK and expected, I will need to change the way I think about programming with these objects, to avoid getting bitten by it.  If it is unexpected, we will want to track it down.

[I put this in a separate branch because it should run fine over a standard isetbio install.  I am working hard with Ben on project management tools that are coming into place in the dev branch and will soon merge these into the master.  But adopting them will require some configuration by users, so I didn't want that to be a burden in tracking this down.]

%% THIS ILLUSTRATES A PROBLEM.
%
% When OK is true, the final cone contrasts in the output are right.  But
% if we set it to false, they are not.  The only difference is whether we
% compute in place into gaborOI or give the result of the computer a new
% variable name.  Just below, we recompute the OI into variable gaborOI
% with optics turned off and then use that going forward, so I don't see
% why what we call the output of the computer here should matter. But it
% does.  This may be related to object pass by reference (which in general
% makes me very nervous) or some sort of state dependency in the oi object.
OK = true;
if (OK)
    gaborOIBlur = oiCompute(gaborOI,gaborScene);
    clearvars('gaborOIBlur');
else
    gaborOI = oiCompute(gaborOI,gaborScene);
end

%% HERE IS WHERE WE RECOMPUTE INTO gaborOI
% Turn off optics for current purpose of checking LMS contrast 
% This involves replacing the OTF with a unity OTF, and recompute
optics = opticsSet(optics,'OTF',ones(size(opticsGet(optics,'OTF'))));
gaborOI = oiSet(gaborOI,'optics',optics);
gaborOI = oiCompute(gaborOI,gaborScene);

%% SO HOW CAN THE CONDITIONAL ABOVE AFFECT ANYTING THAT FOLLOWS?

**Comment by benjamin-heasly** [comment]
Hi David,

I pulled the code and ran this on my end.  What I see is that `gaborOI` is a struct, not an object.  So it should have the familiar pass-by-value behavior.

The effect of `OK = true` should be to assign the updated `gaborOI` to a new variable, then clear that variable.  This should be equivalent to not calling `oiCompute` at all (on line 269).  So then the code would proceed with an "un-computed" `gaborOI` that looks like this:
```
           type: 'opticalimage'
           name: 'human-MW'
           data: [1x1 struct]
         optics: [1x1 struct]
       diffuser: [1x1 struct]
    consistency: 1
       wAngular: 4
```

The effect of `OK = false` should be to update the `gaborOI` struct with `oiCompute`.  In this case the code would proceed with a "computed" `gaborOI` that looks like this:
```
           type: 'opticalimage'
           name: 'rgb image - CRT-MODEL'
           data: [1x1 struct]
         optics: [1x1 struct]
       diffuser: [1x1 struct]
    consistency: 1
       wAngular: 4.9989
       distance: 0.5
       spectrum: [1x1 struct]
       depthMap: [160x160 double]
```

So I think the conditional has a big effect.  Which accounts for the change in contrast?

**Comment by DavidBrainard** [comment]
The difference in the two paths through the code is whether the first oiCompute has been put into a variable called gaborOIBlur or into a variable called gaborOI, and coming out of the conditional (say at line 280) the contents of gaborOI will indeed be different.

But then on line 282 there is a call to gaborOI = oiCompute(gaborOI,gaborScene), so at 283 the contents of gaborOI should be the same in either case.  But they aren't, because the contrasts printed out at the end of the program differ considerably in the two cases.

That is the mystery.  Why does the compute of gaborOI = oiCompute(gaborOI,gaborScene) on line 274 cause the results of the second compute to be different?

If you look at the top level of the structure in these two cases, it matches across the two ways.

I did verify by hand that the contents of the gaborOI.data.photons field are themselves different in the two cases, and that two runs of the good case with different rng() seeds produce the same gaborOI.data.photons value.

I remain stumped for now.

**Comment by hjiang36** [comment]
This issue is related to issue #131 .

The reason for this bug is that in oiCreate line 70. The created optics got a lens with empty wavelength samples.

I made a simple fix to this. I hope it also solve your problem.
If not, let me know.

HJ

**Comment by DavidBrainard** [comment]
Thanks!

This indeed seemed to fix the problem.  Could you say a little more about why having a lens with empty wavelength samples was causing the state dependence, just to satisfy my curiosity?

And then go ahead and close the issue.

**Comment by hjiang36** [comment]
The direct cause for this issue is from [oiSet line 256](https://github.com/isetbio/isetbio/blob/master/isettools/opticalimage/oiSet.m#L256).
This line states that if the new wavelength is the same as the existing wavelength, do nothing. In most cases, this will not cause a problem. But for this special case, though the wavelength samples are the same, we still need line 268 in oiSet to override the wavelength samples in the lens.

Here is a simple example to illustrate this problem (I ran it with the code before fix)
```
scene = sceneCreate;
oi = oiCreate('human');

oi1 = oiCompute(oi, scene);  # this makes oiGet(oi1, 'wave') not empty
oi2 = oi;  # oiGet(oi2, 'wave') is still empty

optics = oiGet(oi, 'optics');
optics = opticsSet(optics,'OTF',ones(size(opticsGet(optics,'OTF'))));
oi1.optics = optics;
oi2.optics = optics;

% To this point, both oi1 and oi2 have empty lens wavelength samples
% But oiGet(oi2, 'wave') is empty while oiGet(oi1, 'wave') is not
%
% After the next compute, due to the oiSet('wave') try to set the same wave to
% oi1, the oiSet function does nothing and does not set the wavelength samples for lens
% As a consequence, the lens transmittance is ignored for oi1
oi1 = oiCompute(oi1, scene);
oi2 = oiCompute(oi2, scene);

% See the difference
oi1.optics.lens   % this will have empty wavelength sample
oi2.optics.lens  % this will have wavelength sample same as the scene
```

To fix this problem, I think the best way is to make sure that the wavelength sample for lens is not empty and is the same as oi (or optics). Thus, we just change oiCreate to make sure it gives the lens the right wavelength samples at creation.

We might also want to flip the behavior in oiSet for setting the same wavelength. I haven't done that and I don't know if that's necessary.

Hope this is clear.

I'm closing this issue for now. Feel free to reopen it any time.

**Comment by DavidBrainard** [comment]
Thanks.  I think this particular bug illustrates two general issues of which we are already aware.  First, we have wavelength sampling specified in many places and don't have a systematic method of making sure it stays consistent.  Second, and more generally, we have some state dependencies in our structs and objects, and these can bite us in unexpected ways.
