### ISSUE TITLE
v_sceneExamples now fails, problem seems to be related to sceneGet(scene,'wave')

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#14]
v_sceneExamples now crashes.  It crashes when it tries to make the tungsten scene.

The problem seems to be that this code, in sceneCreate, produces an illuminant structure that is one too many levels indirected with respect to the wavelength specification.

% Create the scene variable
if isempty(args) || length(args) < 2 || isempty(args{2})
        scene = initDefaultSpectrum(scene,'hyperspectral');
else    scene = sceneSet(scene,'wave',args{2});
end
wave = sceneGet(scene,'wave');

The returned wavelength is a structure, with one field, wave.  So to get the a wavelength sampling, you have to ask for wave.wave.  Code further below then is unhappy, because it expects the wavelengths sampling to be accesed by just variable wave.  (That is what I also expect.)

Any ideas of what change might have produced this new behavior?

[I did check out a fresh version of isetbio, because of Brian's note that he thought the DOS attack on gitHub may have screwed up his local copy.  But that was not the problem.]

**Comment by wandell** [comment]
This one is my fault.

The code used to expect args{2} to be a spectrum, not wave.  But we were sending in wave from various places, and it crashed.  I thought I fixed it.  Apparently not.

I am not sure how this issue and the others you point out about optics OTF have come up.  Very puzzling to me.  

Let's do some investigating of the logs.


Stanford

**Comment by DavidBrainard** [comment]
Well, git is a win here.  I marched through the history and determined that v_sceneExamples broke sometime after the last commit Haomiao made on 4/10/15 (that version works) and before the last commit Brian made on 4/11/15 (broken in that version).

It could be that this problem is related to the wavelength stuff raised earlier in this issue, because the OTF field will get interpolated to match match the wavelength sampling, so if the wavelength samples got transposed then I think a bunch of other things in the OTF structure will as well.  So I'd focus first on the bug that we know roughly where it is and hope fixing it fixes everything else.
