### ISSUE TITLE
sceneFromRGB does not respect distance parameter of display, when display is passed.

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#140]
When I call gaborScene = sceneFromFile(gaborRGB,'rgb',[],display), where display has the viewing distance parameter set, the scene does not inherit the distance.  Seems like it should.

**Comment by hjiang36** [comment]
At line 160 and 167 of sceneFromFile, we set the scene distance to be the same as display viewing distance (Seems redundant though).

I did a simple experiment and the created scene distance do match the display distance.
Could you give an example that I can replicate the bug?

Thanks

**Comment by DavidBrainard** [comment]
My mistake.  It is working OK.  (I had done the displaySet in one place and then gotten confused and was testing in another.
