### ISSUE TITLE
Comments - happening at your local work station over the next few days.

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#143]
@jamesgolden1 is cleaning up the comments in the rgcMosaic functions.

He is checking that each of the different RGC types runs (GLM, LNP, Linear)

He is testing with simple input stimuli (moving bar, rings and rays, Gabor, Vernier, white noise followed by RF decoding, which is in an rgc-reconstruction repository somewhere.)

He will move the code for analyzing the Chichilnisky lab data into a separate repository for doing the analysis and getting the parameters.  Then we will use modified values of the parameters for foveal modeling.

**Comment by wandell** [comment]
@jamesgolden1 has moved the Chichilnisky lab analysis routines and test data into a separate repository

Testing and comments are in process, progressing.

**Comment by chichilnisky** [comment]
Since these emails serve as a form of record-keeping, I just thought I’d check with you guys about this.

Not sure what code this is referring to. I seriously doubt that any "Chichilnisky lab analysis routines” were ever in ISETBIO. The validation data certainly should remain in ISETBIO, of course. The routines to analyze them too, of course.

I don’t know what the “test data” are, nor do I know what “analysis routines” these are.

I’m sure you’ll sort it out but just thought I’d try to get clear on what’s what.

ej


On Aug 8, 2016, at 7:07 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:


@jamesgolden1<https://github.com/jamesgolden1> has moved the Chichilnisky lab analysis routines and test data into a separate repository

Testing and comments are in process, progressing.

**Comment by jamesgolden1** [comment]
EJ, we moved the code that runs a prediction from one of the experiments
from your lab into a new repository attached to isetbio. This is the code
that loads the parameters of GLM fits for a mosaic, as well as the
particular WN or NSEM stimulus file, into the isetbio Matlab object format.

James

**Comment by chichilnisky** [comment]
“Code that runs a prediction” - this sounds like GLM code, which I understood to be part of ISETBIO.

“code that loads the parameters” - this is needed for validation.

Not sure I agree with these choices. My understanding is that validation data and the code needed to analyze it are part of the package. Is the idea to have all validation data in separate repos? Sorry if I’m behind the curve on this.

ej


On Aug 8, 2016, at 8:22 PM, jamesgolden1 <notifications@github.com<mailto:notifications@github.com>> wrote:

EJ, we moved the code that runs a prediction from one of the experiments
from your lab into a new repository attached to isetbio. This is the code
that loads the parameters of GLM fits for a mosaic, as well as the
particular WN or NSEM stimulus file, into the isetbio Matlab object format.

James

**Comment by wandell** [comment]
A lot of ISETBIO related work is structured in satellite repositories.  The Brainard Lab has several, I have several, and these will expand.  There is a central core of routines that is not tied closely to any particular data set or experimental approach.  This code relates to basic physics, such as diffraction or photopigment isomerizations, that is general across any experimental condition.

The code for photocurrent testing, RGC testing, behavioral experimental analyses, and such are all in the satellite repositories.  The repository for analyzing the RGC data EJ obtained is now analyzed with the routines in this repository:

       https://github.com/isetbio/EJLExperimentalRGC

The code in this repository integrates tightly with ISETBIO code, and we will make changes that make sure they work smoothly together.  The experimental data that are used for this repository will be stored in the Remote archive, like all the rest of our data. We stopped putting data sets into github.

In the fullness of time, I expect we will do the same for other related and important work, such as data that test Fred’s photocurrent model.  As additional data come along for, say, wavefront aberrations or cone mosaic packing, or bipolar, we will again try to maintain the foundational calculations in ISETBIO and the routines that connect specific data sets and analyses with ISETBIO in satellite repositories.  

It is very much like separating out the basic python functions and then making the import mumble as foo call.  ISETBIO comprises the basic functions and the satellite repositories are what we import as needed.

The rationale is this:  There are many people who will use ISETBIO but do not need to have the RGC data or methods for deriving parameters from them.  People who want to explore those methods need only download a lightweight repository, and we will direct them to that code on the wiki pages.  In all cases the data will be on the remote archive, just as the validation are on that archive.

I hope you find this helpful and agreeable.

**Comment by chichilnisky** [comment]
This makes perfect sense, thank you for explaining.

I think I was confused about “Chichilnisky lab analysis routines” and “test data” moved into a “separate repository” (original message). That sounded to me like “stuff that doesn’t belong getting shipped out to Siberia”.

Instead it’s "RGC validation data and code being moved into a satellite repository".  This is exactly the clarification I was originally looking for.

If it’s not too late, I’d prefer the satellite repo to be called ChichilniskyRGCData.

ej


On Aug 8, 2016, at 8:47 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:


A lot of ISETBIO related work is structured in satellite repositories. The Brainard Lab has several, I have several, and these will expand. There is a central core of routines that is not tied closely to any particular data set or experimental approach. This code relates to basic physics, such as diffraction or photopigment isomerizations, that is general across any experimental condition.

The code for photocurrent testing, RGC testing, behavioral experimental analyses, and such are all in the satellite repositories. The repository for analyzing the RGC data EJ obtained is now analyzed with the routines in this repository:

   https://github.com/isetbio/EJLExperimentalRGC


The code in this repository integrates tightly with ISETBIO code, and we will make changes that make sure they work smoothly together. The experimental data that are used for this repository will be stored in the Remote archive, like all the rest of our data. We stopped putting data sets into github.

In the fullness of time, I expect we will do the same for other related and important work, such as data that test Fred’s photocurrent model. As additional data come along for, say, wavefront aberrations or cone mosaic packing, or bipolar, we will again try to maintain the foundational calculations in ISETBIO and the routines that connect specific data sets and analyses with ISETBIO in satellite repositories.

It is very much like separating out the basic python functions and then making the import mumble as foo call. ISETBIO comprises the basic functions and the satellite repositories are what we import as needed.

The rationale is this: There are many people who will use ISETBIO but do not need to have the RGC data or methods for deriving parameters from them. People who want to explore those methods need only download a lightweight repository, and we will direct them to that code on the wiki pages. In all cases the data will be on the remote archive, just as the validation are on that archive.

I hope you find this helpful and agreeable.

**Comment by jamesgolden1** [comment]
Sure, I will make that change to the name of the repo.

James

**Comment by wandell** [comment]
Also - we are adding material to the wiki.

We are thinking that some of the comments will become links to the relevant wiki page.  Aspirational.
