### ISSUE TITLE
Small bug in rgcLNP calculation

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#144]
GLM calculation is looking pretty good.  Can @jamesgolden1 please fix this minor problem with LNP, and please check other rgc models with the r_rgcEyeMovement script.  I have run a couple of different stimuii and the GLM model.  But we need to run through each of the different types.

Also I haven't tried the bipolar types.  (Subunit and ...).  Please run through those, too when you can.

Thanks, BW

Error: 

```
You cannot set the read-only property 'dt' of rgcLNP.

Error in rgcMosaic/mosaicSet (line 132)
        obj.dt = val;

Error in rgcLNP/mosaicSet (line 60)
        mosaicSet@rgcMosaic(obj,param,val,varargin{:});

Error in rgcLNP/set (line 101)
            mosaicSet(obj, varargin{:});
```

**Comment by jamesgolden1** [comment]
Sorry, I thought I had fixed this with the commit yesterday, just pushed.
