### ISSUE TITLE
cone mosaic sampleTime parameter

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#147]
@hjiang36 
We ( @jamesgolden1 and brian) think this parameter is the same as the timeStep parameter in the os.  We prefer to eliminate it in the coneMosaic and to only use the os.timeStep parameter.  THen we can also delete the listener function that forces them to be aligned.

In this way, we can set the time step at the first dynamic stage (os) and everything will be inherited from that point and no conflict arises.

**Comment by hjiang36** [comment]
Yes, we can get rid of sampleTime in the cone mosaic.
Besides, we can also consider to force integration time to be the same as sample time.

HJ

**Comment by jamesgolden1** [comment]
Haomiao, we made the changes and I am in the process of merging them back
in.
