### ISSUE TITLE
Something in the recent pushes has broken things

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#148]
My color detect code is now broken after some recent pushes.

The particular issue is that the eye movement generation code does not work if I ask for just one sample of an eye movement.  This is an edge case, but one that used to work.  I get an error during a call mosaic method emGenSequence:

Error using bsxfun
Non-singleton dimensions of the two input arrays must match each other.

Error in coneMosaic/emGenSequence (line 60)
    pos(tPos, :) = bsxfun(@times,pos(tPos,:), t(indx)/sampTime);

Error in colorDetectResponseInstanceArrayFastConstruct (line 69)
    eyeMovementSequence = theMosaic.emGenSequence(eyeMovementsTotalNum);

Error in t_colorGaborConeCurrentEyeMovementsResponseInstances (line 110)
    'responseInstanceArray', colorDetectResponseInstanceArrayFastConstruct(stimulusLabel, testDirectionParams.trialsNum, rParams.temporalParams.simulationTimeStepSecs, ...

Error in c_BanksEtAlReplicate (line 83)
t_colorGaborConeCurrentEyeMovementsResponseInstances(rParams,testDirectionParams);

This error occurs because tPos becomes empty after thes lines in the emGenSequence code:
    t = interval + randn(nFrames, 1) * intervalSD;
    t(t < 0.001) = 0.001; % get rid of negative values
    tPos = cumsum(t);
    tPos = max(1, round(tPos / sampTime));
    indx = 1:find(tPos <= nFrames, 1, 'last');
    tPos = tPos(indx);

I am not really sure what these lines are doing, so I don't want to venture into trying to fix them.  For now I'll either get around this one level up in my code, or roll back in the version of isetbio I am using.  My call to emGenSequence is just passing a single argument that is 1.

It is vaguely possible that this error is related to a change I made in my code to eliminate the key/value pair "sampleTime" in my mosaic creation, which I had to do because that option is gone and leaving it there caused a crash.  But I don't think so, since my sampleTime and integrationTime were always equal at my creation call.

**Comment by DavidBrainard** [comment]
While I was stepping through emGenSequence, I noticed this line.

% Update the integration time to be the number of frames times the sample
% time (in ms).  This should be a listener, I fear (BW).
obj.integrationTime = obj.os.timeStep*nFrames;

In my code, this has the effect of changing the mosaic integrationTime from 100 msec to 1 msec, and not just locally in the eye movement generation routine since the mosaic object arrives as pass by reference.  I am not sure why this is happening, but it is a counterintuitive side effect at least in the case where I am studying what happens for just one frame at the isomerizations.  [I'm calling the eye movements code because I want to keep the called routine general.]

I am hoping this side effect is part of my missing factor of 20 in the comparison between my calculations and those of Banks et al.

**Comment by hjiang36** [comment]
I made a simple fix for this problem. I hope it works.

I agree that `obj.integrationTime = obj.os.timeStep*nFrames;` doesn't look all right. It was added by @wandell in a recent commit. It might have some special uses. We can update the code or the comment when we know what it is exactly used for.

Another thing about eye movement is that we assume the initial eye position is at the origin. That is, if you generate only one sample, you will get [0, 0] for emPositions.

HJ

**Comment by wandell** [comment]
This was a mistake I made when getting rid of the extra time step variable.  James and I changed a series of time variables in eliminating the coneMosaic time step parameter.  I did this one incorrectly.  In the RGC code we were editing this was the relationship, but it should not be imposed.

If I understood enough, I would write a test about the global integration time and the timeStep for eye movements, illustrating their relationship.  I will try, but any help would be welcome.

BW

**Comment by DavidBrainard** [comment]
Thanks for the quick responses on a sunny (very sunny here!) Sunday.  

For right now, I am just avoiding the call to emGenSequence.  The issue just above was not my basic problem, as it is more recent than the last time I ran through the calculations.  

Once I have the static case figured out, I may be able to help with some validations.

**Comment by DavidBrainard** [comment]
Also, Nicolas made some progress on the validations but has not yet uploaded all the fixes he made.  He's deep in some hardware issues we need to resolve right now, but we'll get back to this soon enough.

**Comment by wandell** [comment]
Seems resolved.
