### ISSUE TITLE
Toolbox dependencies

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#149]
I removed Palemedes_1.8 from the isetbio/external directory.  I had put this in a little while ago for fitting psychometric functions from the IBIOColorDetect project.  But, now I can simply put that in as a dependency in the IBIOColorDetect.json file in the toolboxRegistry, and it gets sucked down and put on my path when I'm working on IBIOColorDetect.

I think this is the future, and that we might consider what other toolboxes we can simply have auto-included when we configure isetbio.  

The one downside of this is that for things that we call from core routines, it commits us and others to using the ToolboxToolbox to install.  I'm OK with that, because I think installing the ToolboxToolbox and invoking the command to set up for isetbio is not any harder than installing isetbio.  But, we might gain some experience with that ourselves before pulling out more stuff from external (e.g., BrainardLabToolbox, Psychtoolbox).

**Comment by npcottaris** [comment]
That is so cool!

**Comment by DavidBrainard** [comment]
Well, we in the Brainard Lab love the ToolboxToolbox and think our lives would be much better if everyone used it.  We can no longer function without it.  

But, we live in the real world and making people adopt TbTb to use isetbio seems like it will introduce too much of a barrier to entry.  Usually experts who have their own way of doing things that they like.

So for now we will continue to have our external directory and suck into it the dependencies that we need from other places, so that isetbio is a standalone install.  And some others have had a harder time getting it going.  

Someday we might figure out how to get git to do this for us, something about submodules I think, rather than manually bringing over code and updating it periodically.

But, I'm closing this issue.
