### ISSUE TITLE
Surprising (to me) side effects of displaying scenes

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#15]
Making a call to show a scene, (e.g. vcAddAndSelectObject(scene); sceneWindow;) has the unexpected side effect of changing the data in the scene.  Pasted below is a short function that illustrates the behavior.  

This is problematic not just because it is surprising.  Our validation scripts control whether things are displayed or not to run faster under some circumstances but allow useful debugging plots under others.  This side effects causes validation to fail if the data are generated with plots turned on and then checked with them turned off, or vice-versa.

The problem seems to be related to a truncation of wavelength outside of 400-700 that happens in one case and not the other.  There must also be some global variables hidden somewhere, presumably as part of what happens in ieInit.

---

function displaySideEffects
%
% Script to demonstrate side effects of displaying
% a scene in a window.

%% Init
close all; ieInit;

%% Create isetbio display
displayToTest = 'LCD-Apple';
d = displayCreate(displayToTest);
gammaTable = displayGet(d, 'gamma table');
if (size(gammaTable,2) ~=  3)
    error('Cannot deal with a display that has other than 3 primaries for this test.');
end
nInputLevels = size(gammaTable,1);

% Create a scene using the display
RGBToTest = [0.3 0.73 0.42]';
theRGBImage = ones(20,20,3);
for i1 = 1:3
    theRGBImage(:,:,i1) = round((nInputLevels-1)*RGBToTest(i1));
end
sceneDegrees = 10;  % need large field
scene = sceneFromFile(theRGBImage,'rgb',[],d);
scene = sceneSet(scene,'fov', sceneDegrees);
sceneSize = sceneGet(scene,'size');

%% Compute optial image, for delta function optics.
oi = oiCreate('human');
optics = oiGet(oi,'optics');
optics = opticsSet(optics,'off axis method','skip');
optics = opticsSet(optics,'otf method','skip otf');
oi = oiSet(oi,'optics',optics);
oi = oiCompute(scene,oi);
oi = oiSet(oi,'fov',sceneDegrees);

%% Extract irradiance
roiPixels = 10;
rect = [sceneSize(2)/2,sceneSize(1)/2,roiPixels,roiPixels];
roiRoiLocs = ieRoi2Locs(rect);
foo  =  oiGet(oi,'roi mean photons',  roiRoiLocs);

%% Display scene, that's all.  Should be harmless
%
% But commenting this line in and out affects the
% irradiance contained in the optical image.
vcAddAndSelectObject(scene); sceneWindow;

%% Do the oi thing again
oi = oiCreate('human');
optics = oiGet(oi,'optics');
optics = opticsSet(optics,'off axis method','skip');
optics = opticsSet(optics,'otf method','skip otf');
oi = oiSet(oi,'optics',optics);
oi = oiCompute(scene,oi);
oi = oiSet(oi,'fov',sceneDegrees);

%% Get the irradiance from the new one.  It's different.
%
% Seems to have to do with wavelength truncation
fee  = oiGet(oi,'roi mean photons',  roiRoiLocs);
faa = foo(:)-fee(:);
max(abs(faa(:)))
figure; clf; hold on
plot(foo,'r');
plot(fee,'g');

end

**Comment by wandell** [comment]
Odd. This does not happen in ISET but it does in  ISETBIO.  I will try to figure this out, but as you say somewhere in the calculation the wavelength representation in the oi is getting changed because the scene has been added to the database.

**Comment by hjiang36** [comment]
When we do oiCreate('human'), the program needs to decide some default wavelength samples. Our current code says if we don't have a scene in memory (i.e vcGetObject('scene') returns empty), we use 400:10:700. Otherwise, we use the same wavelength samples as the scene.

Here's a simple example to show this difference
oi1 = oiCreate('human'); % oi1.optics.OTF.wave is 400:10:700
scene = sceneCreate; scene = sceneSet(scene, 'wave', 400:5:700); vcAddObject(scene);
oi2 = oiCreate('human'); % oi2.optics.OTF.wave is 400:5:700

This is actually not a bug. It just means if we can predict what's the right wavelength samples to be used, we do interpolation only once (don't need to interpolate again in oiCompute) instead of twice.

But anyway, this could be annoying to a lot of end users. To handle this, we can comment out line 376 ~ 378 in opticsGet. Then, it should be fine.

Not sure if we want to change this or not. Let me know.

**Comment by wandell** [comment]
OK, so I pushed this along to the condition that when oiCreate() is run in ISETBIO the OTF wavelength samples appear to look up the current scene to set OTF wavelength (might happen in ISET, but I didn't see it yet). 

I have a  shortened version of David's code that illustrates the problem.  Either I or one of you people will figure this out soon enough.  

--- Script
close all; ieInit;

%% Create isetbio scene with 101 wavelength samples
d = displayCreate('LCD-Apple');
gammaTable = displayGet(d, 'gamma table');
nInputLevels = size(gammaTable,1);

% Create a scene using the display
RGBToTest = [0.3 0.73 0.42]';
theRGBImage = ones(20,20,3);
for i1 = 1:3
    theRGBImage(:,:,i1) = round((nInputLevels-1)*RGBToTest(i1));
end
scene = sceneFromFile(theRGBImage,'rgb',[],d);

%% The problem illustrated
oi = oiCreate('human');
% Only 31 wave samples
oi.optics.OTF

vcAddAndSelectObject(scene); % sceneWindow;
oi = oiCreate('human');
% 101 wave samples
oi.optics.OTF

**Comment by wandell** [comment]
I edited opticsGet(optics,'wave') to indicate where the source of the wavelength sampling is coming from (default, current selected scene).  It prints that out to the console.  This will, at least, give people a little warning rather than appear to be so mysterious.
