### ISSUE TITLE
Move the OS Biophys parameters out of the script into the object

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#150]
Give the user permission to edit at least some of these parameters, and guide them.

**Comment by jamesgolden1** [comment]
This is done, but I have not merged it into the master branch yet. The osBioPhys model has 20 parameters. There are two options for how to store the parameters with coneMosaic.os, and I am open to other ways of doing it. Please let me know what you think.

Option 1, all the model properties are at the same level as the few other properties:
```

  osBioPhys with properties:

                state: [1x1 osBioPhys]
                sigma: 22
                  phi: 22
                  eta: 2000
                gdark: 20.5000
                    k: 0.0200
                    h: 3
                cdark: 1
                 beta: 9
             betaSlow: 0.4000
                    n: 4
                  kGc: 0.5000
            OpsinGain: 10
                    q: 0.1045
                 smax: 3.1682e+04
                bgCur: [61x91 double]
                opsin: [61x91 double]
                  PDE: [61x91 double]
                   Ca: [61x91 double]
              Ca_slow: [61x91 double]
                   st: [61x91 double]
                 cGMP: [61x91 double]
            noiseFlag: 0
            patchSize: 1.8200e-04
    coneCurrentSignal: [61x91x196 single]
             timeStep: 1.0000e-03
```


Option 2, keep the model properties in a struct:

```

  osBioPhys with properties:

                state:  [1x1 osBioPhys]
                model: [1x1 struct]
            noiseFlag: 0
            patchSize: 1.7600e-04
    coneCurrentSignal: [61x91x196 single]
             timeStep: 1.0000e-03

```
```
cm.os.model

ans = 

        sigma: 22
          phi: 22
          eta: 2000
        gdark: 20.5000
            k: 0.0200
            h: 3
        cdark: 1
         beta: 9
     betaSlow: 0.4000
            n: 4
          kGc: 0.5000
    OpsinGain: 10
            q: 0.1045
         smax: 3.1682e+04
```

**Comment by fmrieke** [comment]
Some of these are not independent though - e.g. q and smax can be computed from others and requirement that steady state is indeed steady state (see osInit for equations).  I would opt for option 2 below as it helps separate things out logically.

Fred

**Comment by jamesgolden1** [comment]
Ah of course, I will remove the dependencies/redundancies from what we keep
in the object. I am trying to consolidate osInit into the osBioPhys
constructor function (n the osparams branch). I agree that option 2 is a
bit cleaner.

**Comment by wandell** [comment]
I vote for 

  (a) consolidating the parameters inside the 'model' or 'biophys' struct, and of course, 
  (b) making the dependent parameters dependent.  

The display function can print them as you have, but the user shouldn't be allowed to set them.  Some time spent on a reasonable display (print) function would be very useful because there are so many parameters.

Good to get this one done.

**Comment by jamesgolden1** [comment]
The parameters for the computational model are now stored in osB.model. I have removed the dependent properties and made them private. 

@fmrieke Which properties should we allow the user to set? Right now sigma, eta, beta and OpsinGain can be set. I chose those because they were the ones that changed from the peripheral model to the foveal model. Is this a little too much freedom for the user? I could check that any user-entered parameters are between the values specified for the peripheral and foveal models, but it seems unlikely that a user will be capable enough to make appropriate choices for any of these.

```
osB = 

  osBioPhys with properties:

                model: [1x1 struct]
            noiseFlag: 0
            patchSize: []
    coneCurrentSignal: [1x1x26000 double]
             timeStep: 1.0000e-04
```
```

osB.model

ans = 

        sigma: 22
          phi: 22
          eta: 2000
        gdark: 20.5000
            k: 0.0200
            h: 3
        cdark: 1
         beta: 9
     betaSlow: 0.4000
            n: 4
          kGc: 0.5000
    OpsinGain: 10
```

**Comment by wandell** [comment]
Done and merged by @jamesgolden1
