### ISSUE TITLE
Update the cone mosaics on the RDT

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#153]
We haven't moved the mosaics that are in the steady-state up to the RDT yet.  They are created, we think, but not moved up yet.

**Comment by npcottaris** [comment]
Brian,

Which cone mosaics are you referring to?
Nicolas

**Comment by wandell** [comment]
For James to do.  He built cone mosaic responses for the moving bar and several other test stimuli.  The intention was to have the mosaics be built with a stimulus that started out at a uniform field with the proper mean luminance (to avoid the big transient).  The ones that were put up there, however, had the big transients.  This made it impossible for us to assess some of the test stimuli.

So @jamesgolden1 took the task of replacing the cone mosaic responses for the test stimuli with the proper ones that give us a chance to see whether all of the different models run reasonably.

**Comment by npcottaris** [comment]
Ok, thanks.

**Comment by jamesgolden1** [comment]
I have taken care of this for the coneMosaic data but I have not yet done this for coneMosaicHex.

**Comment by wandell** [comment]
Done by JRG for rectangular mosaics.  Will start a separate issue for the conemosaic hex format. Let's start that in a separate issue because it will feel good to close this one.

Onward.
