### ISSUE TITLE
v_DisplayColorConversion runs and is accurate but doesn't match the validation data

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#154]
Is this only on our machines at Stanford?

BW/JRG

**Comment by DavidBrainard** [comment]
This fails for me too.  I think it is a small numerical difference across machines, the discrepancy is very small in fractional terms.  We will increase the tolerance and it will be fine.

**Comment by npcottaris** [comment]
It fails the FAST or the FULL validation?

**Comment by npcottaris** [comment]
Please send me your error reports.

**Comment by DavidBrainard** [comment]
[  1] 'v_DisplayColorConversion'
                Internal validation  : PASSED
               Run-time status      : no exception raised
                Ground truth  url    : http://52.32.77.154/repository/isetbio/validation/fast/display/DisplayColorConversion/run00001/DisplayColorConversion-run00001-mat.mat
                Ground truth  localP : /Volumes/Users1/GradleCaches/isetbio/caches/modules-2/files-2.1/validation.fast.display/DisplayColorConversion/run00001/39b26410e868045791abedb5c50a0071f0b87dde/DisplayColorConversion-run00001-mat.mat
                Fast validation      : FAILED against ground truth data of 08-Sep-2016 16:40:42.
                > Ground truth info :          manta.PSYCH.UPENN.EDU / MACI64, MATLAB 8.6.0.267246 (R2015b) by 'nicolas'
                > Local host info   :       eagleray.psych.upenn.edu / MACI64, MATLAB 9.0.0.341360 (R2016a) by 'dhb'
                DataHash-this run    : 964574bf573af9f67b3b6d8259f54b72db9e03be9ad5102d65ecc50a4defe158
                DataHash-groundTruth : ae189424c9d062ba5fde47aaae4e682e8e4cf7e7a6c1dfbd9885e0364579c0f5
                ---------------------------------------------------------------------------------------------------------------------------------
                Ground truth  url    : http://52.32.77.154/repository/isetbio/validation/full/display/DisplayColorConversion/run00001/DisplayColorConversion-run00001-mat.mat
                Ground truth  localP : /Volumes/Users1/GradleCaches/isetbio/caches/modules-2/files-2.1/validation.full.display/DisplayColorConversion/run00001/684664db6d9ff198a10896c1d808363b00d4e3a7/DisplayColorConversion-run00001-mat.mat
                Full validation      : FAILED against ground truth data of 08-Sep-2016 16:40:59.
                > Ground truth info : manta.PSYCH.UPENN.EDU          / MACI64, MATLAB 8.6.0.267246 (R2015b) by 'nicolas'
                > Local host info   : eagleray.psych.upenn.edu       / MACI64, MATLAB 9.0.0.341360 (R2016a) by 'dhb'
                [data mismatch  1]   : Max difference between 'groundTruthData(1).conversionData(1).ptbIrradianceSpdPhotons' and 'validationData(1).conversionData(1).ptbIrradianceSpdPhotons' (0.03125) is greater than the set tolerance (1e-11). See figure named: ''groundTruthData(1).conversionData(1).ptbIrradianceSpdPhotons' vs. 'validationData(1).conversionData(1).ptbIrradianceSpdPhotons''
               Note (*)             : script does not store any extra data.
                Validation report    :
                                Compare isetbio and PTB display color conversion.
                                Red inversion comparison is within the specified tolerance (0.001) of zero.
                                Green inversion comparison is within the specified tolerance (0.001) of zero.
                                Blue inversion comparison is within the specified tolerance (0.001) of zero.
                                PTB red settings->primary->settings check is within the specified tolerance (0.001) of zero.
                                PTB green settings->primary->settings check is within the specified tolerance (0.001) of zero.
                                PTB blue settings->primary->settings check is within the specified tolerance (0.001) of zero.
                                L isomerization comparison is within the specified tolerance (0.01) of zero.
                                M isomerization comparison is within the specified tolerance (0.01) of zero.
                                S isomerization comparison is within the specified tolerance (0.01) of zero.

**Comment by npcottaris** [comment]
Closing this. It is resolved.
