### ISSUE TITLE
ieValidation error

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#158]
Hi @npcottaris 

While validation is working fine at work, when I try running it from home I receive this error.

Can you look at this and know what is happening?  Something about my configuration, surely.  Can you have a look at the error and tell me what I am doing wrong?

Thanks,
Brian

Error using UnitTest/initializeUnitTest (line 43)
Java exception occurred:
java.net.UnknownHostException: Macula: Macula: nodename nor servname provided, or not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
Caused by: java.net.UnknownHostException: Macula: nodename nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)

Error in UnitTest (line 123)
            obj.initializeUnitTest();

Error in UnitTest.runValidationSession>validateFast (line 65)
    UnitTestOBJ = UnitTest();

Error in UnitTest.runValidationSession (line 27)
        validateFast(vScriptsList);

Error in ieValidateFastOne (line 34)
UnitTest.runValidationSession({{singleScriptToValidate, []}}, 'FAST');

**Comment by npcottaris** [comment]
Brian,

Can you please try the following in Matlab's command window?

`java.net.InetAddress.getLocalHost`

What do you get? If this produces an error there is something wrong with your hosts file. Please see 
https://www.mathworks.com/matlabcentral/answers/196954-why-do-i-get-java-net-unknownhostexception-error-while-trying-to-open-parpool-in-matlab-r2014a

for a Mathworks-proposed resolution for this issue.

Thanks,
Nicolas

**Comment by wandell** [comment]
You are right.  That single line failed.  It failed on two different versions of Matlab.  So, I went deep into my bench of computer science knowledge and rebooted my computer.  That seems to have restarted java properly and I am currently running ieValidateFullAll.

Thanks for your help.
