### ISSUE TITLE
osCompute() methods do not know the sampling rate of their photoRate input

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#160]
Currently the osCompute() methods of @osLinear, @osBiophys, have no way of knowing the temporal resolution of their photon rate input signal.
Unless the user has manually ensured that `os.timeStep` matches the resolution of the passed photon rate signal, this will lead to wrong results. 

Instead of having the user be in charge (which will likely lead to mistakes), we could add a required input argument, the sampling rate of the photon rate signal, in`osCompute()`, and then have `osCompute` either,
(a) adapt the `os.timeStep` property so as to match the  sampling interval of the photonRate signal (that would be ok for @osLinear), or
(b) resample the input photonRate signal with a sampling rate equal to `os.timeStep`

I think scheme (a) would be useful for @osLinear computations as we could save computation time by setting `os.timeStep` to be a fraction of the  photon rate sampling interval, which is also the integration time, instead of its default value which is 1 millisecond. And scheme (b) would be required in @osBiophys computations.

Also `osAddNoise()` has a default sampleTime of 1 millisecond, unless the user passes a params struct with a `sampleTime` property. Again, I can see this leading to errors as we leave it up to the user to either pass the `params.sampTime`, or have an input photonRate that is sampled at 1 millisecond.

Ideas, suggestions?

**Comment by jamesgolden1** [comment]
Nicolas, I agree this was the reason the osBioPhys validations were failing
a few weeks ago. I also agree that a) and b) are best for osLinear and
osBioPhys, respectively.

Another related idea is that osAddNoise does not add noise of the correct
magnitude using the 'Append' method.

**Comment by npcottaris** [comment]
Closing this. The new implementations solves it.
