### ISSUE TITLE
What is status of osvalidation branch?  psuedohex branch?

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#162]
Could we get an update on what is happening in the osvalidation branch?  That is, what is being worked on there, what is the status, etc.  We are getting close to getting serious with some os calculations as we try to march towards RGC based threshold measurements, and having that open makes us unsure of whether we should proceed or wait for some fix that is in the works.

And, has the psuedohex branch been merged into the master, and if so can it be deleted?

**Comment by wandell** [comment]
Pleased to say osvalidation has been merged into master and osvalidation has been deleted from the repository.  The ieValidationFastAll passes without errors.

We hope to move on to the cone mosaic window visualization in a new branch and roc mosaic visualization in another branch.
