### ISSUE TITLE
Why is coneMosaic.integrationTime reset in coneMosaic.emGenSequence() ?

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#166]
In coneMosaic.emGenSequence(), line #33  does not make sense to me.

```
% Update the integration time to be the number of frames times the sample
% time (in ms).  This should be a listener, I fear (BW).
obj.integrationTime = obj.os.timeStep*nFrames;
```

where obj is a coneMosaic object, and nFrames is the number of eye movements to generate.

If we are now treating coneMosaic.integrationTime as the total time that we scanned the current optical image (with or without eye movements), then this implies that each eye movement is lasting for a duration equal to the timeStep of the osComputation, which for @osBiophys objects would be < 0.1 millisecond. This does not seem right. Shouldn't obj.os.timeStep be replaced by the duration of each eye movement instead, a property that does NOT currently exist in the coneMosaic object?

Moreover,  coneMosaic.integrationTime is a user-settable property. if we are resetting it, we should not allow the user to set it in the first place.

I am confused. What is the current interpretation of coneMosaic.integrationTime?

**Comment by npcottaris** [comment]
I suppose we can bypass this issue by defining nFrames as
```
nFrames = eyeMovementDuration / obj.os.timeStep
```

and by not setting  `coneMosaic.integrationTime`  for simulations involving eye movements.

This seems like an OK and self-consistent solution for now, and is what I will be doing from now on.

**Comment by jamesgolden1** [comment]
Nicolas, I think your correction gets at what we were trying to do. We were
interested in the case when there would be multiple eye movements per
stimulus frame - maybe we were thinking of nFrames as the number of eye
movements per frame, or number of frames per eye movement?

We were also trying to prevent the coneMosaic and its os from having
different time steps.

Brian and I have been using the s_initRetina script to generate a cmosaic,
bipolar and ir to work with the GUIs. cmosaic from that script has an os
time step of 0.001 sec, while the integration time for the cmosaic is 0.05
sec. There are 50 eye movement positions, and 50*0.001 = 0.05, but the
integration time should not be 0.05.

**Comment by npcottaris** [comment]
Hi James,

It seems like we are working in parallel. I am also trying to establish a generic method for working with a sequence of optical images, each of which can have any number of eye movements. 

You can run/look through `v_osTimeStep` which has a couple of predefined condition sets.
The first condition set examines the effects of the stimulus interval and computation interval.

The second condition set helps visualize the impact of the photonNoise vs the osNoise. This condition set demonstrates nicely that the effect of photon noise is nothing compared to osNoise for relatively weak stimuli.

In all these runs the stimulus is a uniform field whose radiance is modulated in time. There are eye movements (1 or more per stimulus frame), but they are of no consequence as far as the response is concerned as this is a uniform field stimulus.

There is a couple of routines in that script (`computeMultiOIMosaicResponse`,  `'coneMosaicGenerate`) which do the multi-optical image computation. Perhaps we should compare notes on this part.

One thing that I noticed is that one should call emGenSequence once for the entire number of eye movements, for all optical images.  Calling emGenSequence for each optical image and then concatenating the eye movement paths results in an eye movement path that  mostly stays around 0, with no excursions. This does not seem appropriate.

Nicolas

**Comment by npcottaris** [comment]
Closing this. The new implementation  solves it.
