### ISSUE TITLE
Frozen noise convention/implementation

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#170]
In coneMosaic.photonNoise, there is a 'newNoise' key that takes true or false as its value.  When it is true, the comments say it will generate new random noise.  It is true by default, and when it is true I believe we in fact get a new draw of noise each time the routine is called.

As far as I can tell, however, setting this flag to false has no effect in the case when the code uses the Normal approximation to the Poisson (which is what it does for counts of 25 or greater.)

I am not actually sure we ever care about the case when the flag is false, so perhaps this doesn't matter.  But if we do care, we are not doing the right thing.  And if we don't ever care, we should probably just get rid of this flag.

**Comment by DavidBrainard** [comment]
Also, it's worth knowing that special care is needed to fix the rng if you are using a parfor loop, because the different loop indices will get run in a different order each time through.  [This is actually what caused me to be looking deep into where the rng is seeded in our code). You can handle this by precomputing a vector of seeds, one for each parfor loop iteration, and setting the seed at the top of the loop.  Probably good to save and restore the rng state before and after the whole parfor loop as well.

**Comment by wandell** [comment]
This issue seems stale to me because there is no longer a coneMosaic.photonNoise slot or a newNoise key (AFAIK). 

We are handling noise by coneMosaic.noiseFlag, which manages photon noise, and coneMosaic.os.noiseFlag, which manages current noise.

If you think this is wrong, please reopen.

**Comment by npcottaris** [comment]
There is still a `newNoise` key which propagates along the following function chain:
~~~
coneMosaic.compute() -> coneMosaic.photonNoise() -> [for absorption counts / integrationTimeBin < 25] -> iePoisson() -> iePoissrnd (with new rand).
~~~
If we stick to integration times of 10 msec, an absorptions count of 25 corresponds to 2,500 isomerizations / sec, which is not a completely irrelevant rate.

**Comment by wandell** [comment]
Thanks, not something I say or knew.

Can we handle the photon noise through a single variable, cMosaic.noiseFlag, rather than using two different flags (noiseFlag and 'newNoise').  Perhaps we can set 

 noiseFlag = 0 means no noise, 
 noiseFlag = 1 means frozen noise, and 
 noiseFlag = 2 means new draws of photon noise every time?  

Related - do you understand the logic of the newNoise control?  I followed it down through iePoisson.  But that is buried pretty deep and involves two different random noise generators.  

Finally, I didn't understand the last comment about rates.

**Comment by npcottaris** [comment]
1. The ternary `noiseFlag` is a good idea. We should probably make this a string with valid values { 'zero', 'frozen', 'new draw'} as people may think it is still a binary flag and run into unexpected results. We also need the same  treatment for photocurrent noise and for eye movements (corresponding to zero movement, frozen path, and new path).
2. I believe that the different random noise generators is something that @xnieamo added in our lab, but I could be wrong. Perhaps @DavidBrainard  knows?
3. Comment about rates: All I meant to say its that the newNoise computation kicks in for isomerizations < 25, which for a 10 ms integration time corresponds to 2,500 R*/sec, which is not a rate that we can ignore, so we need to deal with this issue. But I do not understand why it only kicks in for isomerization counts < 25.

**Comment by DavidBrainard** [comment]
Agree that strings are better than numbers for options.

I once understood that noise code.  The complications arise, I think, from trying to avoid needing the stats toolbox but wanting to use it when it is there.  I can look at it again at some point.  I think I concluded it was OK the last time I looked through it.

**Comment by wandell** [comment]
Could do strings.  Or, for backward compatibility with the current true/false we could do

* noiseFlag = 0 means no noise
* noiseFlag = 1 means choose a random seed  with rng('shuffle')
* noiseFlag = A negative number means frozen noise initiated by rng(abs(noiseFlag))

Important for us to all feel comfortable; we want a syntax that could apply to all of our functions.

**Comment by DavidBrainard** [comment]
Going forward, I have a preference for key/value pairs that are either boolean (e.g., 'generatePlots',true) or strings (e.g., 'noiseFlag','noNoise') because this is easier to know what it means when you read it inline in the code, without needing to refer back to
documentation to interpret.

So in the case below, I'd like the code to eventually read something like:

'noiseFlag','noNoise'
'noiseFlag','randomNoise"
'noiseFlag','frozenNoise'

and in the latter case have an optional additional pair that would set the seed, so that you could write

'noiseFlag','frozenNoise','frozenNoiseSeed',10

If we need to keep the other syntax around for backward compatibility that is OK with me.  I'm big on backward compatibility.

**Comment by wandell** [comment]
I will implement the 'string' convention this weekend, along with the 'noiseSeed' parameter.  Let's agree to that and I will do it.

**Comment by wandell** [comment]
I think this is done and in the master branch now.  Be very alert for bugs in this part.  There were dozens of little changes required.  Of course I think I got them.  But really, what are the odds?
