### ISSUE TITLE
cone density

### ISSUE THREAD

**Issue by JWinawer** [isetbio/isetbio#173]
The function _coneDensity.m_ is buggy. For example, the line of code in the example returns a NaN:

density = coneDensity(8, 10, 'left')
> NaN

Trying to track this down...

**Comment by JWinawer** [comment]
The function is fine. The help example is bad due to a units issue. The input should be in m, as indicated in the header. But the example of 8 was probably intended as either mm or deg. A better example would be 

> density = coneDensity(8*1e-3, 10, 'left')

**Comment by DavidBrainard** [comment]
or even something along the lines of:

retinalEccentricityMeters = 81e-3;
whateverTheSecondArgIsPlusUnits = 10;
visualField = 'left';
density = coneDensity(retinalEccentricityMeters, whateverTheSecondArgIsPlusUnits,visualField);
