### ISSUE TITLE
Method definition best practices for method in a separate file

### ISSUE THREAD

**Issue by jamesgolden1** [isetbio/isetbio#175]
@wandell and I were discussing how best to define a method when it is stored in a separate function file. Sometimes the method is also listed on a single line in the class definition file, where its input and output arguments are defined (in addition to their definiton on the  first line of the separate function file). Once or twice I have made changes to the separate file but forgotten to change the method definition in the classdef file and gotten an error that took me some time to figure out.

The [Matlab documentation](https://www.mathworks.com/help/matlab/matlab_oop/methods-in-separate-files.html) suggests "It is a good practice to declare the function signature in the classdef file in a methods block." @wandell and I are leaning towards NOT following this suggestion, which does not seem to have any impact on how the method is used.

Should we include our method declarations in the classdef file, or is it enough that they are included in the @Object folder?

**Comment by DavidBrainard** [comment]
I think your proposal is OK.  We (well, some of us) have converged on this style for some classes we have written for work unrelated to isetbio.  The principle I like to follow is that whenever possible, any given piece of information should only be coded in one place.  As you indicate, declaring the method in the classdef and writing it somewhere else leads to the possibility of things getting out of sync, and here I don't think there is much benefit to the declaration.  If you want the method to be private or something fancy, you have to declare it.

**Comment by npcottaris** [comment]
I prefer to kep the declarations inside the classdef file as it helps me summarize the object's methods, along with a short comment about the methods purpose- I prefer that to opening the methods file. Also if you have private, protected and static methods you have to declare them in the classdef file, so why skip the public ones?

It is just neater, I think, to declare all of them.

**Comment by wandell** [comment]
OK, we each have our different preferences.  Let's move on.  I will try to remember to go back to the main classdef file when editing methods in their own file.  I am getting better at checking.
