### ISSUE TITLE
osAddNoise units

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#179]
I would like to discuss whether we have the units properly scaled and labeled for the osAddNoise function.  Next week.

The shape of the curve is below.  This is the curve returned by the test code in the header comments of osAddNoise in the newLinear branch.

![screen shot 2016-11-12 at 8 44 08 pm](https://cloud.githubusercontent.com/assets/1837145/20243727/daa2798c-a918-11e6-8f5d-da86284373bb.png)

**Comment by fmrieke** [comment]
Something is off in the scaling of the noise amplitude; frequency scaling looks ok.  The noise should asymptote to a value of 0.205 pA^2/Hz.  The noise calculation is described in the last page of the attached notes.  I’ll take a look and see if I can identify what is going on.

Fred

**Comment by fmrieke** [comment]
Here is a piece of code using the old sensor format to check noise.  This looks correct.  Note the noise power spectrum should be robust to the number of points used to measure it and to the time step used in sampling it - those are good to check.  Is the plot below calculating noise spectral density - i.e.:

Noise = 2 * fft(data)*conj(fft(data)) * timeStep / NumSamples

The timeStep and NumSamples factors are important to insure invariance with respect to those factors.  

Fred

%% noise check
 
%  set up parameters for stimulus
nSamples = 1000000;   
TimeStep = 1e-4; % s
stimMean = 0;
freqStep = 1/(nSamples*TimeStep);
freqSamples = 0:nSamples-1;
freqSamples = freqSamples * freqStep;
 
% setup sensor
sensor = sensorCreate('human');
sensor = sensorSet(sensor, 'size', [1 1]);
sensor = sensorSet(sensor, 'time interval', TimeStep); 
sensor = sensorSet(sensor, 'conversion gain', 1);
 
%  create stimulus
clear stimulus;
tme = 1:nSamples;
tme = tme * TimeStep;
stimulus(1:nSamples) = stimMean;
stimulus = reshape(stimulus, [1 1 nSamples]);
 
% set photon rate in sensor and calculate current with noise
sensor = sensorSet(sensor, 'photon rate', stimulus);
LinearModel = osCreate('linear');
LinearModel = osSet(LinearModel, 'noiseFlag', 1);
LinearModel = osCompute(LinearModel, sensor);
LinearCurrent = squeeze(osGet(LinearModel, 'coneCurrentSignal'));
 
% calculate noise power
% 2 is to account for negative frequencies, TimeStep and nSamples are to
% get units right (i.e. to compute noise spectral density)
noisePower = 2*real(fft(LinearCurrent) .* conj(fft(LinearCurrent))) * TimeStep / nSamples 
 
% plot
figure(1); clf;
subplot(1, 2, 1);
plot(tme, LinearCurrent);
xlabel('sec');
ylabel('pA');
subplot(1, 2, 2);
loglog(freqSamples, noisePower);
ylabel('pA^2/Hz');
xlabel('Hz');
xlim([freqStep 2000]);

**Comment by wandell** [comment]
OK.  I think we are back in alignment.  The code snippet that was in the header did not match the formula you used.  The correction for the number of samples was missing, as well as the factor of 2.  When I make the corrections we are good to go.  

The code snippet that checks out with the right units is now in the comment section of osAddNoise.  The resulting figure, with the asymptote at 0.205 pA2/Hz is below the code.  We should probably use this snippet as part of the os validation.  Closing this issue.

![screen shot 2016-11-13 at 11 56 28 am](https://cloud.githubusercontent.com/assets/1837145/20248401/56935370-a998-11e6-8ada-2f96d6002a43.png)

**Comment by wandell** [comment]
Summarized the plots of noise in t_osNoise.m (tutorial).
