### ISSUE TITLE
Full vs fast validation

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#183]
When we started the UnitTestToolbox, the fast validation seemed like a great idea.  But in practice, it is exceptionally hard to guarantee that the hashed value stored in the fast validation file will match when the actual values in the full validation file are within tolerance.  This has to do with the fact that the numerical precision of floating point hardware varies across computers, and that even integers are not represented as exact integers in floating point format.  (That is, the result of fix(a/tolerence) will not be the same across hardware.)

This fact has led to much time spent trying to track down and fix cases where fast validations fail even thought the full validations work.

Nicolas and I can think of schemes that might fix this problem, with the most promising one involving explictly converting numbers to a string representation and truncated the stored number of characters.  This would be a lot of work.  And, it might take more time than just running the compare on the full data, depending on the time required to compute and manipulate the strings and how big the data to be hashed are.

In the meantime, my observation is that we always just run the full validations, and that the data size and compare time is not onerous compared to the actual compute time of things being validated.

I propose that we simply switch to always using the full validations, and stop storing and checking the fast validations.  If we ever feel that we really need the fast validations, we can revisit how to make them robust, but right now it seems like a big time sink for little gain.

But before we make this switch, we wanted to post the issue and see whether anyone objects.

**Comment by wandell** [comment]
For this case and related cases I am strongly in favor of simplification.  So, take this as support for removing one of the potential validation modes.  And making the 'full' case even simpler, and making the validation scripts themselves even simpler, would also be desirable.

@npcottaris and I had a nice conversation yesterday in which we agreed that a goal for this project would be to always choose the simplest way to do something, particularly at first.  One of our main missions is to make code and methods easy for people to read and understand.  So I hope we all return to issues, like this one, and agree that if the code looks complicated and daunting, it is worth our effort to simplify and clarify.

Anyway, agreement from me.

**Comment by wandell** [comment]
Have we done this?  I am only running the full validations.  Can we close this issue now?

**Comment by DavidBrainard** [comment]
We have gotten rid of fast at this point.  Closing.
