### ISSUE TITLE
noiseShot

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#197]
Somehow I have on my list to look into the Poisson noise generation routines, I think based on some comment made in passing in some other exchange.

I started to do this and found the routine noiseShot, which itself is using the old sensor structure.  It was too hard to read, as it involved volts and other things I have purged from my memory.

I suggest we have reached a point where we should just start deleting sensor based stuff from isetbio when we encounter it, and thus force ourselves to update anything that is using the sensor code.

If this is agreeable, I will delete:

noiseShot
coneAbsorptionsApplyPath
sensorAddNoise
sensorComputeImage
sensorPlot

(These are the routines I found that depend on noiseShot, within the isetbio tree.  As I go, that will probably cause me to recursively delete any function that depends on others that I delete.

This might be too radical, so I am posting this first.

I suppose I should do this on a branch, which I will if others sign off.  Probably once I start I will just purge all the sensor stuff.

Thoughts?

**Comment by wandell** [comment]
I think we can (and should) delete all the sensor() related routines.  I believe that we are only going through coneMosaic at this point.  

To the extent that I am wrong about this, we should work to make me right.  So, I vote that we make a branch called sensordelete, and we crush the whole sensor directory, and we see what breaks in our functions.

**Comment by DavidBrainard** [comment]
I will try to take this on a bit over the weekend.

DB

**Comment by DavidBrainard** [comment]
Now engaged in this process on the byebyesensor branch.  Closing this issue and will raise specific issues as they arise.
