### ISSUE TITLE
v_osLinearFilters.m

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#198]
Hi @npcottaris 

Can you shorten v_osLinearFilters.m?  I run ieValidationFullAll somewhat routinely, so trying to keep the validation scripts to within, say 10-20 sec, seems important to me.  That one times in a little under 2 minutes on my Macbook Air.   Given how many there are now (31) and more to come, timing matters to me. 

Your script seems very nice to me, but more in the form of a tutorial in which many different curves are illustrated.  A validation really only needs to check key values.  This might be another topic for us to discuss (the difference between tutorials and validations).

If there is disagreement on these principles, maybe we can discuss.

**Comment by DavidBrainard** [comment]
Should we write up validation files for the validations that don't have them?  I can do that if no-one objects.

The reason this would be handy is that as part of stripping out the sensor, I'd like to start with everything working and then make sure nothing breaks.  Even if we later decide to shorten and fix the files, it is nice to have a mooring before branching and doing major surgery.

**Comment by npcottaris** [comment]
Done.

**Comment by wandell** [comment]
Closing.  Another victory and spurt of dopamine in all our brains.
