### ISSUE TITLE
Byebyesensor: cone spatial integration area now different

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#199]
OK.  I made sure all validations ran for me in the master.  Had to do a little work to freeze noise and increase a tolerance, and then change the hard coded check value a little to get it to work for me, but I don't think there was any real issue.  New validation pushed and with that everything runs and validates for me on the master branch.

Created the byebyesensor branch and deleted the sensor and deprecated directors, plus the emGeneratePath routine that was deprecated (and which used the sensor).  Reran validations. About five didn't pass and am working through them.

I have fixed up v_IrradianceIsomerizations.  Mostly this was just replacing the sensor with the cone mosaic, and also getting rid of the use of the old lens structure in favor of the new lens object.  

One issue arises.  The pixel size by default (for sensorCreate('human') was 2 by 2 uM, for an area of 4 uM^2.  This is roughly consistent with what I think a foveal cone inner segment area should be (2.3 uM, 4.15 uM^2).  In the new code, the patternSampleSample size (for the default coneMosaic creator) is still 2 by 2 uM.  But when isomerizations (aka absorptions) are computed in coneMosaic.computeSingleFrame, the area used is what's in property coneMosaic.pigment.pdArea, and this has the value of 1.96 uM^2.  Thus the new isomerizations values we are getting are roughly half of what we were getting before. 

I don't actually understand how we could have gotten this far with this factor of 2 difference, since I thought we had checked for isomerizations agreement in several places along the way.  But we need to sort this out.

Does anyone know why we're now using 1.96 uM^2?  I decided not to try to track down where this is set on the view that someone might know right off the top of his head.

**Comment by DavidBrainard** [comment]
Digging in a little more, there is a Cone.m function which has a cone diameter parameter with a default of 2 uM.  This is then converted to area via area  = diameter^2, which would be backwards compatible with the old square pixel's area, but which probably should not be left this way in the long term.

I also don't understand the relation between the Cone object and the photoPigment object -- both seem to compute area, but in different ways.  In the photopigmentObject, there are both width and height fields, and pdWidth and pdHeight fields.  By default, all four of these are 2 uM, but in coneMosaic.m these get set to what is returned by coneSize for the default ecc and angle of the retinal patch.  These are 0 and 0, as I think they should be, but the cone aperture returned is 1.4 uM which is smaller than what PTB uses by default.  The PTB number of 2.3 is from Rodiek's book, Appendix B according to the comments in the code.  That code cites Webvision as giving this as 1.5 uM, so there is some variation in the literature with 1.4 uM not being crazy.  There are no comments in coneSize about where the numbers come from, but it looks like the sizes are computed from the density which in turn comes from function coneDensity.  (The comments in coneSize say that it takes density as an argument, but this is not in fact the case.)  In coneDensity, we find that the density comes from two papers, one from Curcio's lab and one from Burns'.

The acceptance aperture is taken as 0.7 times the spacing.  Maybe this is because light isn't gathered with uniform efficiency across the physical aperture?

**Comment by wandell** [comment]
My (uncertain) belief is that Cone.m is deprecated and replaced by coneMosaic and photoPigment.

**Comment by wandell** [comment]
I think this is complete now, so I am closing.
