### ISSUE TITLE
Where should full validation data go?

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#2]
The full validation dataset is currently about 150 MB.  It will probably grow.

Nicolas and I have a copy on dropbox.  That may not be the optimal place, although it would be easy to share with a few people.

We could make a separate gitHub repository that has the validation data.  This would be OK for now and easy to point people to and maintain.  If you put a gun to my head, that is what I would choose at this instant.

There might be a better idea.

**Comment by npcottaris** [comment]
For now the github repository solution would work. However, GitHub has a 1GB limit per repository and complete rejection for fileuploads of 100MB. So we may run into a wall in the future.

**Comment by DavidBrainard** [comment]
We could also put this on our lab svn server and make it readable by anyone via a link we post somewhere.

**Comment by wandell** [comment]
Or Amazon (glacier, S3), which I have never used and know little about.




Stanford

**Comment by chichilnisky** [comment]
Maybe a gdrive?

ej

**Comment by DavidBrainard** [comment]
OK, let's talk this over at one of our chats soon.  Also, we can put ancillary data files (as in, some of those I pulled from the respository) into the same place, once we decide where that is.

**Comment by wandell** [comment]
If you browse to http://scarlet.stanford.edu/validation/SCIEN/ you will see a web-page that shows placeholders for various types of engineering data.  This is the 30T we lucked into from the Stanford Deans, clever people that they are.

It is possible to retrieve data from this site using the Matlab urlwrite('http path to data here',outputFile) command.  This will get the data from that site and write them in outputFile.  It is basically a sftp call that they have wrapped nicely for us.

Given that we have all that space, my lab was thinking of using that server to store all the validation data and a lot more.  It is free, easy enough to access, and so at least worth discussing.  I have been using the site in a related project, and so far so good.  Maybe David, Nicolas, HJ and I can discuss the situation this week.

**Comment by chichilnisky** [comment]
Sounds good.

Unrelated -- any chance that some more of this disk space would fall off the back of the dean's truck into my lap?

ej

**Comment by wandell** [comment]
You need to ask med school.

You are also welcome to plenty of our space when needed.

B

**Comment by chichilnisky** [comment]
Thanks!

I wouldn't even know whom to ask!  

We're doing fine though.  The new 10G research link sounds promising.

ej

**Comment by wandell** [comment]
This is what we are imaging for getting the full validation data.  Try executing these commands.  Let me know if they work at Penn.  If it is quick enough (and produces the output file deleteMe.mat correctly), then I will explain.

% Base URL for the validation data
vDir = 'http://scarlet.stanford.edu/validation/SCIEN/ISETBIO/fullvalidation';

% This particular subfile
vFile = fullfile(vDir,'color','v_Colorimetry_FullGroundTruthDataHistory.mat');

urlwrite(vFile,'deleteMe.mat')

Also, have a look at these web-sites, which is generally where I have the 30T and am building up non-repository but useful largeish data files.
   http://scarlet.stanford.edu/validation/SCIEN/
   http://scarlet.stanford.edu/validation/MRI/

**Comment by chichilnisky** [comment]
We'll definitely want to stash some large-scale retina data in the repository when James gets us fully into RGC modeling mode.

ej

**Comment by DavidBrainard** [comment]
These worked for me.  The full validation files aren't that big and this is probably fast enough for them.  But I am a little worried that for bigger things (hyperspectral image databases) it will be too slow to download on demand.  

Can we also access these sites by some sort  of sftp based mount?  Then one could run a synchronize and keep a local copy up to date.  Maybe not for validation (but maybe, depending on speed).

Is there an equivalent urlwrite?

**Comment by npcottaris** [comment]
These worked for me too.

Matlab 2015a says that urlwrite is not recommended and to use websave instead.
I tried websave as follows:
	outfilename = websave('deleteMe2.mat',vFile)
and it worked too, creating a ‘deleteMe2.mat’ file with the same contents as the one generated by urlwrite.

I could not find in Matlab a 'web' or 'url' way to upload data to a website.
What is the recommended way to send data to scarlet?  
We could use  Matlab's mput (ftp) if ftp access is allowed.

**Comment by wandell** [comment]
Well, no websave in Matlab 2013b.  I suppose we can use a wrapper and make it version dependent.

ftp is too complicated for me.  This approach seems so easy.  Also, note how easy it is to redirect to another site.

Things we might discuss on Friday - 

   What top level functionality should we include?  Download all the validation?  Some?  Check time-stamps or checksums?
  We don't have a plan on writing the data to the site, other than using sftp for users with permission.
  Should we include this within individual validation scripts, or just permit getting the whole thing?

**Comment by npcottaris** [comment]
OK, we'll stick with urlwrite for now.

I think one strategy we could follow is this: 
(1) Every time you run a full validation run, download a syncfile containing timestamps/checksums for all FULL validation files.
(2) For each validation script, check if a full validation dataset for it exists locally.
   (2a) If it does not exist, download it. 
   (2b) If it exists, compare its timestamp/checksum (stored inside the validation data) with the one contained in the sync file. If they disagree, download the file again. If they agree, proceed with the validation.

I think the UnitTestToolbox should be responsible for doing all of the above operations as it goes through each validations script.

How can we get write permission to the site? I would like to try uploading some validation data from Penn.

**Comment by wandell** [comment]
Superceded by RemoteDataToolbox.  Closing
