### ISSUE TITLE
Tweak to ieInit

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#21]
I put a "clear global" into ieInit.  I think this makes things clear out a bit better.  Not 100% sure but it hasn't done any apparent harm to me yet.

I also made s_ieInit simply call ieInit, since we are trying to make s_ieInit go away.  But, I left everything that was there in, just commented out.

**Comment by wandell** [comment]
I have been running this way for a few days.  Seems OK.  Closing this issue.
