### ISSUE TITLE
Black frame at end of oiSequence calculation with coneMosaic.compute - still with us.

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#211]
Hi @npcottaris 

Following on my email ...

Below is some code that produces the final black frame.  I am stumped about where the problem is coming from. 

Here is a link to the blankFrame.mat.gz file that contains the two parameters, an oiSequence called 'harmonic' and a struct 'params'.

   https://drive.google.com/open?id=0B9r5IfvPS81bN2Jxb1lKa0xSVk0

Thanks,
Brian

    % Just visualizes the input data in the oiSequence stored in 'blankFrame'
    load('blankFrame')
    ieAddObject(harmonic.oiModulated); oiWindow;
    ieAddObject(harmonic.oiFixed); oiWindow;
    oi = harmonic.frameAtIndex(10); % ieAddObject(oi); oiWindow;
    vcNewGraphWin; imagesc(oiGet(oi,'rgb'));

    % This is the calculation that (I think) needs fixing.
    cm = coneMosaic;
    cm.setSizeToFOV(params.cmFOV);
    cm.integrationTime = harmonic.timeStep;
    cm.noiseFlag = 'random';
    emPaths  = cm.emGenSequence(harmonic.length, 'nTrials', params.nTrials, ...
       'em', params.em);
    cm.compute(harmonic);
   cm.window;`

**Comment by wandell** [comment]
The problem seems to arise with the calculation on line 295 in computeForOISequence.m

The loop is on oiIndex.  At line 295 a variable is computed that determines where the new absorptions will be placed.  The first two times the absorptions are written into the firstEMinsertionIndex of 1.  The last time through (the final slot in the matrix) never has any absorptions written into them and thus the value is zero.

I am not comfortable enough with the very large number of variables and conditions in this function, so I will wait for Nicolas to have a go at it.

Thanks,
Brian

**Comment by npcottaris** [comment]
I believe I have fixed this rounding-off related error, by rounding all times to the nearest microsecond. 
Please git pull, re-check and let me know if this works for you.
I get no black frames with blankFrame.mat.gz

Best,
Nicolas

**Comment by wandell** [comment]
Thank you.  That did fix the problem.  I am classifying Gabor patches again.  Whew.

At a later time, let's discuss whether we stick with this very general oiSequence and compute architecture, or we try to simplify.  

But for now, just a thanks and let's move on.  I will close this issue.
