### ISSUE TITLE
t_rgcLetter failure

### ISSUE THREAD

**Issue by JWinawer** [isetbio/isetbio#216]
The tutorial, t_rgcLetter, is producing an error on my machine:

```
Undefined function or variable 'ellipseQuadratic'.

Error in buildSpatialRFArray (line 121)
        Q = ellipseQuadratic([(1/rfDiameter)^2,(1/rfDiameter)^2,0]);
```

It seems the function **ellipseQuadratic** does not exist in the repository. 

If we replace line 121 in _buildSpatialRFArray.m_,

`Q = ellipseQuadratic([(1/rfDiameter)^2,(1/rfDiameter)^2,0]);
`

with the commented out lines (lines 119-120), 

```
        d1 = 1; d2 =  10*0.0675*(rand(1,1)-0.5);      % 0.0675*randn(1,1);
        Q = (1/rfDiameter^2)*[d1 d2; d2 d1]./norm([d1 d2; d2 d1]);
```

then the script runs.

**Comment by jamesgolden1** [comment]
We are currently working on another branch to clean up this part of the code, and we mistakenly committed this change to master instead of the branch. Lines 119-120 are indeed how the master branch should be for now, and we will merge the branch with the corrections in the next few days.
