### ISSUE TITLE
t_linearFilters (in tutorials/outersegment) crashes.  It's an error in the plotting section.

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#218]
Also, this tutorial really needs some header comments that explain what it is intended to illustrate.  Same with some of the other tutorials in the same directory.

**Comment by wandell** [comment]
Assigning to Nicolas.  It could be a very useful tutorial that I would point to in the wiki.  But comments are needed.

**Comment by wandell** [comment]
I had a look - as we are cleaning - and on my computer this (apparently very useful!) tutorial stalls when running at the 100.0 cd/m2 level.  I will try to look into this more, but perhaps @npcottaris knows what's up.

**Comment by npcottaris** [comment]
I'm on it.

**Comment by npcottaris** [comment]
This is done. Bug fixed + extensive cleaning up + comments. Moved outside of under_developent_os, into t_outerSegment.
