### ISSUE TITLE
Let's make a function that classifies on subregions of the sensor - and related honks

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#22]
For running the SVM classification we will want to pick out little bits of the larger sensor array.  This is mainly because we can't really run SVMs on a very big array (e.g., 500 x 500) efficiently.  For about 1 deg, we are OK.

So, we will use either a 'saliency' criterion or a 'random sample' criterion to pull out 1 deg regions and check the classification multiple times.  If we never see a difference, say after 5 or so samples, we will declare that the two sensor responses are not discriminable.

So, we need a function to pull out the regions in a systematic way.

This also raises the question of whether we should be putting the classifiers in ISETBIO - the classification code is currently in computationaleyebrain.  Or whether we make a parallel classification tool directory.  And how we will oversee the demise of computationaleyebrain in favor of BL<this> and BL<that>.

**Comment by DavidBrainard** [comment]
Closing.
