### ISSUE TITLE
Checking isetbio tree structure

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#228]
After a recent pull, I now have both isettools/outersegment and isettools/cones/outersegment directories on my machine.  The isettools/outersegment one is grayed out in my git client, which makes me think I should just delete it and treat the one in isettools/cones/outersegment as the real one.

Similarly, I have a grayed out isettools/innerretina directory with an ir object in it, but I think this should also be deleted.

I'm assuming this is a one time git glitch, possibly local to me.

Can someone confirm?

**Comment by wandell** [comment]
I only have isettools/cones/outersegment, and that is all I see on the master branch in the web page.  So, yes - I think you should delete isettools/outersegment.

I do not have innerretina.  And I put @ir into deprecated.  Shortly, we should remove deprecate, though to do that I should make a branch, remove, and run validate.  I will try to do that today.

**Comment by wandell** [comment]
Done.
