### ISSUE TITLE
Deleting branches?

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#229]
Can the bipolar and layer branches now go away?

**Comment by wandell** [comment]
I deleted the layer branch.  Let's wait for @jamesgolden1 to delete the bipolar branch.

**Comment by jamesgolden1** [comment]
The code for the prosthesis paper has mostly been updated to work with the isetbio master branch, but I would like to keep bipolar around just in case there are any problems.

**Comment by DavidBrainard** [comment]
The bipolar branch is gone, so I am closing this issue.  We still have other branches that need merging, but those can go into a new issue if the branches don't get merged soon.
