### ISSUE TITLE
rgcLNP function misses bipolarM input argument

### ISSUE THREAD

**Issue by elinekupers** [isetbio/isetbio#231]
I found a bug in the rgcLNP function when trying to create a RGC layer from our bipolar layer. I use the script s_ogRGC.m in our JWLOrientedGabor ISETBIO repository.

I execute the following line to create a new RGC mosaic:
    `rgcL.mosaic{1} = rgcL.mosaicCreate(bpL.mosaic{1},'on parasol','LNP', rgcParams);`

Line 77 in rgcLNP/rgcLNP.m states:
`obj = obj@rgcMosaic(rgc, cellType, varargin{:});`
    
but I think it should be: 
`obj = obj@rgcMosaic(rgc, **bipolarM**, cellType, varargin{:});`

I get the following error stating that bipolarM should be a cell containing a bipolarMosaic, not the cell type 'on parasol' (which is the third input argument):

```
Error using rgcMosaic (line 108)
The value of 'bipolarM' is invalid. It must satisfy the function:
@(x)(isequal(class(x),'bipolarMosaic')).

Error in rgcLNP (line 77)
            obj = obj@rgcMosaic(rgc, cellType, varargin{:});

Error in rgcMosaicCreate (line 57)
        rgcM = rgcLNP(rgcL, bipolarM, cellType, p.Unmatched);

Error in rgcLayer/mosaicCreate (line 144)
            rgcM = rgcMosaicCreate(rgcL,bipolarM,cellType,varargin{:});
```

Is it possible to change this? If so, what is the preferred way for the future (especially for small bugs like this)? Shall I change this myself and ask for a pull request? Or shall I notify by creating a Github issue? I have no particular preference!

**Comment by wandell** [comment]
Thanks!
@jamesgolden1 and I had meant to eliminate the method 'mosaicCreate' for the layers.  The preferred way to create a mosaic is to do it explicitly by a call like

    bipolarLayer.mosaic{ii} = bipolarMosaic(....)

and similarly for the rgcLayer mosaics.  The reasons are the complexity of managing two different methods of creating the mosaics and also because the calling conventions differ.  We think for now it would be best for people to explicitly add their mosaics.

Examples of how do to this are in s_rgcGrid.

We just updated the master branch, removing the mosaicCreate methods for both the rgcLayer and the bipolarLayer.  Please update your call s_ogRGC.m to create explicitly.  @jamesgolden1 is standing next to me and wants to review that script with you when you get a chance.

**Comment by elinekupers** [comment]
Got it. And thanks for the quick reply!
I'll update the script now and let you know if it works

**Comment by jamesgolden1** [comment]
I think you want this line to replace 235 and it should be ok:

    rgcL.mosaic{idx} = rgcGLM(rgcL, bpL.mosaic{idx},rgcCellTypes{idx},rgcParams);

**Comment by elinekupers** [comment]
Hmm. We would like to use the LNP model if possible.

The rgcGLM function works with the line you provided, but if I use rgcLNP, I get the same error as before:

`    rgcL.mosaic{idx} = rgcLNP(rgcL, bpL.mosaic{idx},rgcCellTypes{idx},rgcParams);
`

```
Error using rgcMosaic (line 108)
The value of 'bipolarM' is invalid. It must satisfy the function:
@(x)(isequal(class(x),'bipolarMosaic')).

Error in rgcLNP (line 77)
            obj = obj@rgcMosaic(rgc, cellType, varargin{:});
```

Adding the input argument "bipolarM" at line 77 before the cellType argument fixes the error..

**Comment by jamesgolden1** [comment]
Ah you are totally right - I just updated rgcLNP on the master branch with the fix you recommended.

There is another problem with handling 'nTrials' input, I will see if I can fix that.

**Comment by elinekupers** [comment]
Great! The rgcLNP function works now, except for the computing the spikes of multiple trials, as you noticed..

**Comment by jamesgolden1** [comment]
I made a new branch called "rgcTrials" that has the nTrials output going again for the rgcLayer. The compute call does not require the bpL.mosaic. Let me know if that is working for you.

[rgcL, nTrialsSpikes] = rgcL.compute('bipolarScale',50,'bipolarContrast',0.2,'bipolarTrials',bpNTrials,'coupling',false);

**Comment by elinekupers** [comment]
Yes, it seems to work. Jonathan and I still have to do some validation of the script (for example how the eccentricity is taken into account across the layers), but so far there are no obvious errors.

Thanks!

**Comment by wandell** [comment]
@jamesgolden1 - s_rgcGrid does not return the same result in rgcTrials branch and master branch.  Please have a look.

**Comment by jamesgolden1** [comment]
Thanks Brian - fixed! Sorry about that.

@elinekupers we also have t_rgcEccData.m and t_rgcWatson.m to map RGC size as a function of eccentricity. In the reorganization we removed the option of setting the RGC size as a function of eccentricity, but we have the data and plan to fix it in @rgcMosaic/initSpace.m. The bipolars are handled in @bipolarMosaic/initSpace.m, where we use a Dacey/Brainard/Lee paper from 2000.

**Comment by jamesgolden1** [comment]
We made a few more updates - see s_rgcGridNTrials in isetbio with an example, and we made a branch in JWLOrientedGabor with an updated version of s_ogRGC, for which I will do a pull request.

**Comment by wandell** [comment]
It seems this is now completed, and the rgcTrials branch is merged into master.
