### ISSUE TITLE
coneMosaic.plot question

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#236]
I was trying to finish off the tutorial on cone noise, and thought it would be good to show how to plot an hline of the L, M and S cone responses programatically.  There is a nice hline LMS method in the coneMosaic window, and I tracked down the actual plotting code in subfunction contextMenuPlot in file coneMosaicWindow.

The code is intertwined with gui stuff and I could not figure out it is called.  That's not a problem per se, but it might be nice whenever possible to move the plotting functionality into coneMosaic.plot so that it can be called both from the gui interface and directly by the user.

For now I am just going to expose the plotting method in its full glory in the tutorial, which might not be a bad thing.  [One comment from the Occulus group is that they are eager for more tutorials that show how to do things without using the gui.]

**Comment by wandell** [comment]
Good idea and done.
