### ISSUE TITLE
'eccentricity' arg update, question of how to proceed

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#237]
I have updated osBioPhys and linearFilters so that they take an 'eccentricityDegs' key/value pair, but left them backwards compatible.  In osBioPhys, there is an 'osType' key/value pair that when false uses peripheral parameters and when true uses foveal parameters, while in linearFilters the same behavior is implemented via the 'eccentricity' key/value pair.  With 'eccentricityDegs' set to -1, the old key/value pairs are respected.  I believe I have changed all calls within isetbio that used the old key/value pairs to use 'eccentricityDegs', but there may be cases outside the isetbio tree that use the old ones.

There is also an 'eccentricity' key/value pair in the initSpace function for the bipolarMosaic object. This takes an actual number for the 'eccentricity' value, and I think based on staring at the numbers in the code that the eccentricity is in degrees.  

We will want to make all of the 'eccentricityDegs'/'eccentricity' arguments compatible soon, before usage diverges too much more.  Choices would appear to be: a) Go ahead and deprecate the old usage in osBioPhys/linearFilters and change 'eccentricityDegs' in those routines to be called 'eccentricity'. b) Change 'eccentrictity' -> 'eccentricityDegs' in bipolarMosaic/initSpace, which then allows us to maintain backward compatibilty on the other routines a while more but will require fixing of things that call bipolarMosaic.

Posting this issue to collect opinions.

**Comment by wandell** [comment]
I think this is a better approach than what we had.  

I think option (a), deprecate, break, fix, is the right choice for this point in the project development.

**Comment by DavidBrainard** [comment]
Implementing choice a) above now.  Will post and close this issue when done.

**Comment by DavidBrainard** [comment]
Done.  Let the breaking and fixing of any code outside of isetbio that used the now deprecated calls begin.

Closing.
