### ISSUE TITLE
A task for wandell and HJ

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#25]
Make an eyeball (eb) object.  Sets/Gets and so forth.  Like the camera object in ISET.

**Comment by hjiang36** [comment]
I made a eyeball object in branch coneTemp. Currently, it's a class, could do set, get, compute, visualize, etc. Well, not that similar to camera object in ISET. But it could be improved gradually.

Maybe I should make some wrappers such as eyeballCreate, eyeballGet, eyeballSet. Or even convert it fully into a structure.

**Comment by wandell** [comment]
Could we call the class 'eb' instead of eyeball?  Votes?  I prefer the shorter version, but I can live with longer one if everybody prefers it.

**Comment by chichilnisky** [comment]
I suppose we can’t call it eye because Matlab took that name?  

We could turn the tables on matlab and call it “identity”.

I like shorter.  I would like to understand what this object does ...

ej

**Comment by hjiang36** [comment]
eb is just a variable name. We can call it whatever we like. I also prefer
to call it eyeball but the class name is also eyeball. Maybe we could
change class name to EyeBall to avoid conflict?

**Comment by wandell** [comment]
So the proposal is to generate the class called eyeball, but we will only use that long name to initialize the object, say

  eb = eyeball(param);

From then on we would use eb.computeSomething.  That seems better to me than what I feared.

As long as we don’t have to see the word eyeball throughout the code, I will be OK.  Once or twice, but not more.

Great you are getting this started!

Brian


> On May 17, 2015, at 10:46 AM, Haomiao Jiang <notifications@github.com> wrote:
> 
> eb is just a variable name. We can call it whatever we like. I also prefer
> to call it eyeball but the class name is also eyeball. Maybe we could
> change class name to EyeBall to avoid conflict?
> On Sun, May 17, 2015 at 10:38 AM E.J. Chichilnisky <notifications@github.com>
> wrote:
> 
> > I suppose we can’t call it eye because Matlab took that name?
> >
> > We could turn the tables on matlab and call it “identity”.
> >
> > I like shorter. I would like to understand what this object does ...
> >
> > ej
> >
> > > On May 16, 2015, at 8:43 PM, Brian Wandell <notifications@github.com>
> > wrote:
> > >
> > > Could we call the class 'eb' instead of eyeball? Votes? I prefer the
> > shorter version, but I can live with longer one if everybody prefers it.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/isetbio/isetbio/issues/25#issuecomment-102809278>.
> >
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/25#issuecomment-102810634>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by npcottaris** [comment]
Just one ne thing to consider.
If you would need  the class to contain Static methods (Static methods are utility methods that do not operate on a class' instance data, but a developer may want to include them in the class because they perform operations closely related to its functionality), then to call them you would have to use the entire class name:
eyeball.doSomerhing();

Nicolas

**Comment by DavidBrainard** [comment]
I am not entirely clear on what the eyeball object is going to do.

I wonder if this is a good moment for us to write down a list of the current isetbio objects with a brief description of what each does and how they are structured hierarchically.  Perhaps on a wiki page on the gitHub site.  This is something that will be useful for us going forward in any case, and may help as the eyeball object comes into existence.

DB

> Just one ne thing to consider.
> If you would need the class to contain Static methods (Static methods are utility methods that do not operate on a class' instance data, but a developer may want to include them in the class because they perform operations closely related to its functionality), then to call them you would have to use the entire class name:
> eyeball.doSomerhing();
> 
> Nicolas 
> 
>

**Comment by wandell** [comment]
Yes, we (I) should improve the documentation.

Concerning the eyeball, the idea is this.  We have assemble a collection of parts (lens, inert pigments, cone mosaic) and do calculations with all of them in series.  In ISET it has been helpful to me to have a single object (which I call camera in that context) that includes the diverse set of objects.  So, it seemed to me that having a single object describing an eyeball would like be helpful to us in this context, as well.  Then rather than computing in series (scene -> oi -> cone mosaic -> bipolar -> ganglion ) we could form a single object (eyeball) that has a record of all the parts and issue a command like

    eb = eyeball;
    eb.compute(scene);

We can set the parameters from a single command, such as eb.set('macular pigment density',val) or eb.set('wavefront aberration',val) or eb.set('cone mosaic',val).

So, that's the thought.  I like the 'camera' object in ISET.  So I thought you might like the eyeball object in ISETBIO.

**Comment by hjiang36** [comment]
I guess we are mostly done for this topic. More objects are coming.
Onward
