### ISSUE TITLE
Minor issue: ConeMosaic GUI bug displaying eccentricity

### ISSUE THREAD

**Issue by elinekupers** [isetbio/isetbio#250]
This is a minor issue, but we would still like to report it in case someone is working on minor fixes

The GUI showing the ConeMosaic doesn't display the correct eccentricity when it is not zero degrees. It is correctly stored in the cone mosaic object (with the correct density etc.), just not correctly updated in "eccentricity" window on the lower right of the GUI.

For example:

``` Matlab

cparams.eccentricity = 6;
whichEye = 'left';
deg2m = 1/3 * 0.001;

% Compute x,y position in m of center of retinal patch from ecc and angle
[x, y] = pol2cart(0, cparams.eccentricity);
x = x * deg2m;  y = y * deg2m;
        
cMosaic = coneMosaic('center', [x, y], 'whichEye', whichEye);

cMosaic.window

````

![image](https://user-images.githubusercontent.com/6117079/29984590-0deb86c0-8f29-11e7-8b53-a23c8acb416f.png)

**Comment by wandell** [comment]
I think I fixed the bug.  Thanks!
