### ISSUE TITLE
Delete isettools/color/transforms/xyz2vSNR.m, or fix

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#258]
@wandell Routine xyz2vSNR depends on scComputeSCIELAB, which is not in isetbio.  So it doesn't currently work.  xyz2vSNR is not called elsewhere in the isetbio tree.

We can delete (easy) or add what is needed to make it work.

I tend to think delete, and then if we ever want it, put the whole required set of routines in at that point.

But, your call.

**Comment by wandell** [comment]
Deleted.
