### ISSUE TITLE
Cone adapt mysteries

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#26]
There was code in sensor get that allows one to get adapted data.  This was incorrectly pointed to in the help text and once we called it correctly (by using sensorGet('adapted data') it crashed.  That's because the code itself called sensorGet('adapted volts') which doesn't exist.  We changed that line to be sensorGet('adaptation offset') because the left hand side had a variable name called offset.  But we aren't sure this is right.  We will push this change up to gitHub once Xiaomao's permissions get sorted out (we should be able to deal with that).

Then we realized that we are very confused, because the cone adaptation tutorial itself runs.  It calls a function named coneAdapt.  We haven't yet traced through this all, because we figure you guys can tell us what is known to be stale and where we should be looking.

**Comment by chichilnisky** [comment]
While you’re on this — “coneAdapt” as a name for this function seems like a misnomer to me.  It’s a model for cone dynamics as a function of the incoming light stream.  It incorporates adaptation but it’s not a model of adaptation per se, certainly not in the sense that the field means it.  I would suggest a new name, e.g. coneModel or coneDynamics

ej

**Comment by fmrieke** [comment]
Very true - this is a cone model, not a model for cone adaptation.  I think coneModel is more appropriate.

Fred

**Comment by hjiang36** [comment]
The sensorGet routine was developed before coneAdapt. At that time, the adapted data is fully characterized by some linear conversions (gain and offset). Later, we added some non-linear model to coneAdapt, but that non-linearity can not be well represented with the existing data structure (gain, offset, etc.). Besides, some model gives the adapted output as membrane current while some gives output as volts. One possible solution is to call coneAdapt in sensorGet. Or we can try something else. I guess David already got some solutions.

**Comment by DavidBrainard** [comment]
I think we've now dealt with this issue, and/or moved the relevant issues to a more recent posted issue.  Closing.
