### ISSUE TITLE
mean illuminance issue ... oops

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#260]
In the opticalImage we have a slot for the mean illuminance (oi.data.meanIll). It became important to me to delete the meanill slot and always calculate the value on the fly.

I deleted the variable and checked the calculations, which were OK.  It was my intention to create a new branch and have a pull request, because my change breaks the validation: none of the numerical values are wrong but there are some checks about the number of fields in some structs. The field counts no longer match up because, well, I deleted the meanIll.

So, I am hoping that one of the pros at Penn might confirm this and run a new set of validation data, ultimately merging this pull request.

Sorry that I didn't get this done by a pull request.  A mistake on my part.

**Comment by DavidBrainard** [comment]
I verified that the three broken validations returned the same data, except for the missing meanIll field. And then I uploaded new validation data for:
  v_HumanRetinalIlluminance580nm
  v_oi
  v_sceneoiSpatialResample
Now they pass.

Closing this issue.  

We should be alert to the possibility that some code somewhere uses the field that now does not exist, and thus that something has a minor break for this reason.
