### ISSUE TITLE
ray trace branch

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#261]
@tlian7 is building an EyeModeling repository that uses ray trace methods.  I started a branch (raytrace) that will extend the optics models.  This work will incorporate both the EyeModeling work and the new pbrt2ISET work in a related repository.

**Comment by tlian7** [comment]
Actually, I did already start a branch for the eye modeling stuff called opticsRayTrace, should we merge raytrace and opticsRayTrace in one?

**Comment by wandell** [comment]
Sorry I missed that. 

Yes, I think so.  I only did one thing, which was to allow setting raytrace as an optics model.  In that case, it converts the label to diffractionlimited so things can still run.  I wanted that so I could use ISETBIO with pbrt2ISET.

Will you do the merge?  If so, then I will switch over to using opticsRayTrace.

**Comment by wandell** [comment]
Using opticsRayTrace.
