### ISSUE TITLE
Wavefront Part II Issues: General Issue 01, wvfRootPath question

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#263]
This issue will include files from the [isetbio/isettools/wavefront/ directory](https://github.com/isetbio/isetbio/tree/master/isettools/wavefront). There will be other issues created for  the sub-directories as needed (for general notes, etc) and specific issues for fix requests, problems, etc.

File: wvfRootPath
 - [Note: JNM - Is there a reason that the other arguments of fileparts (fName, ext) are present, but not returned?]

**Comment by DavidBrainard** [comment]
No, no good reason.  I deleted the non-returned args as well as the note.

I also made the name of the returned variable in the syntax line match that listed in outputs, and then changed them all to wvfRoot for clarity.
