### ISSUE TITLE
Wavefront Part II Issues: General Issue 03, psf folder notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#266]
This issue will include files from the isetbio/isettools/wavefront/iset/ directory. There will be other issues created for the sub-directories as needed (for general notes, etc) and specific issues for fix requests, problems, etc.
File: psfAverageMultiple
 - [Note: DHB - (from below) I really have no idea why I wrote this bit, as it really just verifies the the Fourier transform is invertible. But now that it's here, I left it. It may be that I once thought it was a good idea to average the modulus of the otf, and started down that road without going all the way down it. If we ever want to average the modulus, one could start with this check code.]
 - Please check the example that I created

File: psfCenter
 - [Note: XXX - There should be an inverse to this.  The extrapolated values are set to 0.]
 - [Note: JNM - Please check the example for accuracy and terseness]

File: psfCircularlyAverage
 - Please check on the example that I created

File: psfFindCriterionRadius
 - [Note: JNM - Possibly add error checking for if inPSF or criterion are not supplied?]
 - MATLAB is trying to change sum(inPSF(index)) and its preceding find statement

File: psfFindPeak
 - [nil, ind]... if you're not intending to use nil, why not use ~? Or was the non-null variable intended to be used for something at some point?

**Comment by DavidBrainard** [comment]
The 'nil' dates from before Matlab introduced the ~ syntax for return variables to indicate that the output wasn't needed.  That was my style for indicating what is now best done with the ~.  I made the edit, and also got rid of the "BUGGY" section of the code (which was not being executed.)

**Comment by DavidBrainard** [comment]
Handled.  Closing.
