### ISSUE TITLE
Wavefront Part II Issues: General Issue 04, stilescrawford folder notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#267]
This issue will include files from the [isetbio/isettools/wavefront/stilescrawford/](https://github.com/isetbio/isetbio/tree/master/isettools/wavefront/stilescrawford) directory. There will be other issues created for the sub-directories as needed (for general notes, etc) and specific issues for fix requests, problems, etc.
File: sceCreate
 - To Do List:
   i) There should also be an sceSet
   ii) Could allow unit specification rather than defaulting to mm-based units.
   iii) Understand in more detail dependence of SCE on other things, such as field size and position.
   iv) Is the additive correction of the Berendschot numbers (as opposed to, say, multiplicative) appropriate?
 - [Note: JNM - Why is Digitized hard-coded to false (0) immediately before the if statement?]

**Comment by DavidBrainard** [comment]
I moved the Note into the TODO list.  Although there is a TODO list here, I think that we don't need to keep the issue open.  If people start using the SCE code in earnest, they will see the TODO list and can decide which if any of the ideas they want to implement.   Closing.
