### ISSUE TITLE
Wavefront Part II Issues: General Issue 05, utility folder notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#268]
This issue will include files from the [isetbio/isettools/wavefront/utility/](https://github.com/isetbio/isetbio/tree/master/isettools/wavefront/utility) directory. There will be other issues created for the sub-directories as needed (for general notes, etc) and specific issues for fix requests, problems, etc.
File: wvfComputeConePSF
 - [Note: XXX - Usage 1: If you actually know the hyperspectral image input, you probably don't want to use this routine. Rather, compute the monochromatic PSFs at each wavelength and do your optical blurring in the wavelength domain, before computing cone absorbtions.  Doing so is a more accurate model of the physics. You would use this routine under two circumstances.  First, you might know that the image consists only of intensity modulations of a single relative spectrum.  In this case, you could use that spectrum here and speed things up, since you'd only have to convolve three times (one for each cone class rather than once for each wavelength).  This case corresponds, for example, to psychophysics where achromatic contrast is manipulated. Second, you might only know the unblurred LMS images and not have spectral data.  Then, this routine is useful for providing an approximation to the blurring that will occur for each cone class. For example, your data might originate with a high-resolution RGB camera image, which was then used to estimate LMS values at each location. Keep in mind that what you get in that case is only an approximation, since the actual blur depends on the full spectral image.]
 - [Note: XXX - Usage 2: If you want to compute a strehl ratio quantity for the LMS psfs, the most straightforward way is to call this routine a second time using a zcoeffs vector of all zeros.  This leads to computation of diffraction limited monochromatic psfs that are then summed just like the specified ones.  Taking the ratios of the peaks then gives you a fairly meaningful figure of merit.]
 - [Note: XXX - Need to think through normalization and meaning of coneSceFraction carefully.]

File: wvfLoadThibosVirtualEyes
 - [Note: DHB - compared these calculations to the figures in the Autrusseau paper. He also compared the values of the Zernike polynomial coefficients that we load to the data shown in Figure 6 of the JOSA-A paper. These align as well.]
 - [Note: JNM - The first example doesn't work. is the function that is being called spelled incorrectly? Not instantiated?]

File: wvfOSAIndexToVectorIndex
 - [Note: XXX - I would add 'tip' as a synonym for one of the two tilts below, if I knew which one it was.]
 - [Note: JNM - Is there intentionally not a comma between 'defocus' and 'vertical_astigmatism' in the validation code below?] -- This question is because the situation is unique within that line

File: wvfWave2idx
 - [Note: XXX - Currently only returns exact matches within rouding to 1 nm. And throws an error if there are none.]
 - [Note: XXX - Is this really only for 'calc wavelengths'?  Should we have a flag for 'measured wavelength' and 'sce wavelength'?]

File: wvfZernikeMNToOSAIndex
 - Validation code s postpended to wvfZernikeNMToOSAIndex
 - [Note: JNM - Which is the correct name then? MNT or NMT?]

**Comment by DavidBrainard** [comment]
Handled all of these.  Closing.
