### ISSUE TITLE
Wavefront Part II Issues: Broken Examples: utility folder

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#269]
This issue will include files from the [isetbio/isettools/wavefront/utility/](https://github.com/isetbio/isetbio/tree/master/isettools/wavefront/utility) directory. There will be other issues created for the sub-directories as needed (for general notes, etc) and specific issues for fix requests, problems, etc.
File: wvfLoadThibosVirtualEyes
 - First example does not work!

**Comment by DavidBrainard** [comment]
Somebody has fixed this.  Closing.
