### ISSUE TITLE
Eye movement buglet 

### ISSUE THREAD

**Issue by xnieamo** [isetbio/isetbio#27]
When we set the eye movement sample time to 50 msecs (0.05) right after the call to eye movement create in t_eyemovement, it crashes.  The error is thrown from the emGenSequence function.

**Comment by fmrieke** [comment]
Can you see what happens if you set the ample time to something much shorter?  The underlying code is running a set of numerical differential equations (using the Euler method I believe) and 50 ms is almost certainly too long a time step.  I can investigate a bit more if that does not work (I’ve been playing with a version of that code too).

Fred

**Comment by xnieamo** [comment]
It works fine shorted time intervals, such as 1 msecs.  The error seems to occur when the sample time is greater than 2x the tremor interval, in which case tPos gets a 0 as one of its entries in line 62 of emGenSequence.  This causes an indexing error in line 70 of the same function.  I do not know if this is intended.

**Comment by DavidBrainard** [comment]
In response to Fred’s comment, I don’t think this is related to the cone model, but to the set up of a vector that says when eye positions will be sampled.  It would be nice to be able to run just this part at longer intervals, for debugging purposes if nothing else.

> It works fine shorted time intervals, such as 1 msecs. The error seems to occur when the sample time is greater than 2x the tremor interval, in which case tPos gets a 0 as one of its entries in line 62 of emGenSequence. This causes an indexing error in line 70 of the same function. I do not know if this is intended.
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/27#issuecomment-104702013>.
> 


=========
David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by hjiang36** [comment]
I didn't see the error on my computer. Maybe the position I changed the sample is different from what you do. Anyway, changing sample time to 50 ms could be problematic for both eye movement and cone adaptation computation. Usually, if there's no special reason, I prefer to leave it as 1 ms.

HJ

**Comment by DavidBrainard** [comment]
OK, we’ll post the exact code that crashes.  It may be it is a bad idea to do this, but it shouldn’t crash but rather should print a helpful warning.

> On May 22, 2015, at 1:16 PM, Haomiao Jiang <notifications@github.com> wrote:
> 
> I didn't see the error on my computer. Maybe the position I changed the sample is different from what you do. Anyway, changing sample time to 50 ms could be problematic for both eye movement and cone adaptation computation. Usually, if there's no special reason, I prefer to leave it as 1 ms.
> 
> HJ
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/27#issuecomment-104718266>.
> 


=========
David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by xnieamo** [comment]
sensor = sensorCreate('human');

em = emCreate;
em = emSet(em, 'sample time', 0.050);

sensor = sensorSet(sensor, 'eyemove',em);

sensor = sensorSet(sensor,'positions',zeros(10,2));

sensor = emGenSequence(sensor);

Running the code above causes a crash for me.

**Comment by hjiang36** [comment]
I get the point. And per your suggestion, changing line 62 from round to ceil could help avoid that problem.

Another thing we might want to fix is the redundancy of sample time. There are three different things in  current version of ISETBIO:
1) sensorGet(sensor, 'exp time') - exposure time of the sensor, mainly used in absorption calculation
2) sensorGet(sensor, 'sample time interval') - sample time stored in sensor, mainly used in cone adaptation
3) sensorGet(sensor, 'em sample time') - sample time for eye-movement

In the ideal case, there should be only one sample time for sensor (or perhaps two). Inconsistencies between the fields could cause some problem. In most cases currently, we keep the em sample time and the sensor sample time the same (1 ms).  When doing computation with eye-movement, we manually change the exposure time to first be the same as sample time and compute cone absorptions per sample time. Then, we use a sliding window of length exp time/ sample time to sum up the cone absorptions to get the desired absorptions per exp time. 

I know this sounds a little confusing and we might want to find some way through in the future.

HJ

**Comment by wandell** [comment]
We think this bug is solved, and it has led to a simpler issue.  We will close this one and raise the simpler one as a new issue.
