### ISSUE TITLE
Wavefront Tutorials Part I: Notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#270]
t_wvfZernike
        - Can we explain why a number of the hard-coded values were chosen. I don't think all of these numbers were necessarily explained in the tutorial
        - Notes:
            * [Note: XXX - This might usefully be separated in several shorter tutorials.]
            * [Note: XXX - Introduce notion of a figure of merit for quality of PSF, and compute some explicitly for various cases considered.]
            * [Note: XXX - The fact that for an aberrated eye, the best optical quality does not occur when nominal defocus wl matches the calculated wavelength is not considered here, but can be quite important when thinking about real optical quality.]
            * [Note: JNM - Below, there was a section stating that only onewavelength was to be used, and a variable initialized for the purpose, but it was never used throughout the tutorial, so I have removed the section title, the variable itself, and grouped the other variables initalized in that section into the appropriately named 'Initialize' section]
            * [Note: JNM - There are a number of variables that are initialized and then never used. Was this done intentionally? As a part of the testing process? For what purpose are they kept around? Ex. nCols, nRows, uDataS, defocus]
            * [Note: JNM - the defocus value is summed with lcaMicrons, and then lcaMicrons is used as  the defocus value? (L311-313) - is this done intentionally, or is it an accident? Same question about the variables that are initialized and used once, by name and then never again. Is there a purpose to this? Ex. oblique_astig]
        - Cosmetic Adjustments
    t_wvfZernikeSets
        - This has significantly less commenting done. There is no explanation behind why any of the hard-coded values are chosen (D, A, wavelength=550, plotRange=20). See below note.
        - [Note: JNM - Can we please include explanations for why the included default values are chosen, other potential options, or reasonable alternatives for the selections?]
    t_wvfPupilSize
        - Added note: [Note: JNM - Would it be possible to include an explanation for how the different pupil sizes (from Thibos) would affect the calculations, and the eventual output]
    t_wvfAstigmatism
        - [Note: JNM - Why is 'z' calculated and then never used?]
        - How were these hard-coded values selected?

**Comment by DavidBrainard** [comment]
Handled note in t_wvfPupilSize, on the otf branch.  This will make it into the master soon enough.

**Comment by DavidBrainard** [comment]
One of the notes above is why we might choose to code like this:
  oblique_astig = 0.75;
  wvf3 = wvfSet(wvf0, 'zcoeffs', oblique_astig, {'oblique_astigmatism'});

rather than just
  wvf3 = wvfSet(wvf0, 'zcoeffs', 0.75, {'oblique_astigmatism'});

given that in the first case the variable oblique_astigmatism is only used once.

The reason is that by defining the variable, we hope to make a little clearer the meaning of what is
beging passed to the set call.  Perhaps it is already clear from the fact that the next argument says what it is, but that was the idea.

**Comment by DavidBrainard** [comment]
Handled notes in t_wvfZernike

**Comment by DavidBrainard** [comment]
Handled the rest of the notes here.  Closing.
