### ISSUE TITLE
Documentation standard on wiki

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#273]
Looking good.  But I would suggest that "Examples" be optional rather than required.  They are nice, but the sky doesn't fall if they aren't there.  I'd be happy to say in the standard that we really like having these, though.

For discussion.

**Comment by jenmaxwell** [comment]
I'm good with this. Unless @wandell has any objections, I'll move Examples to the optional section.

**Comment by wandell** [comment]
Happy with all this, and glad to see the documentation in the wiki about the standards.  Onward.
