### ISSUE TITLE
isettools/utility Part I Issues: Example work

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#274]
#The following files in the base utility and file sub-folder have had their examples either altered or added and I would like to ensure that my work is checked over.

isetbio/isettools/utility
 - ieContrast - _Reviewed and OK, DHB_.
 - ieFindWaveIndex  - _Reviewed and OK, DHB._
 - ieFitLine (The example I created is definitely too simplistic to showcase what I believe you want to accomplish with the function.) - _Function now deleted in an earlier commit from BW, DHB_.
 - ieFormatFigure (My examples definitely need to be expanded. They are simplistic and don't actually showcase the capabilities of the function) - _Made the example do something.  Also caught case error in the notDefined calls, and fixed this. DHB._
 - ieSpace2Amp - _Reviewed and OK, DHB._
 - ieUncompressData - _The first line of header comment says "Deprecated".  So I removed the example on the grounds that we don't need it.  DHB.  I think BW is working to ablate this from isetbio altogether and is most of the way there._
 - ieUnitScaleFactor - _Reviewed and OK, DHB_.
 - ieWave2Index - _Reviewed and OK, DHB_.
 - sample2space - _Reviewed and now OK, DHB_.
 - space2sample - _The header comments said this is obsolete, and it is not called anywhere in the isetbio tree.  It printed obsolete when run.  I have deleted it. DHB_.
 - temporalEquivEcc - _This routine is not finished and not ready to use.  I put in an error statement, so that no one will be fooled, and added to the notes.  It is currently only called from rgc code initSpace(), and that code is also best viewed as under development.  DHB_.

isetbio/isettools/utility/file
 - vcExportObject - _No action appears required.  DHB._
 - vcSaveObject - _No action appears required.  DHB._

The following examples I view as incomplete, since they merely open the GUI asking the user to select a file. That doesn't allow us to actually showcase the proper use of the function:
 - ieFieldHeight2Index (I was unable to fix either example -- please help??? ('rtPSFfieldHeight' doesn't exist in opticsGet)).  _Posting new issue just for this. DHB._
 - ieReadSpectra - _This appears to have a working example that behaves fine.  I am not sure what needs addressing.  DHB._
 - ieSaveMultiSpectralImage - _This appears to have a working example that behaves fine.  I am not sure what needs addressing.  DHB._ 
 - ieSaveSIDataFile.  _Example works.  There was a problem with the call to siSynthetic in the example, but this had nothing to do with ieSaveSIDataFile so I got rid of it.  DHB._ 
 - ieSaveSpectralFile (See note in the file. The example has potential complications that may actually be from the function(s) themselves?) - _I am not sure what needs addressing here.  The example seems fine.  DHB._
 - vcImportObject _As with a number of ones above, the example seems to be working now. I
don't think the inline function needs an example. DHB._
    - Example isn't working! (See notes section)
    - does the inline function need its own example?
 - vcSelectImage (Also check programming notes?).  _Opened separate issue. DHB._
 - vcLoadObject -  _Opened separate issue. DHB._

**Comment by DavidBrainard** [comment]
Did some of the things above, and edited inline in the initial issue post to indicate which have been handled.

It looks like maybe BW has also been through this, so am stopping until we coordinate.

**Comment by wandell** [comment]
I like your method of editing the original issue rather than writing a new response.  I will follow that in the future.  Hopefully that will help coordination.

**Comment by DavidBrainard** [comment]
Most things in here were handled or I couldn't figure out what the issue was -- see comments with original post above.

I have opened new issues for the separate routines where I thought something was still pending, so that I could close this long issue out.
