### ISSUE TITLE
isettools/utility Part I Issues: Text (in-)sufficiency

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#275]
This issue is for functions where I'm concerned that the text I've added may be inadequate to describe the function as much as is required to have a general understanding of its intent, or that I am worried that I've missed the mark, and the text does not describe the function's purpose at all.

isetbio/isettools/utility
 - ieHwhm2SD
 - ieHwrect
 - ieShape
 - ieSpace2Amp
 - ieSpaceTimeFilter (The varargin section of input needs to be modified. I am not clear enough on its function to not butcher it.)
 - ieUncompressData

_All of the above handled by BAW, see below._
 - quinterp2 - _This was not called anywhere.  I deleted it from isetbio.  Can put back if we need it. DHB_.
 - ieCmap - _Handled by BAW, see below._

isetbio/isettools/utility/file
 - vcReadImage - Handled by BAW, see below.

**Comment by wandell** [comment]
Checked ieHwhm2SD, improved example
Clarified comments on ieHwrect
ieShape seems fine
Dealing with ieSpace2Amp separately with DHB.  Seems good.
Commented ieSpaceTimeFilter, improved example, introduced new validation func for pad parameter
Placed comment to note Deprecated for ieUncompressData.  This can go away after a little while.
Clarifying examples for ieCmap, answered NOTE

qinterp2 should probably move to external.

Edited your comments in vcReadImage and added additional example.

**Comment by DavidBrainard** [comment]
Everything here seems like it has been addressed.  Closing.

If my deletion of qinterp2 was a bad idea, we can put it back.
