### ISSUE TITLE
isettools/utility Part I Issues: To Do's & Notes requiring further attention

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#276]
This is for functions that have not been called out in issues #274 and #275 that have notes requiring additional attention. If the function has been mentioned in either of the previous two issues here, I will not call it out again, trusting that you will read the notes in the functions as you review them. If you would like to change that, please let me know and I will add an addendum.

isetbio/isettools/utility
 - checkToolbox - _Someone has handled this. DHB._
    = [Note: JNM - The function was marked incorrectly below as returning all of the toolbox names. It is possible to do that if you change ret above to [ret, vv], but as it stands, the function currently returns a boolean indicating whether or not the specific toolbox is installed on the local machine.]
 - dpi2mperdot -  _Someone has handled this. DHB._
   = [Note: JNM - The ~isempty(dpi) throws an error when no dpi is provided, contrary to the expected behavior of going to the else statement (and an empty return). Does this need to be addressed?]
 - ffndgrid - _Restored earlier version and moved to external/matlabcentral.  DHB._
   = Need to determine if we should treat this like randraw (move to external, download latest version, and do not disturb native commenting formats).
   = Worried I might've butchered it...
   = Notes:
       * [Note: XXX - The vector limits can be padded with NaNs if only certain limits are desired, e g if xl1 and fl are wanted: ffndgrid(x, f, [], [.5 nan nan nan 45]) If no output arguments are given, FFGRID will plot the gridded function with the prescribed axes using pColor.]
       * [Note: XXX - Tested on: MatLab 4.2, 5.0, 5.1, 5.2 and 5.3.]
       * [Note: JNM - ~Line 214 - there is an 'if 1' statement with an else case, why is this unreachable code included, or should there have been additional calculation done in the if statement rather than a universal true?]
 - getMiddleMatrix - _This appears to have been handled.  At least, the notes are gone. DHB._
   = Added error checking for missing required variables
   = Notes section
       * [Note: HJ/BW - Changed from round to floor on March 19, 2015. We are worried, but it had no effect on validationfastall and the routine is only called in a few places where this should be OK. Delete this comment after a few months.]
       * [Note: JNM - 1) Is it safe to delete the prior note? 2) The change to floor seems to only be in one of two instances? Is this half-change accidental or intentional?]
 - ieClip - _Handled by BAW as per below.  DHB._
   = Assign TODO?
 - ieGIF - _I think BAW has handled this.  At least, there is a history comment that it has been re-written since this issue was posted.  DHB._
   = Check if was necessary to add separate section for windows to ieGif's video name section
 - ieManualViewer -- _Now deleted as per BAW below.  DHB._
   = Changed /documentation/ directs to home page directs since the former was producing 404 errors.
 - ieN2MegaPixel - _I don't think there is an action item here.  DHB._
   = Added error for missing required argument

isetbio/isettools/utility/file
 - ieImageType - _Fixed up as per BAW below.  DHB._
   = Included TODO for when we can implement contains() calls
 - ieVarInFile - _This appears to have been handled.  DHB._
   = See notes for comment about correct use (or lack thereof) of the second example wrt function behavior
 - vcSelectDataFile -- _Fixed up well enough for now as per BAW below.  DHB._
   = Example line contains a non-existent function. See Note!
   = Assign someone to complete the TODO item?
   = The description probably has to be rewritten? Since it's mostly a description for the inputs section, some of which I've likely convoluted in my attempt to break things out into their proscribed sections.

**Comment by DavidBrainard** [comment]
I think everything here has now been handled.  Closing.
