### ISSUE TITLE
History section format

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#278]
Are we leaving a trailing % on its on on the last line, or not.  I am finding it both ways in the code.  I am happy either way, as long as we pick one.  But if forced, I would vote for not.  (The reason for the trailing % on a line at the end of the header comment is that it makes a feature of the doc command work more nicely, but this does not apply to the history section.)  Jenn, your call.  Let us know what you think.

**Comment by jenmaxwell** [comment]
I am good with whacking the trailing %
