### ISSUE TITLE
Branches?

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#28]
There appear to be a number of branches of isetbio now -- one is called coneTemp and one is called spectrum.

I think we decided a while back that branches should not exist for too long, just so we don't get really confused.  But in any case, I'm simply wondering what these branches are and whether I need to think about them.

**Comment by hjiang36** [comment]
Branch 'spectrum' is for the purpose of modifying data structure from XXX.spectrum.wave to XXX.wave. After making the modification, we found that it could cause a lot of potential bugs and the benefits are quite limited. I think we might want to remove it without merging it back.

For the coneTemp branch, we used cone structure in creation and parameter passing in sensorCreate, etc. Also, the eyeball class should also be there. Besides, there are some other tiny updates and commits in this Branch. Brian and I could try to merge it back to master recently.

**Comment by wandell** [comment]
HJ closed coneTemp.  So we are closing this issue.
