### ISSUE TITLE
isettools/utility changes Part II Issues: utility/functions Notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#283]
This issue is to cover the functions folder and pieces of the functions therein that require additional work, correction, etc.

- coneEmpiricalDimFlash - I have literally zero idea of how to describe this function. I am maybe 15% certain of my descriptions and edits. Please look over both descriptions, and my inputs and outputs sections. _Reviewed and tuned up, DHB._
- hill - Please check my attempts at descriptions for both of those sections, as well as my descriptions of the variables - _Reviewed and tuned up, DHB._
- sumoftwodblexponentials - _Reviewed and tuned up.  Nothing seems to call this, so I renamed it sumOfTwoDblExponentials. DHB._
   = This function does not follow the naming convention of the rest of the functions.
   = Name inside the function did not match the filename
   = There is likely a much better way to describe the inputs and outputs sections.
- weberFechner - I am positive that the inputs and outputs sections need to be reviewed. I am only even semi-confident about one of the variables' (x) descriptions. _Found the paper on which this is based, added refs, and made description explain what its about. DHB._

**Comment by DavidBrainard** [comment]
Everything here dealt with as per comments added to original post.  Closing.
