### ISSUE TITLE
isettools/utility changes Part II Issues: utility/hypercube Notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#284]
This issue is to cover the hypercube folder and pieces of the functions therein that require additional work, correction, etc. Please also note that this does not include the files that have broken examples, as that is covered in issues #282 
- hcBlur - Please check my description & inputs/outputs sections
- hcimage - For the cases for various display types. The first argument of varargin is referenced additionally (after already being assigned to another name) ... should this be referencing later entries?
- hcReadHyspexImgInfo - Note for update to contains() after 2015B cycled out.

**Comment by wandell** [comment]
Fixed these, including comment about the hcReadHyspexImgInfo, which is very special case.  There was a bug in hcBlur that is now fixed.
