### ISSUE TITLE
isettools/utility changes Part II Issues: utility/image Notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#285]
This issue is to cover the image folder and pieces of the functions therein that require additional work, correction, etc. 
- ieLUTDigital - _Reviewed, minor tweaks.  DHB._
   = Single variables inside parentheses?
   = Please make sure I didn't destroy the readability of the description section, or that the information shouldn't possibly be in the inputs section instead.
- ieLUTLinear - Not sure if we need to make a description that is less about the inputs and more about the general use(s) of the function.  _Did a little work on the description.  Good to go now, I think.  DHB._
- imageDataXYZ - **BW** Deprecated.
   = Notes
      * [Note: JNM - This function doesn't work, as imageGet does not exist]
      * [Note: JNM - This function is called in 0 places?]
- imageFlip - _Example tuning.  DHB._
   = I'm not sure if I convoluted the example by fleshing it out more. The plotting portion of it has been commented out
- imageHarmonicColor - **BW** deprecated
   = Why does imageHarmonic exist if this is the same thing plus color? Or should this one be absent??
   = See notes section? Changed parms.color to color in switch statement.
- imageLinearTransform - **BW** Checked.  Also added feature @DavidBrainard  suggested.
   = Existing example wasn't working, so I changed it. Please make sure it's still accomplishing what it was designed to do.
= Please review notes section (notes from DHB & JNM)
- imageMakeMontage **BW** Fixed.
   = See notes
   = Please make sure that the description for the outputs is correct.
- imageMontage **BW** fixed.
   = Example isn't working
   = If there are additional variables (or sections within them) that I've removed, please correct me!
- imageMultiview **BW** fixed.
   = Example isn't working
   = Having the same issues with imageGet... **BW** imageGet is deprecated.
- imagescOPP - The text information contained was primarily for imagescRGB. Please let me know if my suppositions about correct language for the entirety of the text needs to be adjusted. **BW** imagescOPP is deprecated.
- imagescRGB **BW** You did great.  This routine seems fine.
   = I am not certain I got the outputs correct
   = Is this the correct way we want to use varargin?
   = Assign someone for the TODO
- imageSetHarmonic - There are a number of functions included in this file, of which a fair number are never used. Are we to comment all of them? **BW** Deprecated.
- imageSPD **BW** changed to error.  Agree with your fixes.
   = Notes:
      * [Note: JNM - Why do we use errordlg instead of just error here?]
      * [Note: JNM - The value 0 for displayFlag is clearly called out above, yet the value was not present in the if statements for calculations. I changed the if displayFlag == 1 to <= 1, so that for a displayFlag of 0 it will be calculated as if RGB, but will not display further on. This matches the language described above.]
      * [Note: JNM - I added a section for default value for row & col, as it was breaking the examples, and it was easy enough to code]
   = It feels like I've forgotten something in the description section, but I'm not sure what.
- imageShowImage **BW** Deprecated
   = Uses imageGet - with an undefined variable the call never appears to be made? No error is returned for either the undefined variable or the undefined method.
   = Example doesn't work.

**Comment by DavidBrainard** [comment]
All handled, I believe.  Closing.
