### ISSUE TITLE
isettools/utility changes Part II Issues: utility/plots Notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#286]
This issue is to cover the plots folder and pieces of the functions therein that require additional work, correction, etc. (**BW** notes inserted).

 - scenePlot - **BW** went through these and tested with t_scenePlot.  
    = See notes section
        * [Note: JNM - Is there a reason for us using warndlg instead of warning when calling out warnings?]
        * [Note: JNM - in radiancevlineimage case below, y was defined and then x used, I have changed it to x in both places. Please advise if both are supposed to be set (y was unused and x called before definition is how I noticed this).]
        * [Note: JNM - Several case definitions were missing commas. If this was intentional I can go back and remove them, but that doesn't appear to be what was intended.]
        * [Note: JNM - illuminantimage didn't have handle initiated. Fixed]
        * [Note: JNM - When 2015B phases out, replace strfind with contains.]
    = Several of the options for plot type are missing descriptions, can you please resolve this.
 
- plotTextString **BW** examples, checks, but dealing with string length is not worth it now
    = Assign someone for TODO's/Notes
        * [Note: XXX - TODO: Positions aren't right. Fix.]
        * [Note: XXX - TODO: We need to account for the scale type when setting these positions.  Not done properly yet.  Also, it would be better to account for the string length, too.  At the very least, we could count the number of letters to set the value of delta.]
        * [Note: JNM - TODO: We should add a check for if delta is a single argument vs a pair of arguments. Ex. if length(delta) == 1, delta = [delta delta]; end]
 
- plotSetUpWindow
    = Assign someone for existing TODO

 - plotPixelSNR **BW** deprecated
    = pixelSNR does not exist (function called within)
    = legend call does not support integers as a placement-indicator

 - oiPlot - **BW** We have t_oiPlot.  Dealt with roiLocs, and most things now seem OK.
    = Notes in both the title function and the inline functions.
        oiPlot
            * [Note: XXX - TODO: This function includes within it the previous functions plotOTF and oiPlotIrradiance. Those have been deprecated. We should write a script that tests all the different plotting calls for this function and for scenePlot. We should create a sensorPlot function that is analogous.]
            * [Note: JNM - TODO: Fix examples.]
            * [Note: JNM - TODO: Check note in illuminancefft case -- is it broken? Or does the note need to be removed?]
            * [Note: JNM - roiLocs are listed as optional, however a number of the functions will break if they have not been provided because there is not language in place to generate them in all of the cases. Ex. the plot type chromaticityroi requires them but does not have an existing default.]                
        plotIrradiance - **BW** which is now oiPlotIrradiance inside of oiPlot
            * [Note: JNM - The function specified that the user data and the graphWin figure number are returned, but the return only has a single argument?]
            * [Note: JNM - Should we include an error for if roiLocs is not defined since no default value is provided?]
        = plotOTF - **BW** which is now inside oiPlot
            * [Note: JNM - When 2015B cycles out, replace strfind with contains]
            * TODO: Implement raytrace - **BW** We will deprecate this.  sceneEye replaces ray trace.
            * [Note: JNM - TODO: Someone needs to check over the "Note: XXX - " notes below, so we can determine which are safe to remove. There are several such notes.]
            * [Note: BW - We get the OTF slightly differently for the different models. If we rewrote opticsGet to check for the optics model, we could do things a little more simply here. Maybe we should put this code into opticsGet.] - Copied from below. **BW** DHB has done a lot on this front
            * TODO: Determine how to better select the number of samples for the spatial frequency. Currently 100 samples, the number of which is arbitrarily chosen. 
        plotIlluminanceMesh
            * [Note: JNM - the variable roiFlag is not included in the header, but there is a query for whether or not it was defined at the beginning of the function? It is also not used, so I removed the line.]
        oiPlotCIE **BW** it is only called from within oiPlot, so reduced argument checking.
            * [Note: JNM - There are no default options for any of the arguments, or checks that they are populated.]
            * [Note: JNM - Example will not work as this is a nested function and not publicly accessible. Calling oiPlot with a plot type of chromaticityroi, however, will end up using this function.]
        selectPlotSupport **BW** done.
            * [Note: XXX - What if data are a vector? Can we adjust this routine to make it work?]
            * [Note: JNM - if the values are unused, why is v created rather than just the empty placeholder ~ used? (Change [v, idx] to [~, idx])

**Comment by wandell** [comment]
I went through almost all of these.  A few main points
There are s_oiPlot and s_scenePlot to exercise the plotting routine examples.
I removed the pixelSNR related routines because they don't belong here.
I believe I handled the roiLocs issues in plotting, especially related to radiance v/hline image (which become radiance v/hline spectrum).  
Checked plotTxtString, which seemed OK.

Still needed - plot descriptions in the comments.  More words needed, and some way not be listed.  To check (BW).

**Comment by DavidBrainard** [comment]
I will see if I can go through some of the notes in oiPlot soon.  In the meantime, is the following (from the header comments) correct?

{'irradiance vline'} - Horizontal line spectral irradiance
%                                      (photons) - (space x wavelength)
%               {'irradiance hline'} - Vertical line spectral irradiance
%                                      (photons) - (space x wavelength)

That is, does vline give a horizontal line spectral irradiance and vise-versa for hline?  Or are the comments backwards?

**Comment by wandell** [comment]
The comments are wrong.  The plot does the right thing.


I will edit oiPlot header.


I checked using s_oiPlot.


B

________________________________

**Comment by DavidBrainard** [comment]
I think that the things that we will deal with in the finite future have been dealt with.  There are a few notes still in some routines, but none of them look urgent or high priority.  The good thing is that the notes seem clear and that if someone encounters a problem they will have some guidance about what needs doing.

I am closing this issue.  If someone thinks any of the remaining items should be bumped up in priority, I suggest creating a specific issue on the relevant point(s).
