### ISSUE TITLE
isettools/utility changes Part II Issues: utility/programming Notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#287]
This issue is to cover the programming folder and pieces of the functions therein that require additional work, correction, etc.
- checkfields - [Note: JNM - This requires the sequence to be in order, and from the beginning. See Example for clarification.]
~ Did we want the function to perform like this? Or were we looking to use it to be able to select fields from within a string of them regardless of starting point? Regardless of order?

**Comment by wandell** [comment]
I think checkfields, with the nested feature, is what we want.  Let's move on.
