### ISSUE TITLE
isettools/utility changes Part II Issues: utility/statistics Notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#288]
This issue is to cover the statistics folder and pieces of the functions therein that require additional work, correction, etc.
- ieMvnrnd.  _Left description at the end but added note to the header that it exists.  Also that one can simply use mvnrnd these days.  The way things were coded, it worked fine without K passed and K defaults to one.  I added a comment about this.  Deleted the notes and merged the first into the description.  This is good to go, I think.  DHB._
   = Not sure where I should move the 'explanation' at the end of the function - To description perhaps?
   = Notes:
      * [Note: XXX - Draw n random d-dimensional vectors from a multivariate Gaussian distribution with mean mu (n x d) and covariance matrix Sigma (d x d).  K specifies how many samples for each condition.]
      * [Note: JNM - Do we want to include a check for if K is defined?]
- biNormal - Had two NotDefined examples for xSpread -- changed the latter to ySpread. - Good catch.  DHB

**Comment by DavidBrainard** [comment]
These are handled.  Closing.
