### ISSUE TITLE
isettools/utility changes Part II Issues: utility/utility Notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#289]
This issue is to cover the utility folder and pieces of the functions therein that require additional work, correction, etc.
** I have not yet checked in an update for hiddenHandle.
- svmClassifyAcc
    = I was unable to repair the example
    = Notes:
        * [Note: JNM - input check is primative, we should update this.]
        * [Note: JNM - svmtrain is about to be deprecated, we need to update the use of this function or this will break shortly.]
        * [Note: JNM - the default options are the same for both cases, so can we move the notDefined step outside of the case statement so that it only has to be written once?]
        * [Note: JNM - Differences between this and svmAcc? Aside from opts? And two defaults.]
- svmAcc
    = I was unable to repair the example
    = This appears to be an updated version of svmClassifyAcc? Should we remove the older one?
    = svm is instantiated in svmClassifyAcc, and not in this function.
    = Notes:
        * [Note: XXX - For libsvm and liblinear, there are Matlab interfaces. However, for most other packages, there are only C++ implementation. We might write Matlab interface some time in the future. At this point, we use system() command to invoke the compiled files. To run in this mode successfully, you might need to compile the source code on your own.]
        * [Note: JNM - input check is primative, we should update this.]
        * [Note: JNM - the default options are the same for both cases, so can we move the notDefined step outside of the case statement so that it only has to be written once?]
        * [Note: JNM - Differences between this and svmClassifyAcc? Aside from opts? And that this one was created a year later? (This one doesn't have a supported 'svm' case)]
- isetbioTCInstall
    = Need to fix my Outputs section - I've no idea if this is actually what tabComplete contains.
    = A number of the ridiculously long val-string lists were missing spaces between the lines. Please double-check that I didn't miss any more....
    = About half-sure I've correctly identified the inputs for nodeArgValueSet.
    = [Note: XXX - The basic idea here is to update the TC.xml file. Because we do not have a standard for comments in functions, it's hard to extract potential string options by parsing the function file. The content of auto-completion is hard coded here and if we update those functions some time later, we need to update this file as well.]
- ieNormpdf - Update argument length check?  _Added a check. Still not perfect but good enough.  DHB._
- getGaussian - _Tweaked comments.  Someone already dealt with layerariance because it isn't there anymore. DHB._
    = What is layerariance? (L9) I'm really hoping it's just a typo
    = Please check my definitions for inputs/outputs

**Comment by DavidBrainard** [comment]
Moved forward to new separate issues questions about i) libsvm, liblinear and ii) Tab completion.

Eveything else is handled.  Closing.
