### ISSUE TITLE
Heading formats

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#294]
@jenmaxwell 

Do you think we should promote the Optional key/val pairs heading to 'Required'.  

Brian

**Comment by jenmaxwell** [comment]
I don't think we should since not all functions contain them, but it probably wouldn't be hard to convince me otherwise.

**Comment by wandell** [comment]
Let's hear from @DavidBrainard  when lands.  

As a programmer, when the key/val options are present, they are usually a critical part of the documentation.  I think I know what you mean - they aren't there so we can't make them required.  But maybe when they aren't there we just put in something like

> Optional key/val pairs
>   N/A

It is kind of valuable to me to know there aren't any key/val pairs, too.

No rush on this one.  Just noodling.

**Comment by jenmaxwell** [comment]
I'm completely okay with using None or N/A if the section becomes required.

**Comment by DavidBrainard** [comment]
I agree, always having the field 

% Optional key/value pairs:

and then indicating None if there are none is probably best.

As an aside, when documenting these, I think it is worth putting single quotes around the keys.  As in

% Optional key/value pairs:
%       'myKey'       - (string): Possible values are 'house', 'office', 'garage', 'lost' (default, 'house').
%       'keyMatrix'  - (array): A matrix of interesting numbers (default, []).

Note that it is also really helpful to say what type of value each key takes, and indicate the default value.

Jenn, maybe you can update our standards document on the wiki for this.

**Comment by jenmaxwell** [comment]
David,

That sounds great, I will try to implement that as well, going forward. When I’ve a free moment between this project and my other(s), I may try to go back through sections we’ve already worked to update with new items. My current focus will be to get the Wiki up to speed with our new changes.


Jenn

**Comment by wandell** [comment]
Agree.  Notes for TODO.  

I am a little less sure that we are handling the Examples well.  In the past, before we started putting the examples as text within %{ ... %}, they would show up when we typed doc or help. These days the much improved Examples are only visible when we open the code.

So, I am starting to think that some examples might be judiciously put in the comments in the older format.

% 
%  EXAMPLE
%

**Comment by DavidBrainard** [comment]
Let's discuss.  I *really* like the fact that I can selecta and execute the examples as a whole, and in the old format that doesn't work so well.

We could consider adding text to the header that says:

% The source contains executable examples of usage, type edit Foo.m to access these.

That would alert the user to the existence.

Or maybe we can figure out some way to code them so that they can be executed and do show up with the help text.

**Comment by wandell** [comment]
OK, then.  Let's keep doing it this way and put in a note about examples in the code.  That is what I have been doing (mostly).

Brian

________________________________

**Comment by jenmaxwell** [comment]
I added a line to the examples section of the Wiki, and when I have time I will start to go back through the files I’ve checked in and make updates to bring them in line with this change.

Jenn

**Comment by wandell** [comment]
Somewhat aggressively (sorry), I edited the wiki page to reflect the importance of the Examples. Mostly the page is as @jenmaxwell  wrote it.  But, well, I stuck a bunch of opinionated stuff in there reflecting my view.  Please feel free to hack away ... though I think what I put there is pretty much consensus stuff.

(I know I can be pushy.  Apologies in advance).

**Comment by DavidBrainard** [comment]
I did some minor editing but thought it looked just right in general.

This issue is already closed and I'm leaving it that way.
