### ISSUE TITLE
opticsRayTrace merge into master?

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#295]
@tlian7 - This branch has diverged from master enough so that when you try a merge (from master into opticsRayTrace) there are a few conflicts.  To make life easier - and keep coordinated with the other developments - can you please do the merge and resolve the conflicts.  The ones I saw were pretty small.  

Also - is it time to merge this into master?  It's a great contribution, so maybe you are ready to declare victory and move to the next stage?  I am pretty much ready to start working on the wiki pages describing your work.

**Comment by tlian7** [comment]
Sounds good, I was actually looking at merging last night in order to resolve the issues related to opticsRayTrace that Jenn brought up. The core is all already there and what's left to add are a few parameters, so this it seems ready to be moved in.

**Comment by wandell** [comment]
Thanks.  LGTM!  Closing.
