### ISSUE TITLE
ieValidatePreferences

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#296]
This already existed under configuration/isetbioLocalHookTemplate.

I removed ieValidatePreferences, and updated the wiki to point to the above.

The advantage of the above is that it follows ToolboxToolbox conventions, making isetbio work better with ToolboxToolbox.  And it can still be used manually just as ieValidatePreferences.

Posting this to let everyone know, and then closing the issue.  If this requires discussion, just reopen.

**Comment by wandell** [comment]
T
