### ISSUE TITLE
ieFieldHeight2Index

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#297]
Carried forward from issue 274.

The example doesn't work, as it calls an unimplemented opticsGet to get a field height list.

I couldn't figure out from the header comment what a field height or field height list is, so I was unable to fix this in finite time.

This routine does not appear to be called anywhere within isetbio, so one possibility is that we should just delete it. Depends on whether the field height and field height list concepts are important for us.

**Comment by wandell** [comment]
I think we should delete in ISETBIO.  Field height is useful for general optics/cameras but we are using eccentricity or distance on the retina to describe position. The camera/optics people use field height, and I used this function for shift-VARIANT (ray trace) calculations.  But we don't use that approach here.
