### ISSUE TITLE
vcLoadObject

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#299]
Carrying forward from #274.

vcLoadObject does not seem to have had the header comment converted to the new format.

And, the example does not work.

**Comment by wandell** [comment]
I moved vcLoadObject into vcImportObject, where it should have been.  Renamed some things and edited some comments.  So, no one will see vcLoadObject and we don't have to explain it.

I may get rid of vcImportObject (someday) but it is used in several windows as a substitute for reading a file and the calling ieAddObject().  Checking all that might take me half an hour or more, and  nothing is broken.  So, let's wait until the next holiday season.  Classes are looming at the horizon.
