### ISSUE TITLE
Validation documentation

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#3]
The setIsetbioUnitTestPreferencesTemplate discussion and use needs some tweaks. We found it, ran it, and it worked fine for FastAll by default but not for the FullAll (of course). We will think about how to help people like us. We made some edits to the directions at the top.

This doesn't seem like a hugely problematic issue right now because we are the only ones running the validation code. Still ...

Also, there should be a version of this function in the UnitTestToolbox directory that guides set up for any project. Very useful tool!

**Comment by npcottaris** [comment]
Under the UnitTestToolbox directory there is a folder named UnitTestTools. It contains generic versions of
~~~
* UnitTestPreferencesTemplate.m
* ExecutiveValidationScriptTemplate.m
~~~ 
for use with any project.  Also see https://github.com/isetbio/UnitTestToolbox/wiki.

**Comment by DavidBrainard** [comment]
Closing this issue.  This documentation will need to be redone when we figure out how we are going to handle storing validation data, but for now I think we're in pretty good shape.
