### ISSUE TITLE
libsvm, liblinear

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#303]
Bringing forward from issue 289.

We have these in external, and we wanted them before we decided that isetbio can depend on the statistics toolbox.  But now we are committed to the statistics toolbox, which has its own svm support.

In IBIOColorDetect, we are using the Matlab versions.

Do we want to keep libsmv and liblinear?  If so, how will we maintain them and keep things properly compiled.  And we need to worry a bit about name space collisions.

I tend to think that we should get rid of these and move to Matlab versions.  But maybe there is a reason not to do that.

In any case, if we cointinue with libsvm, liblinear then we need to deal with updating svmClassifyAcc and svmAcc.  It's possible we want to keep those and have them use Matlab's svm.  Or possible that we want to get rid of them.  Neither are called in isetbio, IBIOColorDetect, or our illum discrimination code.

******
Here are Jenn's notes on svmClassifyAcc and svmAcc.

svmClassifyAcc
= I was unable to repair the example
= Notes:
* [Note: JNM - input check is primative, we should update this.]
* [Note: JNM - svmtrain is about to be deprecated, we need to update the use of this function or this will break shortly.]
* [Note: JNM - the default options are the same for both cases, so can we move the notDefined step outside of the case statement so that it only has to be written once?]
* [Note: JNM - Differences between this and svmAcc? Aside from opts? And two defaults.]
svmAcc
= I was unable to repair the example
= This appears to be an updated version of svmClassifyAcc? Should we remove the older one?
= svm is instantiated in svmClassifyAcc, and not in this function.
= Notes:
* [Note: XXX - For libsvm and liblinear, there are Matlab interfaces. However, for most other packages, there are only C++ implementation. We might write Matlab interface some time in the future. At this point, we use system() command to invoke the compiled files. To run in this mode successfully, you might need to compile the source code on your own.]
* [Note: JNM - input check is primative, we should update this.]
* [Note: JNM - the default options are the same for both cases, so can we move the notDefined step outside of the case statement so that it only has to be written once?]
* [Note: JNM - Differences between this and svmClassifyAcc? Aside from opts? And that this one was created a year later? (This one doesn't have a supported 'svm' case)]

**Comment by wandell** [comment]
I moved libsvm and liblinear out of external.

**Comment by DavidBrainard** [comment]
Removed associated svmClassify and svmClassifyAcc (from utiltiies).

Closing.
