### ISSUE TITLE
Warnings in tutorials

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#304]
ieRunTutorialsAll does not report any errors.  But there are some warnings.  Warnings should be fixed -- they reduce the confidence a user has in the code.  If the warning is not of consequence, we can use the warning state control in Matlab to turn it off around the offending code.  If the warning matters, we should fix it.

Here are the tutorials that currently throw warnings.  Annotate here as these get addressed and then we can close this issue.

*******
t_displayRendering
Warning: ieReadSpectra: file camera.mat not found. Empty returned 
> In ieReadSpectra (line 78)
  In t_displayRendering (line 151)
  In UnitTest.runProjectTutorials>runTheTutorial (line 97)
  In UnitTest.runProjectTutorials (line 49)
  In ieRunTutorialsAll (line 30) 

*******
t_conesMosaicBasic.m - _Dealt with by turning warning off in ieInit, see below.  DHB._
Warning: A callback recursively calls CLOSE.  Use DELETE to prevent this message. 
> In close>request_close_helper
  In close>request_close
  In close
  In close>request_close
  In close
  In t_conesMosaicBasic (line 12)
  In UnitTest.runProjectTutorials>runTheTutorial (line 97)
  In UnitTest.runProjectTutorials (line 49)
  In ieRunTutorialsAll (line 30) 

*******
t_oisCreate - _Identified and toggle warning in ieMovie.  DHB._
Warning: The video's width and height has been padded to be a multiple of two as required by the H.264 codec.

**Comment by DavidBrainard** [comment]
I looked at t_displayRendering.  This warning reflects a real problem.  It must be that we once had a camera.mat file that we no longer have.  We probably should find it and put it back.  Either that or rewrite the camera not to show how to do metamers for a camera.

**Comment by DavidBrainard** [comment]
I took a look at t_conesMosaicBasic.  The warning happens in Matlab's close function, if there is an isetbio gui open when the tutorial is called.  You don't get the warning if you just run the tutorial.  But you can get it if you run the tutorial and then simply type "close" at the Matlab prompt.  I don't think I'm gui literate enough to figure this one out.  I tried to find where the close went in the gui callbacks, but was not immediately successful.

**Comment by DavidBrainard** [comment]
As an aside, something I learned from Denis Pelli which has stayed with me is "to respect the user's command window", which means that low level routines should not print stuff out to the command window without some clear form of control from the calling routines.  That way, the user's program can control what gets printed out.  In this spirit, I got rid of the "Saving video" and "Done" printouts in oiSequence.visualize.

**Comment by wandell** [comment]
I deleted the file last night.  I will put it back.

B

--------------------
Sent from my iPad
________________________________

**Comment by wandell** [comment]
I meant camera.mat.

--------------------
Sent from my iPad
________________________________

**Comment by wandell** [comment]
Ok.

--------------------
Sent from my iPad
________________________________

**Comment by DavidBrainard** [comment]
Closing.
