### ISSUE TITLE
Routines isetbio/utility/utility -> isetbio/utility

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#305]
We have directory isetbio/utility/utility.  The distinction between the routines in there and those one level up is not immediately clear to me.  I wonder if we shouldn't simply move everything from utility/utility into utility, and delete utility/utilty.

Either that or try to give it a more informative name.

**Comment by wandell** [comment]
I sorted the files into what appeared to be the relevant subdirectory.  Removed the utility/utility directory.
