### ISSUE TITLE
Human Eye Movement and Cone Mosaic Share RNG Seed

### ISSUE THREAD

**Issue by xnieamo** [isetbio/isetbio#31]
It seems that the functions emGenSequence and humanConeMosaic both make use of the same RNG seed field, 'rSeed',  in the sensor object.  emGenSequence also sets the 'rSeed' field in the sensor while humanConeMosaic does not.  This results in coneAbsorptions always returning the same volt/photon data in a sensor that has been passed through emGenSequence.  This is because coneAbsorptions calls sensorHumanResize which calls sensorSet('size') which in turn calls humanConeMosaic.  humanConeMosaic uses the RNG seed saved in the sensor.  This results in the next call to noiseShot to always return the same value for a given sensor because randn is always returning the same matrix.  This makes it impossible to get different noise on the same image via coneAbsorptions. Additionally, the sensor object adds the same randn matrix to different optical images in the noiseShot function.   

This does not occur in sensor objects without eye movement as the RNG seed is not stored in the sensor object, resulting in different values from randn.  I was wondering if this behavior is intended, and if there is any intended relationship between eye movement and the cone mosaic.

**Comment by hjiang36** [comment]
Thanks for pointing it out. I didn't realize this bug when I wrote that function. For me, I think the simplest solution is to remove the part that sets the random seed in emGenSequence. Will this fix it?

**Comment by xnieamo** [comment]
Yes, that should take care of it.
