### ISSUE TITLE
Something broken in scene

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#316]
Something broke recently in the scene code, I believe.

t_oiWave is one place that I detect the problem.  It currently doesn't run, breaking on its first few lines.  

The error is in a call to sceneSet(scene0,'wave',...), which then dies in sceneInterpolateW.

This was OK after all of 1/22 check ins.  I think it broke when I merged in Jenn's branch.

A number of examples are broken in a similar fashion.

Maybe @jenmaxwell will have an idea about what might have been changed that would cause this.  Or maybe the problem will be easy for @wandell to track down, as I am guessing he understands best what that code does.

**Comment by DavidBrainard** [comment]
This message, which seems to come out before things go south in places they didn't used to, might be a clue.

>> t_conesMosaicBasic
Unknown sceneSet parameter: cphotons

**Comment by DavidBrainard** [comment]
OK, getting rid of some calls to sceneSet(...,'compressed photons',...) and sceneSet(...,'cphotons',....)
fixed at least some of these problems.  Maybe all of them.

I think these were probably stray calls that didn't get changed after options for compressed photons were taken out of sceneSet at some point.  I'm not entirely sure, though.

Does this seem like an expected problem to someone, and does the fix of replacing with 'photons' in the set seem right?

**Comment by wandell** [comment]
Yes, you are right.  Compressed photons was removed some time ago.  I thought I changed them all.  This usage would definitely break now.  Not sure why it worked and then it didn’t.  But cphotons should be photons.

**Comment by DavidBrainard** [comment]
I think these might mostly have been exercised in examples that weren't checked.  Also, sceneSet only prints a warning when it is given a parameter it doesn't know about, so in cases where the call was made but not necessary, there would not have been a hard error.

I am going to force sceneSet to throw an error, not just print a warning.

Closing.

**Comment by wandell** [comment]
Wait - I looked through the v_eyeMovementPhysio branch and it contains a lot of usages of compressed photons.  I guess it diverged before the compressed photons were removed.  So, I wanted to add this warning to @npcottaris to be alert when he brings in the new eye movement branch.
