### ISSUE TITLE
New worrisome Matlab behavior

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#318]
Did you know that this (see example pasted below) worked this way?  I don't think it used to.  Boy, will this cause trouble if we're not really careful about our row vectors versus column vectors.

K>> a = [1 2 3];
K>> b = [4 5 6]';
K>> a+b

ans =

     5     6     7
     6     7     8
     7     8     9

K>>

**Comment by npcottaris** [comment]
Yeah, in Python this is is called broadcasting (doing operations between arrays of different sizes).
In matlab it is called arithmetic expansion. It is a superset of what bsxfun does.

Here is an article describing it.
https://blogs.mathworks.com/loren/2016/10/24/matlab-arithmetic-expands-in-r2016b/

Nicolas

**Comment by wandell** [comment]
I did not know.  Thanks for the heads-up.

**Comment by DavidBrainard** [comment]
I think all in all this is a good language feature, but that we are from time to time going to be bitten by it.  Most of those times, something that used to work will just crash and probably be easy to find.

Closing, this was just for information.
