### ISSUE TITLE
The @coneMosaic class has hardwired and inconsistent focal distance and microns/deg

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#321]
This occurs in 2 separate entries, which are not connected by a common parameter, and which are not entirely consistent (focal length corresponding to 300 microns/deg is 0.0172, not 0.017):

In line 277:
```
eccentricityDegs = 1e3*eccentricityMeters/0.3;
```
which is transmitted to the outer segment class, and in lines 392-394:
```
function val = get.fov(obj)
     val = 2 * atand([obj.width obj.height]/2/0.017);
end
```
We should fix this by passing an optional param `umPerDeg` during instantiation of the `coneMosaic`, which will default to 300.

Then:
Replace line 277 with:
```
eccentricityDegs = eccentricityMeters/(micronsPerDeg/1e6);
```
and line 392-395 with:
```
function val = get.fov(obj)
   focalLengthMeters = micronsPerDeg/1e6/tand(1)
   val = 2 * atand([obj.width obj.height]/2/focalLengthMeters);
end
```

Any objections or a different proposed solution? This will break some validations.

**Comment by DavidBrainard** [comment]
This is but one example of a more pervasive issue, which is that our specification of retinal position is not handled in a centralized manner across all of isetbio.  This is true both for how we specify position on the retina and how we convert from degrees of visual angle to position on the retina.

Taking on the whole thing is not at the top of the priority list right now, although relatively soon we will want to do that.  I have been daydreaming about the right design.  Sometimes we want to do the conversions using a fancier eye model than just the trig formula yields, and sometimes we want to specify position not just in terms of eccentricity but also include azimuth.  How to make it all flow smoothly and consistently through all the code is non-trivial, I fear.

I think for right now, doing what you suggest is a net step forward and I am OK with you implementing it.  Check validations before and then make the point change and re-write data for any that are broken.

Maybe focalLengthMeters should be micronsPerDeg/(2*1e6)/tand(0.5), though.  Whichever makes things most consistent across the two ways.

P.S.  We recently did meltdown/spectre updates to the archiva server.  It seems like everything is back fine, but if you hit a problem writing validation files that doesn't have a simple solution (sometimes the password expires), let me know.

**Comment by npcottaris** [comment]
I am 100% with you regarding the more centralized design. Too many modes of failure. I will go ahead with the changes. Leaving this issue open in case @wandell wants to chime in.

**Comment by npcottaris** [comment]
This update is now implemented. All validations passed before and after the change, so no new ground truth files were uploaded.
