### ISSUE TITLE
Cones Pass I Part II Issues: Small Mods

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#325]
Below are small modifications that should be glanced over and hopefully shouldn't cause any complications. If someone can take a quick glance to ensure this I would appreciate it.

- outerSegment/@ osDisplayRGB/osSet - [Note: JNM - Changed the listed value of noiseFlag to an appropriate value to allow the example to work.]
- @ photoPigment/photoPigmnent - please check text just in case.
- @ coneMosaicHex/saveOriginalResState -- please check short/long desc.
- outerSegment/utilities/osCreate - Note explains: [Note: JNM - The empty call wasn't working -- parsing an empty type throws an error. Rather than removing the 'empty' option, I inserted a notDefined, which should accomplish the desired default case.]
- outerSegment/@ osIdentity/osSet - [Note: JNM - Changed the listed value of noiseFlag to an appropriate value to allow the example to work. Added noiseFlag case below, for value to actually set!]
- outerSegment/@ osBioPhys/osSet - noiseFlag was set to 0/1 when supported noiseFlags are 'random' 'frozen' and 'none' -- updated to match the parent class as nothing I've seen conforms to the 0/1 style.
- @ coneMosaicHex/visualizeGrid - changed key/value coneDensityContourLevelStep to coneDensityContourLevels

[Edit: Added space after '@' so path names would resolve.]

**Comment by npcottaris** [comment]
These corrections are all fine. Thanks !
