### ISSUE TITLE
Cones Pass I Part II: Text clarifications and Questions

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#327]
This issue is to group together the functions where I had questions or was uncertain about text.

- @ outerSegment _general_ notes:
   1. patch size has a couple of different definitions in the functions. In OuterSegment it's described as the space between cones. In set & get it's described as the diameter of cones? Which one is correct?
   2. public methods: outerSegment function - varargin is never used?
   3. please check my text blocks from each of the functions
- outerSegment/@ osLinear/osCompute
   1. Check varargin section in inputs - what else is missing?
   2. Is that there are no optional key/value pairs correct?
   3. Please make sure I didn't butcher description by moving section around.
- outerSegment/@ osLinear/plot - not sure if the listed 'none' for key/value pairs is accurate
- outerSegment/@ osLinear/osLinear - I am not certain of the last couple embedded functions, or of my characterization of the main text sections
- outerSegment/@ osIdentity/osIdentity - I am not certain of my characterization of the main text sections or minor functions
- outerSegment/@ osIdentity/osDisplayRGB - I am not certain of my characterization of the main text sections or minor functions
- outerSegment/@ osBioPhys/osBioPhys - I am not certain of my characterization of the main text sections or minor functions
- @ coneMosaicHex/renderHexMesh
   1. Please fill out the portions of Inputs that I am missing (and check the descriptions that I have provided)
   2. Working? Y/N?
- @ coneMosaicHex/movieHex
   1. Check if varargin should contain key/value pairs, or if where I put it is okay
   2. Double-check my attempts at inputs/outputs
- @ coneMosaicHex/computeActivationDensityMap - Please check my input/output descriptions and if the description section needs to be expanded
- @coneMosaicHex/visualizeActivationMaps
   1. Please check all input/output descriptions in function and its embedded function - esp the embedded functions descriptions and variables
   2. Should unused variables transition to ~?
- @ coneMosaicHex/plotMosaicProgression - Someone check my inputs for the embedded function plotMosaic please
- outerSegment/@ osLinear/osSet
   1. See Note. [Note: JNM - Set does not seem to like taking multiple parameters and values. Tends to not agree with anything past the first? Same question as osGet about parameters that do not appear to be supported anymore?]
   2. Changed the else inside noiseFlag case -- displays the illegal parameter without storing data that was never used.
- @coneMosaicHex/plotHexMosaic - embedded functions renderPatchArray and renderHexMesh exist separately. Why are they internal here then?
- @ coneMosaicHex/coneMosaicHex - added shortened name versions of the sizeForSquareApertureFromDiameterForCircularAperture and diameterForCircularApertureFromWidthForSquareAperture at the bottom to help with the calls to those functions not running over the line length. debating if I regret it. But really, those names are ...looong
- @ coneMosaic/plot - trying to decide how I feel about some of the spacing
- @ coneMosaic/computeForOISequence
   1. oiIndex used before instantiated?
   2. Check if my modified scenario graphs are okay?
- @ coneMosaic/setWave
   1. removed ~ from inputs. Why have an empty input in call?
   2. confirm that src represents the light source?
- @ coneMosaic/tResample - Someone please check my interpretations of inputs/outputs (sections were blank)
- @ coneMosaic/copyElement - I share DHB's misgivings about this function.... and his questions...
- @ coneMosaicHex/renderActivationMap
   1. Removed signalName and activationTime assignments from inside the function (they were unused)
   2. renderPatchArray is an embedded function here? with edge and face color parameters switched.... why not just use standalone?
   3. please check text content
- @ coneMosaicHex/resampleGrid - removed unused nullVar from circularDomainFunction
- @ coneMosaicHex/resampleGrid
   1. Please check my text for all embedded functions. A number of variable descriptions were guesses. (Especially wary of my text for circularDomainFunction)
   2. in coneSpacingFunction, should aperture and density returns of coneSizeReadData be replaced with ~ since they are not used?

**Comment by jenmaxwell** [comment]
@DavidBrainard  & @wandell 
Thoughts on which is the preferred method?

Ex. from photoPigment
**Code:**
absorbance;        % spectral absorbance of the cones
**Call:**
help photopigment.absorbance
**Output:**
"absorbance -  spectral absorbance of the cones"

**Code:**
%ABSORBANCE  spectral absorbance of the cones
absorbance;
**Call:**
help photopigment.absorbance
**Output:**
 "**absorbance**  spectral absorbance of the cones"

**Comment by DavidBrainard** [comment]
I think we want the second form, because with that form you can have additional comment lines after the initial one and they show up as help text.  Although I sort of like the bold on the help output, I don't like the use of CAPS in the code itself -- I think it is clearer to have the variable name in the property comment match the case of the property itself.  So I favor (e.g.)

%absorbance - spectral absorbance of the cones
absorbance;

And then for a more elaborated comment (e.g.)

%absorbance - spectral absorbance of the cones
%  This is the key property of a photopigment.
%  And another statement that we'd like to see with
%  the help text.
absorbance;

Note that I suggest a dash after the property name to separate it from the one line description
as it comes out of the help text.

If the property were a camel case variable, then the comment version would match that case.

Open to discussion.  If there is a way to use the first form and still have multi-line comments appear with the help text, that would be nicer because you wouldn't have to retype the variable name.  But I could not find a way to make that happen.

**Comment by jenmaxwell** [comment]
Alright. I'll play around with it a bit more, but of the above, I do like two the best and will go back through and implement it through the cones classes.

**Comment by npcottaris** [comment]
Issues addressed in commit #7e288f37.
