### ISSUE TITLE
Buglet in noiseShot

### ISSUE THREAD

**Issue by xnieamo** [isetbio/isetbio#33]
In the noiseShot function, where it calculates the Poisson sampling for means below the poissonCriterion, theNoise and noisyImage are set to the same value, vn.  It appears that noisyImage should vn, and theNoise should instead be vn - electronImage.  Can this be confirmed?

Another possible issue is that the noisyImage is not guarded against containing negative values.  Should this be a concern?  I've added a few lines that check whether theNoise + electronImage < 0, and update the values in theNoise appropriately.

The help comments state that the function will sample using a Poisson distribution when the number of electrons is less than 20. However, in the function, this number is set to 15.  I believe that the numbers should match but am not sure which one is preferred.   I've also added a brief output parameter section in the header to highlight that noisyImage is in units of volts whereas theNoise is in units of electrons.

**Comment by hjiang36** [comment]
For me, I think setting theNoise to vn - electronImage is reasonable. 

For the second point, the probability of getting a negative value is extremely small. Adding a check is good, but I think we will not get into negative values in most cases.

HJ

**Comment by xnieamo** [comment]
And what about the poissonCriterion?  I'm not sure what effect setting it to 20 as the header says or leaving at 15 as it is now would have.

**Comment by hjiang36** [comment]
Setting that value larger will make the computation more accurate, but slower. Changing either of them will work. Maybe change the comment to match the code?

**Comment by wandell** [comment]
Good catches.

theNoise should be, as you say, vn - v.

While I think fixing the comments to match the code (15) is preferred for consistency, I did just do a little calculation. If we use Gaussian noise for 16 and above, and the std. dev. is 4, we will get negative values rarely but enough times that it might be annoying.  For this project (isetbio), where people might actually care about low light levels and Poisson noise, maybe we should move poissonCriterion to 25, so we are 5 std. dev. away from 0.

It will slow down some calculations, but maybe we should live with that.

Thanks!
Brian

> On Jun 2, 2015, at 2:24 PM, Haomiao Jiang <notifications@github.com> wrote:
> 
> Setting that value larger will make the computation more accurate, but slower. Changing either of them will work. Maybe change the comment to match the code?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/33#issuecomment-108102760>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by DavidBrainard** [comment]
On Jun 2, 2015, at 8:58 PM, Brian Wandell <notifications@github.com> wrote:

> Good catches.
> 
> theNoise should be, as you say, vn - v.
> 
> While I think fixing the comments to match the code (15) is preferred for consistency, I did just do a little calculation. If we use Gaussian noise for 16 and above, and the std. dev. is 4, we will get negative values rarely but enough times that it might be annoying. For this project (isetbio), where people might actually care about low light levels and Poisson noise, maybe we should move poissonCriterion to 25, so we are 5 std. dev. away from 0.
> 
> It will slow down some calculations, but maybe we should live with that.

And, I would keep the check that sets any negative values to zero, even though with 25 they will hardly ever occur.

DB
