### ISSUE TITLE
Optics Pass I Part II: OiSequence Issues

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#335]
The following are issues and comments from within the oiSequence sub-folder.
oiSequence/oisCreate - Assign someone to complete TODO (hunt down what's causing function failures as displayed with examples)

_DONE_

oiSequence/s_oisHarmonic
	- are script files meant to be in the same folder structure as the regular functions, or are they meant to be separated out like the tutorials are?
	- We should determine what kind of formatting we want for scripts. I didn't make too many modifications to this script, but I would like to see a bit more of an extended description of what the script accomplishes at least.

__SIMPLIED AND MOVED TO TUTORIALS_

**Comment by npcottaris** [comment]
Done the above. Closing issue.
