### ISSUE TITLE
iePoisson always returns same answer for a given lambda

### ISSUE THREAD

**Issue by xnieamo** [isetbio/isetbio#34]
The iePoisson function always returns the same answer when the iePoissrnd function is used.  This is because the C++ file for the mex function does not set the seed for number generator it uses.  Nicolas and I addressed this issue by adding a third and optional parameter to iePoissrnd that allows for setting a seed in the C++ file.  

Locally, I am setting the seed to be rand * (arbitrarily large prime number).  This makes the behavior of iePoissrnd in line with poissrnd from the stat toolbox, where multiple calls to poissrnd with the same lambda will return different answers.  I want to make sure that this is the intended behavior of iePoisson.  Additionally, is there a need to add a flag in the parameters for iePoisson to dictate whether or not this random seed is to be set?

**Comment by hjiang36** [comment]
Thanks for pointing it out. Adding an additional parameter sounds a good.
Besides using rand*prime number, we can also try using the current time, or other time varying things as random seed.

**Comment by wandell** [comment]
Good - and yes.  We do want to be able to reproduce the same set of random numbers (frozen noise case).

Thanks!
Brian

> On Jun 3, 2015, at 10:38 AM, Haomiao Jiang <notifications@github.com> wrote:
> 
> Thanks for pointing it out. Adding an additional parameter sounds a good.
> Besides using rand*prime number, we can also try using the current time, or other time varying things as random seed.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/34#issuecomment-108540145>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by npcottaris** [comment]
For consistency, someone with access to a windoze machine should recompile the iePoissrnd.cpp mex file.

**Comment by xnieamo** [comment]
I've added a flag to determine whether or not to use a random seed in iePoisson.  I've also added a similar flag in noiseShot.

**Comment by DavidBrainard** [comment]
This issue seems like it is almost closed.  The one thing someone (Xiaomao, can you do this) should check is that the new flag works both for the .mex file and the .m file fallback code.  

More generally, I wonder if the .m file should simply fail with an error that tells the user to compile the .mex file.  My experience is that .mex files stop working silently as Matlab and the OS are upgraded, and if you have a fallback m-file the effect will be that calculations mysteriously slow down without any clear indication (other than sluggishness) that it is happening.  I don't feel strongly about this, though.

**Comment by DavidBrainard** [comment]
Has anyone checked that the new flag works for both the .mex file and .m file fallback code?  If so, please confirm and close this issue.  If not, please so state so that we know it is something we need to fix.

**Comment by xnieamo** [comment]
I've added a few lines that makes the behavior consistent.  I did notice that the fallback code provides significantly different values when the mean is large (order of 1000).  I don't know if this is a concern since iePoisson is only used for small means anyways.  Maybe a notice should be included in the comment header because right now it only states that the .m fallback code is slow for large means, nothing regarding accuracy.

**Comment by wandell** [comment]
Could you please clarify what you mean by ‘provides significantly different values when the mean is large’.  Different from what?

The mean over many repeats should be 1000.  The variance should be 1000 (std dev sqrt(1000)).

Thanks,
Brian

> On Jun 29, 2015, at 10:49 AM, Xiaomao Ding <notifications@github.com> wrote:
> 
> I've added a few lines that makes the behavior consistent. I did notice that the fallback code provides significantly different values when the mean is large (order of 1000). I don't know if this is a concern since iePoisson is only used for small means anyways. Maybe a notice should be included in the comment header because right now it only states that the .m fallback code is slow for large means, nothing regarding accuracy.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/34#issuecomment-116773955>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by xnieamo** [comment]
What I mean is that the values the fallback code returns are significantly different from poissrnd and the mex file code when the lambda value is on the order of 1000;

```
lambda = 1000 * ones(1,1000);
mex = iePoisson(lambda) % with mex file
fallback = iePoisson(lambda) % with fallback code
```
The mean and std for the two cases are:

mean(mex) = 1000.3;
std(mex) = 31.5776;

mean(fallback) = 745.89;
std(fallback) = 27.4626

For some reason or another, it seems that the fallback code will not generate values above 800-900 no matter how big lambda is.
```
fallback = iePoisson(10000 * ones(1,1000)); % using fallback code
```
mean(fallback) = 746.057

**Comment by hjiang36** [comment]
The fallback code is based on Knuth algorithm. It uses a threshold of exp(-lambda). This works OK for small lambda, but for large lambda, numeric issue occurs in Matlab. For example, exp(-1000) in Matlab will return 0.

I guess that code is not used for large lambda. But anyway, I'll make a fix for it.

**Comment by DavidBrainard** [comment]
I think it would be fine to eliminate the fallback code and force people to compile the MEX file.  Indeed, the effect of the fallback might be that things work but very slowly, without the user being aware that there is a mex file they should compile.

**Comment by hjiang36** [comment]
I commit a fix for fallback code for large lambda.
Now, we have a warning for using the fallback code. We can change that 'warning' to be an error to force people to use the mex file.
