### ISSUE TITLE
Optics Pass I Part III Issues: oiSequence Issues

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#340]
The following comments and issues are related to the oiSequence sub-directory

- frameAtIndex - Assign someone to deal with the note and/or calculation speed?

_DONE: Made oiSequence a subclass of the Handle class, so as to store and retrieve the photons without going through the oiGet all the time_

- oiSequence
		Assign someone to fix/expand the example. Will not currently run since none of the parameters are currently defined.
		Assign someone to provide a fuller example for the inputs aside from just their types.
		Assign someone to fill in the optional key/value pairs section. I think I got a couple of them, I'm not sure if there are more.
		Check my descriptions for inputs/etc please.

_DONE: Added example which runs fine_

- maxEyeMovementsNumGivenIntegrationTime
	varargin is referenced inside the function, but not called out in the inputs section. Should this be added? (to the header and the inputs section) -- I added it, and it's fixed one of the errors from ieRunExamplesAll

_THATS GOOD_

**Comment by npcottaris** [comment]
Dealt with the above issues. Closing issue.
