### ISSUE TITLE
eyeMovements Pass I: Major and/or structural

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#354]
General Notes (will be in all eyeMovement issues as a reminder):
 - None of the fixationalEM functions really had any text, so they will likely need to be more closely examined than other sections...

The following function from within eyeMovements had major and/or structural changes made:

emSet
 - Please make sure I didn't incorrectly identify any of the parameter types.
 - The description section that I've created is embarrassingly short. Please help me flesh this out a bit more at least?
 - Example only contained emGet previously. Please make sure that my alterations make sense.
 - Frequency was missing, so I've populated it (according to how it existed in the emGet function). Please let me know if this was not intended to be added.

**Comment by npcottaris** [comment]
emSet/emGet are only to be used with the (now) obsolete previous-style of generating eye movements. It is to be removed along with emGet and emCreate.

**Comment by npcottaris** [comment]
Closing this.
