### ISSUE TITLE
eyeMovements Pass I: General Part I

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#355]
General Notes (will be in all eyeMovement issues as a reminder):
 - None of the fixationalEM functions really had any text, so they will likely need to be more closely examined than other sections...

emGet
 - There are a number of unit change functions. Would it be possible to standardize one?
 - sampTime was missing from the option list for sampleTime, despite that it is the name by which the variable is stored.

emCreate
 - Assign someone to flesh out the description section.
 - Assign someone to fill in the key/values section.
 - Assign someone to fill in the description section for the embedded function overwriteStruct

**Comment by npcottaris** [comment]
emGet/emCreate are to be removed as they are used with the (now) obsolete eye movement paths.

**Comment by npcottaris** [comment]
Closing this.
