### ISSUE TITLE
eyeMovements Pass I: General Part II

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#356]
General Notes (will be in all eyeMovement issues as a reminder):
 - None of the fixationalEM functions really had any text, so they will likely need to be more closely examined than other sections...

fixationalEyeMovements/visualizableFixationalEM
 - Assign someone to fill in the key/values section   -- **DONE (NPC)**
 - Determine if level of commentary is sufficient for current guidelines -- **Updated where was needed (NPC)**
 - Note: Need  to standardize the syntax for outputs/responses with multiple return type options. Currently using prefix of "VARIES. " Before description of the return. Is this sufficient for our purposes? -- **Removed VARIES. The return is just the property value (NPC)**

fixationalEyeMovements/@ fixationalEM/updatedMicroSaccadeResidualPath - The description section needs to be expanded. -- **DONE (NPC)**

fixationalEyeMovements/@ fixationalEM/compute
 - There was zero text associated with this. I already know what I've added is inadequate and whether it is correct or not is suspect, at best.  -- **DONE (NPC)**
 - There appears to be no checking for inputs?  -- **DONE (NPC)**
 - Assign someone to define useParFor in the key/values section. (Also a problem elsewhere, but is called out in function notes).  -- **DONE (NPC)**

fixationalEyeMovements/@ fixationalEM/computeFixationMap
 - There appears to be no checking for inputs? -- **DONE (NPC)**
 - Why are we providing the timeAxis? This is a read-only property of the fixationalEM. This is also defaulted to [] in the fixationalEM, and not calculated until the compute (not computeFixationMap) is run. Is there a particular reason to pass the timeAxis and emPaths, as opposed to just the fixationalEM and pulling those variables from within the function?  -- **Yes, because this is a static method that does not require a fixationalEM object to run. It can be used with any emPath, such as recorded emPaths from human subjects. So we leave this as is for now. DONE (NPC)**
 - Assign someone to fill in the optional key/values section  -- **DONE (NPC)**
 - My descriptions of input and output variables need to be fixed.  -- **DONE (NPC)**

**Comment by npcottaris** [comment]
All above issues have now been addressed.

**Comment by npcottaris** [comment]
Closing this.
