### ISSUE TITLE
eyeMovements Pass I: General Part III

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#357]
General Notes (will be in all eyeMovement issues as a reminder):
 - None of the fixationalEM functions really had any text, so they will likely need to be more closely examined than other sections...

fixationalEyeMovements/@ fixationalEM/checkForMicroSaccadeEpoch
 - I have literal zero idea of how to describe pretty much any of this... Assign someone to write accurate descriptions (short & long) -- **DONE (NPC)**
 - Assign someone to review my description of the Inputs. -- **DONE (NPC)**
 - Fixed capitalization error in microSaccadeMinDurationMilliSeconds (d in duration was not capitalized) that was causing t_fixationalEyeMovementsCharacterize to fail.

fixationalEyeMovements/@ fixationalEM/computeMicrosaccadeTargetLikelihoodSpatialMap
 - Is there a reason that meshgrid(heatMapXYsupportArcMin, heatMapXYsupportArcMin) follows that format? The meshgrid function would take meshgrid(heatMapXYsupportArcMin) the exact same way... -- **Personal preference. DONE (NPC)**
 - Please assign someone to check my text, I'm maybe 25% confident about it?  -- **DONE (NPC)**

fixationalEyeMovements/@ fixationalEM/computeSingleTrial
 - Assign someone to flesh out description section. I'm sure there's much more to it than my paltry statement. -- **DONE (NPC)**
 - Why is currentPositionHeatLevel set and then never used?  **It is a placeholder in case we decide in the future that we want to trigger a micro saccades based on the current heat level, in addition to  the inter-saccade interval. DONE (NPC)**

fixationalEyeMovements/@ fixationalEM/performDisplayAnalysis
 - Repurposed an example similar to one used in a tutorial, please make sure I didn't corrupt the purpose of the function in how I implemented it. -- **Fixed example (NPC)**
 - Assign someone to review my added text. There was not much for me to work with, so I may be totally off-base here. -- **DONE (NPC)**

**Comment by npcottaris** [comment]
The above issue are now addressed.

**Comment by npcottaris** [comment]
Closing this.
