### ISSUE TITLE
eyeMovements Pass I: General Part IV

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#358]
General Notes (will be in all eyeMovement issues as a reminder):
 - None of the fixationalEM functions really had any text, so they will likely need to be more closely examined than other sections...

fixationalEyeMovements/@ fixationalEM/performD2DisplayAnalysis  -- **This function is obsolete and now removed (NPC)**
 - I'm not even certain that D2 is supposed to mean D^2 ... so ... there's that...
 - Assign someone to review my added text. There was not much for me to work with, so I may be totally off-base here.
 - Basically copied the example from performDisplayAnalysis here ...
 - This function honestly looks like an incomplete form of performDisplayAnalysis. Is there a reason it is separated out?

fixationalEyeMovements/@ fixationalEM/posOfMaxLikelihood **Done (NPC)**
 - Assign someone to review my added text. I made several assumptions based on parameter names, so please forgive me if they are incorrect.

fixationalEyeMovements/@ fixationalEM/setMicroSaccadeStats **Done (NPC)**
 - Assign someone to review my note about the microSaccadeMeanSpeedDegsPerSecond (label and assigned number do not agree) --> POSSIBLE ERROR!
 - Assign someone to review my added text for errors and inconsistencies.
 - There are a number of these little functions that just execute inside one other function and nowhere else. Is there a reason they are encapsulated rather than included?

fixationalEyeMovements/@ fixationalEM/smartInterpolation **Done (NPC)**
 - Trying to decide if I should include language about which dimension of inputMatrix can be the time dimension in the description section.
 - Assign someone to review my added text, and to expand the description section.

**Comment by npcottaris** [comment]
The above issues were all addressed.

**Comment by npcottaris** [comment]
Closing this.
