### ISSUE TITLE
eyeMovements Pass I: General Part V

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#359]
General Notes (will be in all eyeMovement issues as a reminder):
 - None of the fixationalEM functions really had any text, so they will likely need to be more closely examined than other sections...

fixationalEyeMovements/@ fixationalEM/spatialKernelForHeatMap -- **DONE (NPC)**
 - Assign someone to review my added text, and to expand the description section.
 - Same question as above about a piece of code only used once being called out into its own function when it is less than 10 lines sans comments.

fixationalEyeMovements/@ fixationalEM/spatialSupportForHeatMap -- **DONE (NPC)**
 - Assign someone to review my added text, and to expand the description section.
 - Same question as above about a piece of code only used once being called out into its own function when it is fairly short

fixationalEyeMovements/@ fixationalEM/temporalKernelForHeatMap -- **DONE (NPC)**
 - Assign someone to review my added text, and to expand the description section.
 - Same question as above about a piece of code only used once being called out into its own function when it is fairly short

fixationalEyeMovements/@ fixationalEM/updateHeatMap -- **DONE (NPC)**
 - Assign someone to review my added text, and to expand the description section.
 - Same question as above about a piece of code only used once being called out into its own function when it is fairly short

fixationalEyeMovements/@ fixationalEM/computeVelocity  -- **DONE (NPC)**
 - Assign someone to review my added text, and to expand the description section.
 - Same question as above about a piece of code only used once being called out into its own function when it is fairly short

fixationalEyeMovements/@ fixationalEM/generateEMandMosaicComboVideo  -- **DONE (NPC)**
 - Assign someone to review my added text, and to expand the description section.
 - Determine if there are any other key/value pairs, or standalone varargin parameters that I am missing.
 - Note: t_fixationalEyeMovementsAndConeMosaicVideo does not default to rendering and saving the video (L48) --**THIS IS TO AVOID WRITING A VIDEO FILE ON WHEN RUNING ieRunTutorialsAll**

fixationalEyeMovements/@ fixationalEM/fixationalEM  -- **DONE (NPC)**
 - Assign someone to review my added text, and to expand the description section.
 - Assign someone to fill in the key/values section.
 - There are a number of variables I was too unsure of to attempt: They can be found by searching "<FILL OUT>"
   * heatMapTimeSeriesIntermediate
   * emAccumMap
   * heatMapUpdateIntervalStepsNum
   * lastMicroSaccadeTimeStep

**Comment by npcottaris** [comment]
But why @jenmaxwell did you open so many issues each of which builds on the earlier ones?

**Comment by jenmaxwell** [comment]
Mostly because David doesn’t like long lists, and I was trying to keep each issue to covering 5ish or fewer scripts.

**Comment by npcottaris** [comment]
The above issues are now resolved.

**Comment by npcottaris** [comment]
Closing this.
