### ISSUE TITLE
Computing absorptions for OIS without eyemovements

### ISSUE THREAD

**Issue by elinekupers** [isetbio/isetbio#363]
Hi all,
I saw that we are going through some structural changes with the eye movement code, and I was wondering if there is an easy way to compute cone absorptions without eye movements for OIS.

Previously I would create emPaths, and set the em.emFlag to [0 0 0], but with the new code structure, it is not clear to me how I can disable eye movements gracefully, without loosing the time dimension when computing the cone absorptions.

The only thing I could come up with was creating eye movements and then set the emPositions field to a matrix of zeros. 

Any thoughts?

```
% For example:
hparams(2) = harmonicP;
hparams(2).freq = 6;
hparams(2).GaborFlag = .2;
hparams(1) = hparams(2);
hparams(1).contrast = 0;
sparams.fov = 1;
stimWeights = ieScale(fspecial('gaussian', [1, 50], 15), 0, 1);
ois = oisCreate('harmonic', 'blend', stimWeights, ...
        'testParameters', hparams, 'sceneParameters', sparams);
    
cm = coneMosaic; 
cm.emGenSequence(ois.length, 'nTrials', 1);
cm.emPositions = zeros(1,ois.length,2);
cm.compute(ois);  cm.window;
```

**Comment by npcottaris** [comment]
Setting the cm.emPositions to all zeros as you do, `cm.emPositions = zeros(1,ois.length,2);`  is fine for zero eye movement. 
You do not need to call `emGenSequence` on the coneMosaic at all.

**Comment by DavidBrainard** [comment]
Ever optimistic, closing.
