### ISSUE TITLE
Problems with oiWindow

### ISSUE THREAD

**Issue by tlian7** [isetbio/isetbio#364]
Hi all,

I've noticed some problems with using oiWindow with isetbio. I'm not sure how long this has been happening, since I often have isetcam on my path. But when I use _only_ isetbio I can't seem to get optical images to appear in the oiWindow. Code that works with isetcam will show a blank white screen when using oiWindow in isetbio with the line: "`No spectral irradiance data available`."

For example, when I have only isetbio on my path and try to run the first block of tutorial `t_oiCompute.m`:

 ``` 
%% This is the basic radiance to irradiance code 
% Creates an array of points
scene = sceneCreate('point array');   
scene = sceneSet(scene,'hfov',0.5);  
vcAddAndSelectObject(scene); sceneWindow;

% Diffraction limited optics
oi = oiCreate;                        

% Compute optical image and show it
oi = oiCompute(scene,oi);
vcAddAndSelectObject(oi); oiWindow;
 ``` 
I get:

 ``` 
No scene and no oi. Using 128 rows.
No scene and no oi. Using 128 cols.
No scene and no oi. Using 128 rows.
No scene and no oi. Using 128 cols.
 ``` 

I believe I have the  most updated master branch of isetbio. Was there some syntax change for oiWindow's that I wasn't aware of? I've also tried looking through the GUI code and comparing with isetcam, but haven't been having much luck with that.

Thanks in advance!

**Comment by wandell** [comment]
Yes, very peculiar.  I can see that the ieAddObject and vcGetObject functions are not working properly in isetbio.  That is pretty amazing.  I will try to debug while traveling today.

**Comment by wandell** [comment]
I saw the problem yesterday and fixed it.  I run ieValidateFullAll, and now I am pushing the new code to the master branch.  Just running validation on the fix.
