### ISSUE TITLE
Isetbio and retinal images

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#367]
Dear Prof. Brainard,

my name is Kristof Meding, I am a PhD student in Felix Wichmann’s lab at the University Tübingen in Germany.

I have developed software for calculating retinal images based on peripheral wavefront data in my Masterthesis. In brief, I got peripheral wavefront aberration sensing data form Pablo Artal, calculated Point-Spread-Functions together with blurred image patches across the visual field and used an algorithm to combine these patches into a single image.

Felix told me about the discussion he had with you about the isetbio-package and retinal image simulation at VSS. This is of great interest for our own research. In particular, I have three specific questions which I would be grateful if you were able to help me with:

1. The isetbio-package has a function to calculate PSFs from the Artal et al. 2012 horizontal dataset. Does this include the possibility to calculate a single horizontal image from -40 to 40 deg?

2. Isetbio offers the possibility to calculate retinal images for the periphery with ray-tracing. Did you compare (for the periphery) the output of the ray-tracing methods with calculations from wavefront sensing data, e.g. PSFs obtained from both methods?

3. Are chromatic aberrations calculated only with the accommodated Navarro model?

Best regards from Tübingen

Kristof Meding

**Comment by DavidBrainard** [comment]
Agree with Trisha's amendment to my response on point 1.  What I meant referred to what we can currently do with the wavefront PSFs.

I should also add we are eager for community contributions to ISETBio.  So if you start using it and have improvements or bug fixes, please don't hesitate to issue a pull request and we'll try to integrate them in.

**Comment by tuenip** [comment]
Dear Prof Brainard, Dear Trisha,

thank you very much for your effort in answering my questions. A comparison between wavefront and ray-tracing models would be very interesting for us. I’ll have a look at the ray-tracing methods.

Best

Kristof

**Comment by DavidBrainard** [comment]
Let us know if you get stuck, we're happy to help.  Closing this issue, for now at least.
