### ISSUE TITLE
Human Pass I Notes

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#368]
Each function requiring attention is now a task and can be marked complete, so that we can reduce the number of issues submitted per check-in.

General:
* Reminder to remove trailing spaces on lines.
* Is isetcam supposed to be on all machines using isetbio?

Functions:
- [x] conePlot
* Assign someone to fix the example, which isn't working since sensor was removed. Also to review the one I've pilfered/tweaked.
* Review changes to inputs/outputs as I'm not sure if I've convoluted whether or not the support and spread are really the same in input/output if not, please alter.

- [ ] humanAchromaticOTF
* Assign someone (if not HJ) to complete the TODO (in note almost at end)
* Determine if HJ's note wrt scatter effect should be implemented (separate functions).
* Review changes made to the text

- [x] humanConeContrast
* Determine who wrote the note
* Assign someone to complete the TODO from the note

- [x] humanConeIsolating
* Modified examples to actually be standalone, please check.
* Should we include variable checking?

- [x] humanConeMosaic
* Assign someone to review the added/modified examples.
* Confirm text in inputs and outputs section

- [x] humanCore
* Determine who authored first note
* Assign someone to determine if my note is correct (and to change text accordingly if so)
* Assign someone to review language change(s).

- [x] humanLSF
* Note: JNM - Did the order of the variables change at some point? Two of the examples had the entries incorrect such that it resulted in a failing humanLSF and therefore a failing mesh graph... It has been fixed!
* Assign someone to review notes and remove as resolved/noted.
* Determine who wrote note at L84, and if it should be an action item (TODO).
* Confirm that there are no key/value pairs we want to add here

- [x] humanMacularTransmittance
* Density described as default in the description and in the function are NOT the same -- Which is correct?
* Assign someone to review the modified text for errors

- [x] humanOI
* Assign someone to fix the example (missing spectrum?)
* Assign someone to review added text
* WRT "shouldn't be both" note. Assign someone to review the note, and decide whether or not action needs to be taken

- [x] humanOpticalDensity
* Created the default value for visualField mentioned in the text.
* Assign someone to review added text
* Determine if there is someone who should create the 'random subject generator' as discussed here

- [x] humanOTF
* D0 is used in several different functions, and the numerical default doesn't always agree. Is this intentionally done?
* Assign someone to review added text.
* Determine how we want to include the large references/discussion section. Is what we have here a format we are comfortable with?

- [x] ijspeert
* Does not do any variable checking whatsoever
* Should we include default values or ways to switch between eye pigmentation options?
* I adore the dependence/uses/produces sections!

- [x] humanPupilSize
* Not sure if the luminance and... (empty ended) phrase was meant to have luminance and model. Please correct if not.
* Assign someone to review my added text, particularly if the optional key/values section is correctly added.
* Please make sure my reordering of text hasn't broken anything.

- [x] humanSpaceTime
* Assign someone to review my added text. The input models and description changes in particular.
* Assign someone to fix final example (and determine if the rest were split correctly) -> missing sumGauss function is in isetCam
* Ensure that sens return description is correct.

- [x] humanWaveDefocus
* Find citation for the formula used (a la 'Not sure where formula comes from in L41)
* Assign someone to review added/changed text

- [x] kellySpaceTime
* Determine who wrote note, and if someone needs to be assigned to implement the mentioned change(s)?
* Review modified text for accuracy

- [x] mouseCore
* Not sure if humanCore intentionally copied. Check modified text that I didn't butcher anything.
* Lots and lots of hard-coded values make me very nervous
* baseWave in the 'extend with same slope' section is unused?
* Assign TODO from Compute OTF section to someone?
* Is the returned matrix from example supposed to contain complex (imaginary) numbers?
* Review altered text for accuracy

- [x] mouseOTF
* Determine who authored notes and whether TODO's are warranted for any of them
* Review altered text to make sure I didn't botch any of the explanations
* I think example for this (and mouseCore) are still calibrated for humans, even with my alterations.
* Confirm changes between mouse and human I pulled from body text. (esp for cyc/deg. Text says 2 but max says 3???)
* Who should be cited for the References & Discussion section?

- [x] poirsonSpatioChromatic
* sumGauss is not defined??? --> is in isetCam (along with gauss and gauss2)
   * What assumptions are going to be made about how isetbio/isetcam will work together?
* Assign someone to review added text (particularly outputs)

- [x] watsonImpulseResponse
* Several hard-coded values, makes me nervous. I assume they are from the provided reference?
* Assign someone to review the added text
* Is there a reason the old debugging plot code has not been removed?
* Description section seems very ... sparse?

- [x] watsonRGCSpacing
* was ensity supposed to be density? (fix if not)
* yctr is unused at first instantiation (assigned at 156, and then again at 174)
* Assign someone to review the added/altered text please (I have barely any confidence in my additions)
* Should deg?2 be deg^2?
* Make sure I didn't botch any of the tables.
* Assign someone to expand the description, please.

- [x] westheimerLSF
* Assign someone to review the added/altered text
* *From 2nd example* the set command  triggers the "Warning: Negative limits ignored" message. Is this alright?
* The description for outputs (line spread function) should likely be expanded, but I think for the moment at least, it is sufficient.

**Comment by npcottaris** [comment]
Addressed some of these issues in commit e90c3b1d of March 16, 2019.

**Comment by npcottaris** [comment]
- Harmonized D0 in humanOTF
- Added missing citation in humanWaveDefocus
- Fixed deg?2 in watsonRGCspacing (it is supposed to be deg^-2)
- Fixed warning for westheimerLSF.
