### ISSUE TITLE
How to best cite ISETBIO?

### ISSUE THREAD

**Issue by elinekupers** [isetbio/isetbio#369]
I would like to cite ISETBIO in my paper, but was wondering if there is a preferred way (there are no guidelines on the wiki as far as I could see). 

Plus is there a paper that can/should be linked to it? Like the Farrell et al. (2014) SID Symposium Digest of Technical Papers? Or a DOI?

**Comment by DavidBrainard** [comment]
If you are submitting right now, I think the right things to cite are the isetbio.org URL plus one or both of:

Jiang, H., Cottaris, N., Golden, J., Brainard, D., Farrell, J. E., Wandell, B. A. (2017).  Simulating retinal encoding: factors influencing Vernier acuity.  Proceedings of Electronic Imaging 2017, Burlingame, CA.

Farrell, J. E., Jiang, H., Winawer, J., Brainard D. H., & Wandell, B. A. (2014).  Modeling visible differences: the computational observer model.  Proceedings of the 2014 Society for Information Display (SID) International Symposium.

If you are submitting next week, or when you revise, there might be a biorxiv paper on our foveal spatial CSF calculations that would be better.

We should probably add something to the wiki about our preferred citations.

**Comment by npcottaris** [comment]
Updated wiki with the latest ISETBio paper, and closing this.
