### ISSUE TITLE
Tutorials Pass I Part I: t_eyemovement

### ISSUE THREAD

**Issue by jenmaxwell** [isetbio/isetbio#370]
This is a catch-all for the issues discussed in the check-in for t_eyemovement. Please check off the functions as they are completed. Once all items are completed we can close this issue. General notes and implemented changes without corresponding TODO items are not included here.

_DHB: Did some things here. suggest that when both DHB and NCP are in the same place, we walk through the tutorials together, with NCP explaining things to DHB and DHB adding comments._

- [x] t_fixationalEyeMovementsTypes

- - [x]  Why is randomSeed locked for the third case?

- - [x] Tutorial is a function, and contains an embedded function, so has been formatted as function(s) and not tutorial + function

- [x] t_fixationalEyeMovementsToIsomerizations

- - [x] Read over my language changes in description and let me know what you think (of the short description in particular). _Looks good to me.  DHB_

- [x] t_fixationalEyeMovementsFeedbackGainAndControlGainDependence

- Read over my language changes in description and let me know what you think (of the short description in particular)
   Assign someone to expand the description section for embedded function analyzeResults
   = DrandomWalkY2 is never used?
   = plotEMpath
      1.  plotEMpath seems ... rather excessive for the number of arguments, especially with no argument checking whatsoever
      2. the argument nRows appears to never be used?
      3. Please look over the added text for accuracy.
   = plotVelocity
      1. the argument nRows appears to never be used?
      2. Assign someone to please expand the description section.
      3. Please look over the added text for accuracy.
      4. Same problems as other embedded functions with the lack of input checking
      5. Why are there so many hard-coded (and not referenced where they come from) values in this embedded function?
   = plotPowerSpectralDensity
      1. the argument nRows appears to never be used?
      2. Assign someone to please expand the description section.
      3. Please look over the added text for accuracy.
      4. Same problems as other embedded functions with the lack of input checking
   = plotDisplacementD2
      1. the argument nRows appears to never be used?
      2. Assign someone to please expand the description section.
      3. Please look over the added text for accuracy.
      4. Same problems as other embedded functions with the lack of input checking
   = plotDisplacementD1? Unused function?

- [x] t_fixationalEyeMovementsCharacterize

 - - [x] hFig not used? I understand that this is returned, but if it is not going to be used, can we just call the function itself without providing a variable to store the results in?
 - - [x] subjectDR and subkjectDG share a line color/pattern
 - - [x] Please check the added text

- [x] t_fixationalEMConeSampling

 - - [x] Assign someone to review added text
 - - [x] References for why hard-coded values (or explanations?)

- [x] t_fixationalEMParameters

 - - [x] Written as tutorial, so commented as one
 - - [x] No explanations for hard-coded values
 - - [x] Not sure how to best comment any of the cells save initialization, despite that I couldn't particularly speak to why the default values were chosen

- [x] t_fixationalEMTimeSampling

 - - [x] No explanations for hard-coded values? Intervals? Trials? Rates? Why those values?
 - - [x] Assign someone to expand the description section, as it is rather sparse, to put it mildly.

- [x] t_fixationalEyeMovementsAndConeMosaicVideo

 - - [x] Same question about unexplained hard-coded values. Things like 'cone params' are not an explanation as to why to load the mosaic, or why the interval should be a quarter of a millisecond
 - - [x] Assign someone to expand the description section.

**Comment by DavidBrainard** [comment]
Jenn.  Note addition of check boxes for sub-items.  This is handy because in some cases I was able to handle one item but not all, and wanted to indicate that for when I get back to this.

**Comment by npcottaris** [comment]
1) t_fixationalEyeMovementsFeedbackGainAndControlGainDependence
Lets not be so picky regarding argument checking in plotting functions in a tutorial. Added some comments and where hard-coded values came from.

**Comment by npcottaris** [comment]
1. Updated t_fixationalEMParameters and renamed to t_fixationalEM
2. Updated  t_fixationalEMTimeSampling
3. Updated t_fixationalEyeMovementsAndConeMosaicVideo
