### ISSUE TITLE
Stray video generated by tutorial.

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#371]
One of the tutorials in t_cones drops a video file into the t_cones directory.  It should instead be written into tempdir.  I noticed this when I ran all the tutorials, so I am not sure which one is the offending one.  We don't want large files to get checked into the isetbio repository by accident.

**Comment by jenmaxwell** [comment]
Note: This change will get checked in when I check in my cones tutorial folder (EoW at latest). I'm currently working on the advanced tutorials.

It was in two places:
    t_conesMosaicAbsorptionOISequenceEcc
    t_conesMosaicAbsorptionsEccBased

I've changed the helper function initFigure's internal call to videoWriter to the following:
        videoFile = fullfile(tempdir, 'video.m4v');
        writerObj = VideoWriter(videoFile, 'MPEG-4'); % H264 format

original:
        writerObj = VideoWriter(video.m4v', 'MPEG-4'); % H264 format

**Comment by npcottaris** [comment]
Resolved.
