### ISSUE TITLE
Merge coneTemp

### ISSUE THREAD

**Issue by hjiang36** [isetbio/isetbio#38]
coneTemp branch has been merged into master. The only conflict happens in file coneAbsorptions. I hope I'm not breaking something.

I'll do more test recently and if you find any bugs there, let me know.
Thanks

HJ

**Comment by xnieamo** [comment]
I've posted this as an issue separately before seeing this one, but my photoisomerization data has changed to a different size after the merge.  Before it was 164x164.  After the merge, running the same code results in 123x123.

**Comment by hjiang36** [comment]
I'm closing this issue for now.
If more bugs found, feel free to open new issues and we discuss them in different threads.
