### ISSUE TITLE
Marimont-Wandell PSF etc

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#386]
I added a script to scripts, s_opticsMarimontWandell, which illustrates the current state of play with respect to the Marimont-Wandell optics.  Here are the header comments.

% Description:
%    This script shows the Marimont-Wandell OTF and corresponding PSF.
%    It also explores the difference between the original way that
%    isetbio computed the psf and the current method.
%
%    The current method follows Matlab FFT conventions and seems like the
%    right thing to do, and the two methods give similar, but non-the-less
%    noticably different, results for the PSF.
%
%    The plot of the OTF looks quite similar to Figure 3 of M-W.
%
%    A plot of the LSF is not so close to Figure 4 of the M-W paper, with a
%    "peakier" LSF obtained by the current code. The LSF is computed from
%    the OTF using code separate from that which computes the PSF.  The LSF
%    computation is in oiPlot, and looks like it uses the right Matlab
%    conventions.
%
%    The negative values in the original "incorrect" method are smaller
%    than those in the current "correct" method. I am not sure if that has
%    any significance.

**Comment by npcottaris** [comment]
This seems like it should not be an issue. Closing.
