### ISSUE TITLE
Sample times - potential eye movement and cone adaptation incompatibilities

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#39]
There are two places where we use discrete sample times that are shorter than the exposure time. These are

1) sensorGet(sensor, 'sample time interval') - This is used in cone adaptation
2) sensorGet(sensor, 'em sample time')       - This controls the sample times of eye-movement updates.

Do we want to have both available, or should there really only be one sample time that must be smaller than the exposure time?

As currently used, we set the em sample time or the sensor sample time to 1 ms, so no problems arise.  But we could have problems in the future if we sample both eye movements and adaptation at different rates. The current code will not support two different sampling times.  For now, we could require them to be the same and allow them to co-exist.  But to have them be there and be meaningful, we need to write further routines that permit temporal interpolation and to handle the cases in which the sample times differ between eye movements and adaptation.

This issue needs some discussion, testing, and so forth.

HJ/BW

**Comment by DavidBrainard** [comment]
I think we have dealt with this, or at least that if we haven't we should be opening new issues that point at current problems, since the sensor object is long gone from isetbio.
