### ISSUE TITLE
plotFoo should be fooPlot

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#40]
I think it was bad of me to have plotFoo instead of fooPlot.  Just like there is a sensorGet/Set/Create there should be sensorPlot, and so forth for the other main structures.  Live and learn.

I have been meaning to simply convert all the plotFoo to fooPlot in ISET.  I think we should do it here, too.  The path is:

Copy the existing routines to the new names, and put them in the right directory.
Change the old routines to call the new routines.
Add a warning in the old routines that the wrong routine was called and to fix the code.
Wait until the problem is solved.

**Comment by hjiang36** [comment]
Name of plot routine for scene, sensor and oi are changed from plotFoo to fooPlot. And also the files using them.
Hope this doesn't break something.
We might overload the built-in function plot for scene, oi, sensor object. But maybe not for now.

Closing this issue for now...
