### ISSUE TITLE
List of dependencies or required toolboxes?

### ISSUE THREAD

**Issue by javiribera** [isetbio/isetbio#400]
Is there a list of toolboxes that ISETBIO requires?  If dependencies are [not handled automatically](https://github.com/isetbio/isetbio/issues/149), at least a list of dependencies would be helpful. A list of supported MATLAB version would also be appreciated.

Related: https://github.com/isetbio/isetbio/issues/141, https://github.com/isetbio/isetbio/issues/262

**Comment by wandell** [comment]
I hope this is helpful.

https://github.com/isetbio/isetbio/wiki/Installation

**Comment by javiribera** [comment]
Very helpful, thank you. Also, my experience with Matlab tells me that MathWorks often breaks backwards compatibility, so upgrading can sometimes be a hassle. The parts of ISETBIO that I am using work under MATLAB 2014a, but of course I did not evaluate all the code base. I was wondering if there is a version or set of versions of Matlab that ISETBIO officially supports.

**Comment by DavidBrainard** [comment]
Our design goal is to support three years back from the current release.  But I did
recently test fairly thoroughly on 2015a under Linux and it still worked.

**Comment by javiribera** [comment]
That sounds reasonable. I will create a pull request to add this recommendation in the installation instructions if that's ok. I assume this is a best-effort approach and no guarantees are given, since this is practically impossible with MATLAB.

**Comment by DavidBrainard** [comment]
Yes, please go for it on the PR.

Best,

David

**Comment by javiribera** [comment]
I added this information directly to the [installation section of the wiki](https://github.com/isetbio/isetbio/wiki/Installation), since it is not possible to do PR for wiki changes. FYI, the wiki seems open for everyone to edit. Thank you,

**Comment by DavidBrainard** [comment]
Thanks!
