### ISSUE TITLE
Is CSFgenerator2 Broken?

### ISSUE THREAD

**Issue by ferazambuja** [isetbio/isetbio#411]
I've tried to run the CSFgenerator2 using its mlapp however the following error shows:
`Undefined function 'gcp' for input arguments of type 'char'.
Error in CSFGeneratorApp.generate.processingPipeline (line 22)
     poolobj = gcp('nocreate');
Error in ISETBioCSFGenerator/startupFcn (line 289)
            CSFGeneratorApp.generate.processingPipeline(app, 'Starting up.'); `

The "app" opens but is not functional.

How am I supposed to run/start this app? Am I doing something wrong?

**Comment by npcottaris** [comment]
You’re getting this error because the app requires MATLAB’s parallel processing toolbox (as well as the signal processing, image processing, and the statistics toolboxes).
To run the CSFGenerator app, as well as much of the ISETBio functionality, you need to have these toolboxes installed.

**Comment by ferazambuja** [comment]
Thank's I've installed the Parallel Computing Toolbox, however, I'm getting the following error:
```
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 4).
min cone aperture diameter = 3.608448 microns
Will generate optics for Polans subject 6 (rank: 1)
Unrecognized function or variable 'createGratingScene'.
Error in CSFGeneratorApp.generate.gratingSceneEngine (line 5)
       theGratingSceneEngine = createGratingScene(sParams.chromaDir, sParams.sf, ...
Error in CSFGeneratorApp.generate.stimulus (line 16)
        CSFGeneratorApp.generate.gratingSceneEngine(sParams, []);
Error in CSFGeneratorApp.generate.processingPipeline (line 47)
        CSFGeneratorApp.generate.stimulus(app, dialogBox);
Error in ISETBioCSFGenerator/startupFcn (line 289)
            CSFGeneratorApp.generate.processingPipeline(app, 'Starting up.');
Error in appdesigner.internal.service.AppManagementService/runStartupFcn (line 103)
            startupFcn(app);
Error in matlab.apps.AppBase/runStartupFcn (line 69)
            ams.runStartupFcn(app, startfcn);
Error in ISETBioCSFGenerator (line 2374)
            runStartupFcn(app, @startupFcn) 
```

I'm using 2021b with the Statistics and Machine Learning Toolbox, Image Processing Toolbox, Signal Processing Toolbox and [Parallel Computing Toolbox](https://www.mathworks.com/products/parallel-computing.html). And installed isetbio via ToolboxToolbox.

**Comment by npcottaris** [comment]
Oh yeah, if you notice the splash screen of the app states that you need to have the ISETBioCSFGenerator toolbox on your path. This toolbox is freely available at https://github.com/isetbio/ISETBioCSFGenerator 

Nicolas

**Comment by ferazambuja** [comment]
Thanks that's what I was missing. I've must have missed the splash screen.
