### ISSUE TITLE
Thinking about architecture

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#43]
Following up on our Thursday conversation of last week, I had a go of creating some wiki pages that describe our current "objects" and how they are related.  Start here.

https://github.com/isetbio/isetbio/wiki/ISETBIO-Architecture-Vision

I probably forgot some objects, which I invite others to add.  Each object then has its own page with some comments about what it is supposed to do and some questions/action items if I had any to list.  

This is a try at our creating documentation for how we might make some gradual modifications to rationalize bits of the current code, without going completely overboard and starting from scratch.  Ideally, this would become some sort of actual documentation as we proceed, but for the moment it is more conceptual.

If you have thoughts, ideas, questions, perhaps try adding them to the wiki pages I started.

**Comment by wandell** [comment]
I spent a couple of hours editing the wiki pages.  (The thought that our colleagues will be looking these over panicked me a bit). Mainly, I just moved the basic conceptual writing along (not a lot of technical details).  I think it is in the direction we all expected.  Have a look.

**Comment by DavidBrainard** [comment]
I took a quick editing pass over the wiki, didn't make any radical changes.

A minor usage thing we might decide on is whether to refer to the current scene, optics, etc. implementation as data structures or as objects.  Currently both usages occur.  I have a mild preference for objects, because I think even when we implement via structs and functions we are basically treating them as objects.  This preference is not strong.

At some point, we may want to modify the autopublish code so that it allows us to control the order of the sections that show up on the web pages, both for validations and tutorials.  Currently it is alphabetical, although I suppose that may be simply because we listed things in alphabetical order.  I am particularly thinking that it would be nice if the most introductory tutorials could be listed first on the tutorials page.

**Comment by wandell** [comment]
1. Some day we might convert over to objects, but we will not convert classes.objects to structures.

2.  I think we need to rename the pages so the alphabetic ordering is the one we want.  Possibly by pretending numbers.  Say, 01 intro, 02 architecture, and the like.

B

Stanford

**Comment by DavidBrainard** [comment]
Closing.
