### ISSUE TITLE
Validation TODO list

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#44]
Because it might be a little while before we come back to this, I am writing down my current TODO list for the validation code.

A) Move the UnitTest object to its own UnitTestToolbox in a separate repository.  The motivation for this is that both Brian and I would like to use the UnitTest code in non-isetbio projects, and we may not always want isetbio on our Matlab path for such projects.  Move the UnitTest documentation to that repository's wiki and point to it from isetbio.

B) Think a little bit about how best to manage the configuration of the UnitTest code for different projects.  This will concern primarily where the validation data and scripts are stored.  It may be that we should provide a UnitTestConfigTemplate.m file, and that this would be copied and modified for each project to allow appropriate settings.  Currently the UnitTest object uses Matlab preferences for this sort of thing, and thus at any moment there is only one set of active preferences on a machine.  Currently the config file approach is the best I can think of, and a local config file could be invoked by scripts that run a set of validations.  When run in standalone mode, I don't think validation scripts rely in any way on preferences, so that they will run OK without the config being right.  [If they do rely on local preferences in stand-alone mode, we may want to remove this dependence.]   There might be better ideas about how to do this.  We will continue to want to publish validation scripts with individual projects (e.g., isetbio scripts should get published on the isetbio page).

C) Validation data, both FAST and FULL, should be written at the same time, so that they remain consistent.  Currently it requires a separate run of a validation script to generate each type of data.

D) FAST AND FULL validation data should go into separate folders.  And I think only the FULL data should keep the history.  The FAST should just overwrite.  We want to move the isetbio FULL validation directory outside of the isetbio repository - it is too big to keep there.  Preferences should allow the empty string for the validation dir to mean 'don't write this sort of validation data'.  The best way might be to have a separate repository 'isetbio-fullvalidationdata' and put it there.  Then we can keep it up to date and those who want it can get it as needed.  The FULL data is very useful for tracking down what is causing a validation failure, but not needed just to check that things are running correctly.

E) Change the names of 'validation/validationscripts' -> 'validation/scripts' and of 'vadidation/validationdata' -> 'validation/data'.  This latter should just have the most recent FAST validation data (see D above).

F) Think through the help text on the high level validation scripts and what scripts we'd like to have as presets.

G) In individual validation scripts, add help text that shows how to pass arguments to control behavior and convert to the assert format that was recently added to UnitTest.  For the former, the place to start is with the skeleton script.  The help text can then be propagated along and a string replace used to change the name in each individual script when it is created.  I think we want text that can be selected and executed for things like 'generate validation data for this script', 'publish this script'.  But we need to keep in mind that for those options, the current preferences for UnitTest will be used.

F) Once we make these changes, we should rename the current isetbio repository to 'isetbio-ver0.1' and make a new clean repository 'isetbio' that has only the current dev branch as the master branch and no history.  Then make a new dev branch to work on.  This is because there is no (easy) way to get all the huge stuff out of the current repository.  If we keep the ver0.1 version around, it will give us any history we need.

**Comment by DavidBrainard** [comment]
One more little thing.  If you validate and publish a single script, the whole wiki page gets re-written and just the single script shows up.  It might be nice to leave the rest alone in this case, if possible.  Or to have some sort of control.  Low priority.

**Comment by npcottaris** [comment]
Regarding D and E. @UnitTest has now been modified to store FAST and FULL validation data in separate directories under validation/data. When we decide on an alternate directory (outside isetbio), we can change it accordingly.

**Comment by npcottaris** [comment]
The @UnitTest class is now a separate repository, named UnitTestToolbox, under isetbio.org
To use it clone https://github.com/isetbio/UnitTestToolbox.git and add the cloned directory to your matlab path. Examples of how to use the @UnitTest class to validate code and data for any project, not just isetbio, will follow.

**Comment by npcottaris** [comment]
Items A) through E) in the validation-to-do list have now been implemented fully.
- The FULL validation mode now generates simultaneously both the FAST and the FULL validation data.
- The PUBLISH validation mode also generates simultaneously the FAST and the FULL validation data.
- The FAST validation mode is retained and only generates FAST validation data.
- The RUNTIME_ERRORS_ONLY validation mode is retained and does not generate any validation data.

**Comment by DavidBrainard** [comment]
This issue is mostly closed.  Closing and pasting the few remaining things into a new issue so that it isn't as daunting to look at.
