### ISSUE TITLE
Display object questions

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#45]
A) There is a comment in displaySet that the spd is the "average not peak".  I'm guessing this refers to the temporal average of the spd, but the comment is sufficiently terse that I'm not sure.  It would be worth clarifying this in the comment of the code.

B) As far as we can tell, there is not way to get the number of pixels in a display out of the ISETBIO display object.  Is this correct?  Would that be useful information to store?  Currently, ppi is stored (and assumed to be the same horizontal and vertical) but not the display size itself.  

C) [This part is not actually a question, just a comment.]  The design of the Display object appears to treat the black spd (which I tend to call the ambient spd) as what you get when you use the gamma table to find the output for RGB input [0 0 0]. I think this is a somewhat limiting choice.  I have often (well sometimes) had cases where there is enough light reflected from the faceplate of a display that the ambient spectral power distribution is not a linear combination of the display primaries.  The way  I handled this in the PTB calibration code is that there is an ambient spd stored explicitly as such, and the gamma functions by convention represent the incremental light produced by non-zero RGB values.  The gamma table entries for RGB = [0 0 0] are then by definition [0 0 0].  The code that finds display settings then always subtracts the ambient light (or tristimulus values) from the desired light and then uses the gamma table to find the appropriate incremental settings.  This approach has worked well for me, so I mention it here.  It is not important for me that the ISETBIO approach be changed, I'm just mentioning it in case it is of interest.  [This difference does mean that it is a bit hard to go back and forth between PTB and ISETBIO calibration objects and code for displays with non-zero ambient, but so be it.  And note that if you use PTB routines to fit gamma functions, they typically enforce the 0 in 0 out convention in the functional form of the fitting.]

**Comment by hjiang36** [comment]
A) Average means spatial-temporal average. The number stored in spd is directly from the spectrometer, meaning that the peak (material) spd for the primary is actually averaged by the black region around it. Thus, it's scaled down by the fill factor.

B) The display size is not stored in current structure. It's OK to add that field. Assuming that pixels are shift-invariant, we don't actually that parameter in the computation, right?

C) For a lot of cases in ISETBIO, ambient spd is treated as an independent primary (forth primary) and has its own spd, gamma, etc. Not sure if this is a good thing to do. We struggled for a while when we made this design. We could rethink and rewrite it in the future.

**Comment by DavidBrainard** [comment]
Thanks.  I added the display size field.

I will leave it to you to elaborate the comments in displaySet and displayGet.  I'd recommend noting both your point A carefully,

On point C, note that the comments about spd and nprimaries are onfusing given your answer about C) -- the matrix returned can be the number of primaries, or the number of primaries plus 1, depending on whether or not the black field is included (or is it always included?)  In any case, the comments are not clear in either the set or get and I think it would be nice to have them so.  Also, if it is possible for the black field to be there or not, we may find ourselves in a world of pain if we ever want to work with devices with other than three real primaries.

**Comment by hjiang36** [comment]
I agree that having black as a primary is somehow confusing. And we didn't enforce every display file to have that black primary.

It works OK with devices with more than three primaries...But surely, it could be confusing without knowing implementation details. Changing it from black primary to a stand alone ambient field sounds like a good idea. It will require changing a little in the computational routines, but not too much.

I will think more on this issue before I make modifications. I guess it might be good to build it as an object which could take PTB files as input to constructors...

**Comment by wandell** [comment]
I fully agree with introducing the change.

I like the PTB constructor idea, too.

Brian


Stanford

**Comment by DavidBrainard** [comment]
We do have PTB calibration structure to displayObject conversions, in both directions.  I am just about finished with the validations for those. The conversions are in the ptb package in isetbio, under external/psychtoolbox.  It was futzing with that stuff that led to my questions.

If you make this change we’ll also need to modify the conversion routine, but it will be easy.

DB

> On Jun 25, 2015, at 5:17 PM, Brian Wandell <notifications@github.com> wrote:
> 
> I fully agree with introducing the change.
> 
> I like the PTB constructor idea, too.
> 
> Brian
> 
> 
> Stanford
> Sent from mobile device
> 
> > On Jun 25, 2015, at 12:27 PM, Haomiao Jiang <notifications@github.com> wrote:
> > 
> > I agree that having black as a primary is somehow confusing. And we didn't enforce every display file to have that black primary.
> > 
> > It works OK with devices with more than three primaries...But surely, it could be confusing without knowing implementation details. Changing it from black primary to a stand alone ambient field sounds like a good idea. It will require changing a little in the computational routines, but not too much.
> > 
> > I will think more on this issue before I make modifications. I guess it might be good to build it as an object which could take PTB files as input to constructors...
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> > 
> —
> Reply to this email directly or view it on GitHub.
> 


=========
David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by DavidBrainard** [comment]
Display validations updated.  Closing this issue.  Will need to modify PTB<->Display conversions if Display is re-written to store ambient as a separate field.
