### ISSUE TITLE
photon rate in sensor

### ISSUE THREAD

**Issue by fmrieke** [isetbio/isetbio#47]
The photon rate in sensor appears to be discretized in a way I don't completely understand.  Thus if I do something like

stimulus(1:100) = 0;
stimulus(1) = 1;
sensor = sensorSet(sensor, 'photon rate', stimulus)
foo = sensorGet(sensor, 'photon rate')

foo(1) is 0.  I might have it wrong, but it seems like it is getting rounded so we have discrete photon counts in each time window - but for the cone model the time windows will be 1 ms or less (for the DEQs to run stably), and certainly can have only a few photons in that window.  And that will be worse for rods!  

Fred

**Comment by wandell** [comment]
That’s interesting.  Here is the ‘set’ code from sensorSet()

    case {'photonrate', 'isomerizationrate'}
        if ~sensorCheckHuman(sensor)
            error('Set photon to sensor can be only used in human cases');
        end
        cg = sensorGet(sensor, 'conversion gain');
        expTime = sensorGet(sensor, 'exposure time');
        sensor = sensorSet(sensor, 'volts', val * cg * expTime);

A few things -

- It will use ‘photon rate’ only if the word ‘human’ is in the name.  That should probably be removed for ISETBIO (it was useful in ISET).
- Photons is not a fundamental variable in the sensor.  Rather volts is, and these are related   So, the volts are set by multiplying the value sent in (the rate) times the exposure time and conversion gain.  
 - It is possible that the exposure time is set to zero in this case.  That is the value when we use ‘auto exposure’.  I just tried this and 0 is the default for sensor, but not for a human sensor.

>> s = sensorCreate; sensorGet(s,'exp time')

ans =

     0

Note that the default for a human sensor is 50 ms.

>> s = sensorCreate('human'); sensorGet(s,'exp time')

ans =

    0.0500

I am kind of thinking that for ISETBIO, we should always assume the ‘human’ conditions.  This is a really big difference from ISET, which rarely uses the human condition.  But making this move now could save us a lot of grief with other people down the road.

Brian


> On Jun 30, 2015, at 8:12 AM, Fred Rieke <notifications@github.com> wrote:
> 
> The photon rate in sensor appears to be discretized in a way I don't completely understand. Thus if I do something like
> 
> stimulus(1:100) = 0;
> stimulus(1) = 1;
> sensor = sensorSet(sensor, 'photon rate', stimulus)
> foo = sensorGet(sensor, 'photon rate')
> 
> foo(1) is 0. I might have it wrong, but it seems like it is getting rounded so we have discrete photon counts in each time window - but for the cone model the time windows will be 1 ms or less (for the DEQs to run stably), and certainly can have only a few photons in that window. And that will be worse for rods!
> 
> Fred
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/47>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by fmrieke** [comment]
Thanks - that helps me understand how things are getting set.  A couple other observations/notes:

- I am setting the integration time (typically to 0.001)
- volts appears to be set correctly and not rounded, but the return from photon rate appears discretized - here’s a piece of code showing that explicitly:

clear stimulus
stimulus(1:2) = 0;
stimulus(1) = 1;
sensor = sensorSet(sensor, 'integration time', 0.1);
sensor = sensorSet(sensor, 'conversion gain', 0.1);
sensor = sensorSet(sensor, 'photon rate', stimulus);
foo = sensorGet(sensor, 'photon rate')
foo = sensorGet(sensor, 'volts')

photon rate returns 0, volts returns 0.01.  Indeed sensorGet(s, ‘photon rate’) seems always to return an integer.  

I think I know enough to check what is going on now, but this may well trip someone else up as the relationship between those fields is a bit confusing.

Fred

**Comment by wandell** [comment]
One more note 

If you wish to set the number of photons, not the 'photon rate', then the call 

	sensor = sensorSet(s, 'photons', stimulus)

would work OK.  

Still, we should fix the other stuff.  Perhaps not allow 'photon rate' when the exp time is zero (auto-exposure).

Brian

> On Jun 30, 2015, at 8:47 AM, Brian Wandell <wandell@stanford.edu> wrote:
> 
> That’s interesting.  Here is the ‘set’ code from sensorSet()
> 
>     case {'photonrate', 'isomerizationrate'}
>         if ~sensorCheckHuman(sensor)
>             error('Set photon to sensor can be only used in human cases');
>         end
>         cg = sensorGet(sensor, 'conversion gain');
>         expTime = sensorGet(sensor, 'exposure time');
>         sensor = sensorSet(sensor, 'volts', val * cg * expTime);
> 
> A few things -
> 
> - It will use ‘photon rate’ only if the word ‘human’ is in the name.  That should probably be removed for ISETBIO (it was useful in ISET).
> - Photons is not a fundamental variable in the sensor.  Rather volts is, and these are related   So, the volts are set by multiplying the value sent in (the rate) times the exposure time and conversion gain.  
>  - It is possible that the exposure time is set to zero in this case.  That is the value when we use ‘auto exposure’.  I just tried this and 0 is the default for sensor, but not for a human sensor.
> 
> >> s = sensorCreate; sensorGet(s,'exp time')
> 
> ans =
> 
>      0
> 
> Note that the default for a human sensor is 50 ms.
> 
> >> s = sensorCreate('human'); sensorGet(s,'exp time')
> 
> ans =
> 
>     0.0500
> 
> I am kind of thinking that for ISETBIO, we should always assume the ‘human’ conditions.  This is a really big difference from ISET, which rarely uses the human condition.  But making this move now could save us a lot of grief with other people down the road.
> 
> Brian
> 
> 
>> On Jun 30, 2015, at 8:12 AM, Fred Rieke <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> The photon rate in sensor appears to be discretized in a way I don't completely understand. Thus if I do something like
>> 
>> stimulus(1:100) = 0;
>> stimulus(1) = 1;
>> sensor = sensorSet(sensor, 'photon rate', stimulus)
>> foo = sensorGet(sensor, 'photon rate')
>> 
>> foo(1) is 0. I might have it wrong, but it seems like it is getting rounded so we have discrete photon counts in each time window - but for the cone model the time windows will be 1 ms or less (for the DEQs to run stably), and certainly can have only a few photons in that window. And that will be worse for rods!
>> 
>> Fred
>> 
>> —
>> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/47>.
>> 
> 
> _____________________________________
> Brian A. Wandell
> Stein Family Professor
> Cognitive and Neurobiological Imaging (CNI)
> Psychology Department
> Phone: 1-650-725-2466
> http://www.stanford.edu/~wandell <http://www.stanford.edu/~wandell>
> 
> 
> 
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by fmrieke** [comment]
I think a similar issue applies there - sensorGet(sensor, ‘photons’) seems to return an integer only (even when sensor.data.volts is nonzero).  It also appears deterministic (i.e. not a draw from a Poisson dist).

Fred

**Comment by DavidBrainard** [comment]
I haven’t looked at the code, but I can sort of believe this.

That is, a calculation of mean rate is done and rounded to an integer, and then Poisson noise added in cases where noise is desired, using integer mean rate.

But really, the mean rate of a Poisson process should not be constrained to integer values, it should be carried around as a real and then instantiated as either a draw from a Poisson distribution (in the case where we model noise) and something else (when we want no noise.)

I am not quite sure what we want for the no noise case.  Returning real mean values seems most sensible, except that you then can get non-integer photon counts and that might screw up something someone was assuming.  But I think it might be better for someone who wants integers to have to round in this case (in essence adding a non-realistic noise at that stage if it suits immediate purposes) than for mean rates of less than 0.5 photons/integration time to always come back as 0.

> On Jun 30, 2015, at 12:44 PM, Fred Rieke <notifications@github.com> wrote:
> 
> I think a similar issue applies there - sensorGet(sensor, ‘photons’) seems to return an integer only (even when sensor.data.volts is nonzero). It also appears deterministic (i.e. not a draw from a Poisson dist).
> 
> Fred
> > On Jun 30, 2015, at 9:23 AM, Brian Wandell <notifications@github.com> wrote:
> > 
> > One more note 
> > 
> > If you wish to set the number of photons, not the 'photon rate', then the call 
> > 
> > sensor = sensorSet(s, 'photons', stimulus)
> > 
> > would work OK. 
> > 
> > Still, we should fix the other stuff. Perhaps not allow 'photon rate' when the exp time is zero (auto-exposure).
> > 
> > Brian
> > 
> > > On Jun 30, 2015, at 8:47 AM, Brian Wandell <wandell@stanford.edu> wrote:
> > > 
> > > That’s interesting. Here is the ‘set’ code from sensorSet()
> > > 
> > > case {'photonrate', 'isomerizationrate'}
> > > if ~sensorCheckHuman(sensor)
> > > error('Set photon to sensor can be only used in human cases');
> > > end
> > > cg = sensorGet(sensor, 'conversion gain');
> > > expTime = sensorGet(sensor, 'exposure time');
> > > sensor = sensorSet(sensor, 'volts', val * cg * expTime);
> > > 
> > > A few things -
> > > 
> > > - It will use ‘photon rate’ only if the word ‘human’ is in the name. That should probably be removed for ISETBIO (it was useful in ISET).
> > > - Photons is not a fundamental variable in the sensor. Rather volts is, and these are related So, the volts are set by multiplying the value sent in (the rate) times the exposure time and conversion gain. 
> > > - It is possible that the exposure time is set to zero in this case. That is the value when we use ‘auto exposure’. I just tried this and 0 is the default for sensor, but not for a human sensor.
> > > 
> > > >> s = sensorCreate; sensorGet(s,'exp time')
> > > 
> > > ans =
> > > 
> > > 0
> > > 
> > > Note that the default for a human sensor is 50 ms.
> > > 
> > > >> s = sensorCreate('human'); sensorGet(s,'exp time')
> > > 
> > > ans =
> > > 
> > > 0.0500
> > > 
> > > I am kind of thinking that for ISETBIO, we should always assume the ‘human’ conditions. This is a really big difference from ISET, which rarely uses the human condition. But making this move now could save us a lot of grief with other people down the road.
> > > 
> > > Brian
> > > 
> > > 
> > >> On Jun 30, 2015, at 8:12 AM, Fred Rieke <notifications@github.com <mailto:notifications@github.com>> wrote:
> > >> 
> > >> The photon rate in sensor appears to be discretized in a way I don't completely understand. Thus if I do something like
> > >> 
> > >> stimulus(1:100) = 0;
> > >> stimulus(1) = 1;
> > >> sensor = sensorSet(sensor, 'photon rate', stimulus)
> > >> foo = sensorGet(sensor, 'photon rate')
> > >> 
> > >> foo(1) is 0. I might have it wrong, but it seems like it is getting rounded so we have discrete photon counts in each time window - but for the cone model the time windows will be 1 ms or less (for the DEQs to run stably), and certainly can have only a few photons in that window. And that will be worse for rods!
> > >> 
> > >> Fred
> > >> 
> > >> —
> > >> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/47>.
> > >> 
> > > 
> > > _____________________________________
> > > Brian A. Wandell
> > > Stein Family Professor
> > > Cognitive and Neurobiological Imaging (CNI)
> > > Psychology Department
> > > Phone: 1-650-725-2466
> > > http://www.stanford.edu/~wandell <http://www.stanford.edu/~wandell>
> > > 
> > > 
> > > 
> > > 
> > 
> > _____________________________________
> > Brian A. Wandell
> > Stein Family Professor
> > Cognitive and Neurobiological Imaging (CNI)
> > Psychology Department
> > Phone: 1-650-725-2466
> > http://www.stanford.edu/~wandell
> > 
> > 
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/47#issuecomment-117244460>.
> > 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/47#issuecomment-117250708>.
> 

David H. Brainard
Professor of Psychology
Director, Penn Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by wandell** [comment]
Yes, the photons stored in a sensor are the sample from that particular exposure.  So when you call sensorGet you are returned the number of recorded photons in a particular exposure.  This is always an integer.

Fred’s original code appear to set a rate (hence ‘photon rate’) and not a number of photons.  That was the basic reason he discovered this issue.  We added a case that converts from a mean rate to a mean number of photons for that exposure.  This seems to be confusing.

In summary, the stored data is not a mean of a distribution. It is a number of photons.  The Poisson distribution is used during the computation, and it is not used on every sensorGet().

Perhaps we should collaborate on creating a script that does what Fred wants.  Or maybe we are doing well by having Fred poke here and there to see where the confusions can arise.  Not sure what’s best.

Brian


> On Jun 30, 2015, at 9:52 AM, David Brainard <notifications@github.com> wrote:
> 
> 
> I haven’t looked at the code, but I can sort of believe this.
> 
> That is, a calculation of mean rate is done and rounded to an integer, and then Poisson noise added in cases where noise is desired, using integer mean rate.
> 
> But really, the mean rate of a Poisson process should not be constrained to integer values, it should be carried around as a real and then instantiated as either a draw from a Poisson distribution (in the case where we model noise) and something else (when we want no noise.)
> 
> I am not quite sure what we want for the no noise case. Returning real mean values seems most sensible, except that you then can get non-integer photon counts and that might screw up something someone was assuming. But I think it might be better for someone who wants integers to have to round in this case (in essence adding a non-realistic noise at that stage if it suits immediate purposes) than for mean rates of less than 0.5 photons/integration time to always come back as 0.
> 
> > On Jun 30, 2015, at 12:44 PM, Fred Rieke <notifications@github.com> wrote:
> > 
> > I think a similar issue applies there - sensorGet(sensor, ‘photons’) seems to return an integer only (even when sensor.data.volts is nonzero). It also appears deterministic (i.e. not a draw from a Poisson dist).
> > 
> > Fred
> > > On Jun 30, 2015, at 9:23 AM, Brian Wandell <notifications@github.com> wrote:
> > > 
> > > One more note 
> > > 
> > > If you wish to set the number of photons, not the 'photon rate', then the call 
> > > 
> > > sensor = sensorSet(s, 'photons', stimulus)
> > > 
> > > would work OK. 
> > > 
> > > Still, we should fix the other stuff. Perhaps not allow 'photon rate' when the exp time is zero (auto-exposure).
> > > 
> > > Brian
> > > 
> > > > On Jun 30, 2015, at 8:47 AM, Brian Wandell <wandell@stanford.edu> wrote:
> > > > 
> > > > That’s interesting. Here is the ‘set’ code from sensorSet()
> > > > 
> > > > case {'photonrate', 'isomerizationrate'}
> > > > if ~sensorCheckHuman(sensor)
> > > > error('Set photon to sensor can be only used in human cases');
> > > > end
> > > > cg = sensorGet(sensor, 'conversion gain');
> > > > expTime = sensorGet(sensor, 'exposure time');
> > > > sensor = sensorSet(sensor, 'volts', val * cg * expTime);
> > > > 
> > > > A few things -
> > > > 
> > > > - It will use ‘photon rate’ only if the word ‘human’ is in the name. That should probably be removed for ISETBIO (it was useful in ISET).
> > > > - Photons is not a fundamental variable in the sensor. Rather volts is, and these are related So, the volts are set by multiplying the value sent in (the rate) times the exposure time and conversion gain. 
> > > > - It is possible that the exposure time is set to zero in this case. That is the value when we use ‘auto exposure’. I just tried this and 0 is the default for sensor, but not for a human sensor.
> > > > 
> > > > >> s = sensorCreate; sensorGet(s,'exp time')
> > > > 
> > > > ans =
> > > > 
> > > > 0
> > > > 
> > > > Note that the default for a human sensor is 50 ms.
> > > > 
> > > > >> s = sensorCreate('human'); sensorGet(s,'exp time')
> > > > 
> > > > ans =
> > > > 
> > > > 0.0500
> > > > 
> > > > I am kind of thinking that for ISETBIO, we should always assume the ‘human’ conditions. This is a really big difference from ISET, which rarely uses the human condition. But making this move now could save us a lot of grief with other people down the road.
> > > > 
> > > > Brian
> > > > 
> > > > 
> > > >> On Jun 30, 2015, at 8:12 AM, Fred Rieke <notifications@github.com <mailto:notifications@github.com>> wrote:
> > > >> 
> > > >> The photon rate in sensor appears to be discretized in a way I don't completely understand. Thus if I do something like
> > > >> 
> > > >> stimulus(1:100) = 0;
> > > >> stimulus(1) = 1;
> > > >> sensor = sensorSet(sensor, 'photon rate', stimulus)
> > > >> foo = sensorGet(sensor, 'photon rate')
> > > >> 
> > > >> foo(1) is 0. I might have it wrong, but it seems like it is getting rounded so we have discrete photon counts in each time window - but for the cone model the time windows will be 1 ms or less (for the DEQs to run stably), and certainly can have only a few photons in that window. And that will be worse for rods!
> > > >> 
> > > >> Fred
> > > >> 
> > > >> —
> > > >> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/47>.
> > > >> 
> > > > 
> > > > _____________________________________
> > > > Brian A. Wandell
> > > > Stein Family Professor
> > > > Cognitive and Neurobiological Imaging (CNI)
> > > > Psychology Department
> > > > Phone: 1-650-725-2466
> > > > http://www.stanford.edu/~wandell <http://www.stanford.edu/~wandell>
> > > > 
> > > > 
> > > > 
> > > > 
> > > 
> > > _____________________________________
> > > Brian A. Wandell
> > > Stein Family Professor
> > > Cognitive and Neurobiological Imaging (CNI)
> > > Psychology Department
> > > Phone: 1-650-725-2466
> > > http://www.stanford.edu/~wandell
> > > 
> > > 
> > > 
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/47#issuecomment-117244460>.
> > > 
> > 
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/47#issuecomment-117250708>.
> > 
> 
> David H. Brainard
> Professor of Psychology
> Director, Penn Vision Research Center
> Director, Institute for Research in Cognitive Science
> University of Pennsylvania
> 3401 Walnut Street, Suite 400A (mail address)
> 3401 Walnut Street, Room 315C (office location)
> Philadelphia, PA, 19104
> Phone: 215-573-7579
> Email: brainard@psych.upenn.edu
> Web: http://color.psych.upenn.edu/brainard
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/47#issuecomment-117254035>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by fmrieke** [comment]
I think I should keep poking around a bit and collect a set of related issues (this is one, which I can work around by setting straight to volts, another is that there are multiple time scales floating around with the implementation of the cone model, and which gets used to do what can lead to some confusion).  I’ll flag issues as they come up - and maybe we can discuss re James’ code as some of this relates to how the cone model works.

Fred

**Comment by wandell** [comment]
I created a tutorial script (t_sensorInputRefer.m) that illustrates how to set the scene luminance (or retinal illuminance) to achieve a particular photon rate.  That script also tests the Poisson random numbers at low intensity levels.

This is probably how we should set the cone and rod absorption  rates, and thus we should eliminate the sensorSet(s,'photon rate') case.

**Comment by wandell** [comment]
Way past this.  Closing.
