### ISSUE TITLE
Fast (hashed) validations not passing for Brian

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#48]
The full validations work, but not the fast (hashed).  This may be fixed by reducing the precision to which we round to 11 or perhaps 9 digits before hashing.  I hope so.  Otherwise we'll have to figure out what is going on.  In that case, the next question might to ask whether the hash algorithm is stable across versions of Matlab.

**Comment by DavidBrainard** [comment]
I think it is worth writing a little script that simply computes the hash for a few fixed numbers and reports it, and perhaps also tests the rounding function for a few test cases.  Given that the full tests pass, we know we are getting the same basic results on both computers, so I suspect something about how the hash itself is computed is going differently.

**Comment by DavidBrainard** [comment]
We have the same issue you describe with windows not closing.  Running s_initISET (aka ieInit) from the command window does not close them all on our systems.  This is, I thin,  the problem Haomiao and Nicolas were going back and forth on a few days ago, and if I recall correctly it has its own open issue.

**Comment by wandell** [comment]
I might have fixed it with new sceneGet.

**Comment by chichilnisky** [comment]
A thought -- I wonder if it would help for portability to:

- compute the significand (see below), say, a signed 16 bits integer
- compute the exponent, again a signed 16 bit integer
- take the product of these integers (yielding a signed 32bit integer)
- compute the hash

This could be one centralized function used specifically for our validation scripts.

Usually integer operations are more portable.

ej

**Comment by npcottaris** [comment]
Just pushed 9-decimal digit based fast ground truth data.
Brian, please git pull and do a fast validation once more.
Hopefully, this works.

**Comment by wandell** [comment]
No, still not matching.
[ 10] 'v_sceneFromRGB.m'
	Internal validation  : PASSED
	Run-time status      : no exception raised
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users/wandell/GitHub/isetbio/validation/validationdata/scene/v_sceneFromRGB_FastGroundTruthDataHistory.mat
	Fast validation      : FAILED against ground truth data of 01-Jan-2015 11:33:54.
	 > Ground truth info :                   Ithaka.local / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   :                         macula / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	DataHash-this run    : 2279adcc15e0f84747e47036f934c82d57958b42db7895f3415a215b75060a8a
	DataHash-groundTruth : 4c5da66b258bdd09d6425fae39e42faf86f06b95936264f74e05d2a8bf8f4299
	Validation report    : Hand check of h fov is within the specified tolerance (1e-12).



[ 11] 'v_sceneHCCompress.m'
	Internal validation  : PASSED
	Run-time status      : no exception raised
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users/wandell/GitHub/isetbio/validation/validationdata/scene/v_sceneHCCompress_FastGroundTruthDataHistory.mat
	Fast validation      : FAILED against ground truth data of 01-Jan-2015 11:34:02.
	 > Ground truth info :                   Ithaka.local / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   :                         macula / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	DataHash-this run    : 2e09e2f778688e34ad6ee1136ad5e0837bf326db0b5de003a56cc7b21ddf9069
	DataHash-groundTruth : 0d5c6e8ee223332d2964fed3e8c321570e158a72fe5fb44d7b0d6cede25c59b1
	Validation report    :

**Comment by npcottaris** [comment]
What about the other 9 tests? Do they pass? 

Thanks,
Nicolas

**Comment by wandell** [comment]
Yes.

**Comment by npcottaris** [comment]
Ah, then the issue is neither the rounding precision nor the hashing algorithm. Some aspect of the data must be system-dependent.  Stay tuned.

**Comment by DavidBrainard** [comment]
The curious thing is that the tests pass for these scripts for the full validation, suggesting that the data being rounded and hashed are themselves in good agreement.  

One thing these two scripts have in common, and that distinguishes them from the other scripts, is the large size of the full data sets that are hashed.  I don't have a theory of why this should make the hashed values system dependent; it's just an observation.  But if the hash algorithm has some upper size limit, or some machine dependency that is itself size dependent, that might do it.

An explicit test of the output of the rouding and hashing on a fixed bit of data, and indeed on a fixed bit of large data, might be diagnostic here.

**Comment by npcottaris** [comment]
I rechecked the hash data logging code and made all the char fields of the scene struct equal to ''.
New 9-decimal digit hash data uploaded. 
Can you please git pull and recheck the fast validation?
If the validations pass, we can go back to 11/12 digit precision.

Thanks,
Nicolas

**Comment by wandell** [comment]
Progress! [10] passes now, but not [11].

(After git pull and resetting the path for the new functions)

[ 10] 'v_sceneFromRGB.m'
	Internal validation  : PASSED
	Run-time status      : no exception raised
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users/wandell/GitHub/isetbio/validation/validationdata/scene/v_sceneFromRGB_FastGroundTruthDataHistory.mat
	Fast validation      : PASSED against ground truth data of 01-Jan-2015 14:43:02.
	 > Ground truth info :                   Ithaka.local / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   :                         macula / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	Data hash key        : abc8d0d6d7397cdd9bc6b988e94b4065eb79d83d5b71c54c69c1a239615061d6
	Validation report    : Hand check of h fov is within the specified tolerance (1e-12).



[ 11] 'v_sceneHCCompress.m'
	Internal validation  : PASSED
	Run-time status      : no exception raised
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users/wandell/GitHub/isetbio/validation/validationdata/scene/v_sceneHCCompress_FastGroundTruthDataHistory.mat
	Fast validation      : FAILED against ground truth data of 01-Jan-2015 14:43:11.
	 > Ground truth info :                   Ithaka.local / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   :                         macula / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	DataHash-this run    : 56881b7d4281778f930b4351c20cabb7339d1f21edf3d7a37c8a4b50b1c1d913
	DataHash-groundTruth : 777e15f37accd7ca0178606f11888f11b0f29524b184b73e7a29a491f61c0b83
	Validation report    :

**Comment by npcottaris** [comment]
Another thing these two scripts have in common is that they push scene structs in the validation data. The file paths of the files used to generate the scenes are stored in the scene struct as char arrays and they are different between the Penn and the Stanford machines. I have changed the code to null all char fields of structs before they are hashed  and I think this will solve the issue. This char field nulling was done in the FULL validation data, but not in the hashed data. I was under the impression that all scripts failed to validate in FAST mode, so I did not think about checking this until today. Brian, can you please git pull and rerun the fast validation ?

**Comment by npcottaris** [comment]
Sorry I missed your last comment. I will check [11] further.

**Comment by chichilnisky** [comment]
I don't understand why hashing would fail on character arrays.

Seems like we might want to be able to check character arrays in some cases.

ej

**Comment by npcottaris** [comment]
Sorry for not being clear. The validation is not failing in general on char arrays. It is failing on paths (which are char arrays) and which are different in the Penn and the Stanford machines. We can make this nulling smarter to clear only char arrays that are paths.

N.

**Comment by hjiang36** [comment]
I just tested validateFastAll and validateFullAll on my mac and windows
machine and all test scripts passed. Maybe we could assume the currently
version works for Windows.

Thanks,
HJ

**Comment by npcottaris** [comment]
Great !

I wonder why [11] is not passing fast validation for Brian. I checked the [11] validation script and I cannot determine a possible source for this failure.

**Comment by wandell** [comment]
Yes, puzzling.  I just did a new pull and ran it again.  Same story.  Let’s not spend more time on this.  It is only on my machine, so I should track it down some time.

[ 11] 'v_sceneHCCompress.m'
	Internal validation  : PASSED
	Run-time status      : no exception raised
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users/wandell/GitHub/isetbio/validation/validationdata/scene/v_sceneHCCompress_FastGroundTruthDataHistory.mat
	Fast validation      : FAILED against ground truth data of 01-Jan-2015 14:43:11.
	 > Ground truth info :                   Ithaka.local / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   :                         macula / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	DataHash-this run    : 56881b7d4281778f930b4351c20cabb7339d1f21edf3d7a37c8a4b50b1c1d913
	DataHash-groundTruth : 777e15f37accd7ca0178606f11888f11b0f29524b184b73e7a29a491f61c0b83
	Validation report    : 



On Jan 2, 2015, at 12:51 PM, Nicolas Cottaris <notifications@github.com> wrote:

> Great ! 
> 
> I wonder why [11] is not passing fast validation for Brian. I checked the [11] validation script and I cannot determine a possible source for this failure. 
> 
> 
> 
> > On Jan 2, 2015, at 3:47 PM, Haomiao Jiang <notifications@github.com> wrote: 
> > 
> > I just tested validateFastAll and validateFullAll on my mac and windows 
> > machine and all test scripts passed. Maybe we could assume the currently 
> > version works for Windows. 
> > 
> > Thanks, 
> > HJ 
> > 
> > On Thu Jan 01 2015 at 1:48:30 PM Nicolas Cottaris <notifications@github.com> 
> > wrote: 
> > 
> > > Sorry for not being clear. The validation is not failing in general on 
> > > char arrays. It is failing on paths (which are char arrays) and which are 
> > > different in the Penn and the Stanford machines. We can make this nulling 
> > > smarter to clear only char arrays that are paths. 
> > > 
> > > N. 
> > > 
> > > 
> > > > On Jan 1, 2015, at 4:45 PM, E.J. Chichilnisky <notifications@github.com> 
> > > wrote: 
> > > > 
> > > > I don't understand why hashing would fail on character arrays. 
> > > > 
> > > > Seems like we might want to be able to check character arrays in some 
> > > cases. 
> > > > 
> > > > ej 
> > > > 
> > > > 
> > > > > On Jan 1, 2015, at 1:43 PM, Nicolas Cottaris <notifications@github.com> 
> > > wrote: 
> > > > > 
> > > > > Another thing these two scripts have in common is that they push scene 
> > > structs in the validation data. The file paths of the files used to 
> > > generate the scenes are stored in the scene struct as char arrays and they 
> > > are different between the Penn and the Stanford machines. I have changed 
> > > the code to null all char fields of structs before they are hashed and I 
> > > think this will solve the issue. This char field nulling was done in the 
> > > FULL validation data, but not in the hashed data. I was under the 
> > > impression that all scripts failed to validate in FAST mode, so I did not 
> > > think about checking this until today. Brian, can you please git pull and 
> > > rerun the fast validation ? 
> > > > > 
> > > > > — 
> > > > > Reply to this email directly or view it on GitHub. 
> > > > > 
> > > > — 
> > > > Reply to this email directly or view it on GitHub < 
> > > https://github.com/isetbio/isetbio/issues/48#issuecomment-68499354>. 
> > > > 
> > > 
> > > — 
> > > Reply to this email directly or view it on GitHub 
> > > <https://github.com/isetbio/isetbio/issues/48#issuecomment-68499427>. 
> > > 
> > — 
> > Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/48#issuecomment-68560859>. 
> >
> —
> Reply to this email directly or view it on GitHub.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by wandell** [comment]
Two things - though I really can’t work on this now and am signing off ...

1.  I changed the function name in the v_sceneHCCompress to match the file name.  They were out of sync. Will push to repository shortly.

2.  I get no report of an error when I run    ----     validateFullAll(‘verbosity’,’high’)

[ 11] 'v_sceneHCCompress.m'
	Internal validation  : PASSED
	Run-time status      : no exception raised
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users/wandell/GitHub/isetbio/validation/validationdata/scene/v_sceneHCCompress_FullGroundTruthDataHistory.mat
	Full validation      : PASSED against ground truth data of 23-Dec-2014 13:28:12.
	 > Ground truth info :          manta.PSYCH.UPENN.EDU / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   :                         macula / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	Note (*)             : script does not store any extra data.
	Validation report    : 

Is that a clue?

Brian

On Jan 2, 2015, at 1:21 PM, Brian Wandell <wandell@stanford.edu> wrote:

> Yes, puzzling.  I just did a new pull and ran it again.  Same story.  Let’s not spend more time on this.  It is only on my machine, so I should track it down some time.
> 
> [ 11] 'v_sceneHCCompress.m'
> 	Internal validation  : PASSED
> 	Run-time status      : no exception raised
> 	Full validation file : contains 1 instance of historical data.
> 	Ground truth  file   : /Users/wandell/GitHub/isetbio/validation/validationdata/scene/v_sceneHCCompress_FastGroundTruthDataHistory.mat
> 	Fast validation      : FAILED against ground truth data of 01-Jan-2015 14:43:11.
> 	 > Ground truth info :                   Ithaka.local / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
> 	 > Local host info   :                         macula / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
> 	DataHash-this run    : 56881b7d4281778f930b4351c20cabb7339d1f21edf3d7a37c8a4b50b1c1d913
> 	DataHash-groundTruth : 777e15f37accd7ca0178606f11888f11b0f29524b184b73e7a29a491f61c0b83
> 	Validation report    : 
> 
> 
> 
> On Jan 2, 2015, at 12:51 PM, Nicolas Cottaris <notifications@github.com> wrote:
> 
>> Great ! 
>> 
>> I wonder why [11] is not passing fast validation for Brian. I checked the [11] validation script and I cannot determine a possible source for this failure. 
>> 
>> 
>> 
>> > On Jan 2, 2015, at 3:47 PM, Haomiao Jiang <notifications@github.com> wrote: 
>> > 
>> > I just tested validateFastAll and validateFullAll on my mac and windows 
>> > machine and all test scripts passed. Maybe we could assume the currently 
>> > version works for Windows. 
>> > 
>> > Thanks, 
>> > HJ 
>> > 
>> > On Thu Jan 01 2015 at 1:48:30 PM Nicolas Cottaris <notifications@github.com> 
>> > wrote: 
>> > 
>> > > Sorry for not being clear. The validation is not failing in general on 
>> > > char arrays. It is failing on paths (which are char arrays) and which are 
>> > > different in the Penn and the Stanford machines. We can make this nulling 
>> > > smarter to clear only char arrays that are paths. 
>> > > 
>> > > N. 
>> > > 
>> > > 
>> > > > On Jan 1, 2015, at 4:45 PM, E.J. Chichilnisky <notifications@github.com> 
>> > > wrote: 
>> > > > 
>> > > > I don't understand why hashing would fail on character arrays. 
>> > > > 
>> > > > Seems like we might want to be able to check character arrays in some 
>> > > cases. 
>> > > > 
>> > > > ej 
>> > > > 
>> > > > 
>> > > > > On Jan 1, 2015, at 1:43 PM, Nicolas Cottaris <notifications@github.com> 
>> > > wrote: 
>> > > > > 
>> > > > > Another thing these two scripts have in common is that they push scene 
>> > > structs in the validation data. The file paths of the files used to 
>> > > generate the scenes are stored in the scene struct as char arrays and they 
>> > > are different between the Penn and the Stanford machines. I have changed 
>> > > the code to null all char fields of structs before they are hashed and I 
>> > > think this will solve the issue. This char field nulling was done in the 
>> > > FULL validation data, but not in the hashed data. I was under the 
>> > > impression that all scripts failed to validate in FAST mode, so I did not 
>> > > think about checking this until today. Brian, can you please git pull and 
>> > > rerun the fast validation ? 
>> > > > > 
>> > > > > — 
>> > > > > Reply to this email directly or view it on GitHub. 
>> > > > > 
>> > > > — 
>> > > > Reply to this email directly or view it on GitHub < 
>> > > https://github.com/isetbio/isetbio/issues/48#issuecomment-68499354>. 
>> > > > 
>> > > 
>> > > — 
>> > > Reply to this email directly or view it on GitHub 
>> > > <https://github.com/isetbio/isetbio/issues/48#issuecomment-68499427>. 
>> > > 
>> > — 
>> > Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/48#issuecomment-68560859>. 
>> >
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
> _____________________________________
> Brian A. Wandell
> Stein Family Professor
> Cognitive and Neurobiological Imaging (CNI)
> Psychology Department
> Phone: 1-650-725-2466
> http://www.stanford.edu/~wandell
> 
> 
> 
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by DavidBrainard** [comment]
I don't think the name change was the issue.  The new version validated fine for me.

I have created some debugging scripts.  These are in validationscripts/valtemp.

One is a copy of v_sceneHCCompress, (called v_tempHCCompres) with one change.  At the very end it saves out its data into a matfile.  The save is currently commented out.

The other script is called v_xLoadMatfile.  It just loads this matfile and thus returns the same data as v_tempHCCompress, but frozen by the matfile's contents.

I first generated the matfile, then generated FAST validation data for both scripts.  I added both the the list of scripts that get validated by validateFastAll.  These two now get run first.

The matfile is too big for gitHub, so I put it into a dropbox folder that I've shared with Nicolas and Brian.

Brian, if you snag this matfile and put it into validationscripts/valtemp and then run validateFastAll, I think we will gain useful information.

a) I predict that v_tempHCCompress will fail, because it is exactly the same script as the currently failing v_sceneHCCompress.  If it doesn't, something really weird is happening, perhaps something stale in your setup.  On my machine, these two scripts generate the identical hash tag.

b) More interesting is v_xLoadMatfile.   This loads a matfille we wrote, so we know it has the same data as we are using on our system.  If it passes, then we know that the hashing of this data is working the same on Brain's machiine, and that the data produced by v_sceneHCCompress is somehow different.  In that case, Brian can uncomment the save command at the end of v_tempHCCompres, generate the matfile on his machine and send it back to us.

c) If it fails, this points us towards debugging the rounding and hashing code, since exactly the same data were being passed to the calling UnitTest data on Brian's machine as on ours.

There is one mystery, which is why I don't get the same hash key for v_tempHCCompress and v_xLoadMatfile.  I do get the same hash between v_sceneHCCompress and v_tempHCCompress.  And, all three pass the fast validation on my machine.  So I am not going to worry about this little mystery further right now.  Perhaps the initial exercise will tell us enough to solve the problem without solving that mystery.

**Comment by wandell** [comment]
Yes, v_tempHCCompress fails.

v_xLoadMatfile passes

I uncommented the ‘save’ command and generated a new matlab.mat

I just uploaded that file to 
   http://white.stanford.edu/~brian/matlab.mat

Brian


On Jan 2, 2015, at 6:10 PM, David Brainard <notifications@github.com> wrote:

> I don't think the name change was the issue. The new version validated fine for me.
> 
> I have created some debugging scripts. These are in validationscripts/valtemp.
> 
> One is a copy of v_sceneHCCompress, (called v_tempHCCompres) with one change. At the very end it saves out its data into a matfile. The save is currently commented out.
> 
> The other script is called v_xLoadMatfile. It just loads this matfile and thus returns the same data as v_tempHCCompress, but frozen by the matfile's contents.
> 
> I first generated the matfile, then generated FAST validation data for both scripts. I added both the the list of scripts that get validated by validateFastAll. These two now get run first.
> 
> The matfile is too big for gitHub, so I put it into a dropbox folder that I've shared with Nicolas and Brian.
> 
> Brian, if you snag this matfile and put it into validationscripts/valtemp and then run validateFastAll, I think we will gain useful information.
> 
> a) I predict that v_tempHCCompress will fail, because it is exactly the same script as the currently failing v_sceneHCCompress. If it doesn't, something really weird is happening, perhaps something stale in your setup. On my machine, these two scripts generate the identical hash tag.
> 
> b) More interesting is v_xLoadMatfile. This loads a matfille we wrote, so we know it has the same data as we are using on our system. If it passes, then we know that the hashing of this data is working the same on Brain's machiine, and that the data produced by v_sceneHCCompress is somehow different. In that case, Brian can uncomment the save command at the end of v_tempHCCompres, generate the matfile on his machine and send it back to us.
> 
> c) If it fails, this points us towards debugging the rounding and hashing code, since exactly the same data were being passed to the calling UnitTest data on Brian's machine as on ours.
> 
> There is one mystery, which is why I don't get the same hash key for v_tempHCCompress and v_xLoadMatfile. I do get the same hash between v_sceneHCCompress and v_tempHCCompress. And, all three pass the fast validation on my machine. So I am not going to worry about this little mystery further right now. Perhaps the initial exercise will tell us enough to solve the problem without solving that mystery.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by wandell** [comment]
I also did a git pull on a Linux box just now.

Stranger and stranger.

On that machine s_sceneFromRGB fails, but the v_*HCC*.m files pass.

Brian

On Jan 2, 2015, at 9:08 PM, Brian Wandell <wandell@stanford.edu> wrote:

> Yes, v_tempHCCompress fails.
> 
> v_xLoadMatfile passes
> 
> I uncommented the ‘save’ command and generated a new matlab.mat
> 
> I just uploaded that file to 
>    http://white.stanford.edu/~brian/matlab.mat
> 
> Brian
> 
> 
> On Jan 2, 2015, at 6:10 PM, David Brainard <notifications@github.com> wrote:
> 
>> I don't think the name change was the issue. The new version validated fine for me.
>> 
>> I have created some debugging scripts. These are in validationscripts/valtemp.
>> 
>> One is a copy of v_sceneHCCompress, (called v_tempHCCompres) with one change. At the very end it saves out its data into a matfile. The save is currently commented out.
>> 
>> The other script is called v_xLoadMatfile. It just loads this matfile and thus returns the same data as v_tempHCCompress, but frozen by the matfile's contents.
>> 
>> I first generated the matfile, then generated FAST validation data for both scripts. I added both the the list of scripts that get validated by validateFastAll. These two now get run first.
>> 
>> The matfile is too big for gitHub, so I put it into a dropbox folder that I've shared with Nicolas and Brian.
>> 
>> Brian, if you snag this matfile and put it into validationscripts/valtemp and then run validateFastAll, I think we will gain useful information.
>> 
>> a) I predict that v_tempHCCompress will fail, because it is exactly the same script as the currently failing v_sceneHCCompress. If it doesn't, something really weird is happening, perhaps something stale in your setup. On my machine, these two scripts generate the identical hash tag.
>> 
>> b) More interesting is v_xLoadMatfile. This loads a matfille we wrote, so we know it has the same data as we are using on our system. If it passes, then we know that the hashing of this data is working the same on Brain's machiine, and that the data produced by v_sceneHCCompress is somehow different. In that case, Brian can uncomment the save command at the end of v_tempHCCompres, generate the matfile on his machine and send it back to us.
>> 
>> c) If it fails, this points us towards debugging the rounding and hashing code, since exactly the same data were being passed to the calling UnitTest data on Brian's machine as on ours.
>> 
>> There is one mystery, which is why I don't get the same hash key for v_tempHCCompress and v_xLoadMatfile. I do get the same hash between v_sceneHCCompress and v_tempHCCompress. And, all three pass the fast validation on my machine. So I am not going to worry about this little mystery further right now. Perhaps the initial exercise will tell us enough to solve the problem without solving that mystery.
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
> _____________________________________
> Brian A. Wandell
> Stein Family Professor
> Cognitive and Neurobiological Imaging (CNI)
> Psychology Department
> Phone: 1-650-725-2466
> http://www.stanford.edu/~wandell
> 
> 
> 
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by DavidBrainard** [comment]
The fact that the hash value for the matfile version wasn't the same bugged me all night.  The reason is that objects are some sort of "pass by reference" thing -- in any case loading the Matfile wasn't passing any loaded data back up the chain and the hash was just of some baseline information.

I was able to fix this by loading the matfile and then saving the validation data explicitly in the object from what was loaded.  Doing this makee the load version generate the same hash tag  as the versions that do all the computing.

On my machines, I also get the same hash values (i.e., FAST validation passes) if I load either the Matfile I generated or the one that Brian generated.  This points to the problem being in the round/hash/compare stage, not the actual execution of the script.  (And this is consistent with FULL validations passing.)

To confirm the above, Brian can you pull the new code and FAST validation files from gitHub and then re-run the test with each of the two Matfiles on your machine?  (These are now named matfileDavid and matfileBrian in the dropbox folder.)  The prediction is that both will fail for you.  

Given how weird this is, who knows what will actually happen.

**Comment by DavidBrainard** [comment]
This is now solved, by virtue of handling logical variables more carefully.  Closing this issue (yay!)
