### ISSUE TITLE
Display Structure Change - Ambient Field Added

### ISSUE THREAD

**Issue by hjiang36** [isetbio/isetbio#48]
A new field called ambient is added to display structure. This field is used to store spd when display is set to black in units of energy and is a vector of same length of display wavelength samples (d.wave). 

With this change, elements of the first row of the gamma table are all zero. And displayGet(d, 'dark level') is removed. To get the ambient spd, use displayGet(d, 'ambient spd')

1) Do we need to change displayGet for 'white xyz', 'white spd', 'white xy', etc. to add ambient to white
2) Need to change validation and PTB-ISETBIO conversion scripts

I hope this does not break something. If you find any bugs, let me know.
Thanks

**Comment by DavidBrainard** [comment]
> A new field called ambient is added to display structure. This field is used to store spd when display is set to black in units of energy and is a vector of same length of display wavelength samples (d.wave).
> With this change, elements of the first row of the gamma table are all zero. And displayGet(d, 'dark level') is removed. To get the ambient spd, use displayGet(d, 'ambient spd')
> 
> 1) Do we need to change displayGet for 'white xyz', 'white spd', 'white xy', etc. to add ambient to white
> 2) Need to change validation and PTB-ISETBIO conversion scripts
> 
> I hope this does not break something. If you find any bugs, let me know.
> Thanks
> 
t_displayIntroduction and t_displayResolution now crash with an error whose source is not immediately obvious to me.   Can you take a look?

Best,

David

**Comment by hjiang36** [comment]
I made a bug fix and t_displayIntroduction and t_displayResolution should work fine now.

The issue was because I forgot to remove the padded ambient column in d.dixel.intensityMap in two display .mat files.

If you find any more problems, let me know

**Comment by DavidBrainard** [comment]
t_displayIntroduction now works for me, but t_displayResolution still fails with what I think is the same error.

>> t_displayResolution
Error using vcReadImage (line 156)
bad image size

Error in sceneFromFile (line 94)
        photons = vcReadImage(I, imType, dispCal, doSub, sz);

Error in displayShowImage (line 31)
scene = sceneFromFile(rgb, 'rgb', [], d);

Error in displaySetEditsAndButtons (line 40)
displayShowImage(d, [], handles.axes1);

Error in displayWindow>displayRefresh (line 293)
displaySetEditsAndButtons(handles);

Error in displayWindow>displayWindow_OpeningFcn (line 85)
displayRefresh(hObject, eventdata, handles);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in displayWindow (line 55)
    gui_mainfcn(gui_State, varargin{:});

Error in t_displayResolution (line 80)
vcAddObject(d); displayWindow;

**Comment by hjiang36** [comment]
This error is different from the previous one. vcReadImage function get changed by Brian a little in the last commit. With that change, the program requires MxNx4 input image for RGBW display and the RGB image does not work anymore.

For me, I prefer to change vcReadImage back. And I'm checking with Brian and see if he thinks that's a good idea.

**Comment by wandell** [comment]
Sure, change it back.

B

**Comment by DavidBrainard** [comment]
Changing this back seems to fix the tutorial crash.  Was just able to run publishAllTutorials without error. 

Closing this issue.
