### ISSUE TITLE
ieLUTInvert etc.

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#49]
In going through the tutorials I have been trying to eliminate direct loads of files that were in subdirectory cMatch of scripts/color, and replace these either by calles to ieReadSpectra or displayCreate.

Because one of the reads was of a monitor inverse gamma table (in monitorGam, variable monitorInvGam, a 1000 by 3 inverse gamma table for a typical monitor).

I thought I could get this by

d = displayCreate;
monitorGam = displayGet(d,'gamma');
monitorInvGam = ieLUTInvert(monitorGam,8)

where the 8 makes a reasonable size gamma table.

But, the returned inverse table has only one column.  In addition, plotting it looks like a straight line, suggesting it isn't an inverse lookup table.

The example code given in the help text for ieLUTInvert doesn't make sense to me.  First, it accesses a display field directly which seems to violate our preferred style.  Second, it contains a raise of the gamma table to the exponent 0.6, which I don't get.

I suspect I'm not understanding something basic about the way isetbio handles all this sort of thing.

The two relevant tutorials are t_colorMatching (which actually seems to be working OK but I no longer understand why) and xNeedChecking/display/t_displayRendering.  Once we have this sorted out, which should check the way ieLUTInvert is used in other ones I might have modified (I can do this), because I'm no longer sure I deduced correctly how this stuff works.

**Comment by wandell** [comment]
I will try to get to this in a couple of days.

Those are very old tutorials that I use when teaching my class, and they were written independently.  Maybe by Xuemei Zhang a long time ago.  I will try to figure it out.

Brian

On Jan 3, 2015, at 4:27 PM, David Brainard <notifications@github.com> wrote:

> In going through the tutorials I have been trying to eliminate direct loads of files that were in subdirectory cMatch of scripts/color, and replace these either by calles to ieReadSpectra or displayCreate.
> 
> Because one of the reads was of a monitor inverse gamma table (in monitorGam, variable monitorInvGam, a 1000 by 3 inverse gamma table for a typical monitor).
> 
> I thought I could get this by
> 
> d = displayCreate;
> monitorGam = displayGet(d,'gamma');
> monitorInvGam = ieLUTInvert(monitorGam,8)
> 
> where the 8 makes a reasonable size gamma table.
> 
> But, the returned inverse table has only one column. In addition, plotting it looks like a straight line, suggesting it isn't an inverse lookup table.
> 
> The example code given in the help text for ieLUTInvert doesn't make sense to me. First, it accesses a display field directly which seems to violate our preferred style. Second, it contains a raise of the gamma table to the exponent 0.6, which I don't get.
> 
> I suspect I'm not understanding something basic about the way isetbio handles all this sort of thing.
> 
> The two relevant tutorials are t_colorMatching (which actually seems to be working OK but I no longer understand why) and xNeedChecking/display/t_displayRendering. Once we have this sorted out, which should check the way ieLUTInvert is used in other ones I might have modified (I can do this), because I'm no longer sure I deduced correctly how this stuff works.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by hjiang36** [comment]
ieLUTInvert returns the invert gamma table for the first primary of the
display (that is why it's one column). I'll fix this and let it return for
all primaries. The second parameter is 'resolution' and it's different from
color bit depth. Suppose the bit depth is 8 and we set resolution to 8, it
will return inverse gamma table sampled at point 0:1/8:255.

For displayCreate without parameters, it creates a display with no gamma
distortion. Thus, the straight line of ieLUTInvert is expected. You could
create some other displays (say displayCreate('LCD-Apple') or
displayCreate('OLED-Sony')) for more reasonable gamma table.

I'll check and update the tutorial scripts you mentioned above.
Thanks

Best,
HJ

**Comment by hjiang36** [comment]
I just made the updates to ieLUTInvert and the tutorial files. Please pull
and have a look when you get time.
Besides, displayGet(d, 'inverse gamma table') is added.

We may want to change the second parameter in ieLUTInvert to number of
sampling steps or a vector of sampling positions instead of 'resolution'.
Let me know which one is more intuitive or preferable.

Thanks

Best,
HJ

**Comment by DavidBrainard** [comment]
1) OK great.  Thanks for pointing out that the default display has a linear gamma function -- it was bugging me how the code produced a linear inverse gamma table for that case but not for another place where I happened to use a named display.

2) I looked over your changed tutorials and they look good.

3) I like the idea of having a get for the inverse gamma table -- less thinking required.  There was a bug in the code, though.  You need to remove the spaces from the strings in the case statement, because the parsing code strips them from the passed argument.  I made this fix. 

I am closing this issue now, but will open two related ones in a second.
