### ISSUE TITLE
plotOI('ls wavelength') bug - around line 826

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#5]
See the comment in the code around line 826

        % The spaceSamp and nSamp parameters are not clearly enough
        % defined.  The reason we care is because the code is broken when
        % spaceSamp is not 40.  No idea why.  Let's come back and clean it
        % up.

**Comment by DavidBrainard** [comment]
This is, we think, why t_opticsImageTutorial currently fails.

**Comment by hjiang36** [comment]
This is also related to row  / column format of OTF.fx and OTF.fy. Should
be fixed once that one get fixed.
