### ISSUE TITLE
Remote data, load times

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#50]
I brought v_rdata into the UnitTestToolbox world and also did some timing on remote loading.  I compared three ways of loading a .mat file.  One is using rdate.  The second is reading it via a mounted version of Crimson, which I mounted using SSHFS/FUSE on Mac OS/X.  The third is reading a local copy from my desktop.  The mounted disk appears to do some sort of local caching.

For a 10.6 MB file (scene/benchHDR.mat, variable scene):
 SSHFS/FUSE, 2cd time and thereafter: 0.33 seconds
 Local: 0.07 seconds
 rdata: 1.7 seconds

I also tried a 583.3 MB file (slantedBar/slantedBarMultiLF80Diffract.mat).  
  SSHFS/FUSE, 1st time:  395 seconds
  SSHFS/FUSE,  2cd time and thereafter: 6.5 seconds
  Local: 6.4 seconds
  rdata: 57 seconds

I think this is going to be too slow for us to rdata.  The cached mounted disk might work.  We could certainly set up some sort of sync program so that we kept a local copy of the disk on Crimson and kept it up to date when we changed things.

But, I'm curious on how these times are at Stanford when there isn't as much internet between you and the server as there is for us.

**Comment by wandell** [comment]
Thanks for testing, and good to know.

I will time locally.  I haven’t done this.  I am cc’ing Michael Perry who will check with me.

Brian

> On Jul 15, 2015, at 10:19 AM, David Brainard <notifications@github.com> wrote:
> 
> I brought v_rdata into the UnitTestToolbox world and also did some timing on remote loading. I compared three ways of loading a .mat file. One is using rdate. The second is reading it via a mounted version of Crimson, which I mounted using SSHFS/FUSE on Mac OS/X. The third is reading a local copy from my desktop. The mounted disk appears to do some sort of local caching.
> 
> For a 10.6 MB file (scene/benchHDR.mat, variable scene):
> SSHFS/FUSE, 2cd time and thereafter: 0.33 seconds
> Local: 0.07 seconds
> rdata: 1.7 seconds
> 
> I also tried a 583.3 MB file (slantedBar/slantedBarMultiLF80Diffract.mat).
> 
> SSHFS/FUSE, 1st time: 395 seconds
> SSHFS/FUSE, 2cd time and thereafter: 6.5 seconds
> Local: 6.4 seconds
> rdata: 57 seconds
> 
> I think this is going to be too slow for us to rdata. The cached mounted disk might work. We could certainly set up some sort of sync program so that we kept a local copy of the disk on Crimson and kept it up to date when we changed things.
> 
> But, I'm curious on how these times are at Stanford when there isn't as much internet between you and the server as there is for us.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/50>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by DavidBrainard** [comment]
No longer relevant.  For all of their fussiness, archiva/gradle/RemoteDataToolbox do a nice job with caching.
