### ISSUE TITLE
Tutorials, status

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#52]
I've now been through all of the tutorials.  Most ran fine or were easily fixed to run.  These are all now filed in their subfolders under tutorials.  I focussed mostly on making sure they ran, with a bit of tidying up.  

I did not work hard on the comments or on merging together things that seemed redundant with each other.  Some of that might be done at some point, but I think the set of tutorials is now in pretty good shape.

Tutorials that I couldn't or wasn't willing to fix are not in a top level isetbio folder xNeedFixingOrDeleting/tutorials.  I think I put a note at the top of each (there are only about 5) as to what the issue was.  I suspect several can just be deleted without any harm, but Brian will be the best judge of that.  But t_opticsImageFormation is a really nice piece of code.  What it needs is to have the data it reads be brought into isetbio format, but other than that it is ready to go.

I will move on to filtering through the scripts in the same way as I've done with the tutorials when I get a chance. And Nicolas and I will work on an autopublish scheme for the tutorials, as well as writing something that makes it easy to verify in the future that they all run without error.

**Comment by chichilnisky** [comment]
This is great stuff.  We'll start with the tutorials when my postdoc Alexandra comes back.

ej

**Comment by npcottaris** [comment]
The auto feature is now complete. A new script named 'publishAllTutorials.m', located in $isetbioRoot/validation, scans the @isetbioRoot/tutorials folder and publishes all scripts that do not throw runtime errors. Scripts are published at https://github.com/isetbio/isetbio/wiki/Tutorials. The script can be customized to suit specific users' environments and/or different projects by setting various preferences.

**Comment by DavidBrainard** [comment]
Closing this issue.
