### ISSUE TITLE
Small hanging validation clean up

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#53]
In individual validation scripts, add help text that shows how to pass arguments to control behavior and convert to the assert format that was recently added to UnitTest. For the former, the place to start is with the skeleton script. The help text can then be propagated along and a string replace used to change the name in each individual script when it is created. I think we want text that can be selected and executed for things like 'generate validation data for this script', 'publish this script'. But we need to keep in mind that for those options, the current preferences for UnitTest will be used.

**Comment by npcottaris** [comment]
Regarding passing arguments to validation scripts. Only the managing @UnitTest object can pass parameters to scripts. When run in standalone mode all passed arguments are ignored. The stand-alone run mode is useful to establish that the script produces no run-time errors.
Auto publishing, and generation of validation data are both controlled via the managing @UnitTest object.

**Comment by npcottaris** [comment]
Script conversion to the assert format is now done.
