### ISSUE TITLE
git pull error that reflects something we need to discuss

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#55]
I wonder whether these files should be removed from the repository?  I think the problem in the git pull arises because I change the m-file as per NP's suggestion, a new .mat file is created, and this produces the error.  I don't want to chck in my m-file changes, and we probably intend an alternative strategy for the ground truth data.

fovea:isetbio (master) $git pull
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 14 (delta 9), reused 10 (delta 5), pack-reused 0
Unpacking objects: 100% (14/14), done.
From https://github.com/isetbio/isetbio
   3fd2b88..d71ac1e  master     -> origin/master
Updating 3fd2b88..d71ac1e
error: Your local changes to the following files would be overwritten by merge:
	validation/data/fast/data/v_rdata_FastGroundTruthDataHistory.mat
	validation/setIsetbioUnitTestPreferencesTemplate.m
Please, commit your changes or stash them before you can merge.
Aborting
fovea:isetbio (master) $

**Comment by npcottaris** [comment]
I would suggest 

rm v_rdata_FastGroundTruthDataHistory.mat

followed by

git pull

N.

**Comment by npcottaris** [comment]
As for the
setIsetbioUnitTestPreferencesTemplate.m 
file, you should rename it to, say, setIsetbioUnitTestPreferencesFovea.m
(since it contains preferences specific to the installation on fovea) and you should not commit it it to the repository.

N.

**Comment by DavidBrainard** [comment]
What I do is put my pref setting functions on my desktop so that they are easy to find and re-run and so that they don’t live in the repository and confuse me about whether I’ve got uncommitted things.  I think the nature of configuration files is that we can only provide a template with the best defaults we can come up with, but that there is no way around a user having to configure some things in a way that should be stored only on that person’s machine.

> On Jul 19, 2015, at 8:28 AM, Nicolas Cottaris <notifications@github.com> wrote:
> 
> As for the
> setIsetbioUnitTestPreferencesTemplate.m 
> file, you should rename it to, say, setIsetbioUnitTestPreferencesFovea.m
> (since it contains preferences specific to the installation on fovea) and you should not commit it it to the repository.
> 
> N.
> 
> Sent from my iPhone 6+
> 
> > On Jul 18, 2015, at 19:33, Brian Wandell <notifications@github.com> wrote:
> > 
> > I wonder whether these files should be removed from the repository? I think the problem in the git pull arises because I change the m-file as per NP's suggestion, a new .mat file is created, and this produces the error. I don't want to chck in my m-file changes, and we probably intend an alternative strategy for the ground truth data.
> > 
> > fovea:isetbio (master) $git pull
> > remote: Counting objects: 14, done.
> > remote: Compressing objects: 100% (8/8), done.
> > remote: Total 14 (delta 9), reused 10 (delta 5), pack-reused 0
> > Unpacking objects: 100% (14/14), done.
> > >From https://github.com/isetbio/isetbio
> > 3fd2b88..d71ac1e master -> origin/master
> > Updating 3fd2b88..d71ac1e
> > error: Your local changes to the following files would be overwritten by merge:
> > validation/data/fast/data/v_rdata_FastGroundTruthDataHistory.mat
> > validation/setIsetbioUnitTestPreferencesTemplate.m
> > Please, commit your changes or stash them before you can merge.
> > Aborting
> > fovea:isetbio (master) $
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> > 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/55#issuecomment-122657810>.
> 

David H. Brainard
Professor of Psychology
Director, Penn Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by wandell** [comment]
I am thinking what I will do is add a .gitignore for the file that sets up the preferences.

Maybe that could be a part of the installation direction - that users copy the setXX template to a particular file or ‘local’ directory where things are ignored by the git pulls.

Sorry about the validateCoreFast … I didn’t read carefully enough.

B

> On Jul 19, 2015, at 12:47 PM, David Brainard <notifications@github.com> wrote:
> 
> What I do is put my pref setting functions on my desktop so that they are easy to find and re-run and so that they don’t live in the repository and confuse me about whether I’ve got uncommitted things. I think the nature of configuration files is that we can only provide a template with the best defaults we can come up with, but that there is no way around a user having to configure some things in a way that should be stored only on that person’s machine.
> 
> > On Jul 19, 2015, at 8:28 AM, Nicolas Cottaris <notifications@github.com> wrote:
> > 
> > As for the
> > setIsetbioUnitTestPreferencesTemplate.m 
> > file, you should rename it to, say, setIsetbioUnitTestPreferencesFovea.m
> > (since it contains preferences specific to the installation on fovea) and you should not commit it it to the repository.
> > 
> > N.
> > 
> > Sent from my iPhone 6+
> > 
> > > On Jul 18, 2015, at 19:33, Brian Wandell <notifications@github.com> wrote:
> > > 
> > > I wonder whether these files should be removed from the repository? I think the problem in the git pull arises because I change the m-file as per NP's suggestion, a new .mat file is created, and this produces the error. I don't want to chck in my m-file changes, and we probably intend an alternative strategy for the ground truth data.
> > > 
> > > fovea:isetbio (master) $git pull
> > > remote: Counting objects: 14, done.
> > > remote: Compressing objects: 100% (8/8), done.
> > > remote: Total 14 (delta 9), reused 10 (delta 5), pack-reused 0
> > > Unpacking objects: 100% (14/14), done.
> > > >From https://github.com/isetbio/isetbio
> > > 3fd2b88..d71ac1e master -> origin/master
> > > Updating 3fd2b88..d71ac1e
> > > error: Your local changes to the following files would be overwritten by merge:
> > > validation/data/fast/data/v_rdata_FastGroundTruthDataHistory.mat
> > > validation/setIsetbioUnitTestPreferencesTemplate.m
> > > Please, commit your changes or stash them before you can merge.
> > > Aborting
> > > fovea:isetbio (master) $
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > > 
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/55#issuecomment-122657810>.
> > 
> 
> David H. Brainard
> Professor of Psychology
> Director, Penn Vision Research Center
> Director, Institute for Research in Cognitive Science
> University of Pennsylvania
> 3401 Walnut Street, Suite 400A (mail address)
> 3401 Walnut Street, Room 315C (office location)
> Philadelphia, PA, 19104
> Phone: 215-573-7579
> Email: brainard@psych.upenn.edu
> Web: http://color.psych.upenn.edu/brainard
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/55#issuecomment-122680247>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by DavidBrainard** [comment]
Closing this issue, as I think we have reached at least temporary happiness.

**Comment by wandell** [comment]
I changed .gitignore so that the user can create a directory called local and store things there.
I put a file called validatePreferencesSet.m in that directory which contains the form of the Template that works for me (maybe).

I wonder if we should be putting the full validation data in there for people who download it.
