### ISSUE TITLE
ValidateCoreFast/Full

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#56]
I created a ValidateCoreFast and ValidateCoreFull that get their lists from ValidateListCoreValidationFiles.  But they don't quite work.  That's because I couldn't quite figure out the right cell array syntax to pass single files rather than directories to the validate code that is deep inside the UnitTestToolbox.  I tried to merge what was done by the All and One versions of the validations, but it didn't work.  Somehow the trailing two characters of the filename are being truncated in one place but not in others.

Nicolas I Imagine you can quickly find and fix what is going on and then close this issue.

I just picked three scripts to list in the core, to get things working and not because I thought they should be the current list.

**Comment by wandell** [comment]
Some silly thing.  Am in the middle of a cold spring harbor thing.  Can't debug.

------------------------------------------------------------------------------------------------------------
Running in 'FULL' mode with 'catchExceptionAndContinue' runtime hehavior and verbosity level = 'high'.
Will validate 3 scripts.
------------------------------------------------------------------------------------------------------------

[  1] 'v_Colorimet'
	Internal validation  : FAILED
	Run-time status      : exception raised
	Validation report    : exception raised (and caught) with message: Undefined function 'v_Colorimet' for input arguments of type 'double'.



[  2] 'v_HumanRetinalIlluminance580'
	Internal validation  : FAILED
	Run-time status      : exception raised
	Validation report    : exception raised (and caught) with message: Undefined function 'v_HumanRetinalIlluminance580' for input arguments of type 'double'.



[  3] 'v_OTFandPupilSi'
	Internal validation  : FAILED
	Run-time status      : exception raised
	Validation report    : exception raised (and caught) with message: Undefined function 'v_OTFandPupilSi' for input arguments of type 'double'.

**Comment by DavidBrainard** [comment]
Right.  This is the not working part of the core validation stuff that I mentioned in my post.  The core stuff almost works, but not quite.

I think Nicolas will be the one best positioned to fix this — it is related to conventions deep in the UnitTestToolbox that I don’t fully understand.

DB

**Comment by npcottaris** [comment]
Hello,

The only thing that was missing from David’s solution was the .m file extension in the vScriptsList, which I have now added.
All core validation stuff should  working now.

Sorry for being in radio silence but I am currently out of state.
Will resume normal activity in a few days.


N.
