### ISSUE TITLE
Storing full validation data

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#57]
There is now a copy of the full validation data set in ISETBIO/fullvalidation.  I have a sync script set up that I can run manually.  I tried to minimize the amount of dropbox bookkeeping stuff that comes over with it, but I didn't get that to zero.

If you set up your validation preferences so that you can read from that file tree as a mounted disk, you should be able to use it, which would be a good first step.  

It isn’t set up to use urlread, though.  That would require a much more flexible rdata routine that is then used from within the UnitTestToolbox.

**Comment by wandell** [comment]
Great.  It looks like there is about 200M of validation data up there, and by far the largest is in the scene directory.  I wonder if we should consider shrinking down the scene validation data (132M) and the valtemp data (39M).

We might consider writing a script that runs once (even if slow) that does a urlread to bring over the ground truth data and adjusts the UnitToolbox pointer to point to the ground truth data location.

**Comment by npcottaris** [comment]
I think we can totally eliminate the valtemp data. It was used early on to help debugging some validation issues between the Penn and the Stanford machines.

**Comment by DavidBrainard** [comment]
Closing.
