### ISSUE TITLE
validateFullAll recursion error - CompareCellArrays

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#59]
Sorry to keep pestering you with these things.  Some day I may learn how to debug it myself.

Anyway, I get this recursion error with running validateFastAll.  I can run the individual script which generates a very reasonable set of plots.

  6] 'v_DisplayLUTinversion'
	Internal validation  : PASSED
	Run-time status      : no exception raised
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users/wandell/Github/isetbio/validation/data/fast/display/v_DisplayLUTinversion_FastGroundTruthDataHistory.mat
	Fast validation      : PASSED against ground truth data of 16-Jul-2015 12:33:57.
	 > Ground truth info :             fovea.stanford.edu / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	 > Local host info   :                    Fovea.local / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	Data hash key        : 3dbd9fab5c1563a50db48d4d3b900ae8858a55f4594ffb34e59c93720235327c
	---------------------------------------------------------------------------------------------------------------------------------
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users/wandell/Github/isetbio/validation/data/full/display/v_DisplayLUTinversion_FullGroundTruthDataHistory.mat
Maximum recursion limit of 500 reached. Use set(0,'RecursionLimit',N) to change the limit. Be aware that exceeding
your available stack space can crash MATLAB and/or your computer.

Error in UnitTest/structsAreSimilar>CompareCellArrays

**Comment by DavidBrainard** [comment]
That is a real bug that is in Nicolas’ queue to fix.  It is my fault for not posting it as an issue and instead just emailing him about it.  At the time, we were the only ones with the full validation data, which is my lame excuse for being lazy. 

We’ll get this fixed soon.  

> On Jul 20, 2015, at 11:37 PM, Brian Wandell <notifications@github.com> wrote:
> 
> Sorry to keep pestering you with these things. Some day I may learn how to debug it myself.
> 
> Anyway, I get this recursion error with running validateFastAll. I can run the individual script which generates a very reasonable set of plots.
> 
> 6] 'v_DisplayLUTinversion'
> Internal validation : PASSED
> Run-time status : no exception raised
> Full validation file : contains 1 instance of historical data.
> Ground truth file : /Users/wandell/Github/isetbio/validation/data/fast/display/v_DisplayLUTinversion_FastGroundTruthDataHistory.mat
> Fast validation : PASSED against ground truth data of 16-Jul-2015 12:33:57.
> > Ground truth info : fovea.stanford.edu / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
> > Local host info : Fovea.local / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
> Data hash key : 3dbd9fab5c1563a50db48d4d3b900ae8858a55f4594ffb34e59c93720235327c
> ---------------------------------------------------------------------------------------------------------------------------------
> Full validation file : contains 1 instance of historical data.
> Ground truth file : /Users/wandell/Github/isetbio/validation/data/full/display/v_DisplayLUTinversion_FullGroundTruthDataHistory.mat
> Maximum recursion limit of 500 reached. Use set(0,'RecursionLimit',N) to change the limit. Be aware that exceeding
> your available stack space can crash MATLAB and/or your computer.
> 
> Error in UnitTest/structsAreSimilar>CompareCellArrays
> 
> —
> Reply to this email directly or view it on GitHub.
> 


=========
David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by npcottaris** [comment]
Hello all,

I have fixed the cell array comparison bug.
Git pull the UnitTestToolbox and re-run the validateFullAll.m script.

Best,
Nicolas

**Comment by npcottaris** [comment]
Ssuccessful validation on my computer (running Matlab 2014b) against ground truth generated by Wandell running Matlab 2013b.
Cool!

**Comment by npcottaris** [comment]
Please let me know if there are no more cell array comparison issues on your computers so I can close this issue.

**Comment by DavidBrainard** [comment]
OK here.  I was able to see that the reason the current validation data differ from the old are due to the change in isetbio’s display struct, and thus expected and not worrisome.  I generated new Full and Fast data, although I have not yet pushed the Full data to the Stanford server.

So yes, close.

Best,

David

> On Jul 21, 2015, at 4:40 PM, Nicolas Cottaris <notifications@github.com> wrote:
> 
> Please let me know if there are no more cell array comparison issues on your computers so I can close this issue.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/59#issuecomment-123471089>.
> 

David H. Brainard
Professor of Psychology
Director, Penn Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by npcottaris** [comment]
> On Jul 21, 2015, at 16:45, David Brainard <notifications@github.com> wrote:
> 
> OK here. I was able to see that the reason the current validation data differ from the old are due to the change in isetbio’s display struct, and thus expected and not worrisome.

Actually it was worrisome because before today's fix the cell array validation was failing even for data generated using the display structure.

Closing the issue.
