### ISSUE TITLE
Tutorials needed

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#6]
I spent some time writing documentation on the wiki this morning.  I think someone would now have a fighting chance to know what to do to get started.  I'm also sure more tuning would help.

We have tutorials called t_sceneIntroduction and t_oiIntroduction.  These and a tutorial that needs to be written (t_sensorIntroduction) seem like the obvious place for someone to start.  As the mood strikes, putting some effort into making the first two are really clean (they may be, I didn't look) and writing the third seem like a good idea.  

We can then think about t_pixelIntroduction, t_wavefrontIntroduction, t_displayIntroduction, etc.  I think a good goal is one introductory tutorial for each data structure that has its own gets and sets.

**Comment by npcottaris** [comment]
I'll work on these issues.
Nicolas

**Comment by DavidBrainard** [comment]
If you have time before 11:00, swing by and let’s look a little more at stimuli.

DB

> On Apr 1, 2015, at 10:04 AM, Nicolas Cottaris <notifications@github.com> wrote:
> 
> I'll work on these issues.
> Nicolas
> 
> > On Apr 1, 2015, at 08:58, David Brainard <notifications@github.com> wrote:
> > 
> > I spent some time writing documentation on the wiki this morning. I think someone would now have a fighting chance to know what to do to get started. I'm also sure more tuning would help.
> > 
> > We have tutorials called t_sceneIntroduction and t_oiIntroduction. These and a tutorial that needs to be written (t_sensorIntroduction) seem like the obvious place for someone to start. As the mood strikes, putting some effort into making the first two are really clean (they may be, I didn't look) and writing the third seem like a good idea.
> > 
> > We can then think about t_pixelIntroduction, t_wavefrontIntroduction, t_displayIntroduction, etc. I think a good goal is one introductory tutorial for each data structure that has its own gets and sets.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> > 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/6#issuecomment-88495516>.
> 


=========
David H. Brainard
RRL Professor of Psychology
Director, Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by wandell** [comment]
Can someone remind me:  Where should I be putting scripts (s_Mumble) that are currently in xNeedChecking after I have checked them?  Should I be opening up scripts/scene/s_scene<> or are we just putting them all in the single scripts/ directory?  Or are we planning to move them out of ISETBIO?  

I just checked s_sceneCCT.m and didn't know what to do with it.

Also, I am starting on a script called t_introduction.m that is based on t_introduction2ISET.m that I have.  It needs to be trimmed down to remove the parts of ISET that aren't in ISETBIO and expanded to add parts that are missing.  I hope to make a start on this over the next day or two.

**Comment by DavidBrainard** [comment]
My inclination is that one of three things should happen to scripts.

a) The script might be viewed as a first draft of a tutorial.  In that case it would be renamed t_XXX and moved to tutorials.

b) The script might be viewed as a first draft of a validation. In that case it would be renamed to v_XXX and moved into a subdir under validation/scripts with a name like xNeedsUnitTestStuffAdded, and then we can add the unit test stuff at some point and promote it to a validation.

c) The script might really be a project related script that belongs in a project repository outside of the isetbio distribution, in which case it would be moved out into wherever the project is.

This is because I have not been able to articulate for myself quite what the purpose of a script that isn't one of these three things is.  I am open to the idea that there should be a scripts directory in isetbio, but I'd like to understand the conceptual distinction between that and tutorials/validations.

If we do add a scripts directory, I would recommend adding the subdirectory structure to parallel the one now set up in code, tutorials, and validation/scripts.  We would also write something that autopublishes the scripts and add a wiki page that parallels the ones for tutorials and validations.

Maybe a good test for whether we should have a scripts directory is whether we can figure out what prose we would write on the wiki to explain how scripts differ from tutorials and validations.  One possibility is that they are examples but where we think we are never going to comment them to the extent we aspire to do for the tutorials, nor that they check anything that would cause us to make us turn them into validations.

**Comment by chichilnisky** [comment]
As with data, I like the idea of defining what the these directories are *supposed to* house.

Question: do we really need to name things t_XXX given that it's already in tutorials?  Seems redundant.

ej

**Comment by DavidBrainard** [comment]
Typing t_ at the Matlab command prompt autocompletes to a list of all available tutorials.  Similarly with v_.

**Comment by wandell** [comment]
Closing. I think we are all aware of the question of tutorials and validations.
