### ISSUE TITLE
Validation for v_sceneFromRGB now failing

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#60]
Error output pasted below at the end of this issue.

It looks like Brian committed new Fast validation data for this.  There may also be new Full validation data on the Stanford server, can't look just now.  The script still passes against the Full validation file I have on this end, but that would not be touched by a git pull.

This may be related to the change Haomiao posted about earlier today, or to something else.

Was the update in Fast validation intentional?

This is all a little mysterious since if it were updated, I'd think it would still work with an up to date toolbox.  

We tried to make it hard to update validation files by accident.  By default things are set up so you have to go and delete an old validation file manually before a new one is created.  I think that can be overridden in the preferences, but I don't recommend doing so.

Anyone have any insight as to what is happening with this one?

*****

[ 14] 'v_sceneFromRGB'
	Internal validation  : PASSED
	Run-time status      : no exception raised
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users/Shared/Matlab/Toolboxes/isetbio/validation/data/fast/scene/v_sceneFromRGB_FastGroundTruthDataHistory.mat
	Fast validation      : FAILED against ground truth data of 16-Jul-2015 12:34:17.
	 > Ground truth info :             fovea.stanford.edu / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	 > Local host info   :            ray.PSYCH.UPENN.EDU / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'dhb'
	DataHash-this run    : abc8d0d6d7397cdd9bc6b988e94b4065eb79d83d5b71c54c69c1a239615061d6
	DataHash-groundTruth : 786913d412277c5b1b93eeb8f3cc77e0e969f1a9806bbc138cf04a606a2f9227
	---------------------------------------------------------------------------------------------------------------------------------
	Full validation file : contains 1 instance of historical data.
	Ground truth  file   : /Users1/Shared/Dropbox/ISETBIOFullValidationData/scene/v_sceneFromRGB_FullGroundTruthDataHistory.mat
	Full validation      : PASSED against ground truth data of 05-Feb-2015 14:12:39.
	 > Ground truth info : wal-isc-video012.isc-video.upenn.edu / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'nicolas'
	 > Local host info   :            ray.PSYCH.UPENN.EDU / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'dhb'
	Note (*)             : script does not store any extra data.
	Validation report    : Hand check of h fov is within the specified tolerance (1e-12) of zero.

**Comment by DavidBrainard** [comment]
I regenerated the FAST data, which not surprisingly makes this run fine on my machine.  Since the script passed against the dropbox copy of the FULL validation data, I think this was just some glitch in what got written on Brian's end.

If this problem reappears, we will investigate more deeply.  I think the first symptom would be that FAST validation fails on Brian's machine.

Closing this issue

**Comment by wandell** [comment]
I don't really mean to reopen ... I do want to keep this note here, though.

When I run I get a request about v_rdata, asking me if I want to get the ground truth data from the ISETBIO team.  I click that I will email them some day for it, and move on.

Also, I still get the error below, which is a hash error but not a 'numerical' error.

So, in summary, there are a couple of little things.  If we scale to more people we will have to deal with them.  For now, let's produce more content and get ready for the workshop.  So, am adding this comment and closing.

[ 14] 'v_sceneFromRGB'
	Internal validation  : PASSED
	Run-time status      : no exception raised
	Fast validation      : FAILED against ground truth data of 23-Jul-2015 09:21:57.
	 > Ground truth info : wal-apn.339.wlan.wireless-pennnet.upenn.edu / MACI64, MATLAB 8.4.0.150421 (R2014b) by 'dhb'
	 > Local host info   :                    Fovea.local / MACI64, MATLAB 8.2.0.701 (R2013b) by 'wandell'
	DataHash-this run    : 786913d412277c5b1b93eeb8f3cc77e0e969f1a9806bbc138cf04a606a2f9227
	DataHash-groundTruth : abc8d0d6d7397cdd9bc6b988e94b4065eb79d83d5b71c54c69c1a239615061d6
	Validation report    : Hand check of h fov is within the specified tolerance (1e-12) of zero.

**Comment by npcottaris** [comment]
Brian,

For me to debug this one, it would be helpful if you generated Full validation data for this script on your machine and then send it to me so I can investigate where the discrepancy is.

Thanks,
Nicolas
