### ISSUE TITLE
v_sceneFromRGB validation woes.

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#62]
Apparently we still have FAST validation issues between one of Brian's machine and the Penn machines, for v_sceneFromRGB.  You all may recall that this script presented difficulties originally, and then we managed to fix things so that they were OK.  But they appear to have come back, from Brian's most recent post.

Brian, where do you point for your FULL validation?  Are you using the dropbox folder we set up, the version on scarlet/crimson, or something else.

I did update the scarlet/crimson version this morning, as well as the dropbox version.

I would be interested to know whether your FULL validation also fails for v_sceneFromRGB, or if it is just something about the hash.

Finally, the fact that it asks you about validation data for v_rdata suggests that somehow you are not pointed at current versions, as I am pretty sure those validation files exist in both the current FAST and FULL sets.

**Comment by npcottaris** [comment]
Brian,

For me to debug this one, it would be helpful if you generated Full validation data for this script on your machine and then send it to me so I can investigate where the discrepancy is.

Thanks,
Nicolas

**Comment by wandell** [comment]
I will try on this validation and the oiWindow business, which sounds familiar and really bad.

But I have three days of holiday in Berlin just now and I won't get to this until next week.  And HJ might already know the answer.  But I can start about next Wednesday.

B


Stanford

**Comment by npcottaris** [comment]
Has the Penn-Stanford issue with v_sceneFromRGB been eliminated with the merge of the valid branch?
If so we should close this as well.

**Comment by wandell** [comment]
From my point of view, the differences are not important at this time.  A agree, and let's close this issue.  The next question is really about checking the ground truth data set and making sure I know how to properly use it.  Onward!
