### ISSUE TITLE
microsaccades in emGenSequence

### ISSUE THREAD

**Issue by xnieamo** [isetbio/isetbio#63]
In emGenSequence, when the emFlag is set so that tremor and drift are both disabled and only microsaccades are enabled, the position sequence generated is fixed at 0,0.  I was wondering if this is the intended behavior of the microsaccades?

**Comment by hjiang36** [comment]
In current code, microsaccade drag the eye position back to origin with some error. When the eye is already at origin, microsaccade does nothing (see emGenSequence line 110).

This is just based on some vague description and my inference about microsaccde. If we find literature describing exact microsaccade pattern, I would like to change it.

**Comment by DavidBrainard** [comment]
OK, so the idea is that if there were no tremor and no drive, the eye would just stay right where it was supposed to be and there would be no corrective microsaccades.  This seems as sensible as anything unless there is data that contradicts it.  

Closing this issue for now.
