### ISSUE TITLE
Question about scene illuminant units

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#64]
In an isetbio scene, is the convention that the scene illuminant is specified as spectral irradiance (i.e. in units of power/[m2-nm] or as spectral radiance (power/[m2-sr-nm]).

The former is physically more accurate, I believe.

But the latter is what you'd measure if you put a perfect diffuser in a scene and pointed a radiometer at it.  And the latter has the feature that to get the radiance reflected from a diffuse surface, you just multiply the illuminant value by the diffuse reflectance.  (With the former, you'd need divide by the 2pi radians in a hemisphere.)

Either is fine with me, I'd just like to know.

**Comment by wandell** [comment]
Here is my thinking. More vague than I like …

We store two numbers - the scene spectral radiance in q/s/sr/nm/m2 = power/[sr-nm-m2], and the illuminant.  These only come together at this point with the idea that the scene spectral radiance divided by the illuminant is the surface reflectance.

Now, if we believe the surface reflectance is a truly dimensionless quantity, it must be the case that the illuminant has the same units as the scene radiance.

But, perhaps we should think that the reflectance is directional (not Lambertian); the reflectance may be the fraction of the light scattered in the direction of the camera, and its implicit unit is therefore 1/sr.  In that case we should be thinking of the illuminant as

reflectance units = q/s/sr/nm/m2 / (illuminant units) = 1/sr

In that case illuminant units = q/s/nm/m2 = power/[m2-nm] as you prefer.

All of this is consistent with your description of the use of a perfect diffuser (I think).

I do not think we have committed, though I can’t tell you why I think that.  I see that we need to agree on this for the RenderToolbox and PBRT calculations to be physically accurate, particularly as the illuminant, camera, and surfaces change their orientations.  Up to now, we really haven’t had any geometry of the objects embedded in the representation, so this ended up being unspecified.


On Jul 28, 2015, at 9:56 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:


In an isetbio scene, is the convention that the scene illuminant is specified as spectral irradiance (i.e. in units of power/[m2-nm] or as spectral radiance (power/[m2-sr-nm]).

The former is physically more accurate, I believe.

But the latter is what you'd measure if you put a perfect diffuser in a scene and pointed a radiometer at it. And the latter has the feature that to get the radiance reflected from a diffuse surface, you just multiply the illuminant value by the diffuse reflectance. (With the former, you'd need divide by the 2pi radians in a hemisphere.)

Either is fine with me, I'd just like to know.

—
Reply to this email directly or view it on GitHub<https://github.com/isetbio/isetbio/issues/64>.

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by DavidBrainard** [comment]
Thanks.  This is what I thought we were doing.  I agree we might think about this a bit as we move towards considering scenes with 3D structure.   With renderers, illuminants are specified as radiant power (for point sources) and irradiance (for area sources) and the renderers then correctly handle the geometry.

How to handle this for the flat matte scenes currently conceptualized within ISETBIO is a good question.  Let’s make this something we talk through this August when we’re together.

> On Jul 29, 2015, at 2:00 AM, Brian Wandell <notifications@github.com> wrote:
> 
> Here is my thinking. More vague than I like … 
> 
> We store two numbers - the scene spectral radiance in q/s/sr/nm/m2 = power/[sr-nm-m2], and the illuminant. These only come together at this point with the idea that the scene spectral radiance divided by the illuminant is the surface reflectance. 
> 
> Now, if we believe the surface reflectance is a truly dimensionless quantity, it must be the case that the illuminant has the same units as the scene radiance. 
> 
> But, perhaps we should think that the reflectance is directional (not Lambertian); the reflectance may be the fraction of the light scattered in the direction of the camera, and its implicit unit is therefore 1/sr. In that case we should be thinking of the illuminant as 
> 
> reflectance units = q/s/sr/nm/m2 / (illuminant units) = 1/sr 
> 
> In that case illuminant units = q/s/nm/m2 = power/[m2-nm] as you prefer. 
> 
> All of this is consistent with your description of the use of a perfect diffuser (I think). 
> 
> I do not think we have committed, though I can’t tell you why I think that. I see that we need to agree on this for the RenderToolbox and PBRT calculations to be physically accurate, particularly as the illuminant, camera, and surfaces change their orientations. Up to now, we really haven’t had any geometry of the objects embedded in the representation, so this ended up being unspecified. 
> 
> 
> On Jul 28, 2015, at 9:56 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote: 
> 
> 
> In an isetbio scene, is the convention that the scene illuminant is specified as spectral irradiance (i.e. in units of power/[m2-nm] or as spectral radiance (power/[m2-sr-nm]). 
> 
> The former is physically more accurate, I believe. 
> 
> But the latter is what you'd measure if you put a perfect diffuser in a scene and pointed a radiometer at it. And the latter has the feature that to get the radiance reflected from a diffuse surface, you just multiply the illuminant value by the diffuse reflectance. (With the former, you'd need divide by the 2pi radians in a hemisphere.) 
> 
> Either is fine with me, I'd just like to know. 
> 
> — 
> Reply to this email directly or view it on GitHub<https://github.com/isetbio/isetbio/issues/64>. 
> 
> _____________________________________ 
> Brian A. Wandell 
> Stein Family Professor 
> Cognitive and Neurobiological Imaging (CNI) 
> Psychology Department 
> Phone: 1-650-725-2466 
> http://www.stanford.edu/~wandell 
> 
> 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/64#issuecomment-125851325>.
> 

David H. Brainard
Professor of Psychology
Director, Penn Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard
