### ISSUE TITLE
Can we deleted the valid branch?

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#69]
Can we delete the valid branch?  And if we can, please do it and close this issue.

**Comment by wandell** [comment]
I think so.

On Aug 3, 2015, at 1:23 PM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:


—
Reply to this email directly or view it on GitHub<https://github.com/isetbio/isetbio/issues/69>.

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell

**Comment by npcottaris** [comment]
The valid branch was merged onto the master branch by me on 7/30 and nothing has been done to it since then.
I think it can be deleted.

Brian?

**Comment by DavidBrainard** [comment]
Deleted branch and closing.

**Comment by npcottaris** [comment]
valid branch is now deleted.
