### ISSUE TITLE
Getting data to the right place

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#7]
I think we should move isettools/data -> data.  This requires fixing up the functions that know how to load that data so they look in the correct place.  Then we can make my dreams come true by renaming "isettools" to "code" without breaking anything.

When we do this, it would be a good moment to think about how we want to handle big data that is stored elsewhere (I guess, on the Stanford server).  Probably we want some preferences that say where to look for data, and some search order.  The default should be to look in the data folder with the distribution.

I don't think every last detail needs to be worked out before moving the data dir, but thinking about the long range plan when looking through this, and getting the data read/write routines well factorized as a starting point, seems clever.

**Comment by wandell** [comment]
Good.

We have a good tool for getting data in Matlab from a web server.  Simple.

We have a server.  Will spend time organizing some data sets today.

Agree about using setprefs.  Will draft something and check back with you and Nicolas.  Am doing this on MRI side of lab first.  But will try to make it appropriate for ISETBIO too.

Also, I agree about eliminating scripts.

B

Stanford

**Comment by chichilnisky** [comment]
A related question is defining what this data directory is supposed to house once ISETBIO is installed on a user's machine.

Just validation data?  Script sample data?  Data that the user hauls and works on when they want to do a calculation?

ej

**Comment by wandell** [comment]
No longer relevant. Closing.
