### ISSUE TITLE
 v_rdata currently fails

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#71]
>> v_rdata
Error using rdata/set (line 134)
Unknown parameter cd

Error in rdata (line 73)
            obj.set(varargin{ii},varargin{ii+1});

**Comment by DavidBrainard** [comment]
I commented out the line that includes the 'data' directory in the list of full validations run, until this is working again. And I guess it is possible that this should move into the validations for the RemoteDataToolbox.

**Comment by wandell** [comment]
Last night I wrote ieRdata, which is a gateway to the rdata class, but specialized for ISETBIO.  Maybe this function should be a subclass of rdata.  Not sure what I just said.

Anyway, my point is that we can rewrite v_rdata with the tests in the comment fields in the header documentation of ieRdata.  I will try to figure out how to do that, or please go for it.

Brian

Stanford

**Comment by wandell** [comment]
I think HJ and patched up rdata and ieRdata, reinserted the test in validateFastAll, and so onward.  Am closing this.

**Comment by DavidBrainard** [comment]
Hmm.

v_rdata still fails on my machine, after a pull of both isetbio and the RemoteDataToolbox.  Error message pasted below.  Is it possible something didn't get pushed?

K>> v_rdata
Error using rdata.listFiles
Too many output arguments.

Error in ieRdata (line 43)
        val = rd.listFiles(varargin{1});

Error in v_rdata>ValidationFunction (line 31)
val =  ieRdata('dir',rd,'Stryer');

Error in UnitTest.runValidationRun (line 33)
    functionHandle(runTimeParams);

Error in v_rdata (line 12)
varargout = UnitTest.runValidationRun(@ValidationFunction, nargout, varargin);

**Comment by DavidBrainard** [comment]
FALSE ALARM.  It was a stale path issue.  Now it works.  I updated the validation data for this, since the file was for an older version.

DB
