### ISSUE TITLE
Parameter 'k' in the RiekeLinearCone not set in coneAdapt

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#76]
There are some recent changes in the params passed to `RiekeLinearCone`.
When calling `RiekeLinearCone` from `coneAdapt,` the `k` field of  `initialState`  is not set.
What should the default value for this field be?

Nicolas

**Comment by npcottaris** [comment]
There are two additional fields of initialState (`gdark` and `h`) that are not set in `codeAdapt` and which do not have default values in `RiekeLinearCone`.

N.

**Comment by fmrieke** [comment]
Those should be set in riekeInit - and I think a goal would be to migrate all the model parameters into riekeInit (and call it something else probably) so they are all easy to find.  

Fred

**Comment by DavidBrainard** [comment]
Just an aside. The plan is to migrate all this stuff into the outer segment object and get rid of the separate riekeX code.  We’re just pushing hard right now to get stuff to show at the workshop.

DB

**Comment by xnieamo** [comment]
Also in ```coneAdapt```, the linear case uses a field in params called ```Compress```, but there is no default value for this.

**Comment by fmrieke** [comment]
I think I was setting that always in my own code.  If you set it to 0 it will be purely linear (if it is 1 it will add a static nonlinearity to the cone currents to capture some of the effects of saturation of the cone signals).

Fred

**Comment by xnieamo** [comment]
Ok, I've added a line of code in ```coneAdapt``` that's sets ```Compress``` to 0 if it is not specified.  We can change this behavior to 1 later if we want.

**Comment by npcottaris** [comment]
OK. That was very helpful.

Thanks.
