### ISSUE TITLE
Overhauled riekeLinearCone to reduce memory footprint and increase execution speed

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#78]
Overhauled riekeLinearCone to reduce memory footprint and increase execution speed.

1. The temporal filter was defined with a time support equal to the length of the signal. This is unnecessary for long signals (such as the signals produced in our hyperspectral images project which have lengths of the order of a couple of million points). Morover for signals less than 0.3 seconds (approx the length of the temporal filter employed) this would result in truncated filters. This correction yields speed improvements of the order of at least 30-50 times for our project and vastly reduces memory paging.

2. I also prealocated the memory to store the adapted responses and made a special case for photon rate matrices that are 2D - XT (vs. 3D XYT) where cone signals are serialized in first dimension.

**Comment by fmrieke** [comment]
Awesome - thanks.  Apologies in advance for inundating you all with code in need of overhaul (and for my git learning curve).

Fred

**Comment by npcottaris** [comment]
No problem. I feels really good to accelerate some crucial piece of code.
