### ISSUE TITLE
ValidateFullOne, ValidateFullAndPublishOne

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#8]
I would like two more top level validation scripts, as indicated in the issue title.  These should each list all of the validations and ask the user which one of them to run.

This would be very useful when developing/debugging a new validation scrip, so that you could develop and publish without having to run all the scripts. 

If it is hard to publish just one, I'd settle for ValidateFullOne.  But sometimes it requires some fussing to get the published version of a script to look right, so it would be nice to be able to iterate on fixing without having to do them all.

What I can imagine might be hard is to rewrite the wiki page with just one, especially if it wasn't there before.  So I would also be happy if ValidateFullAndPublishOne said it couldn't publish unless the script had already been published at least once, but would update the html published version so that one could refine.

**Comment by DavidBrainard** [comment]
Related to this, both Full and Fast ground truth data should always be generated together.  That is, they should always correspond to the same run of the script.  This does not appear to be the case currently.

a) I deleted the Full data for one of the display validation scripts, and then ran the full validations.  I was properly prompted as to whether I wanted to regenerate the full validation data, and said yes.

b) On a re-run, the full validation passed but the Fast validation failed.  This is because the Fast validation was not updated when the Full was.

Similarly, if Fast is regenerated, so should Full be.  That is, it should always be both or neither that get updated.

**Comment by npcottaris** [comment]
We now have two top-level validation scripts.
- validateFullAndPublishOne
- validateFullOne

Both scripts present the user with a list of all the available validation scripts (as specified in the validateListAllValidationDirs() script). The user is prompted to select  one script and this script ALONE is validated fully. If it passes the validation, this file's wiki publication is updated. The corresponding entry in the ValidationResults catalog is also updated with information about who did this validation, when and where. Every time you run a validateFullAndPublishOne run you get an additional informational entry on that scripts'  position showing when the script was run, by whom and where. To get rid of all accumulated infos, you can do a validateFullAndPublishAll once you have optimized your script.

If the script was not previously run, a new entry is generated as well.

**Comment by npcottaris** [comment]
Regarding David's comment: "Related to this, both Full and Fast ground truth data should always be generated together. That is, they should always correspond to the same run of the script. This does not appear to be the case currently."

This is surprising. I just did the same exercise with a codedev script and both Fast and Full validation data sets were generated at the same time. Which script did you test with?

**Comment by DavidBrainard** [comment]
Tested this.  The two validateOne... scripts seem to work fine. Very useful.

Still need PublishOneTutorial.  

And still need the validate scripts to generate both FULL and FAST data when they generate either one of the two.  As is, you need to delete both FULL and FAST to force a regeneration of both.

**Comment by npcottaris** [comment]
We now have PublishOneTutorial, in addition to PublishAllTutorials. As with ValidateFullOne, the user is presented with an enumerated list of all available tutorials, and he chooses to publish one of them.
To use, git pull on both the UnitTestToolbox and isetbio repositories.

**Comment by npcottaris** [comment]
Full and Fast ground truth data are now generated together. 
All requests in this thread are now addressed, so I am closing this issue.
