### ISSUE TITLE
riekeAddNoise and cone learning

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#80]
Dear colleagues,

Although this issue is not strictly an isetbio issue, I am posting it here so it can reach all of you.

I have run into an issue with our isetbio framework for cone learning, so I am asking for your input.
Our cone learning approach, which learns the types and spatial positions of cones in a cone mosaic,  is based on multi-dimensional scaling of a distance metric computed from correlations of cone responses to multispectral images.

Our isetbio simulations so far have shown that cone types and their spatial positions can both be recovered when the cone response is taken to be either one of the following:
- the photon absorption rate signal
- the adapted photocurrent signal (at least in the linear case, which is just a temporal filtering of the cone absrorption rate)

However, the same simulations show that cone learning fails when the cone response is taken to be the output of riekeAddNoise, i.e., the noisy cone membrane current.

This failure is gradual and depends on the magnitude of the noise added:
1) When the added noise has the amplitude specified by riekeAddNoise, cone identifation fails completely.  Moreover if one looks at the identification performance as a function of stimulus presentation, in the beginning cones are identified to some degree, but as more stimuli are presented cone identification becomes progressively worse. This is to be contrasted with the noise-free simulations in which cone identification becomes progressively better as more stimuli are presented.

2) When the Rieke noise is reduced to 30% of the original amplitude, we begin to get decent cone type/position identification (except for the position of S-cones which are all over the place), and at 10% we get closer to the noise-free simulations.

I have also conducted simulations that include a temporal filter applied to the noisy photocurrent. In these simulation I used two different temporal filters. First, a biphasic filter that matches typical impulse response functions of RGCs (from E.J.'s 2002 paper on assymetries between ON-OFF RGCs) and second, a monophasic filter, which is reminiscent of the impulse response function of V1 cone-opponent monophasic cells (from my own V1 recordings).

Simulations using the biphasic filter resulted in failed cone identification, whereas simulations using the monophasic filter resulted in good cone identification, with the exception of S-cone positions. But the failure to identify S-cone positions is not suprising given the signal/noise ratio of the S-cone photocurrents.

Below are three questions on which it would be great to get your feedback.

1) Is the noise amplitude computed by riekeAddNoise too large? 

2) Is the cone photon absorption signal computed by coneAbsorptions too small?
I am using a human sensor with coneIntegrationTime = 0.050 and cone aperture = 3 microns.
The eye movements consist of 100-200 msec long fixations sampled every 1 msec.
The natural scenes I am using have a range of luminances, but I normalize cone absorptions to all scenes with respect to those in the first scene, whose brigthest region has a luminance ~ 4000 cd/m2 and a corresponding retinal illuminance of ~ 60 lux. So the input signal is not weak. 

3) Perhaps cone identification is really impossible based on the noisy photocurrent and a post-receptoral monophasic temporal filter is needed to significantly increase the signal/noise ratio. Of course, the problem might re-arise when the second stage is also subjected to noise, but if the mangitude of this noise is low we should be OK as the cone identification algorithm performs OK under low noise condictions. Does anyone have suggestions for filter/noise parameters for the bipolar cell IR?

I am attaching 2 figures showing the computed cone absorption, cone Vm, cone current, and filtered cone current signals for an L-, M- and S-cone (shown in red, green and blue, respectively). The two figures differ only in the post-receptoral filter (monophasic vs biphasic - plotted in black in the inset of the 4-th panel). From these figures, it becomes apparent that the reason that cone identification succeeds with the monophasic (V1-like) post-receptoral filtering is because it results in signals that resemble the cone absorption signals whereas the biphasic (RGC-like) filter fails to do so. 

Best,
Nicolas

![conesignals_biphasicir](https://cloud.githubusercontent.com/assets/3444212/9552558/0e0c7988-4d87-11e5-869e-918e7c321714.png)
![conesignals_monophasicir](https://cloud.githubusercontent.com/assets/3444212/9552559/0e16b182-4d87-11e5-81c1-f5ffae15224a.png)

**Comment by DavidBrainard** [comment]
One thing we ought to double check in the code is what happens when you specify a 50 msec cone integration time with 1 ms eye position sampling.  For static images, we simply multiply the isomerization rate by the integration time.  I haven’t looked at the code, but it seems possible that when the eye is moving and we’re sampling every millisecond that the time varying isomerization rate and cone integration time are not handled properly.  If, for example, the 1 msec number overrides the 50 msec number, that could cause the cone responses to be too noisy.

The fact that one can filter the output and recover stable learning says that sufficient information remains in the the signals available in the photocurrent, but that some ways of accumulating the correlation matrix are better than others.  A good thing to think about in any case would be how to do this in a more realistic way.

DB

**Comment by npcottaris** [comment]
Here is the relevant code, in case I am doing something wrong.

~~~
% Generate custom sensor for human retina
sensor = sensorCreate('human');

% Generate custom cones
pixel = sensorGet(sensor,'pixel');
pixel = pixelSet(pixel, 'size', [1.0 1.0]*coneAperture);
sensor  = sensorSet(sensor, 'pixel', pixel);
        
% Generate custom cone mosaic
coneMosaic = coneCreate();
coneMosaic = coneSet(coneMosaic, 'spatial density', [0.0 LMSdensities(1) LMSdensities(2) LMSdensities(3)]);

sensor = sensorCreateConeMosaic(sensor,coneMosaic);
                
% Set the sensor size
sensor = sensorSet(sensor, 'size', round(sensorParams.conesAcross*[sensorParams.heightToWidthRatio 1.0]));

% Set the sensor wavelength sampling to that of the opticalimage
sensor = sensorSet(sensor, 'wavelength', oiGet(opticalImage, 'wavelength'));

% Set the integration time
sensor = sensorSet(sensor,'exp time', 0.050);

% The eye movement part
eyeMovement = emCreate();
           
% Set the eye movement sample time
eyeMovement  = emSet(eyeMovement, 'sample time', 0.001);

% Attach eyemovement to the sensor
sensor = sensorSet(sensor,'eyemove', eyeMovement);

% Generate micro-movements (these do not include saccadic eye movements)
sensor = sensorSet(sensor,'positions', zeros(eyeMovementsNum,2);
sensor = emGenSequence(sensor);

% Add the saccadic eye movement component
saccadicXpos = ..
saccadicXpos = ..

sensorPositions = sensorGet(sensor,'positions');
for saccadicIndex = 1:numel(saccadicXpos)
    i1 = (saccadicIndex-1)*eyeMovementParams.samplesPerFixation + 1;
    i2 = i1 + eyeMovementParams.samplesPerFixation - 1;
    sensorPositions(i1:i2,1) = sensorPositions(i1:i2,1) + saccadicXpos(saccadicIndex) * fx;
    sensorPositions(i1:i2,2) = sensorPositions(i1:i2,2) + saccadicYpos(saccadicIndex) * fx;
 end

% Update the sensor positions to include the saccadic component
sensor = sensorSet(sensor,'positions', sensorPositions);

% Compute the activation of the cone mosaic
sensor = sensorSet(sensor, 'noise flag', sensorParams.noiseFlag);
sensor = coneAbsorptions(sensor, opticalImage);
sensorActivation = sensorGet(sensor, 'volts');

% Compute the corresponding photon rate
sensorConversionGain = pixelGet(sensorGet(sensor,'pixel'),'conversionGain');
sensorExposureTime   = sensorGet(sensor,'exposure time');   
photonRate = sensorActivation/sensorConversionGain/sensorExposureTime;

% Compute photocurrent (noise-free)
initialState = riekeInit;
initialState.timeInterval = sensorGet(sensor, 'time interval');
initialState.Compress = false;
photocurrent = riekeLinearCone(photonRate, initialState);

% Add noise
params.seed = 349573409;
params.sampTime = sensorGet(sensor, 'time interval');
noisyPhotocurrent = riekeAddNoise(photocurrent, params);
~~~

**Comment by npcottaris** [comment]
Here is the relevant code, in case I am doing something wrong.

% Generate custom sensor for human retina
sensor = sensorCreate('human');

% Generate custom cones
pixel = sensorGet(sensor,'pixel');
pixel = pixelSet(pixel, 'size', [1.0 1.0]*coneAperture);
sensor  = sensorSet(sensor, 'pixel', pixel);

% Generate custom cone mosaic
coneMosaic = coneCreate();
coneMosaic = coneSet(coneMosaic, 'spatial density', [0.0 LMSdensities(1) LMSdensities(2) LMSdensities(3)]);

sensor = sensorCreateConeMosaic(sensor,coneMosaic);

% Set the sensor size
sensor = sensorSet(sensor, 'size', round(sensorParams.conesAcross*[sensorParams.heightToWidthRatio 1.0]));

% Set the sensor wavelength sampling to that of the opticalimage
sensor = sensorSet(sensor, 'wavelength', oiGet(opticalImage, 'wavelength'));

% Set the integration time
sensor = sensorSet(sensor,'exp time', 0.050);

% The eye movement part
eyeMovement = emCreate();

% Set the eye movement sample time
eyeMovement  = emSet(eyeMovement, 'sample time', 0.001);

% Attach eyemovement to the sensor
sensor = sensorSet(sensor,'eyemove', eyeMovement);

% Generate micro-movements (these do not include saccadic eye movements)
sensor = sensorSet(sensor,'positions', zeros(eyeMovementsNum,2);
sensor = emGenSequence(sensor);

% Add the saccadic eye movement component
saccadicXpos = ..
saccadicXpos = ..

sensorPositions = sensorGet(sensor,'positions');
for saccadicIndex = 1:numel(saccadicXpos)
    i1 = (saccadicIndex-1)*eyeMovementParams.samplesPerFixation + 1;
    i2 = i1 + eyeMovementParams.samplesPerFixation - 1;
    sensorPositions(i1:i2,1) = sensorPositions(i1:i2,1) + saccadicXpos(saccadicIndex) * fx;
    sensorPositions(i1:i2,2) = sensorPositions(i1:i2,2) + saccadicYpos(saccadicIndex) * fx;
 end

% Update the sensor positions to include the saccadic component
sensor = sensorSet(sensor,'positions', sensorPositions);

% Compute the activation of the cone mosaic
sensor = sensorSet(sensor, 'noise flag', sensorParams.noiseFlag);
sensor = coneAbsorptions(sensor, opticalImage);
sensorActivation = sensorGet(sensor, 'volts');

% Compute the corresponding photon rate
sensorConversionGain = pixelGet(sensorGet(sensor,'pixel'),'conversionGain');
sensorExposureTime   = sensorGet(sensor,'exposure time');   
photonRate = sensorActivation/sensorConversionGain/sensorExposureTime;

% Compute photocurrent (noise-free)
initialState = riekeInit;
initialState.timeInterval = sensorGet(sensor, 'time interval');
initialState.Compress = false;
photocurrent = riekeLinearCone(photonRate, initialState);

% Add noise
params.seed = 349573409;
params.sampTime = sensorGet(sensor, 'time interval');
noisyPhotocurrent = riekeAddNoise(photocurrent, params);
In the above code, the returned  sensorConversionGain is 1.0000e-05. Can this be too low?

Best,
Nicolas

**Comment by fmrieke** [comment]
I will add a bit to the cone validation script to check the power spectrum of the noise and compare it with the target fit to experimental data.

Fred

**Comment by fmrieke** [comment]
I added a check on this at the end of s_coneModelValidate (which seems to work in current version).  Let me know if it helps (or not)!

Fred

**Comment by DavidBrainard** [comment]
This issue is generally related to the question of whether our photocurrent code is accurate in terms of gain and noise.  There are other issues on this already, so I'm closing this one.
