### ISSUE TITLE
oiCreate - default ...

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#81]
HJ and I would like to change the default of oiCreate to be oiCreate('human').  The default was 'diffraction limited'.  We think for the ISETBIO case 'human' is preferred.  Let us know if this is a problem.  On my laptop we made the change and also edited the few validation scripts that needed to be fixed.

I will wait a day or so and if there are no objections, we will push the change.  

Thanks,
BW/HJ

**Comment by wandell** [comment]
Same comment, but for sensorCreate('human')

**Comment by DavidBrainard** [comment]
I think it is OK to change these default, particularly if you fix any validations so they still do what they used to.

I know there are cases in the wavefront code where the default coefficients correspond to diffraction limited, and where this fact is used in validations/tutorials, but that won't be affected by these changes.

**Comment by DavidBrainard** [comment]
I was looking through t_introduction with Johannes over the weekend, and there are calls to oiCreate with no args.  The comments say it creates diffraction limited.

So I think we need to go through carefully and check for instances where this is called and fix them up.

Maybe we should think a little about how much we like the idea of defaults, or whether we should move towards explicitly requiring that a type be passed.  Sometimes defaults are very good (e.g., being able to call oiCreate('human') and have it do something reasonable is nice, even if that behavior later changes), but sometimes it can be hard to track the consequences of changing those defaults in existing code.

**Comment by chichilnisky** [comment]
Without knowing the details, I’ll add:

I think having a tree of default parameters accompanying the specification ‘human’ is very different from having global defaults.  The ‘human’ spec makes sense to me, it has meaning.  But I think it’s right to try to avoid global defaults whenever possible.

ej


On Sep 9, 2015, at 8:12 AM, David Brainard <notifications@github.com<mailto:notifications@github.com>> wrote:


I was looking through t_introduction with Johannes over the weekend, and there are calls to oiCreate with no args. The comments say it creates diffraction limited.

So I think we need to go through carefully and check for instances where this is called and fix them up.

Maybe we should think a little about how much we like the idea of defaults, or whether we should move towards explicitly requiring that a type be passed. Sometimes defaults are very good (e.g., being able to call oiCreate('human') and have it do something reasonable is nice, even if that behavior later changes), but sometimes it can be hard to track the consequences of changing those defaults in existing code.

**Comment by wandell** [comment]
Yes, in ISET the default was diffraction limited.  There may be a few places where we need to catch this.  In ISETBIO we probably never use diffraction limited as the default intentionally.

Maybe when it is unspecified we should announce what we are doing with an fprintf.
