### ISSUE TITLE
outersegment branch merged into master

### ISSUE THREAD

**Issue by jamesgolden1** [isetbio/isetbio#85]
Haomiao and I merged the outersegment branch into master. Please let me know if anything goes wrong. We think it is a good idea to keep the outersegment branch around until everyone is happy that it is working properly.

A basic tutorial is available in t_OuterSegmentClasses.m, and temporary validation against coneAdapt.m is available in v_osLinearObjectTemp.m and v_osBioPhysObjectTemp.m. 

All of the rieke* functions have been changed to os*, with the rest of the function name being unchanged. That means riekeAddNoise is now osAddNoise, etc. 

I have removed the calls to sensorGet(sensor, 'photon rate') and replaced them with sensorGet(sensor, 'photons'), but this is at odds with the latest version of coneAdapt that used 

 sensorGet(sensor, 'volts') / (sensorGet(sensor,'conversion gain')*expTime);

which yields the same vector as sensorGet(sensor, 'photon rate'). This can easily be changed.

Finally, when coneAdapt is executed, a warning is printed that mentions the imminent deprecation and the tutorial and validation scripts for the osLinear and osBioPhys subclasses.

**Comment by chichilnisky** [comment]
I have a comment/request on names.

coneAdapt() isn’t a good name for a function that computes the cone response time course.  Adaptation is only a part of what it does.  This name suggests something very different than what the function does.  I suggest coneResponse or coneSignal or coneCurrent or something like that.

Likewise, I continue to be confused by the use of ‘volts’.  The units is not volts, it’s amps (photocurrent).  I realize there is a history to this, but we need to get the units right.  Maybe this has been fixed, if so, please ignore my comment.

ej


On Sep 16, 2015, at 1:52 PM, jamesgolden1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Haomiao and I merged the outersegment branch into master. Please let me know if anything goes wrong. We think it is a good idea to keep the outersegment branch around until everyone is happy that it is working properly.

A basic tutorial is available in t_OuterSegmentClasses.m, and temporary validation against coneAdapt.m is available in v_osLinearObjectTemp.m and v_osBioPhysObjectTemp.m.

All of the rieke* functions have been changed to os*, with the rest of the function name being unchanged. That means riekeAddNoise is now osAddNoise, etc.

I have removed the calls to sensorGet(sensor, 'photon rate') and replaced them with sensorGet(sensor, 'photons'), but this is at odds with the latest version of coneAdapt that used

sensorGet(sensor, 'volts') / (sensorGet(sensor,'conversion gain')*expTime);

which yields the same vector as sensorGet(sensor, 'photon rate'). This can easily be changed.

Finally, when coneAdapt is executed, a warning is printed that mentions the imminent deprecation and the tutorial and validation scripts for the osLinear and osBioPhys subclasses.

**Comment by DavidBrainard** [comment]
I agree -- volts should go away and we should compte current.  And,
