### ISSUE TITLE
Sensor data sizes different when using default oi vs human oi

### ISSUE THREAD

**Issue by xnieamo** [isetbio/isetbio#86]
In the code below, the size of the photon absorption array in the sensor is different depending on whether the oi used is 'human' or not.  Is there some interaction that requires the use of a human oi with a human sensor?

```
scene = sceneCreate('checkerboard');

oi = oiCreate;
oiH = oiCreate('human');

oi = oiCompute(oi, scene);
oiH = oiCompute(oiH, scene);

sensor = sensorCreate('human');

sensor1 = sensorSetSizeToFOV(sensor, sceneGet(scene, 'fov'), scene, oi);
sensor2 = sensorSetSizeToFOV(sensor, sceneGet(scene, 'fov'), scene, oiH);
```

**Comment by hjiang36** [comment]
I think we changed the default oi to be human. So, if you are using the latest code, oiCreate should be exactly the same as oiCreate('human')

The default diffraction limited lens and human optics have quite different focal length properties. And that will result in different sensor size to achieve the same field of view.

**Comment by xnieamo** [comment]
Ok, that makes sense.  Closing this issue.
