### ISSUE TITLE
osCompute to do list

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#87]
There is an optional DC offset that we don't understand.  Let's track down why it is there and when it should be used (or not).

Referencing on the actual formula.  
Pull out the section that computes the formula as its own function and unit test (let's make the functional form more prominent).

**Comment by jamesgolden1** [comment]
The DC offset was something I put in while working on v_osLinearObjectTemp, and I have squashed it.

I added a citation to the Aguenyra & Rike (2013, Nat Neuro) paper.

I added a new utility function osConvolve.m, but I'm not sure it improves clarity.
