### ISSUE TITLE
osPlot

### ISSUE THREAD

**Issue by wandell** [isetbio/isetbio#88]
Separate the different types of plots by case statements.  Consider which plots we really are likely to want, and whether they should be case statements or separate functions so that the object <tab> completes to the various options.

Consider the possibility of os plot inheritance (i.e., all of the os types may need common plotting routines and maybe these should be represented in a base os class?)

**Comment by jamesgolden1** [comment]
Updated osPlot for subclasses with input parser; still considering inheritance
