### ISSUE TITLE
Sensor wavelength sampling

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#9]
We hit a buglet where when you have sensor = sensorCreate('human') it becomes a bit unclear how to change the wavelength sampling.

Doing a sensorSet of wavelength on the sensor object changes the wavelength sampling of that object.  But there is also a cone object in there, and it has its own wavelength sampling which isn't changed.  This causes problems.

The question is, what is the desired behavior.  Should the sensorSet of wavelength 'recurse' down and change everything?  Or should this be made explicit, so that the user should get the cone object, change its sampling, put it back, and then change the sensor wavelength sampling.

I think similar issues may arise with the wavefront optics stuff, where there is wavelength sampling in the wvf object that may differ from that in the oi object.

Thoughts?

**Comment by hjiang36** [comment]
Great catch. Thanks a lot

For me, I prefer to keep them consistent, i.e. change everything (cone, macular, etc.) in sensorSet(sensor, 'wave'). Actually, I hope, if possible, to 'link' all wavelength together and if we change any of them, the rest get automatically changed. But I don't know how to do that in Matlab.

HJ

**Comment by hjiang36** [comment]
I fixed the bug in coneSet and update sensorSet(.., 'wave'). Now setting wavelength samples for sensor structure should be better.

OI structure is more complicated. We could interpolate all fields and data (optics, OTF, photons, etc.) but I'm not sure if we really want to do it.

HJ

**Comment by wandell** [comment]
Yes to all of you.  

The multiple representations of wavelength has been a problem I created years ago, and I have not adequately addressed.  I think dealing with it now in ISETBIO is the right approach.  Don’t wait, like I did.

Brian

> On Apr 6, 2015, at 1:38 PM, Haomiao Jiang <notifications@github.com> wrote:
> 
> I fixed the bug in coneSet and update sensorSet(.., 'wave'). Now setting wavelength samples for sensor structure should be better.
> 
> OI structure is more complicated. We could interpolate all fields and data (optics, OTF, photons, etc.) but I'm not sure if we really want to do it.
> 
> HJ
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/isetbio/isetbio/issues/9#issuecomment-90232611>.
> 

_____________________________________
Brian A. Wandell
Stein Family Professor
Cognitive and Neurobiological Imaging (CNI)
Psychology Department
Phone: 1-650-725-2466
http://www.stanford.edu/~wandell
