### ISSUE TITLE
OuterSegment: linear cone filters

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#92]
Dear ISETBIO-ers,

I am starting to dig deeper into the (linear) outer segment object, `@osLinear`, as it exists in the `master` branch of isetbio. My intent is to see how to employ `@osLinear` in a simulation where the input is constantly changing due to eye movements scanning different natural scenes.  Below are some initial questions regarding `filterConesLinear.m`, the @osLinear method that constructs the Impulse Response (IR) functions for  L-,M-, and S-cones.

1.  The method computes the LMS IR's using a 5-parameter function (just like Equation 6 in `Angueyra & Rieke (2013)`).  I wanted to cross-check the values of these 5 parameters with the `Angueyra & Rieke (2013)` paper, but I was not able to find that information. Is this information available somewhere else? Moreover,  the exponents associated with the `T_rise` parameter (one of the 5 parameters) are set to *3* in the method but to *4* in the paper. Why this discrepancy?

2.  The computed IRs for different cones only differ in the gain of this function, which depends on each cone's adaptation state (`Ib` and `Io` parameters).  In the code, the L-,M-, and S- cone `Ib` values are fixed to [7131 6017 1973] R*/cone/sec. This presumably corresponds to the L-,M-, and S-cone isomerizations for the background field used in the `Angueyra & Rieke (2013)` paper, but I was not able to cross-check these numbers against the paper as I could not find that information in the paper. Is there a different source where this information is available?

3.  For dynamic scene simulations, the IR gain would need to be constantly changing depending on the recent input history. This then introduces the question of how to compute `Ib` over the previous stimulation history. One option is to convolve the cone's photoisomerization with some kernel and use the output of that kernel at time (`t-1`), to compute the value of `Ib` at time `t`. But what should the memory of that kernel be? Another idea would be to compute `Ib` based on the history of the cone's own outer-segment output (feedback). Suggestions anyone?

4.  It would be nice to have an experimental validation script which reproduces the outer segment responses shown in `Fig 6A` using  `@osLinear` -based computations.

Apologies if any of these issues were discussed earlier. 

Best,
Nicolas

**Comment by fmrieke** [comment]
There is an older validation script (pre outer segment object) called s_coneModelValidate - that compared cone responses to several pieces of experimental data.  I guess this should now be called something more like experimental verification though per our conversation yesterday.  Let me know if you need help finding it or interpreting it!

Fred

**Comment by npcottaris** [comment]
Dear Fred,

Thanks for the pointer. This script is useful, but I think we need to test how close are the predictions of the @OuterSegment to your data. Towards this I am starting with single photon responses in the dark. The following code sets up the isetbio simulation.
**Note: please read this on github's site, so that you can see the figures.**

```MATLAB
    % Simulate response for 1 second with a time step of 0.1 millisecond
    timeStep = 1e-4;                    % set the time step of the simulation to 0.1 milliseconds
    nTimeBins = 10000;                  % compute responses for 1.0 second
    timeAxis = (1:nTimeBins)*timeStep;  % time axis of simulation

    % Create a human sensor with just one cone
    sensor = sensorCreate('human');
    sensor = sensorSet(sensor, 'size', [1 1]);  % a [1x1] cone mosaic
    sensor = sensorSet(sensor, 'time interval', timeStep);

    % Set the stimulus: a single photon in the dark, specified as photon rate for the given timeStep,  delivered at t = 0.5 seconds
    flashIntensity = 1.0/timeStep;    % flash intensity in R*/cone/sec
    flashDurationInBins = 1;
    flashOnsetInBins = 5000;
    
    stimulus = zeros(nTimeBins, 1);
    stimulus(flashOnsetInBins +(1:flashDurationInBins)) = flashIntensity;      
    spatioTemporalStimulus = reshape(stimulus, [1 1 nTimeBins]);
    
    % set stimulus to sensor: sequence of # photons for each of the nTimeBins
    sensor = sensorSet(sensor, 'photons', spatioTemporalStimulus);
    
    % Create a biophysically-based outer segment object
    osBiophys = osCreate('biophys');
    osSet(osBiophys, 'noiseFlag', 0);
    
    % Also create a linear-based outer segment object
    osLinear = osCreate('linear');
    osSet(osLinear, 'noiseFlag', 0);
    
    % Compute responses of two different outer segments
    osCompute(osBiophys, sensor);
    osCompute(osLinear, sensor);
    
    % Fit the ConeEmpiricalDimFlashModel model to the output of the osBiophys
    fittedResponse = fitConeEmpiricalDimFlashModel(timeAxis, flashOnsetInBins, timeStep, squeeze(osBiophys.ConeCurrentSignal(1,1,:)));
    
    % Plot results
    ...
```

The stimulus and the ISETBIO @OS - computed responses are depicted in the top and bottom panels below.
![osresponses](https://cloud.githubusercontent.com/assets/3444212/11700133/162d87c8-9e96-11e5-83eb-4a0b89740340.png)

---

For comparison, Figure 6A of the `Angueyra & Rieke (2013) paper`, which shows measured single photon cone responses is shown below. For now, concentrate on the **Darkness** response.
![measuredresponses](https://cloud.githubusercontent.com/assets/3444212/11699309/cd76831c-9e91-11e5-8a40-f8475252c068.png)

The following observations are notable:
* The magnitudes of  the @linearOS and the @biophys OS'responses **roughly agree** with the magnitude of the measured response
* The durations of both the @linearOS' and the @biophys OS'responses are **less than half** of the  duration of the measured response
* Both the  @linearOS and the @biophys OS responses are somewhat **biphasic**, whereas the measured response is clearly **monophasic**. 

If we agree that the code above does not have a flaw,  then it seems to me that we may need some tuning of the OS models.
It would be great to hear Fred's (and other people's) thoughts on these issues before proceeding with the model's predictions to single photon responses on desensitizing backgrounds.

Best,
Nicolas

**Comment by jamesgolden1** [comment]
Nicolas, I am looking at this now, I almost certain it is a problem with my implementation of the @OS object. My guess is that it is "photons" vs. "photon rate" in a couple of places. 

Where can I find the function "fitConeEmpiricalDimFlashModel"? I have a "ConeEmpiricalDimFlash", but it has different inputs.

**Comment by npcottaris** [comment]
Hi James,

I am not so sure that the problem is related to photon vs photon rate. That would change the results drastically as the time step is 1e-4.

The `fitConeEmpiricalDimFlashMode.m` does not exist anywhere else other than on my own computer. Here it is:

``` MATLAB
function fittedResponse = fitConeEmpiricalDimFlashModel(timeAxis, flashOnsetInBins, timeStep, current)
    initialParams = [0.7 0.02 0.03 0.53 34];
    offset = current(1);
    current = current - offset;
    indices = timeAxis >= flashOnsetInBins*timeStep;
    timeAxisZero = timeAxis(indices)-timeAxis(flashOnsetInBins);
    current = current(indices);
    fittedParams = nlinfit(timeAxisZero', current, 'ConeEmpiricalDimFlash', initialParams);
    fit = ConeEmpiricalDimFlash(fittedParams, timeAxisZero');
    fittedResponse = timeAxis * 0 + offset;
    fittedResponse(indices) = fit + offset;
end
```

**Comment by fmrieke** [comment]
I’ll look back at this, but I suspect part of it is that the empirical fit we are comparing to was an average across cells - so should be a better representation of the typical cell response than the data from a single cell as from our paper.  They often have a slight undershoot in the flash response as in the empirical fit.  The place we have the most data is at 4000 R*/cone/s - i.e. that is where I trust that we know the kinetics of the responses best.  One issue is that in the dark there could be rod contributions to the cone response (via gap junctions) - which could distort the time course.

Fred

**Comment by DavidBrainard** [comment]
Just to make sure.  We are all working with the master branch of isetbio at this point, right? That is the outersegment branch is merged in and the master branch is where we should be testing and if necessary fixing?

If it is otherwise, let’s get clear on what’s where.

DB

On Dec 9, 2015, at 6:03 PM, Fred Rieke <notifications@github.com<mailto:notifications@github.com>> wrote:

I’ll look back at this, but I suspect part of it is that the empirical fit we are comparing to was an average across cells - so should be a better representation of the typical cell response than the data from a single cell as from our paper. They often have a slight undershoot in the flash response as in the empirical fit. The place we have the most data is at 4000 R*/cone/s - i.e. that is where I trust that we know the kinetics of the responses best. One issue is that in the dark there could be rod contributions to the cone response (via gap junctions) - which could distort the time course.

Fred

**Comment by npcottaris** [comment]
Hello,

Here is another little thing I just discovered.  In the existing os tutorials (t_OuterSegmentClasses, s_coneModelValidate), the human sensor is set as follows:
```MATLAB
    % Create human sensor.
    timeStep = 1e-4; 
    sensor = sensorCreate('human');
    sensor = sensorSet(sensor, 'size', [1 1]); % only 1 cone
    sensor = sensorSet(sensor, 'time interval', timeStep);
```
Then we can set a single photon pulse as:
```MATLAB
   % set stimulus to sensor
    spatioTemporalStimulus(1,1,1) = 1
    sensor = sensorSet(sensor, 'photons', spatioTemporalStimulus);
```

Reading the sensor state:
```MATLAB
    photons = sensorGet(sensor, 'photons')
    photonRate = sensorGet(sensor, 'photon rate')
```
we get:
``` MATLAB
photons = 1
photonRate = 20
```

One would have expected that since we set the 'time step' to 1/10,000 seconds, the returned 'photonRate' should be 10,000 R* / sec, not 20.
This discrepancy occurs because in `sensorGet`, the `photon rate` in computed as  `photons` / `exposure time`. 

So to obtain the expected photon rate, we would need to have the `exposure time` match the  `time step` as follows:
```MATLAB
   % Create a human sensor with just one cone
    sensor = sensorCreate('human');
    sensor = sensorSet(sensor, 'size', [1 1]);  % a [1x1] cone mosaic
    sensor = sensorSet(sensor, 'time interval', timeStep);
    sensor = sensorSet(sensor, 'exposure time', timeStep);
```

N.

**Comment by fmrieke** [comment]
This is something I have been very confused by too - there seem to be multiple ways to specify and read out the stimulus - and they incorporate (a) integration time and (b) Poisson fluctuations in different ways.  There may be some issues about units as well. 

Fred

**Comment by fmrieke** [comment]
For our current validation purposes I think the data and target experimental points in s_coneModelValidate are the right ones.  Those are either obtained as averages across multiple cells or chosen as typical cells.  Can we update that to use the outer segment object?  I can do so, but probably not for a week or a bit longer.

Fred

**Comment by jamesgolden1** [comment]
Fred, there are two validation scripts v_osLinearObjTemp and
v_osBioPhysObjTemp that are both based on s_coneModelValidate. Their
purpose is to show that the osLinear and osBioPhys objects give the same
response to the stimuli in s_coneModelValidate as the old coneAdapt
function.

With Nicolas's point about the exposure time/ time interval properties, I
should mention that I built the @OS objects to compute responses using the
'photons' field, even though the coneAdapt function originally used 'photon
rate'. My sense is that the @OS computation should revert to using photon
rate, because the amplitudes of the linear filters (as well as the
computations in Fred's biophysical model) were originally set for computing
with 'photon rate'.

James

**Comment by fmrieke** [comment]
Great - thanks.  I’ll look at those.  Then let’s all talk about stimulus specification (when I am more up to speed on the @OS stuff).  I’m not sure basing it on what we did before is the right move.

Fred

**Comment by npcottaris** [comment]
After coupling `exposure time` and `time interval` in the sensor configuration, the results of the OS computations are off. 

```MATLAB
    timeStep = 1e-4;                    % set the time step of the simulation to 0.1 milliseconds
    
    % Create a human sensor with just one cone
    sensor = sensorCreate('human');
    sensor = sensorSet(sensor, 'size', [1 1]);  % a [1x1] cone mosaic
    sensor = sensorSet(sensor, 'time interval', timeStep);
    sensor = sensorSet(sensor, 'exposure time', timeStep);
    
    % set stimulus to sensor: sequence of photons for each of the nTimeBins
    spatioTemporalStimulus = zeros(1,1,1/timeStep);
    spatioTemporalStimulus(1,1, 0.5/timeStep) = 1;   % 1 photon at delivered at t = 0.5 seconds
    sensor = sensorSet(sensor, 'photons', spatioTemporalStimulus);
    
    % Create a biophysically-based outer segment object
    osBiophys = osCreate('biophys');
    osSet(osBiophys, 'noiseFlag', 0);

    % Also create a linear-based outer segment object
    osLinear = osCreate('linear');
    osSet(osLinear, 'noiseFlag', 0);

    % Compute responses of two different outer segments
    osCompute(osBiophys, sensor);
    osCompute(osLinear, sensor);
    
    % plot ...
```
gives:

![osresponsesnew](https://cloud.githubusercontent.com/assets/3444212/11724085/f0d711d8-9f3f-11e5-9006-0785808eaad7.png)

The initial artifact in the biophys OS  is probably due to the initial state being wrong now. The tiny scale of the response at t = 0.5 sec (when the single photon is delivered) is due to the photon / photon rate issue raised before.

**Comment by npcottaris** [comment]
I am putting here some random thoughts regarding input stimulus specification to @OS* objects.

The stimulus to the @OS objects is photo-isomerizations:  the incident photons which undergo the following 3-step process:
1. captured by the inner segment,
2. funneled to the outer segment,
3. causing isomerization of a single 11-cis retinal molecule

In the ISETBIO framework, photo-isomerizations can be specified by loading either the 'photons' (quantal events specified for each time bin), or the 'photon rate' (number of quantal events / sec) property of the sensor object, and photo-isomerizations are treated as an analog quantity, e.g., perfectly happy if at time bin T, there are 0.245 quantal events. 

Here are some pros and cons in specifying photo-isomerizations via the `photons` field:
##### Loading the  `photons` field:  pros
* Independent of the sensor's `exposure time` setting
* More accurate representation of biology, since photoisomerizations are quantal events, just like photon emissions. 
* More understandable: at each time bin of the simulation, there are either 0 events or an integer number of them.
* Most control of the temporal profile of the stimulus

##### Loading the  `photons` field:  cons
* User would have to specify the actual time-sequence of the isomerizations, instead of a single number (photon rate)
* Simulations using stimuli of identical same photon rates may yield  different results if the isomerization time-sequences are not identical.
* Computationally more expensive, especially for the biophysical version of @OS (speculation, not actually tested)

Here are some pros and cons in specifying photo-isomerizations via the `photon rate` field:
##### Loading the  `photon rate` field:  pros
* Easier to simulate experimental conditions (e.g., pedestals on desensitizing fields) which specify photon rates
* Simulations using stimuli of identical photon rates will yield identical results

##### Loading the  `photon rate` field: cons
* Dependence of the sensor's `exposure time` setting. 
* Unrealistic scenario as we can have time bins with non-integer quantal events

--- 
Please put your own pros and cons, so that we can reach a consensus on what makes most sense.
Also we should decide on whether we want photo-isomerizations to be a strictly discrete quantity.

**Comment by jamesgolden1** [comment]
I updated the outersegment files. The updated v_osLinear* and v_osBioPhys* functions show that the @OS object computations are the same as the old coneAdapt computations. The code cell called "saccade-like stimuli" in each of those files compares the model response to physiological data from one of Fred's experiments and is of particular interest. The original tutorial file has been renamed t_os.m and another has been added as t_osIntroduction. 

There is still something I need to work out for the osBioPhys computation in t_osIntroduction, which hopefully will be fixed by tomorrow.

**Comment by npcottaris** [comment]
Thanks for the update James !

With the updates @OS objects we get the following simulations of the Figure 6A data in Angueyra & Rieke (2013).
![osresponses2](https://cloud.githubusercontent.com/assets/3444212/11823232/f98d9036-a340-11e5-9470-0e2d27daeb13.png)

Comparing model responses (above) and measured data (below) we see that there is relatively good agreement regarding the amplitude of the responses, but the dynamics are still not quite right.
The measured outer segment responses have more sustained dynamics when the background stimulation is low, whereas the dynamics of the model response  appear independent of the background stimulation.

The main question here is the following:
* Are the measured sustained dynamics due to rod-contamination at 1,200 and 4,000 R*/sec backgrounds, or is the model not capable of reproducing different dynamics at different background levels?

I can send the code if someone would like to reproduce these figures.
![measuredresponses](https://cloud.githubusercontent.com/assets/3444212/11823252/0a02582a-a341-11e5-963b-94f8af31fcf1.png)

**Comment by jamesgolden1** [comment]
I also wanted to include Fred's physiological validation data from a measured cone photocurrent. The original file is s_coneModelValidate, and the code cell "Saccade-like stimuli" loads EyeMovementExample.mat. These can now be run with the outer segment objects as v_osLinearObjectTemp.m and v_osBioPhysObjectTemp. The cone photocurrent data is in response to simulated eye movements over a natural scene image. This doesn't really get at the issue Nicolas is interested in, but I wanted to include this to show Fred had already set up the comparison of his models with some of his data.

![oslinear_eyemvmtex](https://cloud.githubusercontent.com/assets/8620201/11824475/9defe254-a32e-11e5-98fa-27b5466afc72.png)

![osbiophys_eyemvmtex](https://cloud.githubusercontent.com/assets/8620201/11824492/c05e848a-a32e-11e5-8156-05b56ed10250.png)

**Comment by npcottaris** [comment]
Back to the linear cone filters. In `filterConesLinear.m`, line 36 states:
~~~ Matlab
pRate = sensorGet(sensor, 'photons');
~~~
I believe it is the `photon rate` field value that we want to extract, correct? 
I am looking at the main branch.

Nicolas

**Comment by jamesgolden1** [comment]
It is true that we want photon rate, but in looking back,
filterConesLinear.m is never called. I should have removed it, and I will
remove it now. It has been replaced by osFilterConesLinear.m, which is
called by @osLinear/initialize.m.

**Comment by npcottaris** [comment]
OK. Thanks James.

**Comment by npcottaris** [comment]
Fred:

Sorry to bother you again, but I would like to settle the issue that the temporal dynamics of the @OSbiophys model do not seem to match those in  Angueyra & Rieke 2013 for single photon pulses on 0, 1200 and 4,000 R*/sec desensitizing backgrounds?  See 5 messages above.

If you think this is not an issue, I would like to close this issue. 
But it would be nice to know what is the source of this mismatch, e.g.,  are the slower recorded responses due to rod intrusion or is the model not intended to capture low light level responses?

Thanks,
Nicolas

**Comment by fmrieke** [comment]
I think the issue is largely variability across cells.  The kinetics of the fit that we compare the model with in the validation script were chosen to be representative of the typical cone - the kinetic of the cell we used as an example in the paper are somewhat slower than typical.  That said I am sure we can do better in terms of the variety of experimental data we compare the cone model to.  I think that is something we should discuss at some point, but at present I think it is capturing the average cone kinetics pretty well across light levels.  

Fred

**Comment by npcottaris** [comment]
OK. Thanks for the explanation. I am closing this issue.
