### ISSUE TITLE
outersegment validations

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/isetbio#94]
A) We appear to have two outersegment validation scripts, v_osBioPhysObjectTemp and v_osLinearObjectTemp.

But we have three outer segment validation files in our database, two corresponding to the above and a third called osBioPhysObject.  This was created in August.  Is this just leftover before some name changed, or does it correspond to an actual script.  If the former, I'll delete it.  If the latter, where is the script?

B) As I understand it, the two scripts with the Temp in their names were intended to show that the current outersegment object produces the same results as the obsolete coneAdapt function, which I believe they do.  I think our idea was to then modify these scripts to not refer to the coneAdapt function and to delete coneAdapt..  Are we now at a juncture where we can take that plunge?

**Comment by jamesgolden1** [comment]
David, regarding A), you are correct that the validation mat file osBioPhysObject from August is left over from before the name change of the script to v_osBioPhysObjectTemp. It can be deleted.

B) I think we are at that point. The validations work for me, and if they look good on your machine as well I think we can deprecate coneAdapt. Both of these validation scripts also compare the os object output with some of Fred's physiology data. I could modify these temporary v_os scripts to directly compare their output with the real data for a more permanent type of os validation. I am open to any other suggestions about a more permanent type of os validation as well.

**Comment by DavidBrainard** [comment]
OK, I am going through these.  Will circle back when I'm done.

**Comment by DavidBrainard** [comment]
I've now been through the linear adaptation validation script and tidied it up.  I agree, the two ways of computing give the same answer in all cases.  I did a bunch of stuff as below.

a) I renamed these scripts as v_osLinearObjectVsOrigCode and v_osBioPhysObjectVsOrigCode.  

b) I took the plunge and removed coneAdapt and riekeLinearCode from isetbio.  I put local copies of both into function v_osLinearObjectVsOrigCode and a local copy of coneAdapt into v_osBioPhysObjectVsOrigCode.  Thus you can still run the validation scripts, but you can no longer call coneAdapt as an external function.  This will break any code that has not converted over to the outersegment object, but it is time.  

c) I deleted the data files Cones/EyeMovementExample.mat and Cones/tree.mat from isetbio.  The first was used by the validation scripts.  It is now on the archiva server and the validation scripts access it using the RemoteDataToolbox.  I am not sure what tree.mat is for, it looks to be an image of something.  I can publish it to the archiva server if we are using it for anything.

d) To make c) work smoothly, I moved validation/ieSetUnitTestPreferencesTemplate -> ieSetPreferencesTemplate (in the root dir of isetbio). I changed the group name to isetbio, from isetbioValidation.  I also moved the rdt-config-isetbio.json file to the root dir of isetbio.  This allows the validation scripts to continue to get their data using the RemoteDataToolbox, but also allows us to read other artifacts fairly easily.  I'm sure how to do this is a work in progress -- see some thought posted as a RemoteDataToolbox issue yesterday.  This is what the read looks like currently.
  % Load experimental data using RDT.
  client = RdtClient(getpref('isetbio','remoteDataToolboxConfig'));
  client.crp('resources/data/experimental/cones');
  [eyeMovementExample, eyeMovementExampleArtifact] = client.readArtifact('eyeMovementExample', 'type', 'mat');

e) At present, all isetbio validations run and successfully pass their tests on my machine, fetching both full and fast data from the archiva server.  They should work from the distribution too, if you run ieSetPreferencesTemplate.

I haven't been through the biophys script yet.  James, I will email you separately some suggestions about cleaning it up before I take a look, based on my experience with the linear version.

**Comment by wandell** [comment]
Confirming that you are doing this on the rgc branch?

**Comment by DavidBrainard** [comment]
No, I haven’t touched the rgc branch.  I didn’t even know there was one.  I did all this on the master branch.

On Dec 31, 2015, at 2:33 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:


Confirming that you are doing this on the rgc branch?

**Comment by jamesgolden1** [comment]
I'm working on these now - Brian, the v_os files have been updated on the master branch.

**Comment by wandell** [comment]
OK.  Can we pull the tutorials/rgc/t_rgcIntroduction.m into the master branch, then.

**Comment by DavidBrainard** [comment]
Fine with me.

Possibly I should have created a branch rather than mainlining my changes.   I am not quite sure what the right scale of
a change or changes is, before it makes sense to do the branch/merge thing.  Something to chat about at some point.

On Dec 31, 2015, at 3:21 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. Can we pull the tutorials/rgc/t_rgcIntroduction.m into the master branch, then.

**Comment by jamesgolden1** [comment]
Done - I removed the final few lines that generate the rgc object, because they would only work in the rgc branch at this point.

**Comment by wandell** [comment]
Good.  Then I will remove the rgc branch and off we go.  Closing.
