### ISSUE TITLE
Best wishes for 2016 !

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#96]
## Best wishes for 2016 !

![retina](https://cloud.githubusercontent.com/assets/3444212/12073690/637c04ac-b0fa-11e5-9521-6bde30ac8cca.png)

I know the image is cheesy, but I just couldn't resist. Plus, I had a lot of fun developing it.
Dynamic version with fake eye movements, linear cone adaptation, and noise downloadable [here](https://www.dropbox.com/s/83ja6n4mix6uf7z/Dynamic2016.mp4?dl=1).

Best regards,
Nicolas

**Comment by wandell** [comment]
Wonderful image!  Happy New Year!


Stanford

**Comment by DavidBrainard** [comment]
Nice!!  Did you build that space varying mosaic right into isetbio?  Do the cone apertures actually vary with position or just the spacing?

Happy New Year!

**Comment by npcottaris** [comment]
Thanks. I have not yet built that into isetbio. Sometime in 2016....
Yes, cone aperture varies linearly with cone eccentricity.

**Comment by DavidBrainard** [comment]
Closing, we're on to 2018!
