### ISSUE TITLE
New class for dynamic visualization of @os responses

### ISSUE THREAD

**Issue by npcottaris** [isetbio/isetbio#99]
ISETBIO now contains `osWindow`, a new isetbio class in the spirit of `sceneWindow`, `oiWindow`, etc,  which enables dynamic visualization of outer segment currents in response to eye movements over hyperspectral images. 

the `osWindow` displays 
- the hyperspectral image examined, the eye movements, and an magnified version of the portion of the optical image or the scene (user - selectable via slider on right) that lies under the sensor position
- the spatiotemporal response of the OS responses for the entire cone mosaic
- the instantaneous 2D response of the cone mosaic
- traces of the highest responding L, M and S-cone (these cones are outlined in R,G, and B in the 2D response plot)
- a time slider with which the user can go through the simulation and interactively examine the results

To see`osWindow` in action, run the `t_osHyperSpectralSceneEyeScan` tutorial, which performs a linear- and a biophysics-based OS computation and presents the results using two `osWindows`, one for each model. I find this tool useful for comparing the two models as well as for debugging complex simulations.

P.S. You will need to have the RemoteDataToolbox to run this tutorial.
P.P.S. Teaser screenshot attached below.

Nicolas

![oswindow](https://cloud.githubusercontent.com/assets/3444212/12420878/32494af2-be8d-11e5-9603-29d9aa1d3e2d.png)

**Comment by wandell** [comment]
Looks great!  James and Rosemary and I started it up and it went pretty far.  It ran well on James' 2015, but on my old clunky 2013b it died at this line in the osWindow

set(obj.hFig, 'Name', figureTitle, 'Menubar', 'none', 'Toolbar', 'none', 'Color', [0.1 0.1 0.1], ...
                'Position',[10+rand(1,1)*300 10+rand(1,1)*100 screenSize(4)*aspectRatio screenSize(4)], ...
                'SizeChangedFcn', {@resizeOSwindow, obj, aspectRatio});

Error using set
Invalid property found.
Object Name: figure
Property Name: 'SizeChangedFcn'.

Error in osWindow/init (line 192)
            set(obj.hFig, 'Name', figureTitle, 'Menubar', 'none', 'Toolbar', 'none', 'Color', [0.1 0.1 0.1], ...

Error in osWindow (line 90)
            obj.init(figureNo, figureTitle);

Error in t_osHyperSpectralSceneEyeScan (line 86)
        osWindow(1001+imageIndex, 'biophys-based outer segment', osB, sensor, oi);

The 'SizeChangedFcn' variable seems to be a new development.  

But mainly, LOOKS GREAT!

**Comment by npcottaris** [comment]
Removed the SizeChangedFcn for compatibility with earlier Matlab versions.
Did not like how it handled figure resizing anyway.

**Comment by DavidBrainard** [comment]
I don't think this needs to be an open issue anymore.  If tutorials are still broken, they are now in "underDevelopment" directories and we'll find them as we pass through the tutorials.
